src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>unique_id__c</fullName>
		<externalId>true</externalId>
        <label>Unique identifier</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Account_Income__c.object
<CustomObject>
    <fields>
        <fullName>account_id__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Incomes</relationshipLabel>
        <relationshipName>Account_Incomes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>gf_income_amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>gf_income_movement_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Income Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>gf_income_type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>product_service_id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Bank Account Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>unique_id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Unique Identifier</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Account Income</label>
    <nameField>
        <displayFormat>INC-{0000000000}</displayFormat>
        <label>Income Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Incomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BE_AccountIncomeGraphic_Tst.cls
/**
   -------------------------------------------------------------------------------------------------
   @Name <BE_AccountIncomeGraphic_Tst>
   @Author Martin Alejandro Mori Chavez (martin.mori.contractor@bbva.com)
   @Date 2020-06-10
   @Description test for BE_AccountIncomeGraphic_Ctr class
   @Changes
   Date        Author   Email                               Type
   2020-06-10  MAMC     martin.mori.contractor@bbva.com     Creation
   -------------------------------------------------------------------------------------------------
 */
@IsTest
public without sharing class BE_AccountIncomeGraphic_Tst {
    /**
     @Description test BE_AccountIncomeGraphic_Tst.getAvgMthBal(param), correct scenary
    */
    @IsTest
    static void getAvgMthBaltTest() {
        Account acc = TestFactory.createAccount();
        List<Account_Income__c> incomes = new List<Account_Income__c>();
        Account_Income__c income = new Account_Income__c();
        income.CurrencyIsoCode = 'USD';
        income.account_id__c = acc.Id;
        income.gf_income_amount__c = 4776000;
        income.gf_income_movement_date__c = System.today();
        income.gf_income_type__c = '04';
        income.unique_id__c = '217161842019104PEN001101830100031112';
        income.product_service_id__c = '001101830100031112';
        incomes.add(income);
        income = new Account_Income__c();
        income.CurrencyIsoCode = 'USD';
        income.account_id__c = acc.Id;
        income.gf_income_amount__c = 4776000;
        income.gf_income_movement_date__c = System.today();
        income.gf_income_type__c = '04';
        income.unique_id__c = '217161842019104PEN001101830100031110';
        income.product_service_id__c = '001101830100031110';
        incomes.add(income);
        income = new Account_Income__c();
        income.CurrencyIsoCode = 'USD';
        income.account_id__c = acc.Id;
        income.gf_income_amount__c = 4776000;
        income.gf_income_movement_date__c = System.today().addYears(-1);
        income.gf_income_type__c = '04';
        income.unique_id__c = '217161842018104PEN001101830100031110';
        income.product_service_id__c = '001101830100031110';
        incomes.add(income);
        insert incomes;
        
        Test.startTest();
        map<String, map<Integer, Decimal>> mapIncome = BE_AccountIncomeGraphic_Ctr.getAvgMthBal(acc.Id);
        Boolean isSuccess = false;
        if(mapIncome.size()>0) {
            isSuccess = true;
        }
        System.assert(isSuccess, 'Correct Value');
        Test.stopTest();
    }
    
    /**
     @Description test BE_AccountIncomeGraphic_Tst.findReport(param), correct scenary
    */
    @IsTest(SeeAllData='true')
    static void findReportTest() {
        String reportDev;
        for(Report rep : [SELECT DeveloperName FROM Report LIMIT 1]) {
            reportDev = rep.DeveloperName;
        }
        Test.startTest();
        final List<Object> reportTest = BE_AccountIncomeGraphic_Ctr.findReport(reportDev);
        Boolean isSuccess = false;
        if(reportTest.size()>0) {
            isSuccess = true;
        }
        System.assert(isSuccess, 'Correct Value');
        Test.stopTest();
    }
}