src/objects/Account.object
<CustomObject>
     <fields>
        <fullName>non_client_code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Non Client Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Record_Type_Non_Client</fullName>
        <active>true</active>
        <label>No Cliente</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>decision_making_desc__c</fullName>
        <label>Decisor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Si</fullName>
                    <label>Sí</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>phone_1__c</fullName>
        <label>Phone 1</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>phone_1_area_code__c</fullName>
        <label>Phone 1 Area Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>41</fullName>
                    <label>Amazonas - 41</label>
                </value>
                <value>
                    <fullName>43</fullName>
                    <label>Ancash - 43</label>
                </value>
                <value>
                    <fullName>83</fullName>
                    <label>Apurimac - 83</label>
                </value>
                <value>
                    <fullName>54</fullName>
                    <label>Arequipa - 54</label>
                </value>
                <value>
                    <fullName>66</fullName>
                    <label>Ayacucho - 66</label>
                </value>
                <value>
                    <fullName>76</fullName>
                    <label>Cajamarca - 76</label>
                </value>
                <value>
                    <fullName>84</fullName>
                    <label>Cusco - 84</label>
                </value>
                <value>
                    <fullName>67</fullName>
                    <label>Huancavelica - 67</label>
                </value>
                <value>
                    <fullName>62</fullName>
                    <label>Huanuco - 62</label>
                </value>
                <value>
                    <fullName>56</fullName>
                    <label>Ica - 56</label>
                </value>
                <value>
                    <fullName>64</fullName>
                    <label>Junin - 64</label>
                </value>
                <value>
                    <fullName>44</fullName>
                    <label>La Libertad - 44</label>
                </value>
                <value>
                    <fullName>74</fullName>
                    <label>Lambayeque - 74</label>
                </value>
                <value>
                    <fullName>01</fullName>
                    <label>Lima y Callo - 01</label>
                </value>
                <value>
                    <fullName>65</fullName>
                    <label>Loreto - 65</label>
                </value>
                <value>
                    <fullName>82</fullName>
                    <label>Madre de Dios - 82</label>
                </value>
                <value>
                    <fullName>53</fullName>
                    <label>Moquegua - 53</label>
                </value>
                <value>
                    <fullName>63</fullName>
                    <label>Pasco - 63</label>
                </value>
                <value>
                    <fullName>73</fullName>
                    <label>Piura - 73</label>
                </value>
                <value>
                    <fullName>51</fullName>
                    <label>Puno - 51</label>
                </value>
                <value>
                    <fullName>42</fullName>
                    <label>San Martin - 42</label>
                </value>
                <value>
                    <fullName>52</fullName>
                    <label>Tacna - 52</label>
                </value>
                <value>
                    <fullName>72</fullName>
                    <label>Tumbes - 72</label>
                </value>
                <value>
                    <fullName>61</fullName>
                    <label>Ucayali - 61</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>phone_2__c</fullName>
        <label>Phone 2</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>phone_2_area_code__c</fullName>
        <label>Phone 2 Area Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>41</fullName>
                    <label>Amazonas - 41</label>
                </value>
                <value>
                    <fullName>43</fullName>
                    <label>Ancash - 43</label>
                </value>
                <value>
                    <fullName>83</fullName>
                    <label>Apurimac- 83</label>
                </value>
                <value>
                    <fullName>54</fullName>
                    <label>Arequipa- 54</label>
                </value>
                <value>
                    <fullName>66</fullName>
                    <label>Ayacucho - 66</label>
                </value>
                <value>
                    <fullName>76</fullName>
                    <label>Cajamarca - 76</label>
                </value>
                <value>
                    <fullName>84</fullName>
                    <label>Cusco - 84</label>
                </value>
                <value>
                    <fullName>67</fullName>
                    <label>Huancavelica - 67</label>
                </value>
                <value>
                    <fullName>62</fullName>
                    <label>Huanuco - 62</label>
                </value>
                <value>
                    <fullName>56</fullName>
                    <label>Ica - 56</label>
                </value>
                <value>
                    <fullName>64</fullName>
                    <label>Junin - 64</label>
                </value>
                <value>
                    <fullName>44</fullName>
                    <label>La Libertad - 44</label>
                </value>
                <value>
                    <fullName>74</fullName>
                    <label>Lambayeque - 74</label>
                </value>
                <value>
                    <fullName>01</fullName>
                    <label>Lima y Callao - 01</label>
                </value>
                <value>
                    <fullName>65</fullName>
                    <label>Loreto - 65</label>
                </value>
                <value>
                    <fullName>82</fullName>
                    <label>Madre de Dios - 82</label>
                </value>
                <value>
                    <fullName>53</fullName>
                    <label>Moquegua - 53</label>
                </value>
                <value>
                    <fullName>63</fullName>
                    <label>Pasco - 63</label>
                </value>
                <value>
                    <fullName>73</fullName>
                    <label>Piura - 73</label>
                </value>
                <value>
                    <fullName>51</fullName>
                    <label>Puno - 51</label>
                </value>
                <value>
                    <fullName>42</fullName>
                    <label>San Martin - 42</label>
                </value>
                <value>
                    <fullName>52</fullName>
                    <label>Tacna - 52</label>
                </value>
                <value>
                    <fullName>72</fullName>
                    <label>Tumbes - 72</label>
                </value>
                <value>
                    <fullName>61</fullName>
                    <label>Ucayali - 61</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>prof_position_type__c</fullName>
        <label>Position</label>
        <picklist>
            <picklistValues>
                <fullName>ACCIONISTA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADMINISTRADOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APODERADO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASISTENTE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DIRECTORIO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE COMERCIAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE ADMINISTRACION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE ADMINISTRACION Y FINANZAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE CONTABILIDAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE FINANZAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE OPERACIONES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE RRHH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE GENERAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JEFE DE ADMINISTRACIÓN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JEFE DE ADMINISTRACION Y FINANZAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JEFE DE CONTABILIDAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JEFE DE FINANZAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JEFE DE TESORERIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTROS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRESIDENTE DE DIRECTORIO</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>		
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACCIONISTA</fullName>
                </value>
                <value>
                    <fullName>PRESIDENTE DE DIRECTORIO</fullName>
                </value>
                <value>
                    <fullName>APODERADO</fullName>
                </value>
                <value>
                    <fullName>DIRECTORIO</fullName>
                </value>
                <value>
                    <fullName>GERENTE GENERAL</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE FINANZAS</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE ADMINISTRACION Y FINANZAS</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE ADMINISTRACION</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE RRHH</fullName>
                </value>
                <value>
                    <fullName>GERENTE COMERCIAL</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE OPERACIONES</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE CONTABILIDAD</fullName>
                </value>
                <value>
                    <fullName>JEFE DE FINANZAS</fullName>
                </value>
                <value>
                    <fullName>JEFE DE TESORERIA</fullName>
                </value>
                <value>
                    <fullName>JEFE DE ADMINISTRACION Y FINANZAS</fullName>
                </value>
                <value>
                    <fullName>JEFE DE ADMINISTRACIÓN</fullName>
                </value>
                <value>
                    <fullName>JEFE DE CONTABILIDAD</fullName>
                </value>
                <value>
                    <fullName>ADMINISTRADOR</fullName>
                </value>
                <value>
                    <fullName>ASISTENTE</fullName>
                </value>
                <value>
                    <fullName>OTROS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/BE_NotUIAPIForm_Tst.cls
/**
   -------------------------------------------------------------------------------------------------
   @Name BE_NotUIAPIForm_Tst
   @Author Martin Alejandro Mori Chavez (martin.mori.contractor@bbva.com)
   @Date 2021-01-08
   @Description
   @Changes
   Date        Author   Email                  				Type
   2021-01-08  MAMCH    martin.mori.contractor@bbva.com    	Creation
   -------------------------------------------------------------------------------------------------
 */
@isTest
public class BE_NotUIAPIForm_Tst {
    /*
	 * @Description method test getStatusMeeting error
	 */
    @isTest
    static void findLookupRecordsTest() {
        final Id rTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Record_Type_Non_Client').getRecordTypeId();
        final Account accOne= new Account(Name='NON_CLIENT_CONTACT_2020_001',AccountNumber='20876543267',non_client_code__c='20876543267',recordTypeId=rTypeId);
        insert accOne;
        final Contact con= new Contact(AccountId=accOne.Id,Salutation='Mr.',FirstName='NON_CLIENT',LastName='NON_CLIENTE_CONTACT_ONE',decision_making_desc__c='Si',Email='contactone@test.com',MobilePhone='924567896',prof_position_type__c='APODERADO', contact_code__c='00001',phone_1__c='9876545',phone_1_area_code__c='01',phone_2__c='2235675',phone_2_area_code__c='01');
        insert con;
        Test.startTest();
        BE_NotUIAPIForm_Ctr.findLookupRecords(null, 'Contact');
        BE_NotUIAPIForm_Ctr.findLookupRecords('NON_CLIENTE_CONTACT_ONE', 'Contact');
        final List<sObject> objs = BE_NotUIAPIForm_Ctr.findLookupRecords('NON_CLIENTE_CONTACT_ONE', 'Contact');
        Test.stopTest();
        System.assert(!objs.isEmpty(), 'success!!!');
    }
    
    /*
	 * @Description method test getStatusMeeting error
	 */
    @isTest
    static void lookUpByIdTest() {
        final Account acc = new Account(Name='Test');
        insert acc;
        Test.startTest();
        Final Account obj = (Account)BE_NotUIAPIForm_Ctr.lookUpById(acc.Id, 'Account', 'Name');
        Test.stopTest();
        System.assert(String.isNotBlank(obj.Name), 'success!!!');
    }
    
    /*
	 * @Description method test getStatusMeeting error
	 */
    @isTest
    static void findRelatedToLookupTest() {
        final Account acc = new Account(Name='Test');
        insert acc;
        Test.startTest();
        Final List<List<SObject>> objs = BE_NotUIAPIForm_Ctr.findRelatedToLookup('Test', 'Account');
        Test.stopTest();
        System.assert(!objs.isEmpty(), 'success!!!');
    }
}