src/objects/Account_Profitability__c.object
<CustomObject>
    <fields>
        <fullName>account_id__c</fullName> 
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Profitability</relationshipLabel>
        <relationshipName>Account_Profitability</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>currenct_mon_amount__c</fullName>
        <label>Current month amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>currenct_mon_per__c</fullName>
        <label>Current month percent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>period__c</fullName>
        <formula>CASE(MONTH(year_month_day_date__c),1, $Label.Month1ShortName ,2,$Label.Month2ShortName,3,$Label.Month3ShortName,4,$Label.Month4ShortName,5,$Label.Month5ShortName,6,$Label.Month6ShortName,7,$Label.Month7ShortName,8,$Label.Month8ShortName,9,$Label.Month9ShortName,10,$Label.Month10ShortName,11,$Label.Month11ShortName,$Label.Month12ShortName) + &apos; &apos; + RIGHT(TEXT(YEAR(year_month_day_date__c)),2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Period</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>profitability_category_type__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>	
        <fullName>profitability_subcategory_type__c</fullName>
        <label>Subcategory</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>profitability_type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>year_month_day_date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
	    <fields>
        <fullName>product_desc__c</fullName>
        <label>product_desc</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>is_type_3_last_date__c</fullName>
        <formula>IF( year_month_day_date__c =  account_id__r.account_profitability_type_3_last_date__c ,true,false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is type 3 last date?</label>
        <type>Checkbox</type>
    </fields>
    <label>Rentabilidad</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rentabilidades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BE_EconomicGroup_Spread_Rate_cls.cls
/**
 * BE_EconomicGroup_Spread_Rate_cls
 * <p /><p />
 * Modification log:<p />
 * -------------------------------------------------------------------
 * Developer                    Date                Description<p />
 * -------------------------------------------------------------------
 * Diego Carbajal    		07/09/2020          Original version.<p />
 *
 * @author Diego Carbajal
 */
public with sharing class BE_EconomicGroup_Spread_Rate_cls extends Be_DTP_ResponseModel_cls {
    
    /*
	 * @Description  Get Custom Data for Profitability
	 */
    public override Be_DTP_ResponseModel_cls.Response getData(Map<String, String> mapParams, String columns, List<String> replaceField) {
        Final Be_DTP_ResponseModel_cls.Response response = new Be_DTP_ResponseModel_cls.Response(true);
        response.columns = columns;
        replaceField.add(mapParams.get('recordId'));
        Final Map<Id, Account> mapClients = new Map<Id, Account>([SELECT Id, Name FROM Account WHERE parentId IN: replaceField]);
        Final Account_Profitability__c[] lstSprdRate = [SELECT Id, account_id__c, currenct_mon_amount__c, profitability_category_type__c, 
                                                currenct_mon_per__c, year_month_day_date__c ,period__c FROM Account_Profitability__c 
                                                WHERE account_id__c IN: mapClients.keySet() AND product_desc__c = 'CLIENTE' AND 
                                                profitability_subcategory_type__c IN ('TOTAL Spread', 'TOTAL Tasa') AND 
                                                is_type_3_last_date__c = true AND profitability_type__c IN ('01','02') AND 
                                                profitability_category_type__c IN ('Spread', 'Tasa') ORDER BY account_id__c, 
                                                year_month_day_date__c ASC];
        Final Map<Id, List<Account_Profitability__c>> mapSR = BE_EconomicGroup_Profitability_cls.generateMapProfitability(lstSprdRate);
        Final List<Map<String, Object>> lstSRRecords = new List<Map<String, Object>>();
        Map<String, Object> mapValues;
        for(Id accId: mapClients.keySet()) {
            mapValues = new Map<String, Object>{'Id' => accId, 'CLIENT_NAME' => mapClients.get(accId).Name, 
                                                                    'URL__Id' => URL.getSalesforceBaseUrl().toExternalForm() + '/' + accId,
                                                                    'Spread' => '0 %', 'Tasa' => '0 %'};
            if(mapSR.containsKey(accId) && !mapSR.get(accId).isEmpty()) {
                for(Account_Profitability__c prof: mapSR.get(accId)) {
                    mapValues.put(prof.profitability_category_type__c, prof.currenct_mon_per__c + ' %');
                    mapValues.put('MONTH', prof.period__c);
                }
            }
            lstSRRecords.add(mapValues);
        }
        response.data = lstSRRecords;
        return response;
    }

}