src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>other_phone_number__c</fullName>
        <label>Other phone</label>
        <type>Phone</type>
    </fields>
     <fields>
        <fullName>non_client_code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Non Client Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>phone_area_code__c</fullName>
        <label>Phone Area Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Area_Code_Phone</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Area_Code_Phone.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>41</fullName>
        <label>Amazonas - 41</label>
    </customValue>
    <customValue>
        <fullName>43</fullName>
        <label>Ancash - 43</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Apurimac - 83</label>
    </customValue>
    <customValue>
        <fullName>54</fullName>
        <label>Arequipa - 54</label>
    </customValue>
    <customValue>
        <fullName>66</fullName>
        <label>Ayacucho - 66</label>
    </customValue>
    <customValue>
        <fullName>76</fullName>
        <label>Cajamarca - 76</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Cusco - 84</label>
    </customValue>
    <customValue>
        <fullName>67</fullName>
        <label>Huancavelica - 67</label>
    </customValue>
    <customValue>
        <fullName>62</fullName>
        <label>Huanuco - 62</label>
    </customValue>
    <customValue>
        <fullName>56</fullName>
        <label>Ica - 56</label>
    </customValue>
    <customValue>
        <fullName>64</fullName>
        <label>Junin - 64</label>
    </customValue>
    <customValue>
        <fullName>44</fullName>
        <label>La Libertad - 44</label>
    </customValue>
    <customValue>
        <fullName>74</fullName>
        <label>Lambayeque - 74</label>
    </customValue>
    <customValue>
        <fullName>01</fullName>
        <label>Lima y Callao - 01</label>
    </customValue>
    <customValue>
        <fullName>65</fullName>
        <label>Loreto - 65</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Madre de Dios - 82</label>
    </customValue>
    <customValue>
        <fullName>53</fullName>
        <label>Moquegua - 53</label>
    </customValue>
    <customValue>
        <fullName>63</fullName>
        <label>Pasco - 63</label>
    </customValue>
    <customValue>
        <fullName>73</fullName>
        <label>Piura - 73</label>
    </customValue>
    <customValue>
        <fullName>51</fullName>
        <label>Puno - 51</label>
    </customValue>
    <customValue>
        <fullName>42</fullName>
        <label>San Martin - 42</label>
    </customValue>
    <customValue>
        <fullName>52</fullName>
        <label>Tacna - 52</label>
    </customValue>
    <customValue>
        <fullName>72</fullName>
        <label>Tumbes - 72</label>
    </customValue>
    <customValue>
        <fullName>61</fullName>
        <label>Ucayali - 61</label>
    </customValue>
    <masterLabel>Area Code Phone</masterLabel>
</GlobalValueSet>

src/classes/BE_NonClient_Modify_Helper.cls
/**
   ----------------------------------------------------------------------------------------------------
   @Name <BE_ModifyNonClient_Helper>
   @Author Lolo Michel Bravo Ruiz (lolo.bravo@bbva.com)
   @Date 2020-02-24
   @Description Class BE_ModifyNonClient_Helper
   @Changes
    Date        Author   Email                  Type
    2020-02-24  LMBR     lolo.bravo@bbva.com    Creation
   ----------------------------------------------------------------------------------------------------
 */
public without sharing class BE_NonClient_Modify_Helper {
/** Non Client Exist in Alpha Code */
private static final String EXIST_CODE = 'EXISTENOCLIENTE';
/** Lang Code */
private static final List<String> LANG_CODE = new List<String> {'es','en_US'};
/** private constructor */
private BE_NonClient_Modify_Helper () {}
/**
   @Description call REST API to modify NonClient
   @param  Account acc
   @return Object type BE_SingleRelatedListModal_Ctr.Response Class
 */
public static BE_SingleRelatedListCRUD_Cls.Response  modifyNonClient(Account acc) {
	final Map<String,String>messages= new Map<String,String>();
	final BE_SingleRelatedListCRUD_Cls.Response res=new BE_SingleRelatedListCRUD_Cls.Response();
	final String nonClientCode=[SELECT non_client_code__c FROM Account WHERE Id=:acc.Id].non_client_code__c;
	if(EXIST_CODE.equals(nonClientCode)) {
		try {
			update acc;
			messages.put(LANG_CODE[0], 'No cliente actualizado correctamente');
			messages.put(LANG_CODE[1], 'Non Client updated successfull');
			res.isSuccess=true;
			res.message=messages.get(UserInfo.getLanguage());
		} catch (DmlException ex) {
			res.isSuccess=false;
			res.message=ex.getDmlMessage(0);
		}
	} else {
		final Map<String, Object>placeholderMap = placeholderGenerator(acc);
		final BE_NonClient_Modify_REST request=new BE_NonClient_Modify_REST();
		final System.HttpResponse response=request.invoke(placeholderMap);
		switch on response.getStatusCode() {
			when 204 {
				try {
					update acc;
					messages.put(LANG_CODE[0], 'No cliente actualizado correctamente');
					messages.put(LANG_CODE[1], 'Non Client updated successfull');
					res.isSuccess=true;
					res.message=messages.get(UserInfo.getLanguage());
				} catch (Exception ex) {
					messages.put(LANG_CODE[0], 'Error al actualizar, por favor revise los datos ingresados');
					messages.put(LANG_CODE[1], 'Error when try to update,please review the values inputted');
					res.isSuccess=false;
					res.message=messages.get(UserInfo.getLanguage());
				}
			}
			when 500 {
				messages.put(LANG_CODE[0], 'Servicio no disponible, intentar mas tarde.');
				messages.put(LANG_CODE[1], 'Service not available, try later please');
				res.isSuccess=false;
				res.message=messages.get(UserInfo.getLanguage());
			}
			when 400 {
				messages.put(LANG_CODE[0], 'Error al actualizar, por favor revise los datos ingresados');
				messages.put(LANG_CODE[1], 'Error when try to update,please review the values inputted');
				res.isSuccess=false;
				res.message=messages.get(UserInfo.getLanguage());
			}
			when else {
				messages.put(LANG_CODE[0], 'Error inesperado');
				messages.put(LANG_CODE[1], 'Error not expected');
				res.isSuccess=false;
				res.message=messages.get(UserInfo.getLanguage());
			}
		}
	}
	return res;
}
/**
   @Description update Account
   @param  Account acc
   @return Map<String, Object> with the nonClient
 */
private static Map<String, Object>placeholderGenerator (Account acc) {
	final String nonClientCode=[SELECT non_client_code__c FROM Account WHERE Id=:acc.Id].non_client_code__c;
	final Map<String, Object>placeholderMap=new Map<String, Object>();
	placeholderMap.put('nonClientCode', nonClientCode);
	final BE_NonClient_Modify_REST.NonClient nonClient=new BE_NonClient_Modify_REST.NonClient();
	/** LEGAL NAME */
	nonClient.legalName=acc.Name;
	/** BUSINESS DOCUMENT */
	final BE_NonClient_Modify_REST.BusinessDocuments ruc=new  BE_NonClient_Modify_REST.BusinessDocuments();
	ruc.businessDocumentType.id='RUC';
	ruc.documentNumber=acc.AccountNumber;
	ruc.isVerified=true;
	nonClient.businessDocuments.add(ruc);
	/** EMAIL */
	if(String.isNotBlank(acc.email__c)) {
		final BE_NonClient_Modify_REST.ContactDetails email=new  BE_NonClient_Modify_REST.ContactDetails();
		email.contact.contactDetailType='EMAIL';
		email.contact.address=acc.email__c;
		email.contact.receivesNotifications=true;
		nonClient.contactDetails.add(email);
	}
	/** EMAIL */
	if(String.isNotBlank(acc.Website)) {
		final BE_NonClient_Modify_REST.ContactDetails website=new  BE_NonClient_Modify_REST.ContactDetails();
		website.contact.contactDetailType='WEBSITE';
		website.contact.address=acc.Website;
		nonClient.contactDetails.add(website);
	}
	/** LAND LINE */
	if(String.isNotBlank(acc.other_phone_number__c)) {
		final BE_NonClient_Modify_REST.ContactDetails landLine=new  BE_NonClient_Modify_REST.ContactDetails();
		landLine.isPreferential=true;
		landLine.contact.contactDetailType='LANDLINE';
		landLine.contact.regionalCode=acc.phone_area_code__c;
		landLine.contact.numberSF=acc.other_phone_number__c;
		nonClient.contactDetails.add(landLine);
	}
	/**ADDRESS*/
	if(String.isNotBlank(acc.BillingStreet) && String.isNotBlank(acc.BillingCity) && String.isNotBlank(acc.BillingCountry)) {
		final BE_NonClient_Modify_REST.Addresses address=new  BE_NonClient_Modify_REST.Addresses();
		address.addressType.id='LEGAL';
		address.location.formattedAddress= acc.BillingStreet+acc.BillingCity+ acc.BillingCountry;
		nonClient.addresses.add(address);
	}
	final String jsonNonClient =JSON.serialize(nonClient, true);
	placeholderMap.put('nonClient', jsonNonClient);
	return placeholderMap;
}
}