src/objects/Account_Banking_System_Classification__c.object
<CustomObject>
    <description>Account Banking System Classification Object</description>
    <fields>
        <fullName>Unique_Id__c</fullName>
		<externalId>true</externalId>
        <label>Unique Identifier</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>account_id__c</fullName>
        <description>a relationship with account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Banking System Classification</relationshipLabel>
        <relationshipName>Account_Banking_System_Classification</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>banking_system_classification_desc__c</fullName>
        <label>Classification</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>banking_system_classification_quota_per__c</fullName>
        <label>Classification percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>banking_system_classification_type__c</fullName>
        <label>Classification code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>year_month_day_date__c</fullName>
        <label>Classification date</label>
        <type>Date</type>
    </fields>
    <label>Clasificación SBS</label>
    <nameField>
        <displayFormat>ABSC-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clasificación SBS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BBVA_SBS_Classification_cls.cls
public with sharing class BBVA_SBS_Classification_cls {
    
    
    @AuraEnabled
    public static list<Account_Banking_System_Classification__c>  fecthBBVA_SBS(){ 
        list<Account_Banking_System_Classification__c>   ABSC = new list<Account_Banking_System_Classification__c>(); 
        ABSC = [SELECT ID,account_id__c,banking_system_classification_desc__c,banking_system_classification_quota_per__c,banking_system_classification_type__c,Name,Unique_Id__c,year_month_day_date__c FROM Account_Banking_System_Classification__c];
        return ABSC;
        
    }
    
   @AuraEnabled
    public static list<String> OrderMonths(){
        string mes = 'Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre';
        date myDate = system.Date.today();
        list<string> Months = Mes.split(',');
        list<string> MonthsOrder= new list<String>();
        integer index = myDate.month();
        integer index2 =0 ;
        for(integer i=0;i<12;i++){
        if(i+index<12){    
            MonthsOrder.add(Months[index+i]);
        }else{
            MonthsOrder.add(Months[index2]);
            index2++;
        }     
        }
        
     return MonthsOrder;   
    }
     
   

}