src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>banking_system_classification_desc__c</fullName>
        <label>Banking system classification desc</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>banking_system_classification_type__c</fullName>
        <label>Banking system classification</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>unique_id__c</fullName>
		<externalId>true</externalId>
        <label>Unique identifier</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Account_Banking_System_Classification__c.object
<CustomObject>
    <description>Account Banking System Classification Object</description>
    <fields>
        <fullName>Unique_Id__c</fullName>
		<externalId>true</externalId>
        <label>Unique Identifier</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>account_id__c</fullName>
        <description>a relationship with account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Banking System Classification</relationshipLabel>
        <relationshipName>Account_Banking_System_Classification</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>banking_system_classification_desc__c</fullName>
        <label>Classification</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>banking_system_classification_quota_per__c</fullName>
        <label>Classification percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>banking_system_classification_type__c</fullName>
        <label>Classification code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>year_month_day_date__c</fullName>
        <label>Classification date</label>
        <type>Date</type>
    </fields>
    <label>Clasificación SBS</label>
    <nameField>
        <displayFormat>ABSC-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clasificación SBS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BBVA_SBS_Classification_Test.cls
/**BBVA_SBS_Classification
*  object.
* <p /><p />
* Modification log:<p />
* -------------------------------------------------------------------
* Developer                    Date                Description<p />
* -------------------------------------------------------------------
* Julio Medellin               21/03/2018          Original version.<p />
*
* @author Julio Medellin
*/
@IsTest
public class BBVA_SBS_Classification_Test {
@testSetup static void setup() {
// Create common test accounts
List<Account> testAccts = new List<Account>();
list<Account_Banking_System_Classification__c> testSBS = new list<Account_Banking_System_Classification__c>();
for(Integer i=0;i<5;i++) {
testAccts.add(new Account(Name = 'TestAcct'+i));
}
insert testAccts;


for(Integer i=0;i<5;i++) {
testSBS.add(new Account_Banking_System_Classification__c(
account_id__c=testAccts[i].Id,
banking_system_classification_desc__c=String.valueOf(i),
banking_system_classification_quota_per__c=Decimal.valueOf(i),
banking_system_classification_type__c=String.valueOf(i+1),
Unique_Id__c=String.valueOf(i),
year_month_day_date__c=System.date.today()));

}
insert testSBS;
}
@isTest static void positiveMethod() {
BBVA_SBS_Classification_cls sbs =  new BBVA_SBS_Classification_cls();
system.assertNotEquals(null,BBVA_SBS_Classification_cls.getJSON());
}

}