src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>unique_id__c</fullName>
		<externalId>true</externalId>
        <label>Unique identifier</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/acpl__Account_Planning__c.object
<CustomObject>
    <fields>
        <fullName>acpl__external_reference_id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Account Planning external id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>acpl__gf_account_planning_name__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Full</fullName>
                </value>
                <value>
                    <fullName>Light</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_indvi_lock_edit_ind_type__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Unlock Account Planning</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_launch_name__c</fullName>
        <label>Launch type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>General period</fullName>
                </value>
                <value>
                    <fullName>Period by priority</fullName>
                </value>
                <value>
                    <fullName>Event driven</fullName>
                </value>
                <value>
                    <fullName>Automatic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_launch_period_desc__c</fullName>
        <description>Periodo de lanzamiento con el formato &quot;YY/YY&quot;</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Launch period</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_limit_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_priority_type_name__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_req_validation_ind_type__c</fullName>
        <label>Validation Required</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_status_type_name__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Validation</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_substatus_type_name__c</fullName>
        <label>Sub-status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>acpl__gf_ap_status_type_name__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>AP team not invited</fullName>
                </value>
                <value>
                    <fullName>AP team invited</fullName>
                </value>
                <value>
                    <fullName>Pending pre-validation</fullName>
                </value>
                <value>
                    <fullName>Pre-validated</fullName>
                </value>
                <value>
                    <fullName>Pending review</fullName>
                </value>
                <value>
                    <fullName>Pending validation</fullName>
                </value>
                <value>
                    <fullName>In place</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_validation_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Validation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_validator_user_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned Validator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Plannings1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acpl__gf_mandatory_type__c</fullName>
        <label>Required</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mandatory</fullName>
                </value>
                <value>
                    <fullName>Optional</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <isActive>false</isActive>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                    <isActive>false</isActive>
                    <label>Yes</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>acpl__participant_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plannings</relationshipLabel>
        <relationshipName>Account_Plannings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acpl__proposal_manager_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Global Banker</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Plannings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Planning</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Planning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plannings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/acpl__Account_Planning_Type__c.object
<CustomObject>
    <fields>
        <fullName>acpl__Default_Type__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default Type</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acpl__external_reference_id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Account Planning Type external id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Account Planning Type</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Planning Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Planning Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/acpl__Commercial_Plan_Event__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_account_planning_id__c</fullName>
        <label>Account Planning</label>
        <referenceTo>acpl__Account_Planning__c</referenceTo>
        <relationshipLabel>Commercial Plan Events</relationshipLabel>
        <relationshipName>Commercial_Plan_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>acpl__participant_id__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Commercial Plan Events</relationshipLabel>
        <relationshipName>Commercial_Plan_Events</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Commercial Plan Event</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Commercial Plan Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commercial Plan Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/bupl__BP_GrowthDriver__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_account_planning_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Planning</label>
        <referenceTo>acpl__Account_Planning__c</referenceTo>
        <relationshipLabel>Growth Drivers</relationshipLabel>
        <relationshipName>Growth_Drivers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>bupl__gf_business_growth_rec_number__c</fullName>
        <label>Counter</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Growth Driver</label>
    <nameField>
        <displayFormat>GD_{YYYY}/{MM}-{0000}</displayFormat>
        <label>Growth Driver Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Growth Drivers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/bupl__BusinessPlan__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_account_planning_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Planning</label>
        <referenceTo>acpl__Account_Planning__c</referenceTo>
        <relationshipLabel>Business Plans</relationshipLabel>
        <relationshipName>Business_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_indvi_lock_edit_ind_type__c</fullName>
        <formula>acpl__gf_account_planning_id__r.acpl__gf_ap_indvi_lock_edit_ind_type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AP unlocked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>bupl__gf_ap_public_ind_type__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Public Business Plan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>bupl__gf_business_growth_rec_number__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Growth Drivers Created</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>bupl__status_type__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Validation</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Business Plan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>unique_id__c</fullName>
        <description>Internal control code</description>
        <label>Unique identifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>Unique_id__c</fullName>
        <externalId>true</externalId>
        <label>Unique_id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
	<fields>
        <fullName>Unique_id__c</fullName>
        <externalId>true</externalId>
        <label>Unique_id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
	<fields>
        <fullName>Unique_id__c</fullName>
        <externalId>true</externalId>
        <label>Unique_id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
	<fields>
        <fullName>User_position_equivalence__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>User position equivalence</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User_Position_equivalence__c.object
<CustomObject>
    <fields>
        <fullName>User_position_equivalence__c</fullName>
        <label>User position equivalence</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Cargo Equivalente</label>
    <nameField>
        <displayFormat>E-{0000000000}</displayFormat>
        <label>User Position equivalence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cargos Equivalentes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AP_Trigger_Helper_tst.cls
/** @Name AP_Trigger_Helper_tst
* @Author Jair Anton jair.anton.contractor@bbva.com
* @Date Created: 2021-08-19
* Jair Anton 		19/08/2021		Cobertura clase AP_ConvertCPE_cls
*/
@isTest
public class AP_Trigger_Helper_tst {
    /** @Description MAP_USERS*/
	Final static Map<String, User> MAP_USERS = AP_FactoryTest_tst.obtainUsers();
    /**@Description IN_PLACE */
    Final static String IN_PLACE = 'In place';
    /** @Description EJECUTIVO*/
	Final static String EJECUTIVO = 'EJECUTIVO';
    /** @Description IN_PROGRESS*/
    Final static String IN_PROGRESS = 'In Progress';
    /**@Description VALIDATED*/
    Final static String VALIDATED = 'Validated';
    /**@Description SUCCESS*/
    Final static String SUCCESS = 'Success';
    /**@Description RECORD_NNAME*/
    Final static String RECORD_NAME = 'AP_RECORD_102 - 2020-05-31';

    /* setUp */
    @TestSetup
    static void setUp() {
		AP_FactoryTest_tst.forSetUp();
		AP_FactoryTest_tst.generateProduct();
        
        Final User usr1 = [SELECT Id, Name FROM User WHERE LastName = 'GERENTE'];
        Final String perfil=[SELECT Id FROM Profile WHERE name='Ejecutivo'].Id;
        Final Id ejecutivoRole = [SELECT Id FROM UserRole WHERE DeveloperName = 'EJECUTIVO_BANCA_EMPRESAS_MIRAFLORES' LIMIT 1].Id;
        Map<Schema.SObjectField, Object> mapFields = new Map<Schema.SObjectField, Object>{User.LastName => 'EJECUTIVO 2', User.ProfileId => perfil, 
            User.user_position_equivalence__c => 'User Test', User.ManagerId => usr1.Id, User.UserRoleId => ejecutivoRole};
		TestFactory.getUser(true, mapFields);
        mapFields = new Map<Schema.SObjectField, Object>{User.LastName => 'EJECUTIVO 3', User.ProfileId => perfil, 
            User.user_position_equivalence__c => 'User Test', User.ManagerId => usr1.Id, User.UserRoleId => ejecutivoRole};
		TestFactory.getUser(true, mapFields);

        Final User admin = [SELECT Id FROM User WHERE Id=:UserInfo.getUserId()];
        Final Account acc = [SELECT Id FROM Account LIMIT 1];
        Final User usr2 = [SELECT Id, LastName FROM User WHERE LastName = 'EJECUTIVO'];
        System.runAs(admin) {
            createAP(acc.Id, usr2.Id, true);
            
            final Product2 prod = TestFactory.createProduct();
            prod.IsActive = true;
            prod.ProductCode = 'PC00012';
            prod.Unique_id__c = '0292230_NEW';
            update prod;
            insert new PriceBookEntry(Product2Id=prod.Id, Pricebook2Id=Test.getStandardPricebookId(), UnitPrice=0, IsActive=true, CurrencyIsoCode='USD');
            final fprd__GBL_Product_version__c prodVersion = new fprd__GBL_Product_version__c(fprd__Active__c = true, fprd__Product__c = prod.Id, fprd__Version_number__c = 1);
            prodVersion.CurrencyIsoCode = 'USD';
            insert prodVersion;
        }
    }
    
    private static void createAP(String account, String usuario, Boolean unlock) {
        final List<acpl__Account_Planning_Type__c> apTypes = [SELECT Id FROM acpl__Account_Planning_Type__c WHERE acpl__external_reference_id__c = 'TypeTest1' LIMIT 1];
        acpl__Account_Planning_Type__c apType;
        if(apTypes.isEmpty()) {
            apType = new acpl__Account_Planning_Type__c(Name = 'Question Catalog',acpl__Default_Type__c = false, acpl__external_reference_id__c = 'TypeTest1');
            insert apType;
        } else {
            apType = apTypes[0];
        }
		final acpl__Account_Planning__c accountPlanning = new acpl__Account_Planning__c(NAME = 'Account Planning', ACPL__GF_ACCOUNT_PLANNING_NAME__C = 'Full', 
                                                                                        ACPL__GF_AP_INDVI_LOCK_EDIT_IND_TYPE__C = unlock, ACPL__GF_AP_LAUNCH_NAME__C = 'General period', 
                                                                                        ACPL__GF_AP_LAUNCH_PERIOD_DESC__C = '20/20', ACPL__GF_AP_LIMIT_DATE__C = System.today()+31, 
                                                                                        ACPL__GF_AP_REQ_VALIDATION_IND_TYPE__C = 'Yes', ACPL__GF_AP_STATUS_TYPE_NAME__C = 'Not started', 
                                                                                        ACPL__GF_AP_SUBSTATUS_TYPE_NAME__C = 'Not started', ACPL__GF_MANDATORY_TYPE__C = 'Mandatory', 
                                                                                        acpl__participant_id__c = account, acpl__proposal_manager_id__c = usuario,
                                                                                        acpl__gf_ap_priority_type_name__c = 'High', acpl__gf_ap_validator_user_id__c = null, 
                                                                                        acpl__Account_Planning_Type__c = apType.Id, acpl__gf_ap_validation_date__c = Date.today());
        
        insert accountPlanning;
        
        
        final bupl__BusinessPlan__c bussPlan = new bupl__BusinessPlan__c(Name = 'Plan de Negocio AP_RECORD_102', bupl__gf_ap_public_ind_type__c = false, 
                                                                        bupl__gf_business_growth_rec_number__c = 1, bupl__status_type__c = 'Not started', 
                                                                        acpl__gf_account_planning_id__c = accountPlanning.id);
        insert bussPlan;
    }

	   /**
	 * @Description Test update record
	 */
	@isTest
	static void updateAPActionsTest() {
        Final Map<Id, acpl__Account_Planning__c> apMap = new Map<Id, acpl__Account_Planning__c>();
        final acpl__Account_Planning__c accPlan = [SELECT Id, NAME, ACPL__GF_ACCOUNT_PLANNING_NAME__C, ACPL__GF_AP_INDVI_LOCK_EDIT_IND_TYPE__C, ACPL__GF_AP_LAUNCH_NAME__C, ACPL__GF_AP_LAUNCH_PERIOD_DESC__C, ACPL__GF_AP_LIMIT_DATE__C, 
                                                    ACPL__GF_AP_REQ_VALIDATION_IND_TYPE__C, ACPL__GF_AP_STATUS_TYPE_NAME__C, ACPL__GF_AP_SUBSTATUS_TYPE_NAME__C, ACPL__GF_MANDATORY_TYPE__C, acpl__participant_id__c, 
                                                    acpl__proposal_manager_id__c, acpl__gf_ap_priority_type_name__c, acpl__gf_ap_validator_user_id__c, acpl__Account_Planning_Type__c, acpl__gf_ap_validation_date__c 
                                                   FROM acpl__Account_Planning__c WHERE Name = 'Account Planning' LIMIT 1];
		
		Test.startTest();
			System.runAs(MAP_USERS.get(EJECUTIVO)) {
				try {	
					createActions(accPlan);
					accPlan.acpl__gf_ap_status_type_name__c = VALIDATED;
					accPlan.acpl__gf_ap_substatus_type_name__c = IN_PLACE;
					accPlan.acpl__gf_ap_indvi_lock_edit_ind_type__c = false;
                    
        			apMap.put(accPlan.Id, accPlan);
					AP_Trigger_Helper.postValidated(apMap);
					updateActions(accPlan);

					accPlan.acpl__gf_ap_status_type_name__c = VALIDATED;
					accPlan.acpl__gf_ap_substatus_type_name__c = IN_PLACE;
					accPlan.acpl__gf_ap_indvi_lock_edit_ind_type__c = false;
					update accPlan;
				} catch(Exception e) {
					System.debug(e.getMessage());
				}
			}
		Test.stopTest();
        Final List<acpl__Commercial_Plan_Event__c> cpeList = [SELECT Id, Name, acpl__gf_account_planning_id__c FROM acpl__Commercial_Plan_Event__c WHERE acpl__gf_account_planning_id__c =: accPlan.Id];
        System.assert(cpeList.size() == 3, SUCCESS);
	}

       /**
	 * @Description Test update record with GD
	 */
	@isTest
	static void updateAPGDTest() {
        Final Map<Id, acpl__Account_Planning__c> apMap = new Map<Id, acpl__Account_Planning__c>();
        final acpl__Account_Planning__c accPlan = [SELECT Id, NAME, ACPL__GF_ACCOUNT_PLANNING_NAME__C, ACPL__GF_AP_INDVI_LOCK_EDIT_IND_TYPE__C, ACPL__GF_AP_LAUNCH_NAME__C, ACPL__GF_AP_LAUNCH_PERIOD_DESC__C, ACPL__GF_AP_LIMIT_DATE__C, 
                                                    ACPL__GF_AP_REQ_VALIDATION_IND_TYPE__C, ACPL__GF_AP_STATUS_TYPE_NAME__C, ACPL__GF_AP_SUBSTATUS_TYPE_NAME__C, ACPL__GF_MANDATORY_TYPE__C, acpl__participant_id__c, 
                                                    acpl__proposal_manager_id__c, acpl__gf_ap_priority_type_name__c, acpl__gf_ap_validator_user_id__c, acpl__Account_Planning_Type__c, acpl__gf_ap_validation_date__c 
                                                   FROM acpl__Account_Planning__c WHERE Name = 'Account Planning' LIMIT 1];
		
        Final bupl__BusinessPlan__c bpAux = [SELECT Id, acpl__gf_account_planning_id__c FROM bupl__BusinessPlan__c LIMIT 1];

		Test.startTest();
			System.runAs(MAP_USERS.get(EJECUTIVO)) {
				try {	
                    createGrowthDriver(accPlan, bpAux);
					accPlan.acpl__gf_ap_status_type_name__c = VALIDATED;
					accPlan.acpl__gf_ap_substatus_type_name__c = IN_PLACE;
					accPlan.acpl__gf_ap_indvi_lock_edit_ind_type__c = false;
                    accPlan.acpl__gf_ap_validation_date__c = Date.today();
                    
        			apMap.put(accPlan.Id, accPlan);
					AP_Trigger_Helper.postValidated(apMap);
					updateGrowthDriver(accPlan);
                    
					AP_Trigger_Helper.postValidated(apMap);
				} catch(Exception e) {
					System.debug(e.getMessage());
				}
			}
		Test.stopTest();

		Final bupl__BP_GrowthDriver__c gdItem = [SELECT Id, bupl__solution_category_desc__c, acpl__gf_account_planning_id__c FROM bupl__BP_GrowthDriver__c WHERE acpl__gf_account_planning_id__c =: accPlan.Id LIMIT 1];
        System.assert(gdItem.bupl__solution_category_desc__c == '0292230_NEW', SUCCESS);
	}

       /**
	 * @Description Test update record with GD
	 */
	@isTest
	static void updateAPAmountTest() {
        Final Map<Id, acpl__Account_Planning__c> apMap = new Map<Id, acpl__Account_Planning__c>();
        final acpl__Account_Planning__c accPlan = [SELECT Id, NAME, ACPL__GF_ACCOUNT_PLANNING_NAME__C, ACPL__GF_AP_INDVI_LOCK_EDIT_IND_TYPE__C, ACPL__GF_AP_LAUNCH_NAME__C, ACPL__GF_AP_LAUNCH_PERIOD_DESC__C, ACPL__GF_AP_LIMIT_DATE__C, 
                                                    ACPL__GF_AP_REQ_VALIDATION_IND_TYPE__C, ACPL__GF_AP_STATUS_TYPE_NAME__C, ACPL__GF_AP_SUBSTATUS_TYPE_NAME__C, ACPL__GF_MANDATORY_TYPE__C, acpl__participant_id__c, 
                                                    acpl__proposal_manager_id__c, acpl__gf_ap_priority_type_name__c, acpl__gf_ap_validator_user_id__c, acpl__Account_Planning_Type__c, acpl__gf_ap_validation_date__c 
                                                   FROM acpl__Account_Planning__c WHERE Name = 'Account Planning' LIMIT 1];
		
        Final bupl__BusinessPlan__c bpAux = [SELECT Id, acpl__gf_account_planning_id__c FROM bupl__BusinessPlan__c LIMIT 1];

		Test.startTest();
			System.runAs(MAP_USERS.get(EJECUTIVO)) {
				try {	
                    createGrowthDriver(accPlan, bpAux);
					accPlan.acpl__gf_ap_status_type_name__c = VALIDATED;
					accPlan.acpl__gf_ap_substatus_type_name__c = IN_PLACE;
					accPlan.acpl__gf_ap_indvi_lock_edit_ind_type__c = false;
                    accPlan.acpl__gf_ap_validation_date__c = Date.today();
                    
        			apMap.put(accPlan.Id, accPlan);
					AP_Trigger_Helper.postValidated(apMap);
					updateAmountGD(accPlan);
                    
					AP_Trigger_Helper.postValidated(apMap);
				} catch(Exception e) {
					System.debug(e.getMessage());
				}
			}
		Test.stopTest();
        Final bupl__BP_GrowthDriver__c gdItem = [SELECT Id, bupl__solution_category_desc__c, acpl__gf_account_planning_id__c, Amount__c FROM bupl__BP_GrowthDriver__c WHERE acpl__gf_account_planning_id__c =: accPlan.Id LIMIT 1];
        System.assert(gdItem.Amount__c == 100300, SUCCESS);

	}

	private static void createActions(acpl__Account_Planning__c accPlan) {	
        Final User usr1 = [SELECT Id, Name FROM User WHERE LastName = 'EJECUTIVO 2'];
        Final List<acpl__Commercial_Plan_Event__c> cpeList = new List<acpl__Commercial_Plan_Event__c>();
		cpeList.add(new acpl__Commercial_Plan_Event__c(Name = RECORD_NAME, acpl__gf_account_planning_id__c = accPlan.Id, acpl__gf_comm_plan_event_type_name__c = 'Task', 
														acpl__gf_event_date__c = System.today(), acpl__participant_id__c = accPlan.acpl__participant_id__c));
    	cpeList.add(new acpl__Commercial_Plan_Event__c(Name = RECORD_NAME, acpl__gf_account_planning_id__c = accPlan.Id, acpl__gf_comm_plan_event_type_name__c = 'Opportunity', 
					acpl__gf_event_date__c = System.today(), acpl__participant_id__c = accPlan.acpl__participant_id__c));
		cpeList.add(new acpl__Commercial_Plan_Event__c(Name = RECORD_NAME, acpl__gf_account_planning_id__c = accPlan.Id, acpl__gf_comm_plan_event_type_name__c = 'Visit', 
					acpl__gf_event_date__c = System.today(), acpl__participant_id__c = accPlan.acpl__participant_id__c, Asiggned_User__c = usr1.Id));
        
        insert cpeList;
	}

	private static void updateActions(acpl__Account_Planning__c accPlan) {
		Final List<acpl__Commercial_Plan_Event__c> cpeList = [SELECT Id, Name, acpl__gf_account_planning_id__c, acpl__gf_comm_plan_event_type_name__c, acpl__gf_event_date__c, acpl__participant_id__c 
																FROM acpl__Commercial_Plan_Event__c WHERE acpl__gf_account_planning_id__c =: accPlan.Id];

		for(acpl__Commercial_Plan_Event__c item : cpeList) {
			item.acpl__gf_event_date__c = System.today().addDays(30);
		}
        
        update cpeList;
	}

    private static void createGrowthDriver(acpl__Account_Planning__c accPlan, bupl__BusinessPlan__c bpAux) {
        Final User usr1 = [SELECT Id, Name FROM User WHERE LastName = 'EJECUTIVO 2'];
        Final bupl__BP_GrowthDriver__c growthDriver = new bupl__BP_GrowthDriver__c(bupl__gf_business_plan_id__c = bpAux.Id, bupl__gf_business_growth_rec_number__c = 1, ExpectedDate__c = System.today(), 
                                     bupl__solution_category_desc__c = '0292235_NEW', CurrencyIsoCode = 'PEN', bupl__solution_category_id__c = 'Riesgo de firma', 
                                     acpl__gf_account_planning_id__c = accPlan.Id);
		
		insert growthDriver;
        
        Final acpl__Commercial_Plan_Event__c cpeItem = new acpl__Commercial_Plan_Event__c(Name = RECORD_NAME, acpl__gf_account_planning_id__c = accPlan.Id, acpl__gf_comm_plan_event_type_name__c = 'Opportunity', 
					acpl__gf_event_date__c = System.today(), acpl__participant_id__c = accPlan.acpl__participant_id__c, GrowthDriver__c = growthDriver.Id, Asiggned_User__c = usr1.Id);
        insert cpeItem;
    }

    private static void updateGrowthDriver(acpl__Account_Planning__c accPlan) {
        Final User usr1 = [SELECT Id, Name FROM User WHERE LastName = 'EJECUTIVO 3'];    
		Final List<bupl__BP_GrowthDriver__c> growthList = [SELECT Id, bupl__gf_business_plan_id__c, bupl__gf_business_growth_rec_number__c, ExpectedDate__c, bupl__solution_category_desc__c, 
							CurrencyIsoCode, bupl__solution_category_id__c, acpl__gf_account_planning_id__c FROM bupl__BP_GrowthDriver__c WHERE acpl__gf_account_planning_id__c =: accPlan.Id LIMIT 1];
    
		growthList[0].CurrencyIsoCode = 'USD';
        growthList[0].bupl__solution_category_desc__c = '0292230_NEW';
		update growthList;
        
        Final List<acpl__Commercial_Plan_Event__c> cpeList = [SELECT Id, Name, acpl__gf_account_planning_id__c, acpl__gf_comm_plan_event_type_name__c, acpl__gf_event_date__c, acpl__participant_id__c, Asiggned_User__c,
														GrowthDriver__c FROM acpl__Commercial_Plan_Event__c WHERE acpl__gf_account_planning_id__c =: accPlan.Id];

        cpeList[0].Asiggned_User__c = usr1.Id;
        update cpeList;
    }

    private static void updateAmountGD(acpl__Account_Planning__c accPlan) {
        Final User usr1 = [SELECT Id, Name FROM User WHERE LastName = 'EJECUTIVO 3'];    
		Final List<bupl__BP_GrowthDriver__c> growthList = [SELECT Id, bupl__gf_business_plan_id__c, bupl__gf_business_growth_rec_number__c, ExpectedDate__c, bupl__solution_category_desc__c, 
							CurrencyIsoCode, bupl__solution_category_id__c, acpl__gf_account_planning_id__c FROM bupl__BP_GrowthDriver__c WHERE acpl__gf_account_planning_id__c =: accPlan.Id LIMIT 1];
    
		growthList[0].Amount__c = 100300;
		update growthList;
        
        Final List<acpl__Commercial_Plan_Event__c> cpeList = [SELECT Id, Name, acpl__gf_account_planning_id__c, acpl__gf_comm_plan_event_type_name__c, acpl__gf_event_date__c, acpl__participant_id__c, Asiggned_User__c,
														GrowthDriver__c FROM acpl__Commercial_Plan_Event__c WHERE acpl__gf_account_planning_id__c =: accPlan.Id];

        cpeList[0].Asiggned_User__c = usr1.Id;
        update cpeList;
    }
}