src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>branch_name__c</fullName>
        <formula>branch_id__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Main Branch</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Account_Banking_System_Classification__c.object
<CustomObject>
    <description>Account Banking System Classification Object</description>
    <fields>
        <fullName>account_id__c</fullName>
        <description>a relationship with account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Banking System Classification</relationshipLabel>
        <relationshipName>Account_Banking_System_Classification</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Clasificación SBS</label>
    <nameField>
        <displayFormat>ABSC-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clasificación SBS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Account_BBVA_Classification__c.object
<CustomObject>
    <description>Clasificación BBVA</description>
    <fields>
        <fullName>account_id__c</fullName>
        <description>Cliente</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account BBVA Classifications</relationshipLabel>
        <relationshipName>Account_BBVA_Classifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Clasificación BBVA</label>
    <nameField>
        <displayFormat>ABC- {0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clasificaciones BBVA</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Account_Rating__c.object
<CustomObject>
    <fields>
        <fullName>account_id__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Ratings</relationshipLabel>
        <relationshipName>Account_Ratings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Rating</label>
    <nameField>
        <displayFormat>ARG-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ratings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Branch__c.object
<CustomObject>
    <description>Objeto de Oficina</description>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/compromiso__c.object
<CustomObject>
    <fields>
        <fullName>Oportunidad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Oportunidad</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>compromisos</relationshipLabel>
        <relationshipName>compromisos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>compromiso</label>
    <nameField>
        <label>Nombre de compromiso</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>compromisos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/fprd__GBL_Guarantee__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>guarantees</relationshipLabel>
        <relationshipName>guarantees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Guarantee</label>
    <nameField>
        <label>Guarantee</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>guarantees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/fprd__GBL_Intervener__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>interveners</relationshipLabel>
        <relationshipName>interveners</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Intervener</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>interveners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User_Branch__c.object
<CustomObject>
    <description>Usuario Oficina</description>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Usuario</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Users_Branches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>branch_name__c</fullName>
        <description>Oficina</description>
        <label>Branch</label>
        <referenceTo>Branch__c</referenceTo>
        <relationshipLabel>Branch users</relationshipLabel>
        <relationshipName>Branches_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Oficina de Usuario</label>
    <nameField>
        <displayFormat>UO-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Oficinas de Usuario</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OpportunityPDFWrap.cls
public  virtual class OpportunityPDFWrap {

    public static OpportunityLineItem OLI {get;set;}
    Public Static Account_BBVA_Classification__c ABBVAC {get;set;}
    Public static Account_Banking_System_Classification__c  CSBS {get;set;}
    Public static Product2 Product {get;set;}
    Public static Account Client {get;set;}
    Public static Contact Contacto {get;set;}
    Public static User_Branch__c usuarioOficina {get;set;}
    Public static Branch__c Oficina {get;set;}
    Public static Account_Rating__c  Rating {get;set;}
    Public static list<fprd__GBL_Intervener__c > Intervenientes {get;set;}
    Public static list<fprd__GBL_Guarantee__c> Garantias {get;set;}
    public static AggregateResult[] totalComprimisos{get;set;}
    public static Integer totalC {get;set;}
    public static String title{get;set;}
    public static opportunity opp{get;set;}
    public static string Modalidad{get;set;}
    public static map<String,String>checkDoc{get;set;}
    private static list<Attachment> docs{get;set;}

    private static String getQuery(String Objeto){
        String SOQLQuery;
       SObjectType objType = Schema.getGlobalDescribe().get(Objeto);
       Map<String,Schema.SObjectField> Mfields = objType.getDescribe().fields.getMap();
       SOQLQuery = 'SELECT ';
        for(Schema.SObjectField mf : Mfields.values()){
          schema.describefieldresult dfield = mf.getDescribe();
            system.debug(String.valueOf(dfield.getType()));
            if(String.valueOf(dfield.getType())=='PICKLIST'){
                SOQLQuery += 'toLabel('+dfield.getname() +'), ';
                    } else{
                        SOQLQuery += dfield.getname() +', ';
                    }
        }
    SOQLQuery =SOQLQuery.substring(0, SOQLQuery.length() - 2);
    SOQLQuery+=' FROM '+Objeto;
    return SOQLQuery;
    }



    public static string setValues(String Oppid){
        string msg;
        checkDoc = new map<string,string>();
        checkDoc.put('Instrucción de transferencia', 'No');
        checkDoc.put('Sustento de operación Comex: Copia Bill of lading ', 'No');
        checkDoc.put('Sustento de operación Comex: Facturas o Letras', 'No');
        checkDoc.put('Pagaré', 'No');
        checkDoc.put('Facturas', 'No');
        checkDoc.put('Tasa', 'No');
        checkDoc.put('Otros documento', 'No');

        try{
            msg= 'Datos incompletos en oportunidad';
            opp = database.query(getQuery('Opportunity')+' WHERE id =\''+Oppid+'\' LIMIT 1');
            Modalidad =opp.Risk_modality_type__c;
            msg= 'Datos incompletos en producto oportunidad';
            OLI = database.query(getQuery('OpportunityLineItem')+' WHERE  OpportunityID =\''+Oppid +'\'ORDER BY CreatedDate DESC LIMIT 1');
            msg= 'Datos incompletos en producto';
            Product = database.query(getQuery('Product2')+' WHERE  Id =\''+OLI.Product2Id +'\' LIMIT 1');
            msg= 'Datos incompletos en cliente';
            Client =database.query(getQuery('Account')+' WHERE  Id =\''+opp.Accountid +'\' LIMIT 1');
            msg= 'Datos incompletos en clasificación BBVA-Cliente';
            ABBVAC = database.query(getQuery('Account_BBVA_Classification__c')+' WHERE  account_id__c =\''+Client.ID +'\' LIMIT 1');
            msg= 'Datos incompletos en SBS';
            CSBS= database.query(getQuery('Account_Banking_System_Classification__c')+' WHERE  account_id__c =\''+Client.ID +'\' LIMIT 1');
            msg= 'Datos incompletos en contacto';
            Contacto = database.query(getQuery('Contact')+' WHERE  AccountId =\''+Client.ID +'\' LIMIT 1');
            msg= 'Datos incompletos en usuario oficina';
            usuarioOficina = database.query(getQuery('User_Branch__c')+' WHERE  User__c =\''+opp.ownerId +'\' LIMIT 1');
            msg= 'Datos incompletos en Oficina';
            oficina =  database.query(getQuery('Branch__c')+' WHERE  id =\''+usuarioOficina.branch_name__c +'\' LIMIT 1');
            msg= 'Datos incompletos en calificación cliente';
            Rating =  database.query(getQuery('Account_Rating__c')+' WHERE  account_id__c =\''+Client.Id+'\' ORDER BY createdDate LIMIT 1');
            msg= 'Datos incompletos en intervieniente';
            Intervenientes = database.query(getQuery('fprd__GBL_Intervener__c')+' WHERE  Opportunity__c =\''+OppId+'\'');
            msg= 'Datos incompletos en garantias';
            Garantias = database.query(getQuery('fprd__GBL_Guarantee__c')+' WHERE  Opportunity__c =\''+Oppid+'\'');
            totalComprimisos = [SELECT COUNT_DISTINCT(Id) total FROM compromiso__c WHERE Oportunidad__c =:Oppid];
            totalC=Integer.valueOf(totalComprimisos[0].get('total'));
            docs = [SELECT ID,Name FROM attachment WHERE ParentId =:Oppid];
            for(attachment d : docs){
                if(d.name =='Instrucción de transferencia'){
                    checkDoc.put('Instrucción de transferencia', 'Sí');
                }
                if(d.name =='Sustento de operación Comex: Copia Bill of lading'){
                    checkDoc.put('Sustento de operación Comex: Copia Bill of lading', 'Sí');
                }
                if(d.name =='Sustento de operación Comex: Facturas o Letras'){
                    checkDoc.put('Sustento de operación Comex: Facturas o Letras', 'Sí');
                }
                if(d.name =='Pagaré'){
                    checkDoc.put('Pagaré', 'Sí');
                }
                if(d.name =='Facturas'){
                    checkDoc.put('Facturas', 'Sí');
                }
                if(d.name =='Tasa'){
                    checkDoc.put('Tasa', 'Sí');
                }
                if(d.name !='Facturas' && d.name !='Tasa' && d.name !='Facturas' && d.name !='Pagaré' && d.name !='Sustento de operación Comex: Facturas o Letras' && d.name !='Sustento de operación Comex: Copia Bill of lading' && d.name !='Instrucción de transferencia'){
                    checkDoc.put('Otros documento', 'Sí');
                }
            }
            msg= 'SUCCESS';

            title = 'PDF Formalización '+Opportunity.Name;
        }catch(System.Exception e){
            system.debug('Exception : '+e.getMessage());
            return msg;
        }

        return msg;
    }


}