src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>segment_desc__c</fullName>
        <label>Segment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/BE_BailLetterCombination__c.object
<CustomObject>
    <fields>
        <fullName>BailObject__c</fullName>
        <label>BailObject</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Beneficiary__c</fullName>
        <label>Beneficiary</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PEN</fullName>
                </value>
                <value>
                    <fullName>USD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UniqueId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>UniqueId</label>
        <length>9</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>BE_BailLetterCombination</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>BE_BailLetterCombination Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BE_BailLetterCombinations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>pricing_model_id__c</fullName>
        <label>Pricing model</label>
        <length>10</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
	<fields>
        <fullName>Type_of_quote__c</fullName>
        <label>Tipo de cotización</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Type_of_quote_stock</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Type_of_quote_stock.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>COTIZADOR</fullName>
    </customValue>
    <customValue>
        <fullName>Tarifario</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
    </customValue>
    <description>Valores del tipo de cotizacion</description>
    <masterLabel>Type of quote</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/SanctionPrice_ctrl_Test.cls
@istest
public class SanctionPrice_ctrl_Test {
	@testSetup
	static void setData() {
		Final Account acc = TestFactory.createAccount();
		Final Opportunity opp = TestFactory.createOpportunity(acc.Id, UserInfo.getUserId());
		Final Product2 prod = TestFactory.createProduct();
		Final OpportunityLineItem oli = TestFactory.createOLI(opp.Id, prod.Id);
        Final BE_BailLetterCombination__c bailLetter = new BE_BailLetterCombination__c(UniqueId__c='USD020101', Currency__c='USD', Beneficiary__c = '02', BailObject__c='01', Period__c='01');
        insert bailLetter;
	}

	@isTest
	static void test_method_one() {
		Final List<Account> lstAccount = [SELECT Id FROM Account];
		lstAccount[0].segment_desc__c = 'SUPERIOR';
		update lstAccount;

		Final List<Product2> lstProd = [SELECT Id, Type_of_quote__c FROM Product2];
		lstProd[0].Type_of_quote__c = 'Tarifario';
		update lstProd;
		
        Final List<Opportunity> lstOpp = [SELECT Id FROM Opportunity];
		Final Map<String, Object> mapReturnInfo1 = SanctionPrice_ctrl.calculateRate(lstOpp[0].Id);
		SanctionPrice_ctrl.getInfo(lstOpp[0].Id);
		SanctionPrice_ctrl.getInfoAnalist(lstOpp[0].Id);
		SanctionPrice_ctrl.getInfoWithoutDefaultValues(lstOpp[0].Id);

		System.assert((Boolean)mapReturnInfo1.get('hasOLI'), 'success!!!');

		delete  [SELECT Id FROM OpportunityLineItem];
		Final Map<String, Object> mapReturnInfo5 = SanctionPrice_ctrl.calculateRate(lstOpp[0].Id);
		SanctionPrice_ctrl.getInfo(lstOpp[0].Id);
		SanctionPrice_ctrl.getInfoAnalist(lstOpp[0].Id);
		SanctionPrice_ctrl.getInfoWithoutDefaultValues(lstOpp[0].Id);
	}
    
	@isTest
	static void test_method_two() {
		Final List<Account> lstAccount = [SELECT Id FROM Account];
		lstAccount[0].segment_desc__c = 'SUPERIOR';
		update lstAccount;

		Final List<Product2> lstProd = [SELECT Id, Type_of_quote__c FROM Product2];
		lstProd[0].Type_of_quote__c = 'Web';
		update lstProd;
		
        Final List<Opportunity> lstOpp = [SELECT Id FROM Opportunity];
        
		insert new iaso__GBL_Rest_Services_Url__c(Name = 'GrantingTickets', iaso__Url__c = 'https://validation/ok', iaso__Cache_Partition__c = 'local.CredentialsPeru');
		insert new iaso__GBL_Rest_Services_Url__c(Name = 'CalculateRate', iaso__Url__c = 'https://CalculateRate/ok', iaso__Cache_Partition__c = 'local.CredentialsPeru');
		insert new iaso__GBL_Rest_Services_Url__c(Name = 'CreateQuotationRequest', iaso__Url__c = 'https://CreateRequestApproved/OK', iaso__Cache_Partition__c = 'local.CredentialsPeru');
		Test.setMock(HttpCalloutMock.class, new Integration_MockGenerator());
		iaso.GBL_Mock.setMock(new Integration_MockGenerator());
		Final PriceRate_helper pricehHelper = new PriceRate_helper(lstOpp[0].Id, false);
		
        Test.startTest();

		System.HttpResponse priceResponse = pricehHelper.invoke();
		Final PriceRate_helper.ResponseSimulateRate_Wrapper responseWrapper = pricehHelper.parse(priceResponse.getBody());
		SanctionPrice_ctrl.calculateRate(lstOpp[0].Id);
		SanctionPrice_ctrl.getInfo(lstOpp[0].Id);
        SanctionPrice_ctrl.requestQuote(lstOpp[0].Id);
		Final Map<String, Object> mapReturnInfo1 = SanctionPrice_ctrl.getInfoAnalist(lstOpp[0].Id);
		System.assert((Boolean)mapReturnInfo1.get('hasOLI'), 'success!!!');

		Test.stopTest();
	}
    
    @isTest
	static void test_method_fail() {
		Final List<Product2> lstProd = [SELECT Id, Type_of_quote__c FROM Product2];
		lstProd[0].Type_of_quote__c = 'Web';
		update lstProd;
        Final List<OpportunityLineItem> lstOli = [SELECT Id, OpportunityId FROM OpportunityLineItem LIMIT 1];
        lstOli[0].pricing_model_id__c = '11';
        update lstOli;
        SanctionPrice_ctrl.calculateRate(null);
		SanctionPrice_ctrl.getInfo(null);
		SanctionPrice_ctrl.getInfoAnalist(null);
		SanctionPrice_ctrl.getInfoWithoutDefaultValues(null);
		Final String result = (String)SanctionPrice_ctrl.calculateRate(lstOli[0].OpportunityId).get('genericError');
        System.assert(!String.isBlank(result), 'Error!!!');
	}
}