src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>unique_id__c</fullName>
		<externalId>true</externalId>
        <label>Unique identifier</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Account_Accounting__c.object
<CustomObject>
    <fields>
        <fullName>account_id__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Accountings</relationshipLabel>
        <relationshipName>Account_Accountings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>gl_account_amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>gl_account_id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>gl_account_id_path_desc__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Level</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>gl_account_path_position_id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Order</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>parent_gl_account_id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Parent Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>unique_id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Unique Identifier</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>year_month_day_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Estado Financiero</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados Financieros</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Account_variation_information__c.object
<CustomObject>
    <fields>
        <fullName>account_id__c</fullName>
        <label>account_id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account variation information</relationshipLabel>
        <relationshipName>Account_variation_information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>indicator_name__c</fullName>
        <label>indicator_name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>indicator_update_date__c</fullName>
        <label>indicator_update_date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>unique_id__c</fullName>
        <label>unique_id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>validation_color_type__c</fullName>
        <label>validation_color_type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Account variation information</label>
    <nameField>
        <displayFormat>T-{0000000000}</displayFormat>
        <label>Account variation information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account variation information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>decision_making_desc__c</fullName>
        <label>Decisor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Si</fullName>
                    <label>Sí</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>prof_position_type__c</fullName>
        <label>Position</label>
        <picklist>
            <picklistValues>
                <fullName>ACCIONISTA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADMINISTRADOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APODERADO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASISTENTE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DIRECTORIO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE COMERCIAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE ADMINISTRACION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE ADMINISTRACION Y FINANZAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE CONTABILIDAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE FINANZAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE OPERACIONES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE RRHH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE GENERAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JEFE DE ADMINISTRACIÓN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JEFE DE ADMINISTRACION Y FINANZAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JEFE DE CONTABILIDAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JEFE DE FINANZAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JEFE DE TESORERIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTROS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRESIDENTE DE DIRECTORIO</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>		
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACCIONISTA</fullName>
                </value>
                <value>
                    <fullName>PRESIDENTE DE DIRECTORIO</fullName>
                </value>
                <value>
                    <fullName>APODERADO</fullName>
                </value>
                <value>
                    <fullName>DIRECTORIO</fullName>
                </value>
                <value>
                    <fullName>GERENTE GENERAL</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE FINANZAS</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE ADMINISTRACION Y FINANZAS</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE ADMINISTRACION</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE RRHH</fullName>
                </value>
                <value>
                    <fullName>GERENTE COMERCIAL</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE OPERACIONES</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE CONTABILIDAD</fullName>
                </value>
                <value>
                    <fullName>JEFE DE FINANZAS</fullName>
                </value>
                <value>
                    <fullName>JEFE DE TESORERIA</fullName>
                </value>
                <value>
                    <fullName>JEFE DE ADMINISTRACION Y FINANZAS</fullName>
                </value>
                <value>
                    <fullName>JEFE DE ADMINISTRACIÓN</fullName>
                </value>
                <value>
                    <fullName>JEFE DE CONTABILIDAD</fullName>
                </value>
                <value>
                    <fullName>ADMINISTRADOR</fullName>
                </value>
                <value>
                    <fullName>ASISTENTE</fullName>
                </value>
                <value>
                    <fullName>OTROS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/dwp_kitv__Visit__c.object
<CustomObject>
    <description>Main object to manage visits</description>
    <fields>
        <fullName>dwp_kitv__account_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account record related to this visit.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>dwp_kitv__visit_duration_number__c</fullName>
        <description>Time in minutes it takes to make the visit. The first hour will be intervals about 15 minutes, then 30 minutes intervals.</description>
        <inlineHelpText>Seleccione la duración en minutos</inlineHelpText>
        <label>Duration</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>120</fullName>
                </value>
                <value>
                    <fullName>150</fullName>
                </value>
                <value>
                    <fullName>180</fullName>
                </value>
                <value>
                    <fullName>210</fullName>
                </value>
                <value>
                    <fullName>240</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>dwp_kitv__visit_location_desc__c</fullName>
        <description>Field to determinate the place where the visit will be realized.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dwp_kitv__visit_purpose_type__c</fullName>
        <description>Visit Type</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <default>true</default>
                    <label>Commercial</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>Strategic</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>Acquisition</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>dwp_kitv__visit_start_date__c</fullName>
        <description>Field to set the start date time of the visit.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dwp_kitv__visit_status_type__c</fullName>
        <description>Status visit</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>Arranged</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>Arranged - Pending Updates</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <label>Visit Completed - Pending Feedback</label>
                </value>
                <value>
                    <fullName>05</fullName>
                    <label>Visit Completed - Minute Sent</label>
                </value>
                <value>
                    <fullName>06</fullName>
                    <label>Finalized</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Visit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/dwp_kitv__Visit_Topic__c.object
<CustomObject>
    <description>Topics about visits</description>
    <fields>
        <fullName>dwp_kitv__visit_id__c</fullName>
        <description>Parent Object</description>
        <label>Visit</label>
        <referenceTo>dwp_kitv__Visit__c</referenceTo>
        <relationshipLabel>Visit Topics</relationshipLabel>
        <relationshipName>Visit_Topics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visit Topic</label>
    <nameField>
        <displayFormat>VT-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Topics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>unique_id__c</fullName>
        <description>Internal control code</description>
        <label>Unique identifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
	<fields>
        <fullName>Unique_id__c</fullName>
        <externalId>true</externalId>
        <label>Unique_id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>prof_position_type__c</fullName>
        <description>Is the name of Position</description>
        <label>Position</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/BE_UtilitysDataTest_Test.cls
/**
* _________________________________________________________________________________
* @Name     BE_UtilitysDataTest_Test
* @Author   Antony de la rosa guzman.
* @Date     2019-11-11
* @Group    DWP Perú
* @Description Clase para crear los Datos de prueba generales de utilería para ser usados
                en las demas clases de prueba.
* _________________________________________________________________________________
* @Changes
* _________________________________________________________________________________
*/
@isTest
public class BE_UtilitysDataTest_Test {
    /**APINAME of the SObject*/ 
    final static String SOBJNAME='Account_Accounting__c';
    /**@general variable*/ 
    final static String FIELDCODE='gl_account_id__c';
    /**@general variable*/ 
    final static String DATEFIELD='year_month_day_date__c';
    /**@general variable*/ 
    final static String UNIQUECODE='203658756Utils'+Date.today();
    
    static Map<String, Profile> perfilMapa = new Map<String, Profile>();
    static Map<String, UserRole> rolMapa   = new Map<String, UserRole>();
    static List<Profile> lstProfile;
    static List<UserRole> userRole;

    static{
        lstProfile = new List<Profile>([SELECT Id, Name FROM Profile WHERE Name != null]);
        userRole   = new List<UserRole>([SELECT Id, Name FROM UserRole WHERE Name != null]);    
        for(Profile perfil:lstProfile){ perfilMapa.put(perfil.Name, perfil); }
        for(UserRole ur:userRole){ rolMapa.put(ur.Name, ur); }    
    }

    @isTest static void test_method_two() {
        Integer MAX_QUERY = Limits.getLimitQueries(); 
        Integer NUM_QUERY = MAX_QUERY - 1;
        System.assert(Limits.getQueries() < NUM_QUERY, 'numero de querys dentro del rango  permitido');
    }
     
    /**
    * @Method:      crearUsuario
    * @param:       String strLastName, String strProfileName, String strRol
    * @Description: Funcion que retorna un objeto User 
    */
    public static User crearUsuario(String strLastName, String strProfileName, String strRol) {
        String email                  = 'tstBBVA'+Math.random()*10000+'@bbva.test.com';   
        final User usuario                  = new User(); 
        usuario.LastName              = strLastName;
        usuario.Alias                 = String.valueOf((Math.random() * 10000).round());
        usuario.Email                 = email;
        usuario.UserName              = email;
        usuario.EmailEncodingKey      = 'UTF-8';
        usuario.LanguageLocaleKey     = 'en_US';
        usuario.TimeZoneSidKey        = 'America/Lima';
        usuario.LocaleSidKey          = 'en_US';
        usuario.IsActive              = true;
        usuario.ProfileId = userinfo.getProfileId();
        if(String.isNotBlank(strRol)) {usuario.UserRoleId = rolMapa.get(strRol).Id;}
        usuario.CompanyName           = 'DWP Perú';
        return usuario;
    }

    /**
    * @Method:      crearCuenta
    * @param:       String strName
    * @Description: Funcion que retorna un objeto cliente
    */
	public static Account crearCuenta(String strName) {
		final Account cliente          = new Account();
		cliente.Name             = strName;
		cliente.unique_id__c = UNIQUECODE;	
		return cliente;
    }
    
    /**
    * @Method:      crearCuenta Accounting
    * @param:       String strName,Id Acc
    * @Description: Funcion que retorna un objeto Account_Accounting__c
    */
	public static Account_Accounting__c crearAccount_Accouting(String strName,Id idAccount) {
		final Account_Accounting__c accAcc = new Account_Accounting__c();
        accAcc.Name = strName;
        accAcc.account_id__c = idAccount;
        accAcc.gl_account_amount__c=200;
        accAcc.year_month_day_date__c=Date.today()-70;
        accAcc.parent_gl_account_id__c='';
        accAcc.gl_account_id__c='PARENT_TEST';
        accAcc.gl_account_id_path_desc__c='1';
        accAcc.gl_account_path_position_id__c='1';
		return accAcc;
    }
    
    /**
    * @Method:      crearOportunidad
    * @param:       String strName, Id idAccount,  Id idOwner, String strTipoProd
    * @Description: Funcion que retorna un objeto Oportunidad
    */
    public static Opportunity crearOportunidad(String strName, Id idAccount,  Id idOwner, String strTipoProd) {     
        final Opportunity objOpp       = new Opportunity();
        objOpp.Name              = strName;
        objOpp.StageName         = '02';
        objOpp.AccountId         = idAccount;
        objOpp.CloseDate         = Date.today().addDays(15);        
        objOpp.OwnerId           = idOwner;
        return objOpp;
    }
    
    /**
    * @Method:      crearVisitas
    * @param:       String strName, Id idAccount,  Id idOwner, String strTipoVisita
    * @Description: Funcion que retorna un objeto Visita
    */
    public static dwp_kitv__Visit__c crearVisita(String strName, Id idAccount, String strTipoVisita) {     
        final dwp_kitv__Visit__c visit = new dwp_kitv__Visit__c();
        visit.Name=strName;
        visit.dwp_kitv__visit_start_date__c = datetime.newInstance(System.today().year(), System.today().Month(), System.today().day(), 13, 30, 0);
        visit.dwp_kitv__visit_duration_number__c='30';
        visit.dwp_kitv__visit_purpose_type__c=strTipoVisita;
        visit.dwp_kitv__visit_status_type__c='01';
        visit.dwp_kitv__account_id__c=idAccount;
        visit.dwp_kitv__visit_location_desc__c='torre bancomer';
        return visit;
    }
    
    /**
    * @Method:      crearVariation
    * @param:       String strName, Id idAccount
    * @Description: Funcion que retorna un objeto Account_variation_information__c
    */
    public static Account_variation_information__c crearVariation(String strName, Id idAccount,String StrColor) {     
        final Account_variation_information__c Variation = new Account_variation_information__c();
        Variation.indicator_name__c=strName;
        Variation.Account_Id__c=idAccount;
        Variation.validation_color_type__c = StrColor;
        Variation.indicator_update_date__c=Date.today();
        return Variation;
    }
    
     /**
    * @Method:      crtVisitTopic
    * @Description: Crea un registro del tipo dwp_kitv__Visit_Topic__c
    * @param: String tipoRegistro
    */
    public static dwp_kitv__Visit_Topic__c crtVisitTopic(String visita) {
        final dwp_kitv__Visit_Topic__c topic = new dwp_kitv__Visit_Topic__c();
        topic.dwp_kitv__visit_id__c = visita;
        return topic;
    }
    
      /**
    * @Method:      crearContacto
    * @param:       Id idCuenta, String strFirstName, String strLastName,  String devNameTipoRegistro
    * @Description: Funcion que retorna un objeto contacto
    */
	public static Contact crearContacto(Id idCuenta, String strFirstName, String strLastName) {
		final Contact contacto   = new Contact();
		contacto.FirstName = strFirstName;
        contacto.Salutation='Sr.';
		contacto.LastName  = strLastName;
		contacto.Phone     = '(234) 567-8987';
        contacto.MobilePhone = '999999999';
        contacto.decision_making_desc__c ='Si';
        contacto.prof_position_type__c = 'APODERADO';
        contacto.Cargo_inicio__c = 'APODERADO';
		contacto.Email     = 'tstBBVA'+ (Math.random()*10000).round()+'@bbva.test.com';
        if(idCuenta!=null){contacto.AccountId = idCuenta;}
		return contacto;
    }
}