src/objects/AccountContactRelation.object
<CustomObject>
    <fields>
        <fullName>other_prof_prosition_type__c</fullName>
        <label>Other position</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>prof_position_type__c</fullName>
        <label>Position</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACCIONISTA</fullName>
                </value>
                <value>
                    <fullName>PRESIDENTE DE DIRECTORIO</fullName>
                </value>
                <value>
                    <fullName>APODERADO</fullName>
                </value>
                <value>
                    <fullName>DIRECTORIO</fullName>
                </value>
                <value>
                    <fullName>GERENTE GENERAL</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE FINANZAS</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE ADMINISTRACION Y FINANZAS</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE ADMINISTRACION</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE RRHH</fullName>
                </value>
                <value>
                    <fullName>GERENTE COMERCIAL</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE OPERACIONES</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE CONTABILIDAD</fullName>
                </value>
                <value>
                    <fullName>JEFE DE FINANZAS</fullName>
                </value>
                <value>
                    <fullName>JEFE DE TESORERIA</fullName>
                </value>
                <value>
                    <fullName>JEFE DE ADMINISTRACION Y FINANZAS</fullName>
                </value>
                <value>
                    <fullName>JEFE DE ADMINISTRACIÓN</fullName>
                </value>
                <value>
                    <fullName>JEFE DE CONTABILIDAD</fullName>
                </value>
                <value>
                    <fullName>ADMINISTRADOR</fullName>
                </value>
                <value>
                    <fullName>ASISTENTE</fullName>
                </value>
                <value>
                    <fullName>OTROS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>decision_making_desc__c</fullName>
        <label>Decision Making Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Si</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>decision_making_desc__c</fullName>
        <label>Decisor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Si</fullName>
                    <label>Sí</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>other_prof_prosition_type__c</fullName>
        <label>Other Position</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>parent_account_decision_making_desc__c</fullName>
        <label>Decision Parent Account</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Si</fullName>
                    <label>Sí</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>parent_account_other_prof_prosition_type__c</fullName>
        <label>Other Position Parent Account</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>parent_account_prof_position_type__c</fullName>
        <label>Position Parent Account</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACCIONISTA</fullName>
                    <isActive>false</isActive>
                    <label>ACCIONISTA</label>
                </value>
                <value>
                    <fullName>ADMINISTRADOR</fullName>
                    <isActive>false</isActive>
                    <label>ADMINISTRADOR</label>
                </value>
                <value>
                    <fullName>APODERADO</fullName>
                    <isActive>false</isActive>
                    <label>APODERADO</label>
                </value>
                <value>
                    <fullName>ASISTENTE</fullName>
                    <isActive>false</isActive>
                    <label>ASISTENTE</label>
                </value>
                <value>
                    <fullName>DIRECTORIO</fullName>
                    <isActive>false</isActive>
                    <label>DIRECTORIO</label>
                </value>
                <value>
                    <fullName>GERENTE COMERCIAL</fullName>
                    <isActive>false</isActive>
                    <label>GERENTE COMERCIAL</label>
                </value>
                <value>
                    <fullName>GERENTE DE ADMINISTRACION</fullName>
                    <isActive>false</isActive>
                    <label>GERENTE DE ADMINISTRACION</label>
                </value>
                <value>
                    <fullName>GERENTE DE ADMINISTRACION Y FINANZAS</fullName>
                    <isActive>false</isActive>
                    <label>GERENTE DE ADMINISTRACION Y FINANZAS</label>
                </value>
                <value>
                    <fullName>GERENTE DE CONTABILIDAD</fullName>
                    <isActive>false</isActive>
                    <label>GERENTE DE CONTABILIDAD</label>
                </value>
                <value>
                    <fullName>GERENTE DE FINANZAS</fullName>
                    <isActive>false</isActive>
                    <label>GERENTE DE FINANZAS</label>
                </value>
                <value>
                    <fullName>GERENTE DE OPERACIONES</fullName>
                    <isActive>false</isActive>
                    <label>GERENTE DE OPERACIONES</label>
                </value>
                <value>
                    <fullName>GERENTE DE RRHH</fullName>
                    <isActive>false</isActive>
                    <label>GERENTE DE RRHH</label>
                </value>
                <value>
                    <fullName>GERENTE GENERAL</fullName>
                    <isActive>false</isActive>
                    <label>GERENTE GENERAL</label>
                </value>
                <value>
                    <fullName>JEFE DE ADMINISTRACION Y FINANZAS</fullName>
                    <isActive>false</isActive>
                    <label>JEFE DE ADMINISTRACION Y FINANZAS</label>
                </value>
                <value>
                    <fullName>JEFE DE ADMINISTRACIÓN</fullName>
                    <isActive>false</isActive>
                    <label>JEFE DE ADMINISTRACIÓN</label>
                </value>
                <value>
                    <fullName>JEFE DE CONTABILIDAD</fullName>
                    <isActive>false</isActive>
                    <label>JEFE DE CONTABILIDAD</label>
                </value>
                <value>
                    <fullName>JEFE DE FINANZAS</fullName>
                    <isActive>false</isActive>
                    <label>JEFE DE FINANZAS</label>
                </value>
                <value>
                    <fullName>JEFE DE TESORERIA</fullName>
                    <isActive>false</isActive>
                    <label>JEFE DE TESORERIA</label>
                </value>
                <value>
                    <fullName>OTROS</fullName>
                    <isActive>false</isActive>
                    <label>OTROS</label>
                </value>
                <value>
                    <fullName>PRESIDENTE DE DIRECTORIO</fullName>
                    <isActive>false</isActive>
                    <label>PRESIDENTE DE DIRECTORIO</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>prof_position_type__c</fullName>
        <label>Position</label>
        <picklist>
            <picklistValues>
                <fullName>ACCIONISTA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADMINISTRADOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APODERADO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASISTENTE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DIRECTORIO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE COMERCIAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE ADMINISTRACION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE ADMINISTRACION Y FINANZAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE CONTABILIDAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE FINANZAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE OPERACIONES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE RRHH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE GENERAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JEFE DE ADMINISTRACIÓN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JEFE DE ADMINISTRACION Y FINANZAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JEFE DE CONTABILIDAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JEFE DE FINANZAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JEFE DE TESORERIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTROS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRESIDENTE DE DIRECTORIO</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>		
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACCIONISTA</fullName>
                </value>
                <value>
                    <fullName>PRESIDENTE DE DIRECTORIO</fullName>
                </value>
                <value>
                    <fullName>APODERADO</fullName>
                </value>
                <value>
                    <fullName>DIRECTORIO</fullName>
                </value>
                <value>
                    <fullName>GERENTE GENERAL</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE FINANZAS</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE ADMINISTRACION Y FINANZAS</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE ADMINISTRACION</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE RRHH</fullName>
                </value>
                <value>
                    <fullName>GERENTE COMERCIAL</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE OPERACIONES</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE CONTABILIDAD</fullName>
                </value>
                <value>
                    <fullName>JEFE DE FINANZAS</fullName>
                </value>
                <value>
                    <fullName>JEFE DE TESORERIA</fullName>
                </value>
                <value>
                    <fullName>JEFE DE ADMINISTRACION Y FINANZAS</fullName>
                </value>
                <value>
                    <fullName>JEFE DE ADMINISTRACIÓN</fullName>
                </value>
                <value>
                    <fullName>JEFE DE CONTABILIDAD</fullName>
                </value>
                <value>
                    <fullName>ADMINISTRADOR</fullName>
                </value>
                <value>
                    <fullName>ASISTENTE</fullName>
                </value>
                <value>
                    <fullName>OTROS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/AccountContactParentAssociation.cls
/**
 * Handler of Trigger of the AccountContactRelation object.
 * <p /><p />
 * Modification log:<p />
 * -------------------------------------------------------------------
 * Developer                    Date                Description<p />
 * -------------------------------------------------------------------
 * Julio Medellin               22/02/2018          Original version.<p />
 * Alberto Gómez                27/02/2018          Added updateValuesRelationInContact method.<p />
 *
 * @author Julio Medellin
 */
 public with sharing class AccountContactParentAssociation {
public static boolean uContact= true;
    
    /**
     * Method for set values in AccountContactRelation records.
     *
     * @param lstAccountContactRelation Account Contact Relation List.
     */
    public static void setValuesRelation(List<AccountContactRelation> lstAccountContactRelation) {
        List<AccountContactRelation> lstAccountContactRelationUpdated = new List<AccountContactRelation>();
        Map<Id, Contact> mapContact = new Map<Id, Contact>([SELECT Id, AccountId,Account.ParentID,prof_position_type__c, other_prof_prosition_type__c, decision_making_desc__c, parent_account_prof_position_type__c,parent_account_other_prof_prosition_type__c,parent_account_decision_making_desc__c   FROM Contact]);
        for(AccountContactRelation objAccountContactRelation : lstAccountContactRelation) {
           if(objAccountContactRelation.IsDirect == TRUE) {
             AccountContactRelation objAccountContactRelation2  = new AccountContactRelation(
                    Id = objAccountContactRelation.Id,
                    prof_position_type__c = (objAccountContactRelation.AccountId != mapContact.get(objAccountContactRelation.contactId).Account.parentId) ? mapContact.get(objAccountContactRelation.contactId).prof_position_type__c : mapContact.get(objAccountContactRelation.contactId).parent_account_prof_position_type__c ,
                    other_prof_prosition_type__c = (objAccountContactRelation.AccountId != mapContact.get(objAccountContactRelation.contactId).Account.parentId) ? mapContact.get(objAccountContactRelation.contactId).other_prof_prosition_type__c : mapContact.get(objAccountContactRelation.contactId).parent_account_other_prof_prosition_type__c ,
                    decision_making_desc__c = (objAccountContactRelation.AccountId != mapContact.get(objAccountContactRelation.contactId).Account.parentId) ? mapContact.get(objAccountContactRelation.contactId).decision_making_desc__c : mapContact.get(objAccountContactRelation.contactId).parent_account_decision_making_desc__c
                    );
            lstAccountContactRelationUpdated.add(objAccountContactRelation2);
           }
           }
       
        update lstAccountContactRelationUpdated;
         
    }

    /**
     * Method for update Contact values according to AccountContactRelation updates.
     *
     * @param lstAccountContactRelation Account Contact Relation List.
     */
    public static void updateValuesRelationInContact(List<AccountContactRelation> lstAccountContactRelation) {
        List<Contact> lstContact = new List<Contact>();
        set<Id> Ids = new set<Id>();
        for(AccountContactRelation objAccountContactRelation1 : lstAccountContactRelation) {
           Ids.add(objAccountContactRelation1.ContactId);
        }
        if(!Ids.isEmpty()){
        lstContact=[SELECT Id, prof_position_type__c, other_prof_prosition_type__c, decision_making_desc__c 
                            FROM Contact WHERE Id in:Ids];
        for(AccountContactRelation objAccountContactRelation : lstAccountContactRelation) {
            for(Contact objContact : lstContact) {
                if(objAccountContactRelation.IsDirect == TRUE && objAccountContactRelation.ContactId == objContact.id ) {
                    objContact.prof_position_type__c = objAccountContactRelation.prof_position_type__c;
                    objContact.other_prof_prosition_type__c = objAccountContactRelation.other_prof_prosition_type__c;
                    objContact.decision_making_desc__c = objAccountContactRelation.decision_making_desc__c;
                }
            }
            
        }
           if(uContact){//esta variable es actualizada mediante otro Proceso
               update lstContact;
                }
        }
    }  
    

}