src/objects/Account_Profitability__c.object
<CustomObject>
    <fields>
        <fullName>account_id__c</fullName> 
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Profitability</relationshipLabel>
        <relationshipName>Account_Profitability</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>current_ydt_amount__c</fullName>
        <label>Annual amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>previous_ydt_amount__c</fullName>
        <label>Previous annual amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>profitability_category_type__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>profitability_type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>year_month_day_date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Rentabilidad</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rentabilidades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/acpl__Account_Planning__c.object
<CustomObject>
    <fields>
        <fullName>acpl__external_reference_id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Account Planning external id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>acpl__gf_account_planning_name__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Full</fullName>
                </value>
                <value>
                    <fullName>Light</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_indvi_lock_edit_ind_type__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Unlock Account Planning</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_launch_name__c</fullName>
        <label>Launch type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>General period</fullName>
                </value>
                <value>
                    <fullName>Period by priority</fullName>
                </value>
                <value>
                    <fullName>Event driven</fullName>
                </value>
                <value>
                    <fullName>Automatic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_launch_period_desc__c</fullName>
        <description>Periodo de lanzamiento con el formato &quot;YY/YY&quot;</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Launch period</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_limit_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_req_validation_ind_type__c</fullName>
        <label>Validation Required</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_status_type_name__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Validation</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_substatus_type_name__c</fullName>
        <label>Sub-status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>acpl__gf_ap_status_type_name__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>AP team not invited</fullName>
                </value>
                <value>
                    <fullName>AP team invited</fullName>
                </value>
                <value>
                    <fullName>Pending pre-validation</fullName>
                </value>
                <value>
                    <fullName>Pre-validated</fullName>
                </value>
                <value>
                    <fullName>Pending review</fullName>
                </value>
                <value>
                    <fullName>Pending validation</fullName>
                </value>
                <value>
                    <fullName>In place</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>acpl__gf_mandatory_type__c</fullName>
        <label>Required</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mandatory</fullName>
                </value>
                <value>
                    <fullName>Optional</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <isActive>false</isActive>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                    <isActive>false</isActive>
                    <label>Yes</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>acpl__participant_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plannings</relationshipLabel>
        <relationshipName>Account_Plannings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acpl__proposal_manager_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Global Banker</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Plannings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Planning</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Planning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plannings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/bupl__BP_GrowthDriver__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_account_planning_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Planning</label>
        <referenceTo>acpl__Account_Planning__c</referenceTo>
        <relationshipLabel>Growth Drivers</relationshipLabel>
        <relationshipName>Growth_Drivers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>bupl__gf_business_plan_id__c</fullName>
        <label>Business Plan</label>
        <referenceTo>bupl__BusinessPlan__c</referenceTo>
        <relationshipLabel>Growth Drivers</relationshipLabel>
        <relationshipName>Growth_Drivers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>bupl__solution_category_id__c</fullName>
        <label>Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Financiamiento a corto plazo</fullName>
                </value>
                <value>
                    <fullName>Riesgo de firma</fullName>
                </value>
                <value>
                    <fullName>Recursos</fullName>
                </value>
                <value>
                    <fullName>Serv. Transaccionales</fullName>
                </value>
                <value>
                    <fullName>Tesorería</fullName>
                </value>
                <value>
                    <fullName>Programa financiero</fullName>
                </value>
                <value>
                    <fullName>Corporate Finance</fullName>
                    <isActive>false</isActive>
                    <label>Corporate Finance</label>
                </value>
                <value>
                    <fullName>Global Finance</fullName>
                    <isActive>false</isActive>
                    <label>Global Finance</label>
                </value>
                <value>
                    <fullName>Global Markets</fullName>
                    <isActive>false</isActive>
                    <label>Global Markets</label>
                </value>
                <value>
                    <fullName>Global Transaction Banking</fullName>
                    <isActive>false</isActive>
                    <label>Global Transaction Banking</label>
                </value>
                <value>
                    <fullName>Others</fullName>
                    <isActive>false</isActive>
                    <label>Others</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Growth Driver</label>
    <nameField>
        <displayFormat>GD_{YYYY}/{MM}-{0000}</displayFormat>
        <label>Growth Driver Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Growth Drivers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/bupl__BusinessPlan__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_account_planning_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Planning</label>
        <referenceTo>acpl__Account_Planning__c</referenceTo>
        <relationshipLabel>Business Plans</relationshipLabel>
        <relationshipName>Business_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_indvi_lock_edit_ind_type__c</fullName>
        <formula>acpl__gf_account_planning_id__r.acpl__gf_ap_indvi_lock_edit_ind_type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AP unlocked</label>
        <type>Checkbox</type>
    </fields>
    <label>Business Plan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BE_ProfilabilityController_Tst.cls
/**BE_ProfilabilityController_Tst
 *  object.
 * <p /><p />
 * Modification log:<p />
 * -------------------------------------------------------------------
 * Developer                       Date                Description<p />
 * -------------------------------------------------------------------
 * Eduardo Vargas    13/08/2021          Original version.<p />
 *
 * @author Eduardo Vargas
 */

@Istest
public with sharing class BE_ProfilabilityController_Tst {
  /**
	   @Description setup data
	 */
  @testSetup
  static void setup() {
    final User manager = TestFactory.createUser('sample', 'Ejecutivo');
    final Account acc1 = new Account(Name = 'ASIA MOTORS');
    insert acc1;
    final List<Account> accs = new List<Account>{ new Account(Name = 'DM Shangai SAC', ParentId = acc1.Id), new Account(Name = 'Tokio Tyres', ParentId = acc1.Id), new Account(Name = 'Pekin cooling SAC', ParentId = acc1.Id) };
    insert accs;

    final acpl__Account_Planning__c accPlan = new acpl__Account_Planning__c();
    accPlan.NAME = 'AP-REVIEW EV V1';
    accPlan.ACPL__EXTERNAL_REFERENCE_ID__C = 'AP-REVIEW EV V11';
    accPlan.ACPL__GF_ACCOUNT_PLANNING_NAME__C = 'Full';
    accPlan.ACPL__GF_AP_INDVI_LOCK_EDIT_IND_TYPE__C = true;
    accPlan.ACPL__GF_AP_LAUNCH_NAME__C = 'General period';
    accPlan.ACPL__GF_AP_LAUNCH_PERIOD_DESC__C = '04/21';
    accPlan.ACPL__GF_AP_LIMIT_DATE__C = Date.newInstance(2030, 12, 31);
    accPlan.ACPL__GF_AP_REQ_VALIDATION_IND_TYPE__C = 'Yes';
    accPlan.ACPL__GF_AP_STATUS_TYPE_NAME__C = 'Not started';
    accPlan.ACPL__GF_AP_SUBSTATUS_TYPE_NAME__C = 'Not started';
    accPlan.ACPL__GF_MANDATORY_TYPE__C = 'Mandatory';
    accPlan.acpl__participant_id__c = acc1.Id; //Asia Motors
    accPlan.acpl__proposal_manager_id__c = manager.Id; // EDUARDO VARGAS

    insert accPlan;

    final bupl__BusinessPlan__c bussinessPl = [SELECT ID, Name FROM bupl__BusinessPlan__c LIMIT 1];

    writeDate(accPlan, bussinessPl, acc1, accs);
  }

  /**
	 @Description test success method
	*/
  @isTest
  public static void unitTest() {
    final acpl__Account_Planning__c accountPlan = [SELECT Id FROM acpl__Account_Planning__c WHERE Name = 'AP-REVIEW EV V1' LIMIT 1];

    final Map<String, Object> rentabilityUI = BE_ProfilabilityController_cls.getRDt(accountPlan.Id);
    Integer count = 0;
    for (Object accsObj : (List<Object>) rentabilityUI.get('data')) {
      final Map<String, Object> accsMap = (Map<String, Object>) accsObj;
      for (Object sect : (List<Object>) accsMap.get('sections')) {
        System.debug(sect);
        count++;
      }
    }

    System.assertEquals(count, 9, 'Wrong number of Accounts');
  }

  /** testGetGrowthVariableData */
  @isTest
  public static void testGetGrowthVariableData() {
    final acpl__Account_Planning__c accountPlan = [SELECT Id FROM acpl__Account_Planning__c WHERE Name = 'AP-REVIEW EV V1' LIMIT 1];
    final Map<String, Object> rentabilityUI = BE_ProfilabilityController_cls.getGrowthVariableData(accountPlan.Id);

    Integer rentCount = 0;
    for (Object rentObj : (List<Object>) rentabilityUI.get('data')) {
      System.debug(rentObj);
      rentCount++;
    }
    System.assertEquals(rentCount, 3, 'Rentability Growth Variables');
  }

  /** writeDate */
  private void writeDate(acpl__Account_Planning__c accPlan, bupl__BusinessPlan__c bussinessPl, Account acc1, List<Account> accs) {
    final List<bupl__BP_GrowthDriver__c> growDrivers = new List<bupl__BP_GrowthDriver__c>{
      new bupl__BP_GrowthDriver__c(acpl__gf_account_planning_id__c = accPlan.Id, Amount__c = 160000, bupl__solution_category_id__c = 'Financiamiento a largo plazo', ClientAssigned__c = accs[1].Id, CurrencyIsoCode = 'PEN', ExpectedDate__c = date.valueOf('2021-11-11'), bupl__gf_business_plan_id__c = bussinessPl.Id),
      new bupl__BP_GrowthDriver__c(acpl__gf_account_planning_id__c = accPlan.Id, Amount__c = 90000, bupl__solution_category_id__c = 'Financiamiento a corto plazo', ClientAssigned__c = accs[1].Id, CurrencyIsoCode = 'USD', ExpectedDate__c = date.valueOf('2021-09-30'), bupl__gf_business_plan_id__c = bussinessPl.Id),
      new bupl__BP_GrowthDriver__c(acpl__gf_account_planning_id__c = accPlan.Id, Amount__c = 300000, bupl__solution_category_id__c = 'Tesorería', ClientAssigned__c = accs[2].Id, CurrencyIsoCode = 'PEN', ExpectedDate__c = date.valueOf('2021-09-30'), bupl__gf_business_plan_id__c = bussinessPl.Id)
    };

    insert growDrivers;

    final List<Account_Profitability__c> accProf = new List<Account_Profitability__c>{
      new Account_Profitability__c(account_id__c = acc1.Id, current_ydt_amount__c = 24254, previous_ydt_amount__c = 147399, profitability_category_type__c = 'Margen Financiero', profitability_type__c = '03', year_month_day_date__c = date.valueOf('2018-10-31')),
      new Account_Profitability__c(account_id__c = acc1.Id, current_ydt_amount__c = 151914, previous_ydt_amount__c = 67789, profitability_category_type__c = 'Margen Financiero', profitability_type__c = '03', year_month_day_date__c = date.valueOf('2018-10-31')),
      new Account_Profitability__c(account_id__c = acc1.Id, current_ydt_amount__c = 0, previous_ydt_amount__c = 0, profitability_category_type__c = 'Margen Financiero', profitability_type__c = '03', year_month_day_date__c = date.valueOf('2018-10-31')),
      new Account_Profitability__c(account_id__c = acc1.Id, current_ydt_amount__c = 38775, previous_ydt_amount__c = 78252, profitability_category_type__c = 'Comisiones', profitability_type__c = '03', year_month_day_date__c = date.valueOf('2018-10-31')),
      new Account_Profitability__c(account_id__c = acc1.Id, current_ydt_amount__c = 0, previous_ydt_amount__c = 0, profitability_category_type__c = 'Altas', profitability_type__c = '01', year_month_day_date__c = date.valueOf('2020-09-28')),
      new Account_Profitability__c(account_id__c = acc1.Id, current_ydt_amount__c = 0, previous_ydt_amount__c = 0, profitability_category_type__c = 'Spread', profitability_type__c = '02', year_month_day_date__c = date.valueOf('2020-04-28')),
      new Account_Profitability__c(account_id__c = acc1.Id, current_ydt_amount__c = 0, previous_ydt_amount__c = 0, profitability_category_type__c = 'Tasa', profitability_type__c = '02', year_month_day_date__c = date.valueOf('2020-04-28')),
      new Account_Profitability__c(account_id__c = acc1.Id, current_ydt_amount__c = 39388, previous_ydt_amount__c = 61751, profitability_category_type__c = 'Margen Financiero', profitability_type__c = '03', year_month_day_date__c = date.valueOf('2018-09-28')),
      new Account_Profitability__c(account_id__c = acc1.Id, current_ydt_amount__c = 0, previous_ydt_amount__c = 0, profitability_category_type__c = 'Margen Financiero', profitability_type__c = '03', year_month_day_date__c = date.valueOf('2018-09-28')),
      new Account_Profitability__c(account_id__c = acc1.Id, current_ydt_amount__c = 98395, previous_ydt_amount__c = 168050, profitability_category_type__c = 'Comisiones', profitability_type__c = '03', year_month_day_date__c = date.valueOf('2018-09-28')),
      new Account_Profitability__c(account_id__c = acc1.Id, current_ydt_amount__c = 0, previous_ydt_amount__c = 0, profitability_category_type__c = 'Altas', profitability_type__c = '01', year_month_day_date__c = date.valueOf('2020-08-28')),
      new Account_Profitability__c(account_id__c = acc1.Id, current_ydt_amount__c = 0, previous_ydt_amount__c = 0, profitability_category_type__c = 'DI', profitability_type__c = '02', year_month_day_date__c = date.valueOf('2020-04-28')),
      new Account_Profitability__c(account_id__c = acc1.Id, current_ydt_amount__c = 4019, previous_ydt_amount__c = 9325, profitability_category_type__c = 'Margen Financiero', profitability_type__c = '03', year_month_day_date__c = date.valueOf('2018-09-28'))
    };
    insert accProf;
  }
}