src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>financial_program_expiry_date__c</fullName>
        <label>Financial programme due date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>main_code_id__c</fullName>
        <label>Client Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
<fields>
        <fullName>opportunity_status_type__c</fullName>
        <description>Status of an opportunity</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Email_SIO_Test.cls
@isTest
public class Email_SIO_Test {
    static Account acctest;
    static Opportunity opptest;
    static User defaultUser;

    static void setData() {        
        defaultUser = TestFactory.createUser('Test','Migracion');        
    }
    @isTest
    static void handleInboundEmailWithoutOpp() {
        setData();
        
        acctest = new Account (Name = 'Acctest', main_code_id__c ='222');
        insert acctest;
        opptest = new Opportunity (ownerId=defaultUser.Id,Name='testopp', AccountId=acctest.Id,StageName='01',Amount=100 ,CloseDate=system.Date.today(),opportunity_status_type__c='01');
        insert opptest;
        
        Test.startTest();
        Messaging.InboundEmail email = new Messaging.InboundEmail() ;
        Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
        email.subject = 'SIOCode##SIOStatus##??##??##222';
        email.fromAddress = 'comunicacion@p-1oflcjcwitlx140fa83tigxgbb3nmkavaczc81frgpisa8v1ih.29-8p7zeaa.cs19.apex.sandbox.salesforce.com';
        email.plainTextBody = 'comments';
        
        Email_SIO emailSIO = new Email_SIO();
        emailSIO.handleInboundEmail(email, env);
        
        Test.stopTest();        
    }
    @isTest
    static void handleInboundEmailWithOpp() {
        setData();
        Test.startTest();
        
        acctest = new Account (Name = 'Acctest', main_code_id__c ='222');
        insert acctest;
        opptest = new Opportunity (ownerId=defaultUser.Id,Name='testopp', AccountId=acctest.Id,StageName='04',Amount=100 ,CloseDate=system.Date.today(),opportunity_status_type__c='14',sio_status_type__c='Sanción Aprobado CM',sio_code__c='2222');
        insert opptest;
        
        
        Messaging.InboundEmail email = new Messaging.InboundEmail() ;
        Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
        email.subject = '2222##Sanción Aprobado CM##??##??##222';
        email.fromAddress = 'comunicacion@p-1oflcjcwitlx140fa83tigxgbb3nmkavaczc81frgpisa8v1ih.29-8p7zeaa.cs19.apex.sandbox.salesforce.com';
        email.plainTextBody = 'comments';
        
        Email_SIO emailSIO = new Email_SIO();
        emailSIO.handleInboundEmail(email, env);
        
        Test.stopTest();        
    }
    @isTest
    static void handleInboundEmailWithOppstatus() {
        setData();
        Test.startTest();
        
        acctest = new Account (Name = 'Acctest', main_code_id__c ='222');
        insert acctest;
        opptest = new Opportunity (ownerId=defaultUser.Id,Name='testopp', AccountId=acctest.Id,StageName='04',Amount=100 ,CloseDate=system.Date.today(),opportunity_status_type__c='14',sio_status_type__c='Sanción Denegado',sio_code__c='2222');
        insert opptest;
        
        
        Messaging.InboundEmail email = new Messaging.InboundEmail() ;
        Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
        email.subject = '2222##Sanción Denegado##??##??##222';
        email.fromAddress = 'comunicacion@p-1oflcjcwitlx140fa83tigxgbb3nmkavaczc81frgpisa8v1ih.29-8p7zeaa.cs19.apex.sandbox.salesforce.com';
        email.plainTextBody = 'comments';
        
        Email_SIO emailSIO = new Email_SIO();
        emailSIO.handleInboundEmail(email, env);
        
        Test.stopTest();        
    }
    @isTest
    static void handleInboundEmailUpdateAcc() {
        
        setData();
        
        acctest = new Account (Name = 'Acctest', main_code_id__c ='222',financial_program_expiry_date__c =date.today());
        insert acctest;
        opptest = new Opportunity (ownerId=defaultUser.Id,Name='testopp3', AccountId=acctest.Id,StageName='01',Amount=100 ,opportunity_status_type__c='01',CloseDate=system.Date.today()+2);
        insert opptest;
        
        Test.startTest();        
        Messaging.InboundEmail email = new Messaging.InboundEmail() ;
        Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
        
        email.subject = '222##12/07/2013';
        email.fromAddress = 'comunicacion@p-1oflcjcwitlx140fa83tigxgbb3nmkavaczc81frgpisa8v1ih.29-8p7zeaa.cs19.apex.sandbox.salesforce.com';
        email.plainTextBody = 'comments';
        
        Email_SIO emailSIO = new Email_SIO();
        emailSIO.handleInboundEmail(email, env);
        
        Messaging.InboundEmail email2 = new Messaging.InboundEmail() ;
        Messaging.InboundEnvelope env2 = new Messaging.InboundEnvelope();
        
        email2.subject = '222##2013/07/12';
        email2.fromAddress = 'comunicacion@p-1oflcjcwitlx140fa83tigxgbb3nmkavaczc81frgpisa8v1ih.29-8p7zeaa.cs19.apex.sandbox.salesforce.com';
        email2.plainTextBody = 'comments';
        
        Email_SIO emailSIO2 = new Email_SIO();
        emailSIO2.handleInboundEmail(email2, env2);
        
        Test.stopTest();
    }
}