src/objects/Account.object
<CustomObject>
     <fields>
        <fullName>non_client_code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Non Client Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Record_Type_Client</fullName>
        <active>true</active>
        <label>Client</label>
    </recordTypes>
    <recordTypes>
        <fullName>Record_Type_Non_Client</fullName>
        <active>true</active>
        <label>No Cliente</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>decision_making_desc__c</fullName>
        <label>Decisor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Si</fullName>
                    <label>Sí</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>phone_1__c</fullName>
        <label>Phone 1</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>phone_1_area_code__c</fullName>
        <label>Phone 1 Area Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>41</fullName>
                    <label>Amazonas - 41</label>
                </value>
                <value>
                    <fullName>43</fullName>
                    <label>Ancash - 43</label>
                </value>
                <value>
                    <fullName>83</fullName>
                    <label>Apurimac - 83</label>
                </value>
                <value>
                    <fullName>54</fullName>
                    <label>Arequipa - 54</label>
                </value>
                <value>
                    <fullName>66</fullName>
                    <label>Ayacucho - 66</label>
                </value>
                <value>
                    <fullName>76</fullName>
                    <label>Cajamarca - 76</label>
                </value>
                <value>
                    <fullName>84</fullName>
                    <label>Cusco - 84</label>
                </value>
                <value>
                    <fullName>67</fullName>
                    <label>Huancavelica - 67</label>
                </value>
                <value>
                    <fullName>62</fullName>
                    <label>Huanuco - 62</label>
                </value>
                <value>
                    <fullName>56</fullName>
                    <label>Ica - 56</label>
                </value>
                <value>
                    <fullName>64</fullName>
                    <label>Junin - 64</label>
                </value>
                <value>
                    <fullName>44</fullName>
                    <label>La Libertad - 44</label>
                </value>
                <value>
                    <fullName>74</fullName>
                    <label>Lambayeque - 74</label>
                </value>
                <value>
                    <fullName>01</fullName>
                    <label>Lima y Callo - 01</label>
                </value>
                <value>
                    <fullName>65</fullName>
                    <label>Loreto - 65</label>
                </value>
                <value>
                    <fullName>82</fullName>
                    <label>Madre de Dios - 82</label>
                </value>
                <value>
                    <fullName>53</fullName>
                    <label>Moquegua - 53</label>
                </value>
                <value>
                    <fullName>63</fullName>
                    <label>Pasco - 63</label>
                </value>
                <value>
                    <fullName>73</fullName>
                    <label>Piura - 73</label>
                </value>
                <value>
                    <fullName>51</fullName>
                    <label>Puno - 51</label>
                </value>
                <value>
                    <fullName>42</fullName>
                    <label>San Martin - 42</label>
                </value>
                <value>
                    <fullName>52</fullName>
                    <label>Tacna - 52</label>
                </value>
                <value>
                    <fullName>72</fullName>
                    <label>Tumbes - 72</label>
                </value>
                <value>
                    <fullName>61</fullName>
                    <label>Ucayali - 61</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>phone_2__c</fullName>
        <label>Phone 2</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>phone_2_area_code__c</fullName>
        <label>Phone 2 Area Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>41</fullName>
                    <label>Amazonas - 41</label>
                </value>
                <value>
                    <fullName>43</fullName>
                    <label>Ancash - 43</label>
                </value>
                <value>
                    <fullName>83</fullName>
                    <label>Apurimac- 83</label>
                </value>
                <value>
                    <fullName>54</fullName>
                    <label>Arequipa- 54</label>
                </value>
                <value>
                    <fullName>66</fullName>
                    <label>Ayacucho - 66</label>
                </value>
                <value>
                    <fullName>76</fullName>
                    <label>Cajamarca - 76</label>
                </value>
                <value>
                    <fullName>84</fullName>
                    <label>Cusco - 84</label>
                </value>
                <value>
                    <fullName>67</fullName>
                    <label>Huancavelica - 67</label>
                </value>
                <value>
                    <fullName>62</fullName>
                    <label>Huanuco - 62</label>
                </value>
                <value>
                    <fullName>56</fullName>
                    <label>Ica - 56</label>
                </value>
                <value>
                    <fullName>64</fullName>
                    <label>Junin - 64</label>
                </value>
                <value>
                    <fullName>44</fullName>
                    <label>La Libertad - 44</label>
                </value>
                <value>
                    <fullName>74</fullName>
                    <label>Lambayeque - 74</label>
                </value>
                <value>
                    <fullName>01</fullName>
                    <label>Lima y Callao - 01</label>
                </value>
                <value>
                    <fullName>65</fullName>
                    <label>Loreto - 65</label>
                </value>
                <value>
                    <fullName>82</fullName>
                    <label>Madre de Dios - 82</label>
                </value>
                <value>
                    <fullName>53</fullName>
                    <label>Moquegua - 53</label>
                </value>
                <value>
                    <fullName>63</fullName>
                    <label>Pasco - 63</label>
                </value>
                <value>
                    <fullName>73</fullName>
                    <label>Piura - 73</label>
                </value>
                <value>
                    <fullName>51</fullName>
                    <label>Puno - 51</label>
                </value>
                <value>
                    <fullName>42</fullName>
                    <label>San Martin - 42</label>
                </value>
                <value>
                    <fullName>52</fullName>
                    <label>Tacna - 52</label>
                </value>
                <value>
                    <fullName>72</fullName>
                    <label>Tumbes - 72</label>
                </value>
                <value>
                    <fullName>61</fullName>
                    <label>Ucayali - 61</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>prof_position_type__c</fullName>
        <label>Position</label>
        <picklist>
            <picklistValues>
                <fullName>ACCIONISTA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADMINISTRADOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APODERADO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASISTENTE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DIRECTORIO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE COMERCIAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE ADMINISTRACION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE ADMINISTRACION Y FINANZAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE CONTABILIDAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE FINANZAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE OPERACIONES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE RRHH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE GENERAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JEFE DE ADMINISTRACIÓN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JEFE DE ADMINISTRACION Y FINANZAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JEFE DE CONTABILIDAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JEFE DE FINANZAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JEFE DE TESORERIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTROS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRESIDENTE DE DIRECTORIO</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>		
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACCIONISTA</fullName>
                </value>
                <value>
                    <fullName>PRESIDENTE DE DIRECTORIO</fullName>
                </value>
                <value>
                    <fullName>APODERADO</fullName>
                </value>
                <value>
                    <fullName>DIRECTORIO</fullName>
                </value>
                <value>
                    <fullName>GERENTE GENERAL</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE FINANZAS</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE ADMINISTRACION Y FINANZAS</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE ADMINISTRACION</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE RRHH</fullName>
                </value>
                <value>
                    <fullName>GERENTE COMERCIAL</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE OPERACIONES</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE CONTABILIDAD</fullName>
                </value>
                <value>
                    <fullName>JEFE DE FINANZAS</fullName>
                </value>
                <value>
                    <fullName>JEFE DE TESORERIA</fullName>
                </value>
                <value>
                    <fullName>JEFE DE ADMINISTRACION Y FINANZAS</fullName>
                </value>
                <value>
                    <fullName>JEFE DE ADMINISTRACIÓN</fullName>
                </value>
                <value>
                    <fullName>JEFE DE CONTABILIDAD</fullName>
                </value>
                <value>
                    <fullName>ADMINISTRADOR</fullName>
                </value>
                <value>
                    <fullName>ASISTENTE</fullName>
                </value>
                <value>
                    <fullName>OTROS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/BE_Contact_Edit_Tst.cls
/**
   -------------------------------------------------------------------------------------------------
   @Name <BE_Contact_Edit_Tst>
   @Author Lolo Michel Bravo Ruiz (lolo.bravo@bbva.com)
   @Date  2020-09-02
   @Description test for BE_Contact_Edit_Ctr class
   @Changes
   Date        Author   Email                  Type
   2020-09-02  LMBR     lolo.bravo@bbva.com    Creation
   -------------------------------------------------------------------------------------------------
 */
@IsTest
public with sharing class BE_Contact_Edit_Tst {
    /** Lang Code */
    private static final List<String> RECORD_TYPE = new List<String> {'Record_Type_Non_Client','Record_Type_Client'};
    /** GrantingTickets */
    private static final String GRANT_TICKET = 'GrantingTickets';
    /** GrantingTickets Value */
    private static final String GRANT_TICKETVAL = 'https://validation/ok';
    /** GrantingTickets */
    private static final String CACHE_PARTITION = 'iaso.ServicesPartition';
    /**
    @Description test BE_EditNonClient_Ctr.getFields(), correct scenary
     */
    @IsTest
    static void updateRecordCreateTest() {
        final List<String>sObjNames=new List<String> {'Account'};
	    final Map<String,Schema.RecordTypeInfo>recordType=BE_General_Utils.getRecordTypeInfo(sObjNames);
        List<Account> accs=new List<Account> {
            new Account(Name='Client',AccountNumber='20876543267',non_client_code__c='20876543267',recordTypeId=recordType.get(RECORD_TYPE[0]).getRecordTypeId()),
            new Account(Name='NoClient',AccountNumber='20876543265',non_client_code__c='20876543265',recordTypeId=recordType.get(RECORD_TYPE[1]).getRecordTypeId())
        };
        insert accs;
        List<Contact> contacts= new List<Contact> {
            new Contact(AccountId=accs[1].Id,Salutation='Mr.',FirstName='NON_CLIENT',LastName='NON_CLIENTE_CONTACT_ONE',decision_making_desc__c='Si',Email='contactone@test.com',MobilePhone='924567896',prof_position_type__c='APODERADO', contact_code__c='00001',phone_1__c='9876545',phone_1_area_code__c='01',phone_2__c='2235675',phone_2_area_code__c='01')
        };
        insert contacts;
        BE_Contact_Edit_Ctr conEdit=new BE_Contact_Edit_Ctr();
        insert new iaso__GBL_Rest_Services_Url__c(Name = GRANT_TICKET, iaso__Url__c = GRANT_TICKETVAL, iaso__Cache_Partition__c = CACHE_PARTITION);
	    insert new iaso__GBL_Rest_Services_Url__c(Name = 'CreateNonBusinessContact', iaso__Url__c = 'https://CreateNonBusinessContact/204', iaso__Cache_Partition__c = CACHE_PARTITION);
	    Test.setMock(HttpCalloutMock.class, new Integration_MockGenerator());
        iaso.GBL_Mock.setMock(new Integration_MockGenerator());
        Test.startTest();
        contacts[0].AccountId=accs[0].Id;
        conEdit.updateRecord(contacts[0]);
        Test.stopTest();
    }
    /**
    @Description test BE_EditNonClient_Ctr.getFields(), correct scenary
     */
    @IsTest
    static void updateRecordUpdateTest() {
        final List<String>sObjNames=new List<String> {'Account'};
	    final Map<String,Schema.RecordTypeInfo>recordType=BE_General_Utils.getRecordTypeInfo(sObjNames);
        final Account acc=new Account(Name='Client',AccountNumber='20876543267',non_client_code__c='20876543267',recordTypeId=recordType.get(RECORD_TYPE[0]).getRecordTypeId());
        insert acc;
        final Contact contact= new Contact(AccountId=acc.Id,Salutation='Mr.',FirstName='NON_CLIENT',LastName='NON_CLIENTE_CONTACT_ONE',decision_making_desc__c='Si',Email='contactone@test.com',MobilePhone='924567896',prof_position_type__c='APODERADO', contact_code__c='00001',phone_1__c='9876545',phone_1_area_code__c='01',phone_2__c='2235675',phone_2_area_code__c='01');
        insert contact;
        final BE_Contact_Edit_Ctr conEdit=new BE_Contact_Edit_Ctr();
        insert new iaso__GBL_Rest_Services_Url__c(Name = GRANT_TICKET, iaso__Url__c = GRANT_TICKETVAL, iaso__Cache_Partition__c = CACHE_PARTITION);
	    insert new iaso__GBL_Rest_Services_Url__c(Name = 'ModifyNonBusinessContact', iaso__Url__c = 'https://ModifyNonBusinessContact/204', iaso__Cache_Partition__c = CACHE_PARTITION);
	    Test.setMock(HttpCalloutMock.class, new Integration_MockGenerator());
	    iaso.GBL_Mock.setMock(new Integration_MockGenerator());
        Test.startTest();
        conEdit.updateRecord(contact);
        Test.stopTest();
    }
    /**
    @Description test BE_EditNonClient_Ctr.getFields(), correct scenary
     */
    @IsTest
    static void updateRecordDeleteCreateTest() {
        final List<String>sObjNames=new List<String> {'Account'};
	    final Map<String,Schema.RecordTypeInfo>recordType=BE_General_Utils.getRecordTypeInfo(sObjNames);
        List<Account> accs=new List<Account> {
            new Account(Name='NoClient',AccountNumber='20876543265',non_client_code__c='20876543265',recordTypeId=recordType.get(RECORD_TYPE[0]).getRecordTypeId()),
            new Account(Name='NoClient',AccountNumber='20876543265',non_client_code__c='20876543265',recordTypeId=recordType.get(RECORD_TYPE[0]).getRecordTypeId())
        };
        insert accs;
        List<Contact> contacts= new List<Contact> {
            new Contact(AccountId=accs[0].Id,Salutation='Mr.',FirstName='NON_CLIENT',LastName='NON_CLIENTE_CONTACT_ONE',decision_making_desc__c='Si',Email='contactone@test.com',MobilePhone='924567896',prof_position_type__c='APODERADO', contact_code__c='00001',phone_1__c='9876545',phone_1_area_code__c='01',phone_2__c='2235675',phone_2_area_code__c='01'),
            new Contact(AccountId=accs[1].Id,Salutation='Mr.',FirstName='NON_CLIENT',LastName='NON_CLIENTE_CONTACT_ONE',decision_making_desc__c='Si',Email='contactone@test.com',MobilePhone='924567896',prof_position_type__c='APODERADO', contact_code__c='00001',phone_1__c='9876545',phone_1_area_code__c='01',phone_2__c='2235675',phone_2_area_code__c='01')
        };
        insert contacts;
        BE_Contact_Edit_Ctr conEdit=new BE_Contact_Edit_Ctr();
        insert new iaso__GBL_Rest_Services_Url__c(Name = GRANT_TICKET, iaso__Url__c = GRANT_TICKETVAL, iaso__Cache_Partition__c = CACHE_PARTITION);
	    insert new iaso__GBL_Rest_Services_Url__c(Name = 'DeleteNonBusinessContact', iaso__Url__c = 'https://DeleteNonBusinessContact/204', iaso__Cache_Partition__c = CACHE_PARTITION);
	    Test.setMock(HttpCalloutMock.class, new Integration_MockGenerator());
        iaso.GBL_Mock.setMock(new Integration_MockGenerator());
        insert new iaso__GBL_Rest_Services_Url__c(Name = GRANT_TICKET, iaso__Url__c = GRANT_TICKETVAL, iaso__Cache_Partition__c = CACHE_PARTITION);
	    insert new iaso__GBL_Rest_Services_Url__c(Name = 'CreateNonBusinessContact', iaso__Url__c = 'https://CreateNonBusinessContact/204', iaso__Cache_Partition__c = CACHE_PARTITION);
	    Test.setMock(HttpCalloutMock.class, new Integration_MockGenerator());
        iaso.GBL_Mock.setMock(new Integration_MockGenerator());
        Test.startTest();
        contacts[0].AccountId=accs[1].Id;
        conEdit.updateRecord(contacts[0]);
        Test.stopTest();
    }

        /**
    @Description test BE_EditNonClient_Ctr.getFields(), correct scenary
     */
    @IsTest
    static void updateRecordDeleteTest() {
        final List<String>sObjNames=new List<String> {'Account'};
	    final Map<String,Schema.RecordTypeInfo>recordType=BE_General_Utils.getRecordTypeInfo(sObjNames);
        List<Account> accs=new List<Account> {
            new Account(Name='NoClient',AccountNumber='20876543267',non_client_code__c='20876543267',recordTypeId=recordType.get(RECORD_TYPE[1]).getRecordTypeId()),
            new Account(Name='NoClient',AccountNumber='20876543265',non_client_code__c='20876543265',recordTypeId=recordType.get(RECORD_TYPE[0]).getRecordTypeId())
        };
        insert accs;
        Contact contact= new Contact(AccountId=accs[1].Id,Salutation='Mr.',FirstName='NON_CLIENT',LastName='NON_CLIENTE_CONTACT_ONE',decision_making_desc__c='Si',Email='contactone@test.com',MobilePhone='924567896',prof_position_type__c='APODERADO', contact_code__c='00001',phone_1__c='9876545',phone_1_area_code__c='01',phone_2__c='2235675',phone_2_area_code__c='01');
        insert contact;
        BE_Contact_Edit_Ctr conEdit=new BE_Contact_Edit_Ctr();
        insert new iaso__GBL_Rest_Services_Url__c(Name = GRANT_TICKET, iaso__Url__c = GRANT_TICKETVAL, iaso__Cache_Partition__c = CACHE_PARTITION);
	    insert new iaso__GBL_Rest_Services_Url__c(Name = 'DeleteNonBusinessContact', iaso__Url__c = 'https://DeleteNonBusinessContact/204', iaso__Cache_Partition__c = CACHE_PARTITION);
	    Test.setMock(HttpCalloutMock.class, new Integration_MockGenerator());
        iaso.GBL_Mock.setMock(new Integration_MockGenerator());
        Test.startTest();
        contact.AccountId=accs[0].Id;
        conEdit.updateRecord(contact);
        Test.stopTest();
    }
}