src/objects/Account_Contract__c.object
<CustomObject>
    <fields>
        <fullName>account_id__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Contracts</relationshipLabel>
        <relationshipName>Account_Contracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>contract_end_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Cancellation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>contract_id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>gf_lc_contract_lc_amount__c</fullName>
        <label>Local Amount</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>gf_tl_bal_contract_oc_amount__c</fullName>
        <label>Origin Amount</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>product_type__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>solution_category_name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>solution_expiry_type__c</fullName>
        <label>Term Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>subproduct_type__c</fullName>
        <label>Subcategory</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Calce__c.object
<CustomObject>
    <fields>
        <fullName>close_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>start_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Iniciado</fullName>
                </value>
                <value>
                    <fullName>En progreso</fullName>
                </value>
                <value>
                    <fullName>Compartido</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Calce</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calce</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Calce_Details__c.object
<CustomObject>
    <fields>
        <fullName>account_contract_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Contract</label>
        <referenceTo>Account_Contract__c</referenceTo>
        <relationshipLabel>Calce Details</relationshipLabel>
        <relationshipName>Calce_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>account_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Client</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Calce Details</relationshipLabel>
        <relationshipName>Calce_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>calce_id__c</fullName>
        <label>Calce</label>
        <referenceTo>Calce__c</referenceTo>
        <relationshipLabel>Calce Details</relationshipLabel>
        <relationshipName>Calce_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>close_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>contract_number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>product_code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sub_type__c</fullName>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <label>cancelaciones del dia</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>Nuevas oportunidades</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>Cancelaciones anticipadas</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <label>Caida de Cartera</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Indirect</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Resource</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Calce Details</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calce Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BE_CalcePortafolioFall_Tst.cls
/**
   -------------------------------------------------------------------------------------------------
   @Name <BE_CalcePortafolioFall_Tst>
   @Author Martin Alejandro Mori Chavez (martin.mori.contractor@bbva.com)
   @Date 2020-06-21
   @Description Test class from BE_CalcePortafolioFall_Ctr
   @Changes
   Date        Author   Email                  				Type
   2020-06-21  MAMC     martin.mori.contractor@bbva.com    	Creation
   -------------------------------------------------------------------------------------------------
 */
@isTest
private class BE_CalcePortafolioFall_Tst {
    /**
    @Description test method readRecords
    */
    @isTest
    public static void readRecordsTest() {
        final Account acc = TestFactory.createAccount();
        final Account_Contract__c contract = new Account_Contract__c();
        contract.account_id__c = acc.Id;
        contract.CurrencyIsoCode = 'USD';
        contract.contract_end_date__c = Date.today().addDays(-17);
        contract.contract_id__c = '001109499600108767';
        contract.gf_lc_contract_lc_amount__c = 120823.84;
        contract.gf_tl_bal_contract_oc_amount__c = 35715;
        contract.product_type__c = '01';
        contract.solution_category_name__c = 'PRESTAMOS EMPRESAS';
        contract.solution_expiry_type__c = '02';
        contract.subproduct_type__c = '01';
        insert contract;
        Test.setCreatedDate(contract.Id, System.now().addHours(-6));
        final Calce__c calce = new Calce__c();
        calce.Name = 'Test Calce';
        calce.close_date__c = Date.today();
        calce.start_date__c=date.today();
        calce.status__c = 'Iniciado';
        insert calce;
        final Calce_Details__c detail = new Calce_Details__c();
        detail.calce_id__c=calce.Id;
        detail.account_contract_id__c=contract.Id;
        detail.account_id__c=acc.Id;
        detail.Name='detail';
        detail.CurrencyIsoCode='PEN';
        detail.amount__c=50000;
        detail.Contract_Number__c='23212312321';
        detail.close_date__c=date.today();
        detail.type__c='Direct';
        detail.product_code__c='CODE001';
        detail.sub_type__c='04';
        insert detail;
        final Map<String,Object> mapCalce = new Map<String,Object>();
        mapCalce.put('recordId', calce.Id);
        Test.StartTest();
        final BE_CalcePortafolioFall_Ctr portafolioFall = new BE_CalcePortafolioFall_Ctr();
        Final BE_SingleRelatedListCRUD_Cls.Response resp = portafolioFall.readRecords(mapCalce);
        System.assert(resp.isSuccess, 'success!!!');
        test.stopTest();
    }
    
    /**
    @Description test method updateRecords
    */
    @isTest
    public static void updateRecordsTest() {
        final Calce__c calce = new Calce__c();
        calce.Name = 'Test Calce';
        calce.close_date__c = Date.today().addDays(-45);
        calce.status__c = 'Iniciado';
        insert calce;
        final Calce_Details__c detail = new Calce_Details__c();
        detail.calce_id__c=calce.Id;
        detail.Name='detail';
        detail.CurrencyIsoCode='PEN';
        detail.amount__c=50000;
        detail.Contract_Number__c='23212312321';
        detail.close_date__c=date.today();
        detail.type__c='Direct';
        detail.product_code__c='CODE001';
        detail.sub_type__c='04';
        insert detail;
        final List<sObject> lts = new List<sObject>();
        detail.amount__c=40000;
        lts.add(detail);
        Test.StartTest();
        final BE_CalcePortafolioFall_Ctr portafolioFall = new BE_CalcePortafolioFall_Ctr();
        final BE_SingleRelatedListCRUD_Cls.Response resp = portafolioFall.updateRecords(lts);
        System.assert(resp.isSuccess, 'success!!!');
        test.stopTest();
    }
}