src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>branch_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <referenceTo>Branch__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>unique_id__c</fullName>
		<externalId>true</externalId>
        <label>Unique identifier</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/acpl__Account_Planning__c.object
<CustomObject>
    <fields>
        <fullName>acpl__external_reference_id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Account Planning external id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_limit_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>acpl__participant_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plannings</relationshipLabel>
        <relationshipName>Account_Plannings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acpl__proposal_manager_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Global Banker</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Plannings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Planning</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Planning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plannings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Be_Dynamic_Report_Chart__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Active_cache__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active cache</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Filters__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Filters</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Hide_on_error__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hide on error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rendered__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rendered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Report_DeveloperName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Report Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show_refresh_button__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Show refresh button</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Size__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Specify a chart’s size with one of these values:
    - tiny
    - small
    - medium
    - large
    huge</inlineHelpText>
        <label>Size</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_cache_data__c</fullName>
        <label>Time cache data (milliseconds)</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>unique_id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Unique Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Dynamic Report Chart</label>
</CustomObject>

src/objects/dwp_kitv__Visit__c.object
<CustomObject>
    <description>Main object to manage visits</description>
    <fields>
        <fullName>dwp_kitv__account_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account record related to this visit.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>dwp_kitv__visit_duration_number__c</fullName>
        <description>Time in minutes it takes to make the visit. The first hour will be intervals about 15 minutes, then 30 minutes intervals.</description>
        <inlineHelpText>Seleccione la duración en minutos</inlineHelpText>
        <label>Duration</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>120</fullName>
                </value>
                <value>
                    <fullName>150</fullName>
                </value>
                <value>
                    <fullName>180</fullName>
                </value>
                <value>
                    <fullName>210</fullName>
                </value>
                <value>
                    <fullName>240</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>dwp_kitv__visit_start_date__c</fullName>
        <description>Field to set the start date time of the visit.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
	<fields>
        <fullName>Unique_id__c</fullName>
        <externalId>true</externalId>
        <label>Unique_id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
	<fields>
        <fullName>User_position_equivalence__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>User position equivalence</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User_Position_equivalence__c.object
<CustomObject>
    <fields>
        <fullName>User_position_equivalence__c</fullName>
        <label>User position equivalence</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Cargo Equivalente</label>
    <nameField>
        <displayFormat>E-{0000000000}</displayFormat>
        <label>User Position equivalence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cargos Equivalentes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Be_RecordId_Related_Sobject_tst.cls
/**
 * @Name Be_RecordId_Related_Sobject_tst
 * @Author Diego Carbajal diego.carbajal@bbva.com
 * @Date Created: 2020-06-01
 * @Group
 * @Description Esta clase valida la funcionalidad de los metodos de la clase Be_RecordId_Related_Sobject_helper
 *
 */
@isTest
public class Be_RecordId_Related_Sobject_tst {
    /*FAIL*/
    private static Final String FAIL = 'Fail';
	/*Setup Data*/
	@TestSetup
	public static void setUp() {
		//Create custom settings
		Final Be_Dynamic_Report_Chart__c chartConfig = new Be_Dynamic_Report_Chart__c(Name = 'Account_Risk_Strategy', Active_cache__c = true,  Rendered__c = true, Size__c = 'large',
		                                                                              Filters__c = '[{column:\'Account.Id\',operator:\'equals\',value:\'recordId\'}]',
		                                                                              Hide_on_error__c = false, Report_DeveloperName__c = 'Account_Risk_Strategy',
		                                                                              Show_refresh_button__c = false, Time_cache_data__c = 86400000,
		                                                                              unique_id__c = 'AP_Account_Risk_Strategy');
		insert chartConfig;
		//Create Account
		Final Map<Schema.SObjectField, Object> mapFields = new Map<Schema.SObjectField, Object> {Account.OwnerId => UserInfo.getUserId(), Account.Name => 'CLIENTE MARTÍN'};
		TestFactory.getAccount(true, mapFields);
	}

	/*
	 * @Description  method instanceClass
	 */
	public static testmethod void instanceClass() {
		Final Account acc = [SELECT Id FROM Account LIMIT 1];
		Final List<Be_Dynamic_Report_Chart__c> chartConfig = Be_Dynamic_Report_Chart__c.getAll().values();
		Boolean condition = false;
		ApexPages.currentPage().getParameters().put('Id', String.valueOf(acc.Id));
		ApexPages.currentPage().getParameters().put('configName', String.valueOf(chartConfig[0].Report_DeveloperName__c));
		Test.startTest();
		Try {
			new Be_RecordId_Related_Sobject_helper();
			condition = true;
		} catch(Exception e) {
			System.debug(e.getMessage());
		}
		Test.stopTest();
		System.assert (condition, FAIL);
	}

	/*
	 * @Description  method getRecordIdSobjectTest
	 */
	public static testmethod void getRecordIdSobjectTest() {
		insert new dwp_kitv__Visit_validations_acc_cs__c(SetupOwnerId = UserInfo.getOrganizationId(), dwp_kitv__User_Team_Member__c = true);
		Final Account cuenta = [SELECT Id, branch_id__c FROM Account LIMIT 1];
		Final dwp_kitv__Visit__c visita = new dwp_kitv__Visit__c(Name = 'Visita', dwp_kitv__account_id__c = cuenta.Id, dwp_kitv__visit_duration_number__c = '15',
		                                                         dwp_kitv__visit_start_date__c = DateTime.now());
		insert visita;
		String result;
		Test.startTest();
		result = Be_RecordId_Related_Sobject_helper.getRecordIdSobject('dwp_kitv__Visit__c', 'dwp_kitv__account_id__c', visita.Id);
		Test.stopTest();
		Final Boolean condition = String.isNotBlank(result);
		System.assert (condition, FAIL);
	}

	/*
	 * @Description  method getUrlPageSuccess
	 */
	public static testmethod void getUrlPageSuccess() {
		insert new dwp_kitv__Visit_validations_acc_cs__c(SetupOwnerId = UserInfo.getOrganizationId(), dwp_kitv__User_Team_Member__c = true);
		Final Account cuenta = [SELECT Id, branch_id__c FROM Account LIMIT 1];
		Final dwp_kitv__Visit__c visita = new dwp_kitv__Visit__c(Name = 'Visita', dwp_kitv__account_id__c = cuenta.Id, dwp_kitv__visit_duration_number__c = '15',
		                                                         dwp_kitv__visit_start_date__c = DateTime.now());
		insert visita;
		Map<String, Object> mapResult;
		Test.startTest();
		mapResult = Be_RecordId_Related_Sobject_helper.getUrlPage(
            '{"reportDeveloperName":"Account_Risk_Strategy","sObjType":"dwp_kitv__Visit__c", "field":"dwp_kitv__account_id__c", "recordId":"'+visita.Id+'"}');
		Test.stopTest();
		Final Boolean condition = (Boolean)mapResult.get('isError');
		System.assert(condition, FAIL);
	}

	/*
	 * @Description  method getVisitValues
	 */
	public static testmethod void getVisitValues() {
		Final String perfil = [SELECT Id FROM Profile WHERE name = 'Ejecutivo'].Id;
		Final Map<Schema.SObjectField, Object> mapFields = new Map<Schema.SObjectField, Object> {User.LastName => 'Risotto', User.ProfileId => perfil,
			                                                                               User.user_position_equivalence__c => 'EJECUTIVO BEC'};
		Final User userOwner = TestFactory.getUser(true, mapFields);
		Final Account cuenta = [SELECT Id, branch_id__c FROM Account LIMIT 1];
		Final acpl__Account_Planning__c apR = new acpl__Account_Planning__c(acpl__participant_id__c = cuenta.Id, acpl__external_reference_id__c = 'AP123', Name = 'AP record',
		                                                             acpl__gf_ap_limit_date__c = System.today(), acpl__proposal_manager_id__c = userOwner.Id);
		insert apR;
		List<Integer> lstResult;
		Test.startTest();
		lstResult = Be_RecordId_Related_Sobject_helper.getVisitValues(apR.Id);
		Test.stopTest();
		Final Integer size = lstResult.size();
		Final Boolean condition = size > 0;
		System.assert (condition, FAIL);
	}
}