src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>unique_id__c</fullName>
		<externalId>true</externalId>
        <label>Unique identifier</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Account_Profitability__c.object
<CustomObject>
    <fields>
        <fullName>account_id__c</fullName> 
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Profitability</relationshipLabel>
        <relationshipName>Account_Profitability</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>currenct_mon_amount__c</fullName>
        <label>Current month amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>currenct_mon_per__c</fullName>
        <label>Current month percent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>profitability_category_type__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>	
        <fullName>profitability_subcategory_type__c</fullName>
        <label>Subcategory</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>profitability_type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>unique_id__c</fullName>
		<externalId>true</externalId>
        <label>Unique Identifier</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>year_month_day_date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
	    <fields>
        <fullName>product_desc__c</fullName>
        <label>product_desc</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Rentabilidad</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rentabilidades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/acpl__Account_Planning__c.object
<CustomObject>
    <label>Account Planning</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Planning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plannings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
	<fields>
        <fullName>Unique_id__c</fullName>
        <externalId>true</externalId>
        <label>Unique_id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/BE_EconomicGroup_Spread_Rate_tst.cls
/**
 * BE_EconomicGroup_Spread_Rate_tst
 * <p /><p />
 * Modification log:<p />
 * -------------------------------------------------------------------
 * Developer                    Date                Description<p />
 * -------------------------------------------------------------------
 * Diego Carbajal    		11/09/2020          Original version.<p />
 *
 * @author Diego Carbajal
 */
@isTest
public class BE_EconomicGroup_Spread_Rate_tst {

    /**
	 * @Description  setUp
	 */
    @TestSetup
    public static void setUp() {
        Final User admin = [SELECT Id FROM User WHERE Id=:UserInfo.getUserId()];
        Final Account acc = BE_EconomicGroup_DebtAndFee_tst.generateData(admin);
        Final Account_Profitability__c [] lstProf = new Account_Profitability__c []{};
        lstProf.add(new Account_Profitability__c (account_id__c = acc.Id, unique_id__c = 'TEST_1', profitability_type__c  = '03', profitability_subcategory_type__c = 'TOTAL CLIENTE', 
                                                  year_month_day_date__c = System.today(), currenct_mon_amount__c = 100045));
        lstProf.add(new Account_Profitability__c (account_id__c = acc.Id, unique_id__c = 'TEST_2', profitability_type__c  = '02', profitability_subcategory_type__c = 'TOTAL Spread', 
                                                  year_month_day_date__c = System.today(), currenct_mon_per__c = 1.10, product_desc__c = 'CLIENTE', profitability_category_type__c = 'Spread'));
        lstProf.add(new Account_Profitability__c (account_id__c = acc.Id, unique_id__c = 'TEST_3', profitability_type__c  = '02', profitability_subcategory_type__c = 'TOTAL Tasa', 
                                                  year_month_day_date__c = System.today(), currenct_mon_per__c = 1.72, product_desc__c = 'CLIENTE', profitability_category_type__c = 'Tasa'));
        System.runAs(admin) {
            insert lstProf;
        }
    }
    
    /**
	 * @Description  Test getData FROM BE_EconomicGroup_Spread_Rate_cls
	 */
    @isTest
    public static void getValues() {
        Final acpl__Account_Planning__c[] lstAP = [SELECT Id FROM acpl__Account_Planning__c LIMIT 1];
		Test.startTest();
        Final Map<String, String> mapParams = new Map<String, String>{'config' => 'Economic_Group_Spread_Rate', 'mode' => 'Basic', 'recordId' => lstAP[0].Id};
		Final Be_DTP_ResponseModel_cls.Response response = Be_DynamicTablePresentation_ctr.getValues(mapParams, 'ClientsGroup_Spread_Rate');
		Test.stopTest();
		System.assert(response.isSuccess, 'FAIL');
    }
}