src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>branch_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <referenceTo>Branch__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>branch_name__c</fullName>
        <formula>branch_id__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Main Branch</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Branch__c.object
<CustomObject>
    <description>Objeto de Oficina</description>
    <fields>
        <fullName>branch_id__c</fullName>
        <description>Código</description>
        <label>Branch Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Branch_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relates an opportunity with a branch</description>
        <label>Branch</label>
        <referenceTo>Branch__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
<fields>
        <fullName>opportunity_status_type__c</fullName>
        <description>Status of an opportunity</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User_Branch__c.object
<CustomObject>
    <description>Usuario Oficina</description>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Usuario</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Users_Branches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>branch_id__c</fullName>
        <formula>branch_name__r.branch_id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Branch code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>branch_name__c</fullName>
        <description>Oficina</description>
        <label>Branch</label>
        <referenceTo>Branch__c</referenceTo>
        <relationshipLabel>Branch users</relationshipLabel>
        <relationshipName>Branches_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Oficina de Usuario</label>
    <nameField>
        <displayFormat>UO-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Oficinas de Usuario</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GetOppBranchOperative_Test.cls
@isTest
public class GetOppBranchOperative_Test {
	@isTest
	public static void test1() {
		Account acc = TestFactory.createAccount();
		User operativoTest1 = TestFactory.createUser('operativoTest1', 'Operativo');
		User operativoTest2 = TestFactory.createUser('operativoTest2', 'Operativo');
		User operativoTest3 = TestFactory.createUser('operativoTest3', 'Operativo');
		User ejecutivoTest1 = TestFactory.createUser('operativoTest1', 'Ejecutivo');
		List<Branch__c> branchList = new List<Branch__c>();
		Branch__c branch1 = new Branch__c();
		branchList.add(branch1);
		Branch__c branch2 = new Branch__c();
		branchList.add(branch2);
		insert branchList;
		List<User_Branch__c> ubList = new List<User_Branch__c>();
		User_Branch__c ub1 = new User_Branch__c(branch_name__c = branchList[0].id, User__c = operativoTest1.Id);
		ubList.add(ub1);
		User_Branch__c ub2 = new User_Branch__c(branch_name__c = branchList[0].id, User__c = operativoTest2.Id);
		ubList.add(ub2);
		User_Branch__c ub3 = new User_Branch__c(branch_name__c = branchList[1].id, User__c = operativoTest3.Id);
		ubList.add(ub3);
		User_Branch__c ub4 = new User_Branch__c(branch_name__c = branchList[1].id, User__c = ejecutivoTest1.Id);
		ubList.add(ub4);
		insert ubList;
		List<Opportunity> oppList = new List<Opportunity>();
		Opportunity opp1 = new Opportunity(
			ownerId = operativoTest1.Id,
			Name = 'testopp1',
			AccountId = acc.Id,
			StageName = '01',
			Amount = 100,
			CloseDate = system.Date.today(),
			opportunity_status_type__c = '01',
			Branch_id__c = branchList[0].Id);
		oppList.add(opp1);
		Opportunity opp2 = new Opportunity(
			ownerId = operativoTest1.Id,
			Name = 'testopp2',
			AccountId = acc.Id,
			StageName = '01',
			Amount = 100,
			CloseDate = system.Date.today(),
			opportunity_status_type__c = '01',
			Branch_id__c = branchList[1].Id);
		oppList.add(opp2);
		insert oppList;
		List<Id> oppIdList = new List<Id>();
		for(Opportunity opp : oppList) {
			oppIdList.add(opp.Id);
		}
		System.runAs(operativoTest1) {
			Map<Id, List<Id>> result = GetOppBranchOperative.getRecipients(oppIdList, 'Opportunity');
			System.debug('Resultado Test ' + result);
			System.assertEquals(result.size(), 2);
		}
	}
}