src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>unique_id__c</fullName>
		<externalId>true</externalId>
        <label>Unique identifier</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Account_Income__c.object
<CustomObject>
    <fields>
        <fullName>account_id__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Incomes</relationshipLabel>
        <relationshipName>Account_Incomes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>gf_income_amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>gf_income_movement_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Income Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>gf_income_type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>unique_id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Unique Identifier</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Account Income</label>
    <nameField>
        <displayFormat>INC-{0000000000}</displayFormat>
        <label>Income Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Incomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/acpl__Account_Planning__c.object
<CustomObject>
    <label>Account Planning</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Planning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plannings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
	<fields>
        <fullName>Unique_id__c</fullName>
        <externalId>true</externalId>
        <label>Unique_id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/BE_EconomicGroup_AccountIncome_tst.cls
/**
 * BE_EconomicGroup_AccountIncome_tst
 * <p /><p />
 * Modification log:<p />
 * -------------------------------------------------------------------
 * Developer                    Date                Description<p />
 * -------------------------------------------------------------------
 * Diego Carbajal    		11/09/2020          Original version.<p />
 *
 * @author Diego Carbajal
 */
@isTest
public class BE_EconomicGroup_AccountIncome_tst {

    /**
	 * @Description  setUp
	 */
    @TestSetup
    public static void setUp() {
        Final User admin = [SELECT Id FROM User WHERE Id=:UserInfo.getUserId()];
        Final Account acc = BE_EconomicGroup_DebtAndFee_tst.generateData(admin);
        Final Account_Income__c[] lstAI = new Account_Income__c[]{};
        lstAI.add(new Account_Income__c(account_id__c = acc.Id, unique_id__c = 'TEST_1', CurrencyIsoCode = 'PEN', gf_income_type__c = '03', 
                                        gf_income_movement_date__c = Date.newInstance(System.today().year(), 1, 1), gf_income_amount__c = 10000));
        lstAI.add(new Account_Income__c(account_id__c = acc.Id, unique_id__c = 'TEST_2', CurrencyIsoCode = 'USD', gf_income_type__c = '03', 
                                        gf_income_movement_date__c = Date.newInstance(System.today().year(), 1, 1), gf_income_amount__c = 10000));
        lstAI.add(new Account_Income__c(account_id__c = acc.Id, unique_id__c = 'TEST_3', CurrencyIsoCode = 'PEN', gf_income_type__c = '03', 
                                        gf_income_movement_date__c = Date.newInstance(System.today().year() - 1, 1, 1), gf_income_amount__c = 10000));
        lstAI.add(new Account_Income__c(account_id__c = acc.Id, unique_id__c = 'TEST_4', CurrencyIsoCode = 'USD', gf_income_type__c = '03', 
                                        gf_income_movement_date__c = Date.newInstance(System.today().year() - 1, 1, 1), gf_income_amount__c = 10000));
        System.runAs(admin) {
            insert lstAI;
        }
    }
    
    /**
	 * @Description  Test getData FROM BE_EconomicGroup_AccountIncome_cls
	 */
    @isTest
    public static void getValues() {
        Final acpl__Account_Planning__c[] lstAP = [SELECT Id FROM acpl__Account_Planning__c LIMIT 1];
		Test.startTest();
        Final Map<String, String> mapParams = new Map<String, String>{'config' => 'Economic_Group_AccountIncome', 'mode' => 'Basic', 'recordId' => lstAP[0].Id};
		Final Be_DTP_ResponseModel_cls.Response response = Be_DynamicTablePresentation_ctr.getValues(mapParams, 'ClientsGroup_AccountIncome');
		Test.stopTest();
		System.assert(response.isSuccess, 'FAIL');
    }
}