src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>unique_id__c</fullName>
		<externalId>true</externalId>
        <label>Unique identifier</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Record_Type_Economic_Group</fullName>
        <active>true</active>
        <label>Economic Group</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/acpl__Account_Planning__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_ap_validation_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Validation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>acpl__gf_event_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Event date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>acpl__participant_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plannings</relationshipLabel>
        <relationshipName>Account_Plannings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Planning</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Planning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plannings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/acpl__Commercial_Plan_Event__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <formula>GrowthDriver__r.Amount__c</formula>
        <label>Monto</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Asiggned_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Usuario asignado</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Commercial_Plan_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientAssigned__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asignación de cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Commercial Plan Events (Asignación de cliente)</relationshipLabel>
        <relationshipName>Commercial_Plan_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Comentarios</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>GrowthDriver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Variable de crecimiento</label>
        <referenceTo>bupl__BP_GrowthDriver__c</referenceTo>
        <relationshipLabel>Commercial Plan Events</relationshipLabel>
        <relationshipName>Commercial_Plan_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acpl__gf_account_planning_id__c</fullName>
        <label>Account Planning</label>
        <referenceTo>acpl__Account_Planning__c</referenceTo>
        <relationshipLabel>Commercial Plan Events</relationshipLabel>
        <relationshipName>Commercial_Plan_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>acpl__gf_event_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Expected Completion Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>acpl__participant_id__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Commercial Plan Events</relationshipLabel>
        <relationshipName>Commercial_Plan_Events</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Commercial Plan Event</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Commercial Plan Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commercial Plan Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/bupl__BP_GrowthDriver__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_account_planning_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Planning</label>
        <referenceTo>acpl__Account_Planning__c</referenceTo>
        <relationshipLabel>Growth Drivers</relationshipLabel>
        <relationshipName>Growth_Drivers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>bupl__solution_category_desc__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>bupl__solution_category_id__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Préstamo comercial CP (manual)</fullName>
                </value>
                <value>
                    <fullName>Préstamo comercial CP</fullName>
                </value>
                <value>
                    <fullName>Comex importación (manual)</fullName>
                </value>
                <value>
                    <fullName>Comex importación</fullName>
                </value>
                <value>
                    <fullName>Comex exportación (manual)</fullName>
                </value>
                <value>
                    <fullName>Comex exportación</fullName>
                </value>
                <value>
                    <fullName>Forfaiting</fullName>
                </value>
                <value>
                    <fullName>Letras (manual)</fullName>
                </value>
                <value>
                    <fullName>Letras</fullName>
                </value>
                <value>
                    <fullName>Factoring</fullName>
                </value>
                <value>
                    <fullName>Préstamo comercial LP (manual)</fullName>
                </value>
                <value>
                    <fullName>Préstamo comercial LP</fullName>
                </value>
                <value>
                    <fullName>Leasing (manual)</fullName>
                </value>
                <value>
                    <fullName>Leasing</fullName>
                </value>
                <value>
                    <fullName>Carta fianza técnica (manual)</fullName>
                </value>
                <value>
                    <fullName>Carta fianza técnica</fullName>
                </value>
                <value>
                    <fullName>Carta fianza económica (manual)</fullName>
                </value>
                <value>
                    <fullName>Carta fianza económica</fullName>
                </value>
                <value>
                    <fullName>Stand by</fullName>
                </value>
                <value>
                    <fullName>Carta de crédito de importación</fullName>
                </value>
                <value>
                    <fullName>Carta de crédito de exportación</fullName>
                </value>
                <value>
                    <fullName>Vista PJ</fullName>
                </value>
                <value>
                    <fullName>Depósito a plazo</fullName>
                </value>
                <value>
                    <fullName>Pago a proveedores</fullName>
                </value>
                <value>
                    <fullName>Pago de haberes</fullName>
                </value>
                <value>
                    <fullName>Net Cash</fullName>
                </value>
                <value>
                    <fullName>FX</fullName>
                </value>
                <value>
                    <fullName>Forward</fullName>
                </value>
                <value>
                    <fullName>PFL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Growth Driver</label>
    <nameField>
        <displayFormat>GD_{YYYY}/{MM}-{0000}</displayFormat>
        <label>Growth Driver Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Growth Drivers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>opportunity_planning_date__c</fullName>
        <description>Planning date of an opportunity</description>
        <label>Planning date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>opportunity_product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>a product related to an opportunity</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>opportunity_product_family__c</fullName>
        <description>Product family in an opportunity</description>
        <label>Product family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>unique_id__c</fullName>
        <description>Internal control code</description>
        <label>Unique identifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
	<fields>
        <fullName>Unique_id__c</fullName>
        <description>Unique Id</description>
        <inlineHelpText>Unique Id</inlineHelpText>
        <label>Unique_id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
	<fields>
        <fullName>Unique_id__c</fullName>
        <description>Unique Id</description>
        <inlineHelpText>Unique Id</inlineHelpText>
        <label>Unique_id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>Unique_id__c</fullName>
        <externalId>true</externalId>
        <label>Unique_id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
	<fields>
        <fullName>Unique_id__c</fullName>
        <externalId>true</externalId>
        <label>Unique_id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
	<fields>
        <fullName>Unique_id__c</fullName>
        <externalId>true</externalId>
        <label>Unique_id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/AP_ConvertCPE_Helper_cls.cls
/** @Name AP_ConvertCPE_Helper_cls
* @Author Jair Anton jair.anton.contractor@bbva.com
* @Date Created: 2021-08-19
* Jair Anton 		19/08/2021		Helper clase AP_ConvertCPE_cls
*/
public with sharing class AP_ConvertCPE_Helper_cls {
    /** @Description  NAME*/
    private static Final String NAME = 'Name';
    /** @Description  NAME*/
    private static Final String RT_ECO_GRP = 'Record_Type_Economic_Group';

    private AP_ConvertCPE_Helper_cls() {}

    /** Modify actions commercial created */
    public static void verifyCPEModified(Map<Id, acpl__Commercial_Plan_Event__c> mapCPE, Map<Id, acpl__Commercial_Plan_Event__c> mapCPEAux, Map<Id, User> mapUser, Map<Id, Id> mapCPEPartner) {
		Final Set<Id> cpeModifiedSet = new Set<Id>();
		Final List<acpl__Commercial_Plan_Event__c> cpeList = [SELECT Id, acpl__gf_account_planning_id__r.acpl__gf_ap_validation_date__c, LastModifiedDate, CreatedDate 
																FROM acpl__Commercial_Plan_Event__c WHERE Id IN : mapCPE.keySet()];

        for(acpl__Commercial_Plan_Event__c item : cpeList) {
			if(Date.valueOf(item.LastModifieddate) >= item.acpl__gf_account_planning_id__r.acpl__gf_ap_validation_date__c) {
				cpeModifiedSet.add(item.Id);
			}
		}

		if(!cpeModifiedSet.isEmpty()) {
			Final Map<String, PriceBookEntry> mapPBE = new Map<String, PriceBookEntry>();
			for(PriceBookEntry pbe: [SELECT Id, Product2.Name, Product2.Family, Product2.Unique_id__c, CurrencyIsoCode FROM PriceBookEntry WHERE IsActive = TRUE AND Product2.isActive = TRUE]) {
				mapPBE.put(pbe.Product2.Unique_id__c + '_' + PBE.CurrencyIsoCode, pbe);
			}

            validateCPE(cpeModifiedSet, mapCPE, mapCPEAux, mapPBE, mapUser, mapCPEPartner);
		}	

	}

    private static void validateCPE(Set<Id> cpeModifiedSet, Map<Id, acpl__Commercial_Plan_Event__c> mapCPE, Map<Id, acpl__Commercial_Plan_Event__c> mapCPEAux, Map<String, PriceBookEntry> mapPBE, Map<Id, User> mapUser, Map<Id, Id> mapCPEPartner) {        
        Final Map<Id, Opportunity> oppToUpdateMap = new Map<Id, Opportunity>([SELECT  Id, StageName, commercial_plan_event__c, name, Description, currencyIsoCode, Amount, opportunity_planning_date__c, opportunity_product__c, 
                                                                                    opportunity_product_family__c FROM Opportunity WHERE commercial_plan_event__c IN: cpeModifiedSet AND StageName IN ('01', '02', '03')]);
        
        Final Map<Id, Opportunity> resultOppToUpdate = mapOpportunity(oppToUpdateMap);
        Final Map<Id, OpportunityLineItem> oppLineItemMap = new Map<Id, OpportunityLineItem>([SELECT Id, OpportunityId, Quantity, UnitPrice, PricebookEntryId  FROM OpportunityLineItem WHERE OpportunityId IN : oppToUpdateMap.keySet()]);
        Final Map<Id, OpportunityLineItem> resultOppLineItem = mapOpportunityLineItem(oppLineItemMap);

        Final List<OpportunityLineItem> oliToInsert = new List<OpportunityLineItem>();
        Final List<OpportunityLineItem> oliToDelete = new List<OpportunityLineItem>();
        Final List<OpportunityLineItem> oliToUpdate = new List<OpportunityLineItem>();
        Final List<Opportunity> oppToUpdate = new List<Opportunity>();
        Final List<OpportunityTeamMember> otmToInsert = new List<OpportunityTeamMember>();
        Final Map<Id, Id> visitTeamMap = new Map<Id, Id>();

        for(acpl__Commercial_Plan_Event__c item : mapCPE.values()) {
            if(cpeModifiedSet.contains(item.Id) && resultOppToUpdate.containsKey(item.Id)) {
                Opportunity oppItem = resultOppToUpdate.get(item.Id);
                
                validateGD(item, mapCPEAux, oppItem, mapPBE, resultOppLineItem, oliToInsert, oliToDelete, oliToUpdate, oppToUpdate);
                validateCreateATM(oppItem, item, otmToInsert, visitTeamMap, mapUser, mapCPEPartner);
            }
        }
        validateAction(oliToInsert, oliToDelete, oliToUpdate, oppToUpdate);

        if(!otmToInsert.isEmpty()) {
            insert otmToInsert;
        }
    }

    private static void validateCreateATM(Opportunity oppItem, acpl__Commercial_Plan_Event__c item, List<OpportunityTeamMember> otmToInsert, Map<Id, Id> visitTeamMap, Map<Id, User> mapUser, Map<Id, Id> mapCPEPartner) {
        if(mapCPEPartner.containsKey(item.Id)) {
            Id itemId = mapCPEPartner.get(item.Id);
            if(mapUser.containsKey(itemId)) {   
                otmToInsert.add(new OpportunityTeamMember(UserId = item.Asiggned_User__c, OpportunityId = oppItem.Id));
                visitTeamMap.put(item.Id, item.Asiggned_User__c);
            }
        }
    }

    private static void validateAction(List<OpportunityLineItem> oliToInsert, List<OpportunityLineItem> oliToDelete, List<OpportunityLineItem> oliToUpdate, List<Opportunity> oppToUpdate) {
        if(!oliToDelete.isEmpty()) {
            delete oliToDelete;
        }

        if(!oppToUpdate.isEmpty()) {
            update oppToUpdate;
        }

        if(!oliToInsert.isEmpty()) {
            insert oliToInsert;
        }

        if(!oliToUpdate.isEmpty()) {
            update oliToUpdate;
        }
    }

    private static void validateGD(acpl__Commercial_Plan_Event__c item, Map<Id, acpl__Commercial_Plan_Event__c> mapCPEAux, Opportunity oppItem, Map<String, PriceBookEntry> mapPBE, Map<Id, OpportunityLineItem> resultOppLineItem,
                                        List<OpportunityLineItem> oliToInsert, List<OpportunityLineItem> oliToDelete, List<OpportunityLineItem> oliToUpdate, List<Opportunity> oppToUpdate) {
        if(mapCPEAux.containsKey(item.Id)) {
            Final acpl__Commercial_Plan_Event__c cpeAuxItem = mapCPEAux.get(item.Id);
            Final OpportunityLineItem oppLineItem = resultOppLineItem.get(oppItem.Id);

            oppItem.CloseDate = item.acpl__gf_event_date__c; 
            oppItem.Description = item.Comments__c;

            oppItem.Amount = mapCPEAux.get(item.Id).GrowthDriver__r.Amount__c;

            validateProduct(mapPBE, cpeAuxItem, oppLineItem, oppItem, oliToInsert, oliToDelete, oliToUpdate, item, mapCPEAux);     
        } else {
            oppItem.CloseDate = item.acpl__gf_event_date__c; 
            oppItem.Description = item.Comments__c;
        }

        oppToUpdate.add(oppItem);   
    }

    private static void validateProduct(Map<String, PriceBookEntry> mapPBE, acpl__Commercial_Plan_Event__c cpeAuxItem, OpportunityLineItem oppLineItem, Opportunity oppItem, List<OpportunityLineItem> oliToInsert, 
                                            List<OpportunityLineItem> oliToDelete, List<OpportunityLineItem> oliToUpdate, acpl__Commercial_Plan_Event__c item, Map<Id, acpl__Commercial_Plan_Event__c> mapCPEAux) {
        if(mapPBE.containsKey(cpeAuxItem.GrowthDriver__r.bupl__solution_category_desc__c + '_' + cpeAuxItem.GrowthDriver__r.CurrencyIsoCode)) {
            if(mapPBE.get(cpeAuxItem.GrowthDriver__r.bupl__solution_category_desc__c + '_' + cpeAuxItem.GrowthDriver__r.CurrencyIsoCode).Id == oppLineItem.PricebookEntryId) {
                oppLineItem.UnitPrice = oppItem.Amount;
                oliToUpdate.add(oppLineItem);
            } else {
                Final PriceBookEntry pbeItem = mapPBE.get(cpeAuxItem.GrowthDriver__r.bupl__solution_category_desc__c + '_' + cpeAuxItem.GrowthDriver__r.CurrencyIsoCode);
                oliToDelete.add(oppLineItem);
                oliToInsert.add(new OpportunityLineItem(OpportunityId = oppItem.Id, Quantity = 1, UnitPrice = oppItem.Amount, PricebookEntryId = pbeItem.Id));

                oppItem.CurrencyIsoCode = mapCPEAux.get(item.Id).GrowthDriver__r.CurrencyIsoCode;
                oppItem.opportunity_product__c = pbeItem.Product2.Name;
                oppItem.opportunity_product_family__c = pbeItem.Product2.Family;
            }	
        }    
    }
    
	private static Map<Id, Opportunity> mapOpportunity(Map<Id, Opportunity> objectMap) {
		Final Map<Id, Opportunity> resultMap = new Map<Id, Opportunity>();
		
		for(Opportunity item : objectMap.values()) {
			resultMap.put(item.commercial_plan_event__c, item);
		}

		return resultMap;
	}

	private static Map<Id, OpportunityLineItem> mapOpportunityLineItem(Map<Id, OpportunityLineItem> objectMap) {
		Final Map<Id, OpportunityLineItem> resultMap = new Map<Id, OpportunityLineItem>();
		
		for(OpportunityLineItem item : objectMap.values()) {
			resultMap.put(item.OpportunityId, item);
		}
		
		return resultMap;
	}
    
	/*
	 * @Description  getMapClientAssigned
	 */
	public static Map<String, String> getMapClientAssigned(acpl__Commercial_Plan_Event__c cpe) {
		Final Map<String, String> mapClient = new Map<String, String>();
		if(cpe.acpl__gf_account_planning_id__r.acpl__participant_id__r.RecordType.DeveloperName == RT_ECO_GRP) {
			mapClient.put(NAME, cpe.ClientAssigned__r.Name);
			mapClient.put('Id', cpe.ClientAssigned__c);
		} else {
			mapClient.put(NAME, cpe.acpl__gf_account_planning_id__r.acpl__participant_id__r.Name);
			mapClient.put('Id', cpe.acpl__gf_account_planning_id__r.acpl__participant_id__c);
		}
		return mapClient;
	}
}