src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>segment_desc__c</fullName>
        <label>Segment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/acpl__Account_Planning__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_ap_limit_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_priority_type_name__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_status_type_name__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Validation</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_substatus_type_name__c</fullName>
        <label>Sub-status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>acpl__gf_ap_status_type_name__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>AP team not invited</fullName>
                </value>
                <value>
                    <fullName>AP team invited</fullName>
                </value>
                <value>
                    <fullName>Pending pre-validation</fullName>
                </value>
                <value>
                    <fullName>Pre-validated</fullName>
                </value>
                <value>
                    <fullName>Pending review</fullName>
                </value>
                <value>
                    <fullName>Pending validation</fullName>
                </value>
                <value>
                    <fullName>In place</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>acpl__participant_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plannings</relationshipLabel>
        <relationshipName>Account_Plannings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>segment_desc__c</fullName>
        <formula>acpl__participant_id__r.segment_desc__c</formula>
        <label>Segmento</label>
        <type>Text</type>
    </fields>
    <label>Account Planning</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Planning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plannings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/bupl__AP_Team__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_account_planning_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Planning</label>
        <referenceTo>acpl__Account_Planning__c</referenceTo>
        <relationshipLabel>Planning Team Members</relationshipLabel>
        <relationshipName>Account_Planning_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>bupl__gf_ap_team_user_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Planning_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Planning Team Member</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Planning Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planning Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BE_AP_HomeView_GOF_cls.cls
/**
 * ------------------------------------------------------------------------------------------------
 * @Name BE_AP_HomeView_GOF_cls
 * @Author Diego Carbajal diego.carbajal@bbva.com
 * @Date Created: 2020-06-08
 * @Group
 * @Description BE_AP_HomeView_GOF_cls
 *
 */
public class BE_AP_HomeView_GOF_cls extends Be_DTP_ResponseModel_cls {
	/*
	 * @Description  method getData
	 */
	public override Be_DTP_ResponseModel_cls.Response getData(String filter) {
		Final Be_DTP_ResponseModel_cls.Response response = new Be_DTP_ResponseModel_cls.Response();
		response.isSuccess = false;
		response.message = 'Ha ocurrido un error, por favor contacte a su administrador.';
		try {
			response.isSuccess = true;
			response.data = getGOFData(filter);
		} catch(Exception e) {
			System.debug('BE_AP_HomeView_GOF_cls');
			System.debug(e.getMessage());
		}
		return response;
	}

	/*
	 * @Description  method getGOFData
	 */
	private static List<Map<String, Object>> getGOFData(String filter) {
		Final List<Map<String, Object>> lstData = new List<Map<String, Object>>();
		List<acpl__Account_Planning__c> lstAP = new List<acpl__Account_Planning__c>();
		switch on filter {
			when 'not_started' {
				lstAP = [SELECT Id, acpl__participant_id__c, acpl__participant_id__r.Name, toLabel(acpl__gf_ap_status_type_name__c),
				         acpl__gf_ap_limit_date__c, toLabel(acpl__gf_ap_priority_type_name__c), segment_desc__c,
				         (SELECT Id, bupl__gf_ap_team_user_id__c FROM acpl__Account_Planning_Team_Members__r) FROM
				         acpl__Account_Planning__c WHERE RecordType.developerName = 'Account_Planning' AND
				                                                                    acpl__gf_ap_status_type_name__c = 'Not started' AND acpl__gf_ap_substatus_type_name__c = 'Not started'
				                                                                                                                                                             ORDER BY Name];
			}
			when 'in_progress' {
				lstAP = [SELECT Id, acpl__participant_id__c, acpl__participant_id__r.Name, toLabel(acpl__gf_ap_status_type_name__c),
				         acpl__gf_ap_limit_date__c, toLabel(acpl__gf_ap_priority_type_name__c), segment_desc__c,
				         (SELECT Id, bupl__gf_ap_team_user_id__c FROM acpl__Account_Planning_Team_Members__r) FROM
				         acpl__Account_Planning__c WHERE RecordType.developerName = 'Account_Planning' AND
				                                                                    acpl__gf_ap_status_type_name__c = 'In Progress' AND acpl__gf_ap_substatus_type_name__c != 'Expired'
				                                                                                                      ORDER BY Name];
			}
			when 'pending_validation' {
				lstAP = [SELECT Id, acpl__participant_id__c, acpl__participant_id__r.Name, toLabel(acpl__gf_ap_status_type_name__c),
				         acpl__gf_ap_limit_date__c, toLabel(acpl__gf_ap_priority_type_name__c), segment_desc__c FROM acpl__Account_Planning__c
				         WHERE RecordType.developerName = 'Account_Planning' AND acpl__gf_ap_status_type_name__c = 'Pending Validation' AND
				                                                                                                   acpl__gf_ap_substatus_type_name__c = 'Pending validation'
				                                                                                                                                        ORDER BY Name];
			}
			when 'validated' {
				lstAP = [SELECT Id, acpl__participant_id__c, acpl__participant_id__r.Name, toLabel(acpl__gf_ap_status_type_name__c),
				         acpl__gf_ap_limit_date__c, toLabel(acpl__gf_ap_priority_type_name__c), segment_desc__c,
				         (SELECT Id, bupl__gf_ap_team_user_id__c FROM acpl__Account_Planning_Team_Members__r) FROM
				         acpl__Account_Planning__c WHERE RecordType.developerName = 'Account_Planning' AND
				                                                                    acpl__gf_ap_status_type_name__c = 'Validated' AND acpl__gf_ap_substatus_type_name__c = 'In place'
				                                                                                                                                                           ORDER BY Name];
			}
			when 'closed_this_month' {
				lstAP = [SELECT Id, acpl__participant_id__c, acpl__participant_id__r.Name, toLabel(acpl__gf_ap_status_type_name__c),
				         acpl__gf_ap_limit_date__c, toLabel(acpl__gf_ap_priority_type_name__c), segment_desc__c,
				         (SELECT Id, bupl__gf_ap_team_user_id__c FROM acpl__Account_Planning_Team_Members__r) FROM
				         acpl__Account_Planning__c WHERE RecordType.developerName = 'Account_Planning' AND acpl__gf_ap_limit_date__c = THIS_MONTH
				                                                                                                                       AND acpl__gf_ap_substatus_type_name__c NOT IN('Expired', 'In place') ORDER BY Name];
			}
			when 'closed_next_month' {
				lstAP = [SELECT Id, acpl__participant_id__c, acpl__participant_id__r.Name, toLabel(acpl__gf_ap_status_type_name__c),
				         acpl__gf_ap_limit_date__c, toLabel(acpl__gf_ap_priority_type_name__c), segment_desc__c,
				         (SELECT Id, bupl__gf_ap_team_user_id__c FROM acpl__Account_Planning_Team_Members__r) FROM
				         acpl__Account_Planning__c WHERE RecordType.developerName = 'Account_Planning' AND acpl__gf_ap_limit_date__c = NEXT_MONTH
				                                                                                                                       AND acpl__gf_ap_substatus_type_name__c NOT IN('Expired', 'In place') ORDER BY Name];
			}
		}
		Map<String, Object> mapData;
		for(acpl__Account_Planning__c ap : lstAP) {
			mapData = new Map<String, Object> {'Id' => ap.Id, 'priority' => ap.acpl__gf_ap_priority_type_name__c,
				                               'clientName' => ap.acpl__participant_id__r.Name, 'segment' => ap.segment_desc__c,
				                               'DueDate' => ap.acpl__gf_ap_limit_date__c, 'status' => ap.acpl__gf_ap_status_type_name__c,
				                               'linkAP' => URL.getSalesforceBaseUrl().toExternalForm() + '/' + ap.Id};
			lstData.add(mapData);
		}
		return lstData;
	}
}