src/objects/acpl__Account_Planning__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_ap_indvi_lock_edit_ind_type__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Unlock Account Planning</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_limit_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_status_type_name__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Validation</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_substatus_type_name__c</fullName>
        <label>Sub-status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>acpl__gf_ap_status_type_name__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>AP team not invited</fullName>
                </value>
                <value>
                    <fullName>AP team invited</fullName>
                </value>
                <value>
                    <fullName>Pending pre-validation</fullName>
                </value>
                <value>
                    <fullName>Pre-validated</fullName>
                </value>
                <value>
                    <fullName>Pending review</fullName>
                </value>
                <value>
                    <fullName>Pending validation</fullName>
                </value>
                <value>
                    <fullName>In place</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>acpl__participant_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plannings</relationshipLabel>
        <relationshipName>Account_Plannings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acpl__proposal_manager_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Global Banker</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Plannings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Planning</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Planning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plannings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/bupl__BP_GrowthDriver__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_account_planning_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Planning</label>
        <referenceTo>acpl__Account_Planning__c</referenceTo>
        <relationshipLabel>Growth Drivers</relationshipLabel>
        <relationshipName>Growth_Drivers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>bupl__gf_business_growth_rec_number__c</fullName>
        <label>Counter</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>bupl__gf_business_plan_id__c</fullName>
        <label>Business Plan</label>
        <referenceTo>bupl__BusinessPlan__c</referenceTo>
        <relationshipLabel>Growth Drivers</relationshipLabel>
        <relationshipName>Growth_Drivers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>bupl__solution_category_desc__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>bupl__solution_category_id__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Préstamo comercial CP (manual)</fullName>
                </value>
                <value>
                    <fullName>Préstamo comercial CP</fullName>
                </value>
                <value>
                    <fullName>Comex importación (manual)</fullName>
                </value>
                <value>
                    <fullName>Comex importación</fullName>
                </value>
                <value>
                    <fullName>Comex exportación (manual)</fullName>
                </value>
                <value>
                    <fullName>Comex exportación</fullName>
                </value>
                <value>
                    <fullName>Forfaiting</fullName>
                </value>
                <value>
                    <fullName>Letras (manual)</fullName>
                </value>
                <value>
                    <fullName>Letras</fullName>
                </value>
                <value>
                    <fullName>Factoring</fullName>
                </value>
                <value>
                    <fullName>Préstamo comercial LP (manual)</fullName>
                </value>
                <value>
                    <fullName>Préstamo comercial LP</fullName>
                </value>
                <value>
                    <fullName>Leasing (manual)</fullName>
                </value>
                <value>
                    <fullName>Leasing</fullName>
                </value>
                <value>
                    <fullName>Carta fianza técnica (manual)</fullName>
                </value>
                <value>
                    <fullName>Carta fianza técnica</fullName>
                </value>
                <value>
                    <fullName>Carta fianza económica (manual)</fullName>
                </value>
                <value>
                    <fullName>Carta fianza económica</fullName>
                </value>
                <value>
                    <fullName>Stand by</fullName>
                </value>
                <value>
                    <fullName>Carta de crédito de importación</fullName>
                </value>
                <value>
                    <fullName>Carta de crédito de exportación</fullName>
                </value>
                <value>
                    <fullName>Vista PJ</fullName>
                </value>
                <value>
                    <fullName>Depósito a plazo</fullName>
                </value>
                <value>
                    <fullName>Pago a proveedores</fullName>
                </value>
                <value>
                    <fullName>Pago de haberes</fullName>
                </value>
                <value>
                    <fullName>Net Cash</fullName>
                </value>
                <value>
                    <fullName>FX</fullName>
                </value>
                <value>
                    <fullName>Forward</fullName>
                </value>
                <value>
                    <fullName>PFL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>bupl__solution_category_id__c</fullName>
        <label>Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Financiamiento a corto plazo</fullName>
                </value>
                <value>
                    <fullName>Riesgo de firma</fullName>
                </value>
                <value>
                    <fullName>Recursos</fullName>
                </value>
                <value>
                    <fullName>Serv. Transaccionales</fullName>
                </value>
                <value>
                    <fullName>Tesorería</fullName>
                </value>
                <value>
                    <fullName>Programa financiero</fullName>
                </value>
                <value>
                    <fullName>Corporate Finance</fullName>
                    <isActive>false</isActive>
                    <label>Corporate Finance</label>
                </value>
                <value>
                    <fullName>Global Finance</fullName>
                    <isActive>false</isActive>
                    <label>Global Finance</label>
                </value>
                <value>
                    <fullName>Global Markets</fullName>
                    <isActive>false</isActive>
                    <label>Global Markets</label>
                </value>
                <value>
                    <fullName>Global Transaction Banking</fullName>
                    <isActive>false</isActive>
                    <label>Global Transaction Banking</label>
                </value>
                <value>
                    <fullName>Others</fullName>
                    <isActive>false</isActive>
                    <label>Others</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Growth Driver</label>
    <nameField>
        <displayFormat>GD_{YYYY}/{MM}-{0000}</displayFormat>
        <label>Growth Driver Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Growth Drivers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/bupl__BusinessPlan__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_account_planning_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Planning</label>
        <referenceTo>acpl__Account_Planning__c</referenceTo>
        <relationshipLabel>Business Plans</relationshipLabel>
        <relationshipName>Business_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_indvi_lock_edit_ind_type__c</fullName>
        <formula>acpl__gf_account_planning_id__r.acpl__gf_ap_indvi_lock_edit_ind_type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AP unlocked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>bupl__gf_ap_public_ind_type__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Public Business Plan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>bupl__gf_business_growth_rec_number__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Growth Drivers Created</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>bupl__status_type__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Validation</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Business Plan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BE_CreateDriveGrowth_Helper_Tst.cls
/**@Name <BE_CreateDriveGrowth_Tst>
   @Author Jair Anton Atuncar (jair.anton.contractor@bbva.com)
   Date        Author   Email                  				Type
   2021-08-19  JAAA    jair.anton.contractor@bbva.com		Creation
   -------------------------------------------------------------------------------------------------
 */
@isTest
public class BE_CreateDriveGrowth_Helper_Tst {
    /** @Description VALIDATED*/
    Final static String VALIDATED = 'Validated';
    /**@Description IN_PLACE */
    Final static String IN_PLACE = 'In place';
    /**@Description FAILED */
    Final static String FAILED = 'Failed';
    /**@Description SUCCESS */
    Final static String SUCCESS = 'Success';

    
    /*Setup Data*/
    @TestSetup
    public static void setUp() {
        final List<String> sObjNames=new List<String>{'acpl__Account_Planning__c'};
        final Map<String,Schema.RecordTypeInfo> recordType=BE_General_Utils.getRecordTypeInfo(sObjNames);
        
        final User userExecutive = TestFactory.createUser('userExecutiveOwner','Ejecutivo');
        final Account acc = TestFactory.createAccount();        
        
        final acpl__Account_Planning__c accPlan = new acpl__Account_Planning__c(recordTypeId = recordType.get('Account_Planning').getRecordTypeId(), Name = 'Account_Planning Test', 
                                                                               acpl__gf_ap_indvi_lock_edit_ind_type__c = true, acpl__gf_ap_limit_date__c = System.today().addDays(90), 
                                                                               acpl__gf_ap_status_type_name__c = 'Not started', acpl__participant_id__c = acc.Id, 
                                                                               acpl__proposal_manager_id__c = userExecutive.Id);
        insert accPlan;
        
        final bupl__BusinessPlan__c bussPlan = new bupl__BusinessPlan__c(Name = 'Plan de Negocio AP_RECORD_102', bupl__gf_ap_public_ind_type__c = false, 
                                                                        bupl__gf_business_growth_rec_number__c = 1, bupl__status_type__c = 'Validated', 
                                                                        acpl__gf_account_planning_id__c = accPlan.id);
        insert bussPlan;
        AP_FactoryTest_tst.generateProduct();
    }
    
    private static bupl__BP_GrowthDriver__c obtainGD() {
        Final bupl__BusinessPlan__c bpAux = [SELECT Id, acpl__gf_account_planning_id__c FROM bupl__BusinessPlan__c LIMIT 1];
        return new bupl__BP_GrowthDriver__c(bupl__gf_business_plan_id__c = bpAux.Id, bupl__gf_business_growth_rec_number__c = 1, ExpectedDate__c = System.today(), 
                                     bupl__solution_category_desc__c = '0292235_NEW', CurrencyIsoCode = 'PEN', bupl__solution_category_id__c = 'Riesgo de firma', 
                                     acpl__gf_account_planning_id__c = bpAux.acpl__gf_account_planning_id__c);
    }

    /**
     @Description test updateRecords method, correct scenary invalid Product
    */
    @isTest
    static void updateRecordsClientTest() {
        Final List<acpl__Account_Planning__c> apList = [SELECT Id FROM acpl__Account_Planning__c LIMIT 1];
        Final Account acc = new Account(Name = 'TestAcct 2');
		insert acc;

        Final bupl__BP_GrowthDriver__c growthDriver = obtainGD();
        new BE_CreateDriveGrowth_ctr().createRecords(new List<SObject>{growthDriver});

        Test.startTest();
		apList[0].acpl__gf_ap_status_type_name__c = VALIDATED;
        apList[0].acpl__gf_ap_substatus_type_name__c = IN_PLACE;
        apList[0].acpl__gf_ap_indvi_lock_edit_ind_type__c = false;
        update apList[0];

		apList[0].acpl__gf_ap_status_type_name__c = 'In Progress';
        apList[0].acpl__gf_ap_substatus_type_name__c = 'Pre-validated';
        apList[0].acpl__gf_ap_indvi_lock_edit_ind_type__c = true;
        update apList[0];

        growthDriver.ClientAssigned__c = acc.Id;

        final BE_SingleRelatedListCRUD_Cls.Response resp = new BE_CreateDriveGrowth_ctr().updateRecords(new List<SObject>{growthDriver});
        Test.stopTest();
        System.assert(!resp.isSuccess, FAILED);
    }

        /**
     @Description test updateRecords method, correct scenary
    */
    @isTest
    static void updateRecordsNullTest() {
        Test.startTest();
        Final BE_SingleRelatedListCRUD_Cls.Response response = new BE_CreateDriveGrowth_ctr().updateRecords(null);
        Test.stopTest();
        System.assert(!response.isSuccess, FAILED);
    }
    
    /**
     @Description test deleteRecords method, correct scenary invalid CPE
    */
    @isTest
    static void deleteRecordsInvalidTest() {
        Final List<acpl__Account_Planning__c> apList = [SELECT Id FROM acpl__Account_Planning__c LIMIT 1];
        Final bupl__BP_GrowthDriver__c growthDriver = obtainGD();
        new BE_CreateDriveGrowth_ctr().createRecords(new List<SObject>{growthDriver});
        
        Test.startTest();
		apList[0].acpl__gf_ap_status_type_name__c = VALIDATED;
        apList[0].acpl__gf_ap_substatus_type_name__c = IN_PLACE;
        apList[0].acpl__gf_ap_indvi_lock_edit_ind_type__c = false;
        update apList[0];

        final BE_SingleRelatedListCRUD_Cls.Response resp = new BE_CreateDriveGrowth_ctr().deleteRecords(new List<SObject>{growthDriver});
        Test.stopTest();
        System.assert(!resp.isSuccess, FAILED);
    }

    /**
     @Description test deleteRecords method, correct scenary 
    */
    @isTest
    static void deleteRecordsTest() {
        Final bupl__BP_GrowthDriver__c growthDriver = obtainGD();
        new BE_CreateDriveGrowth_ctr().createRecords(new List<SObject>{growthDriver});
        
        Test.startTest();
        final BE_SingleRelatedListCRUD_Cls.Response resp = new BE_CreateDriveGrowth_ctr().deleteRecords(new List<SObject>{growthDriver});
        Test.stopTest();
        System.assert(resp.isSuccess, SUCCESS);
    }

       /**
     @Description test deleteRecords method, correct scenary
    */
    @isTest
    static void deleteRecordsNullTest() {
        Test.startTest();
        Final BE_SingleRelatedListCRUD_Cls.Response response = new BE_CreateDriveGrowth_ctr().deleteRecords(null);
        Test.stopTest();
        System.assert(!response.isSuccess, FAILED);
    }
}