src/objects/acpl__Account_Planning__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_ap_indvi_lock_edit_ind_type__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Unlock Account Planning</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_limit_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_public_ind_type__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Public Business Plan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_status_type_name__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Validation</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>acpl__participant_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plannings</relationshipLabel>
        <relationshipName>Account_Plannings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acpl__proposal_manager_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Global Banker</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Plannings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Planning</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Planning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plannings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/bupl__BP_Need__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_account_planning_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Planning</label>
        <referenceTo>acpl__Account_Planning__c</referenceTo>
        <relationshipLabel>Needs</relationshipLabel>
        <relationshipName>Needs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>bupl__gf_bus_pl_cust_lock_name__c</fullName>
        <label>Pain Points</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Insufficient credit lines</fullName>
                </value>
                <value>
                    <fullName>Lack of product capabilities</fullName>
                </value>
                <value>
                    <fullName>High competition on pricing</fullName>
                </value>
                <value>
                    <fullName>Legal issues pending to be solved</fullName>
                </value>
                <value>
                    <fullName>Our timing is out of the market</fullName>
                </value>
                <value>
                    <fullName>Lack of Strategic dialogue</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>bupl__gf_bus_pl_sales_goal_name__c</fullName>
        <label>Need</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Increase credit lines</fullName>
                </value>
                <value>
                    <fullName>Increase guarantees lines</fullName>
                </value>
                <value>
                    <fullName>Increase industry asset allocation</fullName>
                </value>
                <value>
                    <fullName>Increase country risk limits</fullName>
                </value>
                <value>
                    <fullName>Build new product capabilities</fullName>
                </value>
                <value>
                    <fullName>More aggresive pricing strategy</fullName>
                </value>
                <value>
                    <fullName>Increase execution speed</fullName>
                </value>
                <value>
                    <fullName>Improve internal coordination</fullName>
                </value>
                <value>
                    <fullName>BBVA Senior Management support</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>bupl__gf_bus_pl_unlk_revenue_amount__c</fullName>
        <label>Potential Revenue Increase</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>bupl__gf_business_lock_record_number__c</fullName>
        <label>Counter</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>bupl__gf_business_plan_id__c</fullName>
        <label>Business Plan</label>
        <referenceTo>bupl__BusinessPlan__c</referenceTo>
        <relationshipLabel>Needs</relationshipLabel>
        <relationshipName>Needs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Need</label>
    <nameField>
        <displayFormat>BPNeed-{0}</displayFormat>
        <label>Needs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Needs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/bupl__BusinessPlan__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_account_planning_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Planning</label>
        <referenceTo>acpl__Account_Planning__c</referenceTo>
        <relationshipLabel>Business Plans</relationshipLabel>
        <relationshipName>Business_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_indvi_lock_edit_ind_type__c</fullName>
        <formula>acpl__gf_account_planning_id__r.acpl__gf_ap_indvi_lock_edit_ind_type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AP unlocked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>bupl__gf_ap_public_ind_type__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Public Business Plan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>bupl__gf_business_growth_rec_number__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Growth Drivers Created</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>bupl__gf_business_lock_record_number__c</fullName>
        <label>Total Needs Created</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>bupl__status_type__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Validation</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Business Plan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BE_CreateNeed_Tst.cls
/**
   -------------------------------------------------------------------------------------------------
   @Name <BE_CreateNeed_Tst>
   @Author Martin Alejandro Mori Chavez (martin.mori.contractor@bbva.com)
   @Date 2020-06-04
   @Description test for BE_CreateNeed_ctr class
   @Changes
   Date        Author   Email                  				Type
   2020-06-04  MAMC     martin.mori.contractor@bbva.com		Creation
   -------------------------------------------------------------------------------------------------
 */
@isTest
public without sharing class BE_CreateNeed_Tst {
    /*Setup Data*/
    @TestSetup
    public static void setUp() {
        final List<String> sObjNames=new List<String>{'acpl__Account_Planning__c'};
        final Map<String,Schema.RecordTypeInfo> recordType=BE_General_Utils.getRecordTypeInfo(sObjNames);
        
        final User userExecutive = TestFactory.createUser('userExecutiveOwner','Ejecutivo');
        final Account acc = TestFactory.createAccount();        
        
        final acpl__Account_Planning__c accPlan = new acpl__Account_Planning__c();
        accPlan.recordTypeId = recordType.get('Account_Planning').getRecordTypeId();
        accPlan.Name = 'Account_Planning Test';
        accPlan.acpl__gf_ap_indvi_lock_edit_ind_type__c = true;
        accPlan.acpl__gf_ap_limit_date__c = System.today().addDays(90);
        accPlan.acpl__gf_ap_public_ind_type__c = true;
        accPlan.acpl__gf_ap_status_type_name__c = 'Not started';
        accPlan.acpl__participant_id__c = acc.Id;
        accPlan.acpl__proposal_manager_id__c = userExecutive.Id;
        insert accPlan;
        
        final bupl__BusinessPlan__c bussPlan = new bupl__BusinessPlan__c();
        bussPlan.Name = 'Plan de Negocio AP_RECORD_102';
        bussPlan.bupl__gf_ap_public_ind_type__c = false;
        bussPlan.bupl__gf_business_growth_rec_number__c = 1;
        bussPlan.bupl__status_type__c = 'Validated';
        bussPlan.acpl__gf_account_planning_id__c = accPlan.id;
        insert bussPlan;
    }
    
    /**
     @Description test createRecords method, correct scenary
    */
    @isTest
    static void createRecordsTest() {
        final bupl__BusinessPlan__c bussPlan = [SELECT Id, acpl__gf_account_planning_id__c FROM bupl__BusinessPlan__c LIMIT 1][0];
        final bupl__BP_Need__c need = new bupl__BP_Need__c();
        need.bupl__gf_business_plan_id__c = bussPlan.Id;
        need.bupl__gf_bus_pl_cust_lock_name__c = 'Insufficient credit lines';
        need.bupl__gf_bus_pl_sales_goal_name__c = 'Increase credit lines';
        need.bupl__gf_bus_pl_unlk_revenue_amount__c = 23456;
        need.bupl__gf_business_lock_record_number__c = 1;
        need.acpl__gf_account_planning_id__c = bussPlan.acpl__gf_account_planning_id__c;
        final List<SObject> sObjs = new List<SObject>();
        sObjs.add(need);
        
        Test.startTest();
        final BE_CreateNeed_ctr createNeed = new BE_CreateNeed_ctr();
        final BE_SingleRelatedListCRUD_Cls.Response resp = createNeed.createRecords(sObjs);
        System.assertEquals(resp.message, 'Successful', 'success!!!');
        Test.stopTest();
    }
    
    /**
     @Description test createRecords method, fail scenary
    */
    @isTest
    static void createRecordsNullTest() {
        Test.startTest();
        final BE_CreateNeed_ctr createNeed = new BE_CreateNeed_ctr();
        final BE_SingleRelatedListCRUD_Cls.Response resp = createNeed.createRecords(null);
        System.assert(!resp.isSuccess, 'fail!');
        Test.stopTest();
    }
}