src/objects/acpl__Account_Planning__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_ap_indvi_lock_edit_ind_type__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Unlock Account Planning</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_limit_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_public_ind_type__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Public Business Plan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_status_type_name__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Validation</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_substatus_type_name__c</fullName>
        <label>Sub-status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>acpl__gf_ap_status_type_name__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>AP team not invited</fullName>
                </value>
                <value>
                    <fullName>AP team invited</fullName>
                </value>
                <value>
                    <fullName>Pending pre-validation</fullName>
                </value>
                <value>
                    <fullName>Pre-validated</fullName>
                </value>
                <value>
                    <fullName>Pending review</fullName>
                </value>
                <value>
                    <fullName>Pending validation</fullName>
                </value>
                <value>
                    <fullName>In place</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>acpl__gf_event_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Event date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>acpl__participant_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plannings</relationshipLabel>
        <relationshipName>Account_Plannings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acpl__proposal_manager_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Global Banker</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Plannings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Planning</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Planning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plannings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/acpl__Commercial_Plan_Event__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <formula>GrowthDriver__r.Amount__c</formula>
        <label>Monto</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Asiggned_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Usuario asignado</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Commercial_Plan_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GrowthDriver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Variable de crecimiento</label>
        <referenceTo>bupl__BP_GrowthDriver__c</referenceTo>
        <relationshipLabel>Commercial Plan Events</relationshipLabel>
        <relationshipName>Commercial_Plan_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acpl__gf_account_planning_id__c</fullName>
        <label>Account Planning</label>
        <referenceTo>acpl__Account_Planning__c</referenceTo>
        <relationshipLabel>Commercial Plan Events</relationshipLabel>
        <relationshipName>Commercial_Plan_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>acpl__gf_comm_plan_event_type_name__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Visit</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
                <value>
                    <fullName>Task</fullName>
                </value>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Pitch</fullName>
                    <isActive>false</isActive>
                    <label>Pitch</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>acpl__gf_event_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Expected Completion Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>acpl__participant_id__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Commercial Plan Events</relationshipLabel>
        <relationshipName>Commercial_Plan_Events</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Commercial Plan Event</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Commercial Plan Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commercial Plan Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/bupl__BP_GrowthDriver__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_account_planning_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Planning</label>
        <referenceTo>acpl__Account_Planning__c</referenceTo>
        <relationshipLabel>Growth Drivers</relationshipLabel>
        <relationshipName>Growth_Drivers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>bupl__gf_business_plan_id__c</fullName>
        <label>Business Plan</label>
        <referenceTo>bupl__BusinessPlan__c</referenceTo>
        <relationshipLabel>Growth Drivers</relationshipLabel>
        <relationshipName>Growth_Drivers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>bupl__solution_category_desc__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>bupl__solution_category_id__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Préstamo comercial CP (manual)</fullName>
                </value>
                <value>
                    <fullName>Préstamo comercial CP</fullName>
                </value>
                <value>
                    <fullName>Comex importación (manual)</fullName>
                </value>
                <value>
                    <fullName>Comex importación</fullName>
                </value>
                <value>
                    <fullName>Comex exportación (manual)</fullName>
                </value>
                <value>
                    <fullName>Comex exportación</fullName>
                </value>
                <value>
                    <fullName>Forfaiting</fullName>
                </value>
                <value>
                    <fullName>Letras (manual)</fullName>
                </value>
                <value>
                    <fullName>Letras</fullName>
                </value>
                <value>
                    <fullName>Factoring</fullName>
                </value>
                <value>
                    <fullName>Préstamo comercial LP (manual)</fullName>
                </value>
                <value>
                    <fullName>Préstamo comercial LP</fullName>
                </value>
                <value>
                    <fullName>Leasing (manual)</fullName>
                </value>
                <value>
                    <fullName>Leasing</fullName>
                </value>
                <value>
                    <fullName>Carta fianza técnica (manual)</fullName>
                </value>
                <value>
                    <fullName>Carta fianza técnica</fullName>
                </value>
                <value>
                    <fullName>Carta fianza económica (manual)</fullName>
                </value>
                <value>
                    <fullName>Carta fianza económica</fullName>
                </value>
                <value>
                    <fullName>Stand by</fullName>
                </value>
                <value>
                    <fullName>Carta de crédito de importación</fullName>
                </value>
                <value>
                    <fullName>Carta de crédito de exportación</fullName>
                </value>
                <value>
                    <fullName>Vista PJ</fullName>
                </value>
                <value>
                    <fullName>Depósito a plazo</fullName>
                </value>
                <value>
                    <fullName>Pago a proveedores</fullName>
                </value>
                <value>
                    <fullName>Pago de haberes</fullName>
                </value>
                <value>
                    <fullName>Net Cash</fullName>
                </value>
                <value>
                    <fullName>FX</fullName>
                </value>
                <value>
                    <fullName>Forward</fullName>
                </value>
                <value>
                    <fullName>PFL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>bupl__solution_category_id__c</fullName>
        <label>Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Financiamiento a corto plazo</fullName>
                </value>
                <value>
                    <fullName>Riesgo de firma</fullName>
                </value>
                <value>
                    <fullName>Recursos</fullName>
                </value>
                <value>
                    <fullName>Serv. Transaccionales</fullName>
                </value>
                <value>
                    <fullName>Tesorería</fullName>
                </value>
                <value>
                    <fullName>Programa financiero</fullName>
                </value>
                <value>
                    <fullName>Corporate Finance</fullName>
                    <isActive>false</isActive>
                    <label>Corporate Finance</label>
                </value>
                <value>
                    <fullName>Global Finance</fullName>
                    <isActive>false</isActive>
                    <label>Global Finance</label>
                </value>
                <value>
                    <fullName>Global Markets</fullName>
                    <isActive>false</isActive>
                    <label>Global Markets</label>
                </value>
                <value>
                    <fullName>Global Transaction Banking</fullName>
                    <isActive>false</isActive>
                    <label>Global Transaction Banking</label>
                </value>
                <value>
                    <fullName>Others</fullName>
                    <isActive>false</isActive>
                    <label>Others</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Growth Driver</label>
    <nameField>
        <displayFormat>GD_{YYYY}/{MM}-{0000}</displayFormat>
        <label>Growth Driver Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Growth Drivers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/bupl__BusinessPlan__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_account_planning_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Planning</label>
        <referenceTo>acpl__Account_Planning__c</referenceTo>
        <relationshipLabel>Business Plans</relationshipLabel>
        <relationshipName>Business_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_indvi_lock_edit_ind_type__c</fullName>
        <formula>acpl__gf_account_planning_id__r.acpl__gf_ap_indvi_lock_edit_ind_type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AP unlocked</label>
        <type>Checkbox</type>
    </fields>
    <label>Business Plan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BE_CreateCommercialPlantEvent_Tst.cls
/**@Name <BE_CreateCommercialPlantEvent_Tst>
   @Author Martin Alejandro Mori Chavez (martin.mori.contractor@bbva.com)
   Date        Author   Email                  				Type
   2020-06-04  MAMC     martin.mori.contractor@bbva.com		Creation
   2020-10-09  DCP     diego.carbajal@bbva.com				Modified
   19/08/2021  JAA     jair.anton.contractor@bbva.com      Valida CPE creados.
   -------------------------------------------------------------------------------------------------
 */
@isTest
public without sharing class BE_CreateCommercialPlantEvent_Tst {
    /** @Description VALIDATED*/
    Final static String VALIDATED = 'Validated';
    /**@Description IN_PLACE */
    Final static String IN_PLACE = 'In place';
    /**@Description FAILED */
    Final static String FAILED = 'Failed';
    /**@Description SUCCESS */
    Final static String SUCCESS = 'Success';
    /**@Description TASK */
    Final static String TASK = 'Task';
    /**@Description RECORD_NAME */ 
    Final static String RECORD_NAME = 'AP_RECORD_102 - 2020-05-31';

    /*Setup Data*/
    @TestSetup
    public static void setUp() {
        final List<String> sObjNames=new List<String>{'acpl__Account_Planning__c'};
        final Map<String,Schema.RecordTypeInfo> recordType = BE_General_Utils.getRecordTypeInfo(sObjNames);
        
        final User userExecutiveO = TestFactory.createUser('userExecutiveOwner','Ejecutivo');
        final Account acc = TestFactory.createAccount();        
        
        insert new acpl__Account_Planning__c(Name = 'Account_Planning Test', acpl__gf_ap_indvi_lock_edit_ind_type__c = true,
                                             acpl__gf_ap_limit_date__c = System.today().addDays(90), acpl__gf_ap_public_ind_type__c = true, 
                                             acpl__gf_ap_status_type_name__c = 'Not started', acpl__proposal_manager_id__c = userExecutiveO.Id, 
                                             acpl__participant_id__c = acc.Id, recordTypeId = recordType.get('Account_Planning').getRecordTypeId());
    }
    
        /**
     @Description test readRecords method, correct scenary
    */
    @isTest
    static void readRecordsTest() {
        Final acpl__Account_Planning__c accPlan = [SELECT Id, acpl__participant_id__c FROM acpl__Account_Planning__c LIMIT 1][0];
        Final acpl__Commercial_Plan_Event__c evt1 = new acpl__Commercial_Plan_Event__c(Name = RECORD_NAME, acpl__gf_account_planning_id__c = accPlan.Id, acpl__gf_comm_plan_event_type_name__c = TASK, 
                                                            acpl__gf_event_date__c = System.today(), acpl__participant_id__c = accPlan.acpl__participant_id__c);
        Final acpl__Commercial_Plan_Event__c evt2 = new acpl__Commercial_Plan_Event__c(Name = RECORD_NAME, acpl__gf_account_planning_id__c = accPlan.Id, acpl__gf_comm_plan_event_type_name__c = 'Opportunity', 
                                                                acpl__gf_event_date__c = System.today(), acpl__participant_id__c = accPlan.acpl__participant_id__c);
        Final acpl__Commercial_Plan_Event__c evt3 = new acpl__Commercial_Plan_Event__c(Name = RECORD_NAME, acpl__gf_account_planning_id__c = accPlan.Id, acpl__gf_comm_plan_event_type_name__c = 'Visit', 
                                                                acpl__gf_event_date__c = System.today(), acpl__participant_id__c = accPlan.acpl__participant_id__c);
        
        Final List<SObject> sObjs = new List<SObject>();
        sObjs.add(evt1);
        
        new BE_CreateCommercialPlantEvent_cls().createRecords(sObjs);
        sObjs[0] = evt2;        
        new BE_CreateCommercialPlantEvent_cls().createRecords(sObjs);
        sObjs[0] = evt3;
        new BE_CreateCommercialPlantEvent_cls().createRecords(sObjs);

        Test.startTest();
		accPlan.acpl__gf_ap_status_type_name__c = VALIDATED;
        accPlan.acpl__gf_ap_substatus_type_name__c = IN_PLACE;
        accPlan.acpl__gf_ap_indvi_lock_edit_ind_type__c = false;
        update accPlan;

        
        Final Map<String,Object> apMap = new Map<String,Object>();
        apMap.put('recordId', accPlan.Id);

        final BE_SingleRelatedListCRUD_Cls.Response response = new BE_CreateCommercialPlantEvent_cls().readRecords(apMap);

        Test.stopTest();
        System.assert(response.isSuccess, SUCCESS);
    }


    /**
     @Description test createRecords method, correct scenary
    */
    @isTest
    static void createRecordsTest() {
        final acpl__Account_Planning__c accPlan = [SELECT Id, acpl__participant_id__c FROM acpl__Account_Planning__c LIMIT 1][0];
        final acpl__Commercial_Plan_Event__c planEvt = new acpl__Commercial_Plan_Event__c();
        planEvt.Name = RECORD_NAME;
        planEvt.acpl__gf_account_planning_id__c = accPlan.Id;
        planEvt.acpl__gf_comm_plan_event_type_name__c = TASK;
        planEvt.acpl__gf_event_date__c = System.today();
        planEvt.acpl__participant_id__c = accPlan.acpl__participant_id__c;
        final List<SObject> sObjs = new List<SObject>();
        sObjs.add(planEvt);
        
        Test.startTest();
        final BE_CreateCommercialPlantEvent_cls commPlanEvt = new BE_CreateCommercialPlantEvent_cls();
        final BE_SingleRelatedListCRUD_Cls.Response resp = commPlanEvt.createRecords(sObjs);
        System.assert(resp.isSuccess, SUCCESS);
        Test.stopTest();
    }
    
    /**
     @Description test createRecords method, fail scenary
    */
    @isTest
    static void createRecordsNullTest() {
        Test.startTest();
        final BE_CreateCommercialPlantEvent_cls commPlanEvt = new BE_CreateCommercialPlantEvent_cls();
        final BE_SingleRelatedListCRUD_Cls.Response resp = commPlanEvt.createRecords(null);
        System.assert(!resp.isSuccess, FAILED);
        Test.stopTest();
    }
    
    /**
     @Description test updateRecords method, correct scenary
    */
    @isTest
    static void updateRecordsTest() {
        Final User usrInactive = [SELECT Id FROM User WHERE IsActive = false AND Profile.Name = 'Ejecutivo' LIMIT 1][0];
        Final User usrActive = [SELECT Id FROM User WHERE IsActive = true AND Profile.Name = 'Especialista' LIMIT 1][0];
        Final acpl__Account_Planning__c accPlan = [SELECT Id, acpl__participant_id__c FROM acpl__Account_Planning__c LIMIT 1][0];
        Final bupl__BusinessPlan__c bpAux = [SELECT Id, acpl__gf_account_planning_id__r.acpl__participant_id__c, acpl__gf_account_planning_id__r.Name
                                                     FROM bupl__BusinessPlan__c WHERE acpl__gf_account_planning_id__c = :accPlan.Id LIMIT 1];
        Final bupl__BP_GrowthDriver__c gdAux = new bupl__BP_GrowthDriver__c(acpl__gf_account_planning_id__c = accPlan.Id, bupl__gf_business_plan_id__c = bpAux.Id,
                                                                            CurrencyIsoCode = 'PEN', Amount__c = 123.4567, bupl__solution_category_id__c = 'Financiamiento a corto plazo', 
                                                                            bupl__solution_category_desc__c = '0160010_NEW', ExpectedDate__c = System.today());
        insert gdAux;
        acpl__Commercial_Plan_Event__c planEvt = new acpl__Commercial_Plan_Event__c();
        planEvt.Name = RECORD_NAME;
        planEvt.acpl__gf_account_planning_id__c = accPlan.Id;
        planEvt.acpl__gf_comm_plan_event_type_name__c = 'Opportunity';
        planEvt.acpl__gf_event_date__c = System.today();
        planEvt.acpl__participant_id__c = accPlan.acpl__participant_id__c;
        planEvt.GrowthDriver__c = gdAux.Id;
        final List<SObject> sObjCreate = new List<SObject>();
        sObjCreate.add(planEvt);
        
        final BE_CreateCommercialPlantEvent_cls commPlanEvt1 = new BE_CreateCommercialPlantEvent_cls();
        commPlanEvt1.createRecords(sObjCreate);

        planEvt = [SELECT Id, acpl__gf_event_date__c, acpl__gf_account_planning_id__c, Asiggned_User__c FROM acpl__Commercial_Plan_Event__c LIMIT 1][0];
        
        Test.startTest();
        planEvt.acpl__gf_event_date__c = System.today().addDays(30);
        planEvt.Asiggned_User__c = usrInactive.Id;
        final List<SObject> sObjUpd1 = new List<SObject>();
        sObjUpd1.add(planEvt);
        final BE_CreateCommercialPlantEvent_cls commPlanEvt2 = new BE_CreateCommercialPlantEvent_cls();
        commPlanEvt2.updateRecords(sObjUpd1);
        
        planEvt.Asiggned_User__c = usrActive.Id;
        final List<SObject> sObjUpd2 = new List<SObject>();
        sObjUpd2.add(planEvt);
        final BE_CreateCommercialPlantEvent_cls commPlanEvt3 = new BE_CreateCommercialPlantEvent_cls();
        final BE_SingleRelatedListCRUD_Cls.Response resp = commPlanEvt3.updateRecords(sObjUpd2);
        System.assert(resp.isSuccess, SUCCESS);
        Test.stopTest();
    }
    
    /**
     @Description test updateRecords method, fail scenary
    */
    @isTest
    static void updateRecordsNullTest() {
        final BE_CreateCommercialPlantEvent_cls commPlanEvt = new BE_CreateCommercialPlantEvent_cls();
        Test.startTest();
        final BE_SingleRelatedListCRUD_Cls.Response resp  = commPlanEvt.updateRecords(null);
        System.assert(!resp.isSuccess, FAILED);
        Test.stopTest();
    }
}