src/objects/acpl__Account_Planning__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_ap_status_type_name__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Validation</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_substatus_type_name__c</fullName>
        <label>Sub-status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>acpl__gf_ap_status_type_name__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>AP team not invited</fullName>
                </value>
                <value>
                    <fullName>AP team invited</fullName>
                </value>
                <value>
                    <fullName>Pending pre-validation</fullName>
                </value>
                <value>
                    <fullName>Pre-validated</fullName>
                </value>
                <value>
                    <fullName>Pending review</fullName>
                </value>
                <value>
                    <fullName>Pending validation</fullName>
                </value>
                <value>
                    <fullName>In place</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Planning</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Planning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plannings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/bupl__AP_Team__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_account_planning_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Planning</label>
        <referenceTo>acpl__Account_Planning__c</referenceTo>
        <relationshipLabel>Planning Team Members</relationshipLabel>
        <relationshipName>Account_Planning_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>bupl__gf_ap_team_user_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Planning_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>bupl__gf_business_plan_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Plan</label>
        <referenceTo>bupl__BusinessPlan__c</referenceTo>
        <relationshipLabel>Business Plan Team</relationshipLabel>
        <relationshipName>Business_Plan_Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Planning Team Member</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Planning Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planning Team Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/User_APSharing_batch.cls
/**
 * User_APSharing_batch
 * <p /><p />
 * Modification log:<p />
 * -------------------------------------------------------------------
 * Developer                    Date                Description<p />
 * -------------------------------------------------------------------
 * Diego Carbajal    		04/06/2020          Original version.<p />
 *
 * @author Diego Carbajal
 */
public without sharing class User_APSharing_batch implements Database.Batchable<sObject>, Database.Stateful {
	/**
	   @Description userIds
	 */
    private Set<Id> userIds {get; set;}
	/**
	   @Description User_APSharing_batch
	 */
	public User_APSharing_batch(Set<Id> ids) {
		this.userIds = ids;
	}

	/**
	   @Description start
	 */
	public Database.QueryLocator start(Database.BatchableContext batchC) {
		return Database.getQueryLocator([SELECT Id, acpl__gf_account_planning_id__c, bupl__gf_ap_team_user_id__c, bupl__gf_business_plan_id__c FROM bupl__AP_Team__c 
                                         WHERE bupl__gf_ap_team_user_id__c IN: userIds AND acpl__gf_account_planning_id__r.RecordType.DeveloperName = 'Account_Planning' 
                                         AND(acpl__gf_account_planning_id__r.acpl__gf_ap_status_type_name__c NOT IN ('Validated') OR 
                                             acpl__gf_account_planning_id__r.acpl__gf_ap_substatus_type_name__c NOT IN ('Expired'))]);
	}

	/**
	   @Description execute
	 */
	public void execute(Database.BatchableContext batchC, List<bupl__AP_Team__c> lstobj) {
		system.debug('>>>>> BATCH lstobj: ' + lstobj);
		Final Map<Id, bupl__AP_Team__c> mapAPT = new Map<Id, bupl__AP_Team__c>();
		for(bupl__AP_Team__c apt:lstobj) {
			mapAPT.put(apt.Id, apt);
		}
		if(!mapAPT.isEmpty()) {
			Sharing_AP_Team_User_cls.SharingAPT(mapAPT, false);
		}
	}

	/**
	   @Description finish
	 */
	public void finish(Database.BatchableContext batchC) {}
}