src/objects/acpl__Account_Planning__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_ap_status_type_name__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Validation</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Planning</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Planning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plannings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/bupl__BP_GrowthDriver__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_account_planning_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Planning</label>
        <referenceTo>acpl__Account_Planning__c</referenceTo>
        <relationshipLabel>Growth Drivers</relationshipLabel>
        <relationshipName>Growth_Drivers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>bupl__gf_business_plan_id__c</fullName>
        <label>Business Plan</label>
        <referenceTo>bupl__BusinessPlan__c</referenceTo>
        <relationshipLabel>Growth Drivers</relationshipLabel>
        <relationshipName>Growth_Drivers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>bupl__solution_category_desc__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>bupl__solution_category_id__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Préstamo comercial CP (manual)</fullName>
                </value>
                <value>
                    <fullName>Préstamo comercial CP</fullName>
                </value>
                <value>
                    <fullName>Comex importación (manual)</fullName>
                </value>
                <value>
                    <fullName>Comex importación</fullName>
                </value>
                <value>
                    <fullName>Comex exportación (manual)</fullName>
                </value>
                <value>
                    <fullName>Comex exportación</fullName>
                </value>
                <value>
                    <fullName>Forfaiting</fullName>
                </value>
                <value>
                    <fullName>Letras (manual)</fullName>
                </value>
                <value>
                    <fullName>Letras</fullName>
                </value>
                <value>
                    <fullName>Factoring</fullName>
                </value>
                <value>
                    <fullName>Préstamo comercial LP (manual)</fullName>
                </value>
                <value>
                    <fullName>Préstamo comercial LP</fullName>
                </value>
                <value>
                    <fullName>Leasing (manual)</fullName>
                </value>
                <value>
                    <fullName>Leasing</fullName>
                </value>
                <value>
                    <fullName>Carta fianza técnica (manual)</fullName>
                </value>
                <value>
                    <fullName>Carta fianza técnica</fullName>
                </value>
                <value>
                    <fullName>Carta fianza económica (manual)</fullName>
                </value>
                <value>
                    <fullName>Carta fianza económica</fullName>
                </value>
                <value>
                    <fullName>Stand by</fullName>
                </value>
                <value>
                    <fullName>Carta de crédito de importación</fullName>
                </value>
                <value>
                    <fullName>Carta de crédito de exportación</fullName>
                </value>
                <value>
                    <fullName>Vista PJ</fullName>
                </value>
                <value>
                    <fullName>Depósito a plazo</fullName>
                </value>
                <value>
                    <fullName>Pago a proveedores</fullName>
                </value>
                <value>
                    <fullName>Pago de haberes</fullName>
                </value>
                <value>
                    <fullName>Net Cash</fullName>
                </value>
                <value>
                    <fullName>FX</fullName>
                </value>
                <value>
                    <fullName>Forward</fullName>
                </value>
                <value>
                    <fullName>PFL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>bupl__solution_category_id__c</fullName>
        <label>Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Financiamiento a corto plazo</fullName>
                </value>
                <value>
                    <fullName>Riesgo de firma</fullName>
                </value>
                <value>
                    <fullName>Recursos</fullName>
                </value>
                <value>
                    <fullName>Serv. Transaccionales</fullName>
                </value>
                <value>
                    <fullName>Tesorería</fullName>
                </value>
                <value>
                    <fullName>Programa financiero</fullName>
                </value>
                <value>
                    <fullName>Corporate Finance</fullName>
                    <isActive>false</isActive>
                    <label>Corporate Finance</label>
                </value>
                <value>
                    <fullName>Global Finance</fullName>
                    <isActive>false</isActive>
                    <label>Global Finance</label>
                </value>
                <value>
                    <fullName>Global Markets</fullName>
                    <isActive>false</isActive>
                    <label>Global Markets</label>
                </value>
                <value>
                    <fullName>Global Transaction Banking</fullName>
                    <isActive>false</isActive>
                    <label>Global Transaction Banking</label>
                </value>
                <value>
                    <fullName>Others</fullName>
                    <isActive>false</isActive>
                    <label>Others</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Growth Driver</label>
    <nameField>
        <displayFormat>GD_{YYYY}/{MM}-{0000}</displayFormat>
        <label>Growth Driver Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Growth Drivers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/bupl__BusinessPlan__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_account_planning_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Planning</label>
        <referenceTo>acpl__Account_Planning__c</referenceTo>
        <relationshipLabel>Business Plans</relationshipLabel>
        <relationshipName>Business_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Business Plan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BP_GrowthDriver_Handler_tst.cls
/**
 * Test class for BP_GrowthDriver_Handler_cls and subclass
 * <p /><p />
 * Modification log:<p />
 * -------------------------------------------------------------------
 * Developer                    Date                Description<p />
 * -------------------------------------------------------------------
 * Diego Carbajal    		04/06/2020          Original version.<p />
 *
 * @author Diego Carbajal
 */
@isTest
public class BP_GrowthDriver_Handler_tst {
	/**
	   @Description mapUsers
	 */
	Final static Map<String, User> mapUsers = AP_FactoryTest_tst.getUsers();

	/**
	   @Description afterInsert
	 */
	@TestSetup
	public static void setUp() {
		AP_FactoryTest_tst.forSetUp();
	}

	/**
	 * @Description Test method beforeInsert
	 */
	public static testmethod void beforeInsert() {
		Final Account acc = [SELECT Id FROM Account LIMIT 1];
		Final acpl__Account_Planning__c apR = TestFactory.createAccountPlanning(acc.Id, mapUsers.get('EJECUTIVO').Id, null, false);
		insert apR;
		Final bupl__BusinessPlan__c bpR = [SELECT Id FROM bupl__BusinessPlan__c WHERE acpl__gf_account_planning_id__c =:apR.Id LIMIT 1];
		Test.startTest();
		System.runAs(mapUsers.get('EJECUTIVO')) {
			try {
				Final bupl__BP_GrowthDriver__c[] auxGD = new bupl__BP_GrowthDriver__c[] {};
				auxGD.add(new bupl__BP_GrowthDriver__c(acpl__gf_account_planning_id__c = apR.Id, bupl__gf_business_plan_id__c = bpR.Id,
				                                       bupl__solution_category_id__c = 'Riesgo de firma', bupl__solution_category_desc__c = 'Stand by'));
				auxGD.add(new bupl__BP_GrowthDriver__c(acpl__gf_account_planning_id__c = apR.Id, bupl__gf_business_plan_id__c = bpR.Id,
				                                       bupl__solution_category_id__c = 'Riesgo de firma', bupl__solution_category_desc__c = 'Stand by'));
				insert auxGD;
			} catch(Exception e) {
				System.debug(e.getMessage());
			}
		}
		Test.stopTest();
		Final bupl__BP_GrowthDriver__c[] lstGD = [SELECT Id FROM bupl__BP_GrowthDriver__c WHERE acpl__gf_account_planning_id__c =:apR.Id];
		Final Integer size = lstGD.size();
		System.assertEquals(size, 0, 'Fail Assertion');
	}

	/**
	 * @Description Test method beforeUpdate
	 */
	public static testmethod void beforeUpdate() {
		Final Account acc = [SELECT Id FROM Account LIMIT 1];
		Final acpl__Account_Planning__c apR = TestFactory.createAccountPlanning(acc.Id, mapUsers.get('EJECUTIVO').Id, null, false);
		insert apR;
		Final bupl__BusinessPlan__c bpR = [SELECT Id FROM bupl__BusinessPlan__c WHERE acpl__gf_account_planning_id__c =:apR.Id LIMIT 1];
		Final bupl__BP_GrowthDriver__c vGD = new bupl__BP_GrowthDriver__c(acpl__gf_account_planning_id__c = apR.Id, bupl__gf_business_plan_id__c = bpR.Id,
		                                                                  bupl__solution_category_id__c = 'Riesgo de firma', bupl__solution_category_desc__c = 'Stand by');
		insert vGD;
		Final String product = 'Stand by';
		Test.startTest();
		System.runAs(mapUsers.get('EJECUTIVO')) {
			try {
				vGD.bupl__solution_category_desc__c = 'Carta fianza económica';
				update vGD;
			} catch(Exception e) {
				System.debug(e.getMessage());
			}
		}
		Test.stopTest();
		Final bupl__BP_GrowthDriver__c[] lstGD = [SELECT Id, bupl__solution_category_desc__c FROM bupl__BP_GrowthDriver__c WHERE acpl__gf_account_planning_id__c =:apR.Id];
		System.assertEquals(product, lstGD[0].bupl__solution_category_desc__c, 'Fail Assertion');
	}

	/**
	 * @Description Test method beforeDelete
	 */
	public static testmethod void beforeDelete() {
		Final Account acc = [SELECT Id FROM Account LIMIT 1];
		Final acpl__Account_Planning__c apR = TestFactory.createAccountPlanning(acc.Id, mapUsers.get('EJECUTIVO').Id, null, false);
		insert apR;
		Final bupl__BusinessPlan__c bpR = [SELECT Id FROM bupl__BusinessPlan__c WHERE acpl__gf_account_planning_id__c =:apR.Id LIMIT 1];
		Final bupl__BP_GrowthDriver__c vGD = new bupl__BP_GrowthDriver__c(acpl__gf_account_planning_id__c = apR.Id, bupl__gf_business_plan_id__c = bpR.Id,
		                                                                  bupl__solution_category_id__c = 'Riesgo de firma', bupl__solution_category_desc__c = 'Stand by');
		insert vGD;
		Test.startTest();
		System.runAs(mapUsers.get('EJECUTIVO')) {
			try {
				delete vGD;
			} catch(Exception e) {
				System.debug(e.getMessage());
			}
		}
		Test.stopTest();
		Final bupl__BP_GrowthDriver__c[] lstGD = [SELECT Id FROM bupl__BP_GrowthDriver__c WHERE acpl__gf_account_planning_id__c =:apR.Id];
		Final Integer size = lstGD.size();
		System.assert (size > 0, 'Fail Assertion');
	}

	/**
	 * @Description Test method afterInsert
	 */
	public static testmethod void afterInsert() {
		Final Account acc = [SELECT Id FROM Account LIMIT 1];
		Final acpl__Account_Planning__c apR = TestFactory.createAccountPlanning(acc.Id, mapUsers.get('EJECUTIVO').Id, null, true);
		insert apR;
		Final bupl__BusinessPlan__c bpR = [SELECT Id FROM bupl__BusinessPlan__c WHERE acpl__gf_account_planning_id__c =:apR.Id LIMIT 1];
		Test.startTest();
		System.runAs(mapUsers.get('EJECUTIVO')) {
			insert new bupl__BP_GrowthDriver__c(acpl__gf_account_planning_id__c = apR.Id, bupl__gf_business_plan_id__c = bpR.Id,
			                                    bupl__solution_category_id__c = 'Riesgo de firma', bupl__solution_category_desc__c = 'Stand by');
		}
		Test.stopTest();
		Final acpl__Account_Planning__c apAux = [SELECT Id, acpl__gf_ap_status_type_name__c FROM acpl__Account_Planning__c WHERE Id =:apR.Id LIMIT 1];
		System.assertEquals('In Progress', apAux.acpl__gf_ap_status_type_name__c, 'Fail Assertion');
	}
}