src/objects/acpl__Account_Planning__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_ap_status_type_name__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Validation</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_substatus_type_name__c</fullName>
        <label>Sub-status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>acpl__gf_ap_status_type_name__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>AP team not invited</fullName>
                </value>
                <value>
                    <fullName>AP team invited</fullName>
                </value>
                <value>
                    <fullName>Pending pre-validation</fullName>
                </value>
                <value>
                    <fullName>Pre-validated</fullName>
                </value>
                <value>
                    <fullName>Pending review</fullName>
                </value>
                <value>
                    <fullName>Pending validation</fullName>
                </value>
                <value>
                    <fullName>In place</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Planning</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Planning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plannings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BE_AP_Administration_Helper_tst.cls
/**
 * Test class BE_AP_Administration_Helper_tst
 * <p /><p />
 * Modification log:<p />
 * -------------------------------------------------------------------
 * Developer                    Date                Description<p />
 * -------------------------------------------------------------------
 * Diego Carbajal    		04/06/2020          Original version.<p />
 *
 * @author Diego Carbajal
 */
@isTest
public class BE_AP_Administration_Helper_tst {

    /** @Description  FAIL*/
    private static Final String FAIL = 'Fail';
    
    /*
	 * @Description  method setUp
	 */
	@TestSetup
	static void setUp() {
		BE_AP_Administration_tst.setUp();
	}
    
    /*
	 * @Description  method validateStatusValidated
	 */
	public static testmethod void validateStatusValidated() {
		Map<String, Object> mapValidated = new Map<String, Object>();
		Final acpl__Account_Planning__c apR = [SELECT Id, acpl__gf_ap_substatus_type_name__c, acpl__gf_ap_status_type_name__c FROM acpl__Account_Planning__c LIMIT 1];
		Test.startTest();
		mapValidated = BE_AP_Administration_helper.validateStatus(apR);
		Test.stopTest();
		System.assert ((Boolean)mapValidated.get('validation'), FAIL);
	}

	/*
	 * @Description  method addErrorOnSobject
	 */
	public static testmethod void addErrorOnSobject() {
		Final List<acpl__Account_Planning__c> lstAP = new List<acpl__Account_Planning__c> {[SELECT Id, acpl__gf_ap_substatus_type_name__c, acpl__gf_ap_status_type_name__c FROM acpl__Account_Planning__c LIMIT 1]};
		Boolean result;
		Test.startTest();
		try {
			BE_AP_Administration_helper.addErrorOnSobject(lstAP, 'acpl__Account_Planning__c', 'Error');
			result = true;
		} catch(Exception e) {
			System.debug(e.getMessage());
			result = false;
		}
		Test.stopTest();
		System.assert (result, FAIL);
	}

	/*
	 * @Description  method customMessageInsert
	 */
	public static testmethod void customMessageInsert() {
		String result;
		Test.startTest();
		result = BE_AP_Administration_helper.customMessage('insert', 'registro', 'bloqueado');
		Test.stopTest();
		System.assert (String.isNotBlank(result), FAIL);
	}

	/*
	 * @Description  method customMessageUpdate
	 */
	public static testmethod void customMessageUpdate() {
		String result;
		Test.startTest();
		result = BE_AP_Administration_helper.customMessage('update', 'registro', 'bloqueado');
		Test.stopTest();
		System.assert (String.isNotBlank(result), FAIL);
	}

	/*
	 * @Description  method customMessageDelete
	 */
	public static testmethod void customMessageDelete() {
		String result;
		Test.startTest();
		result = BE_AP_Administration_helper.customMessage('delete', 'registro', 'bloqueado');
		Test.stopTest();
		System.assert (String.isNotBlank(result), FAIL);
	}
}