src/objects/acpl__Account_Planning__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_ap_indvi_lock_edit_ind_type__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Unlock Account Planning</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_status_type_name__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Validation</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_substatus_type_name__c</fullName>
        <label>Sub-status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>acpl__gf_ap_status_type_name__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>AP team not invited</fullName>
                </value>
                <value>
                    <fullName>AP team invited</fullName>
                </value>
                <value>
                    <fullName>Pending pre-validation</fullName>
                </value>
                <value>
                    <fullName>Pre-validated</fullName>
                </value>
                <value>
                    <fullName>Pending review</fullName>
                </value>
                <value>
                    <fullName>Pending validation</fullName>
                </value>
                <value>
                    <fullName>In place</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Planning</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Planning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plannings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/bupl__BP_Need__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_account_planning_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Planning</label>
        <referenceTo>acpl__Account_Planning__c</referenceTo>
        <relationshipLabel>Needs</relationshipLabel>
        <relationshipName>Needs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>bupl__gf_business_plan_id__c</fullName>
        <label>Business Plan</label>
        <referenceTo>bupl__BusinessPlan__c</referenceTo>
        <relationshipLabel>Needs</relationshipLabel>
        <relationshipName>Needs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Need</label>
    <nameField>
        <displayFormat>BPNeed-{0}</displayFormat>
        <label>Needs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Needs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/bupl__BusinessPlan__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_account_planning_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Planning</label>
        <referenceTo>acpl__Account_Planning__c</referenceTo>
        <relationshipLabel>Business Plans</relationshipLabel>
        <relationshipName>Business_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_indvi_lock_edit_ind_type__c</fullName>
        <formula>acpl__gf_account_planning_id__r.acpl__gf_ap_indvi_lock_edit_ind_type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AP unlocked</label>
        <type>Checkbox</type>
    </fields>
    <label>Business Plan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BP_Need_Trigger_cls.cls
/**
 * Handler class of Trigger handler of the Need object.
 * <p /><p />
 * Modification log:<p />
 * -------------------------------------------------------------------
 * Developer                    Date                Description<p />
 * -------------------------------------------------------------------
 * Diego Carbajal    		15/05/2020          Original version.<p />
 *
 * @author Diego Carbajal
 */
public without sharing class BP_Need_Trigger_cls {
    
    /*
	 * @Description  BP_Need_Trigger_cls
	 */
    private BP_Need_Trigger_cls() {}
	/*
	 * @Description  Valida que el usuario tenga permisos para insertar/modificar/eliminar registros
	 */
	public static void validateUserPermission(bupl__BP_Need__c[] newNeeds, String actionType) {
		Final Map<Id, List<bupl__BP_Need__c>> mapNeeds = new Map<Id, List<bupl__BP_Need__c>>();
		List<bupl__BP_Need__c> tmpNeed;
		for(bupl__BP_Need__c need:newNeeds) {
			tmpNeed = new List<bupl__BP_Need__c> {need};
			if(mapNeeds.containsKey(need.acpl__gf_account_planning_id__c)) {
				tmpNeed.addAll(mapNeeds.get(need.acpl__gf_account_planning_id__c));
			}
			mapNeeds.put(need.acpl__gf_account_planning_id__c, tmpNeed);
		}
		Final acpl__Account_Planning__c[] lstAP = [SELECT Id, acpl__gf_ap_indvi_lock_edit_ind_type__c, acpl__gf_ap_status_type_name__c, acpl__gf_ap_substatus_type_name__c
		                                     FROM acpl__Account_Planning__c WHERE Id IN:mapNeeds.keySet() AND recordType.DeveloperName = 'Account_Planning'];
		Final Integer lstAPSize = lstAP.size();
		if(lstAPSize > 0) {
			Final BE_AP_Permission_helper apAdministration = new BE_AP_Permission_helper(UserInfo.getUserId());
			Final Map<String, String> mapConfig = new Map<String, String> {'sobjectType' => 'bupl__BP_Need__c', 'actionType' => actionType};
			apAdministration.permissionOnRelatedRecords(lstAP, mapNeeds, mapConfig);
		}
	}

	/*
	 * @author       Global Desktop
	 * @Description  Check if Need has been created and propagates this change on Status field in related AP.
	 */
	public static void updateStatusOnAP(Map<Id, bupl__BP_Need__c> triggerNewMap) {
		Final Set<Id> bpIdList = new Set<Id>();
		for(bupl__BP_Need__c nd : triggerNewMap.values()) {
			//save de BP id's to query on it later
			bpIdList.add(nd.bupl__gf_business_plan_id__c);
		}

		if(!bpIdList.isEmpty()) {
			final List<bupl__BusinessPlan__c> listRelatedBP = [SELECT Id, acpl__gf_account_planning_id__c FROM bupl__BusinessPlan__c WHERE Id IN :bpIdList AND acpl__gf_account_planning_id__r.acpl__gf_ap_status_type_name__c = 'Not started'];
			final Set<Id> apIdList = new Set<Id>();
			for(bupl__BusinessPlan__c bp : listRelatedBP) {
				apIdList.add(bp.acpl__gf_account_planning_id__c);
			}
			if(!apIdList.isEmpty()) {
				updateAP(apIdList);
			}
		}
	}
    
    /*
	 * @Description  updateAP
	 */
    private static void updateAP(final Set<Id> apIdList) {
        Final BE_AP_Permission_helper permission = new BE_AP_Permission_helper(UserInfo.getUserId());
        Final Map<Id, Set<Id>> mapAPTs = permission.getAPTs(apIdList);
        final List<acpl__Account_Planning__c> listAPtoUpdate = [SELECT Id, acpl__gf_ap_status_type_name__c, acpl__gf_ap_substatus_type_name__c FROM acpl__Account_Planning__c WHERE Id IN :APidList AND acpl__gf_ap_status_type_name__c = 'Not started'];
        for(acpl__Account_Planning__c ap : listAPtoUpdate) {
            Final Boolean userInAPT = (mapAPTs.get(ap.Id) == null ? false :mapAPTs.get(ap.Id).contains(UserInfo.getUserId()));
            if(userInAPT && ap.acpl__gf_ap_status_type_name__c == 'Not started' && ap.acpl__gf_ap_substatus_type_name__c != Label.acpl.AP_Timed_Out) {
                ap.acpl__gf_ap_status_type_name__c = 'In Progress';
                ap.acpl__gf_ap_substatus_type_name__c = 'AP team not invited';
            }
        }
        if(!listAPtoUpdate.isEmpty()) {
            update listAPtoUpdate;
        }
    }
}