src/objects/acpl__Account_Planning__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_mandatory_type__c</fullName>
        <label>Required</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mandatory</fullName>
                </value>
                <value>
                    <fullName>Optional</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <isActive>false</isActive>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                    <isActive>false</isActive>
                    <label>Yes</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Planning</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Planning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plannings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/acpl__Account_Planning_Type__c.object
<CustomObject>
    <label>Account Planning Type</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Planning Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Planning Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/acpl__AP_Question__c.object
<CustomObject>
    <fields>
        <fullName>acpl__AA_answer_text__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Answer text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>acpl__gf_account_planning_id__c</fullName>
        <label>Account Planning</label>
        <referenceTo>acpl__Account_Planning__c</referenceTo>
        <relationshipLabel>Account Planning Questions</relationshipLabel>
        <relationshipName>Account_Planning_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_question_form_desc__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Question</label>
        <type>TextArea</type>
    </fields>
    <label>Account Planning Question</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Planning Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Planning Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/dyfr__Field_Config__c.object
<CustomObject>
    <fields>
        <fullName>dyfr__DeveloperName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Developer name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>dyfr__Important__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Important</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>dyfr__Tab__c</fullName>
        <label>Tab</label>
        <referenceTo>dyfr__Tab__c</referenceTo>
        <relationshipName>Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Field Config</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Field Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Configs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/dyfr__Tab__c.object
<CustomObject>
    <label>Tab</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Tabs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AP_QuestionsProgressController_Test.cls
@isTest
public class AP_QuestionsProgressController_Test {
    /**
	 * @Description variable MAP_USERS
	 */
	private static Final Map<String, User> MAP_USERS = AP_FactoryTest_tst.obtainUsers();
    /**
	 * @Description variable EJECUTIVO
	 */
    private static Final String EJECUTIVO = 'EJECUTIVO';
    /**
	 * @Description variable handler
	 */
    private static Final acpl.AccountPlanningHandler AP_HANDLER = acpl.AccountPlanningHandler.getInstance();
    
    @TestSetup
    static void makeData(){
        AP_FactoryTest_tst.forSetUp();
    }

    @isTest
    public static void calculateQuestionsTest() {
        Final Account acc = [SELECT Id FROM Account LIMIT 1];
		Final acpl__Account_Planning__c apR = AP_FactoryTest_tst.createAccountPlanning(acc.Id, MAP_USERS.get(EJECUTIVO).Id, null, true);
		insert apR;
        
        Final List<acpl__Account_Planning__c> apList = [SELECT Id, Name, acpl__Account_Planning_Type__c, CreatedDate, acpl__gf_mandatory_type__c FROM acpl__Account_Planning__c 
                                                  WHERE CreatedDate = TODAY AND Name = 'Account Planning'];
        AP_HANDLER.relateAPQuestions(apList);
        
        Final dyfr__Tab__c dfTab = [SELECT Id FROM dyfr__Tab__c LIMIT 1];
        Final List<dyfr__Field_Config__c> fconfigList = new List<dyfr__Field_Config__c>();
        fconfigList.add(new dyfr__Field_Config__c(dyfr__Tab__c = dfTab.Id, dyfr__DeveloperName__c = apR.acpl__Account_Planning_Type__c + '_Q1'));
        fconfigList.add(new dyfr__Field_Config__c(dyfr__Tab__c = dfTab.Id, dyfr__DeveloperName__c = apR.acpl__Account_Planning_Type__c + '_Q2', dyfr__Important__c = true));
        insert fconfigList;

        Final List<acpl__AP_Question__c> questionList = new List<acpl__AP_Question__c>();
        questionList.add(new acpl__AP_Question__c(Name = apR.acpl__Account_Planning_Type__c + '_Q1', acpl__gf_account_planning_id__c = apR.Id, acpl__gf_ap_question_form_desc__c = 'question', acpl__AA_answer_text__c = ''));
        questionList.add(new acpl__AP_Question__c(Name = apR.acpl__Account_Planning_Type__c + '_Q2', acpl__gf_account_planning_id__c = apR.Id, acpl__gf_ap_question_form_desc__c = 'question', acpl__AA_answer_text__c = ''));
        insert questionList;

		Test.startTest();
		System.runAs(MAP_USERS.get(EJECUTIVO)) {
			try {
				questionList[0].acpl__AA_answer_text__c = 'new values';
				update questionList;

                AP_QuestionsProgressController.calculateQuestions(apR.Id);
			} catch(Exception e) {
				System.debug(e.getMessage());
			}
		}
		Test.stopTest();

    }
}