src/objects/acpl__Account_Planning__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_ap_status_type_name__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Validation</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>acpl__gf_event_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Event date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>acpl__participant_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plannings</relationshipLabel>
        <relationshipName>Account_Plannings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Planning</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Planning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plannings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/acpl__Commercial_Plan_Event__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_account_planning_id__c</fullName>
        <label>Account Planning</label>
        <referenceTo>acpl__Account_Planning__c</referenceTo>
        <relationshipLabel>Commercial Plan Events</relationshipLabel>
        <relationshipName>Commercial_Plan_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>acpl__gf_comm_plan_event_type_name__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Visit</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
                <value>
                    <fullName>Task</fullName>
                </value>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Pitch</fullName>
                    <isActive>false</isActive>
                    <label>Pitch</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>acpl__gf_event_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Expected Completion Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>acpl__participant_id__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Commercial Plan Events</relationshipLabel>
        <relationshipName>Commercial_Plan_Events</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Commercial Plan Event</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Commercial Plan Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commercial Plan Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AP_CommercialPlanEvent_Handler_tst.cls
/**
 * Test class for AP_CommercialPlanEvent_Handler_cls and subclass
 * <p /><p />
 * Modification log:<p />
 * -------------------------------------------------------------------
 * Developer                    Date                Description<p />
 * -------------------------------------------------------------------
 * Diego Carbajal    		04/06/2020          Original version.<p />
 *
 * @author Diego Carbajal
 */
@isTest
public class AP_CommercialPlanEvent_Handler_tst {
	/**
	 * @Description variable mapUsers
	 */
	static Map<String, User> mapUsers = AP_FactoryTest_tst.getUsers();
	/**
	 * @Description variable ejecutivo
	 */
	static Final String ejecutivo = 'EJECUTIVO';
	/**
	 * @Description variable fail
	 */
	static Final String fail = 'Fail Assertion';
	/**
	 * @Description method setUp
	 */
	@TestSetup
	public static void setUp() {
		AP_FactoryTest_tst.forSetUp();
	}

	/**
	 * @Description Test method beforeInsert
	 */
	public static testmethod void beforeInsert() {
		Final Account acc = [SELECT Id FROM Account LIMIT 1];
		Final acpl__Account_Planning__c apRecord = TestFactory.createAccountPlanning(acc.Id, mapUsers.get(ejecutivo).Id, null, false);
		insert apRecord;
		Test.startTest();
		System.runAs(mapUsers.get(ejecutivo)) {
			try {
				Final acpl__Commercial_Plan_Event__c[] cpeAux = new acpl__Commercial_Plan_Event__c[] {};
				cpeAux.add(new acpl__Commercial_Plan_Event__c(acpl__gf_account_planning_id__c = apRecord.Id, acpl__participant_id__c = acc.Id,
				                                              acpl__gf_event_date__c = System.today() + 31, acpl__gf_comm_plan_event_type_name__c = 'Visit'));
				cpeAux.add(new acpl__Commercial_Plan_Event__c(acpl__gf_account_planning_id__c = apRecord.Id, acpl__participant_id__c = acc.Id,
				                                              acpl__gf_event_date__c = System.today() + 31, acpl__gf_comm_plan_event_type_name__c = 'Opportunity'));
				insert cpeAux;
			} catch(Exception e) {
				System.debug(e.getMessage());
			}
		}
		Test.stopTest();
		Final acpl__Commercial_Plan_Event__c[] lstCPE = [SELECT Id FROM acpl__Commercial_Plan_Event__c WHERE acpl__gf_account_planning_id__c =:apRecord.Id];
		Final Integer size = lstCPE.size();
		System.assertEquals(size, 0, fail);
	}

	/**
	 * @Description Test method beforeUpdate
	 */
	public static testmethod void beforeUpdate() {
		Final Account acc = [SELECT Id FROM Account LIMIT 1];
		Final acpl__Account_Planning__c apRecord = TestFactory.createAccountPlanning(acc.Id, mapUsers.get(ejecutivo).Id, null, false);
		insert apRecord;
		Final acpl__Commercial_Plan_Event__c cpe = new acpl__Commercial_Plan_Event__c(acpl__gf_account_planning_id__c = apRecord.Id, acpl__participant_id__c = acc.Id,
		                                                                              acpl__gf_event_date__c = System.today() + 31, acpl__gf_comm_plan_event_type_name__c = 'Visit');
		insert cpe;
		Final Date eventDate = cpe.acpl__gf_event_date__c;
		Test.startTest();
		System.runAs(mapUsers.get(ejecutivo)) {
			try {
				cpe.acpl__gf_event_date__c = System.today() + 15;
				update cpe;
			} catch(Exception e) {
				System.debug(e.getMessage());
			}
		}
		Test.stopTest();
		Final acpl__Commercial_Plan_Event__c[] lstCPE = [SELECT Id, acpl__gf_event_date__c FROM acpl__Commercial_Plan_Event__c WHERE acpl__gf_account_planning_id__c =:apRecord.Id];
		System.assertEquals(eventDate, lstCPE[0].acpl__gf_event_date__c, fail);
	}

	/**
	 * @Description Test method beforeDelete
	 */
	public static testmethod void beforeDelete() {
		Final Account acc = [SELECT Id FROM Account LIMIT 1];
		Final acpl__Account_Planning__c apRecord = TestFactory.createAccountPlanning(acc.Id, mapUsers.get(ejecutivo).Id, null, false);
		insert apRecord;
		Final acpl__Commercial_Plan_Event__c cpe = new acpl__Commercial_Plan_Event__c(acpl__gf_account_planning_id__c = apRecord.Id, acpl__participant_id__c = acc.Id,
		                                                                              acpl__gf_event_date__c = System.today() + 31, acpl__gf_comm_plan_event_type_name__c = 'Visit');
		insert cpe;
		Test.startTest();
		System.runAs(mapUsers.get(ejecutivo)) {
			try {
				delete cpe;
			} catch(Exception e) {
				System.debug(e.getMessage());
			}
		}
		Test.stopTest();
		Final acpl__Commercial_Plan_Event__c[] lstCPE = [SELECT Id, acpl__gf_event_date__c FROM acpl__Commercial_Plan_Event__c WHERE acpl__gf_account_planning_id__c =:apRecord.Id];
		Final Integer size = lstCPE.size();
		System.assertEquals(size, 1, fail);
	}

	/**
	 * @Description Test method afterInsert
	 */
	public static testmethod void afterInsert() {
		Final Account acc = [SELECT Id FROM Account LIMIT 1];
		Final acpl__Account_Planning__c apRecord = TestFactory.createAccountPlanning(acc.Id, mapUsers.get(ejecutivo).Id, null, true);
		insert apRecord;
		Test.startTest();
		System.runAs(mapUsers.get(ejecutivo)) {
			insert new acpl__Commercial_Plan_Event__c(acpl__gf_account_planning_id__c = apRecord.Id, acpl__participant_id__c = acc.Id,
			                                          acpl__gf_event_date__c = System.today() + 31, acpl__gf_comm_plan_event_type_name__c = 'Visit');
		}
		Test.stopTest();
		Final acpl__Account_Planning__c apAux = [SELECT Id, acpl__gf_ap_status_type_name__c FROM acpl__Account_Planning__c WHERE Id =:apRecord.Id LIMIT 1];
		System.assertEquals('In Progress', apAux.acpl__gf_ap_status_type_name__c, fail);
	}
}