src/objects/acpl__Account_Planning__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_ap_status_type_name__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Validation</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_substatus_type_name__c</fullName>
        <label>Sub-status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>acpl__gf_ap_status_type_name__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>AP team not invited</fullName>
                </value>
                <value>
                    <fullName>AP team invited</fullName>
                </value>
                <value>
                    <fullName>Pending pre-validation</fullName>
                </value>
                <value>
                    <fullName>Pre-validated</fullName>
                </value>
                <value>
                    <fullName>Pending review</fullName>
                </value>
                <value>
                    <fullName>Pending validation</fullName>
                </value>
                <value>
                    <fullName>In place</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Planning</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Planning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plannings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>prof_position_id__c</fullName>
        <description>Id for the user position</description>
        <label>Position code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>User_position_equivalence__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>User position equivalence</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User_Position_equivalence__c.object
<CustomObject>
    <fields>
        <fullName>User_position_equivalence__c</fullName>
        <label>User position equivalence</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Cargo Equivalente</label>
    <nameField>
        <displayFormat>E-{0000000000}</displayFormat>
        <label>User Position equivalence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cargos Equivalentes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BE_AP_Administration_tst.cls
/**
 * Test class BE_AP_Administration_tst
 * <p /><p />
 * Modification log:<p />
 * -------------------------------------------------------------------
 * Developer                    Date                Description<p />
 * -------------------------------------------------------------------
 * Diego Carbajal    		04/06/2020          Original version.<p />
 *
 * @author Diego Carbajal
 */
@isTest
public class BE_AP_Administration_tst {
    /** @Description  FAIL*/
    private static Final String FAIL = 'Fail';
	/*
	 * @Description  method setUp
	 */
	@TestSetup
	public static void setUp() {
		Final String perfil = [SELECT Id FROM Profile WHERE name = 'Ejecutivo'].Id;
		//Creación de usuario
		Final Id gerenteRole = [SELECT Id FROM UserRole WHERE DeveloperName = 'GERENTE_BANCA_EMPRESAS_MIRAFLORES' LIMIT 1].Id;
		Final Map<Schema.SObjectField, Object> mapFields = new Map<Schema.SObjectField, Object> {User.LastName => 'GERENTE', User.ProfileId => perfil,
			                                                                               User.prof_position_id__c => 'E01', User.user_position_equivalence__c => 'User Test', 
            																				User.UserRoleId => gerenteRole};
		Final User gof = TestFactory.getUser(true, mapFields);
		Final User usuario = [SELECT Id FROM User WHERE Id =:UserInfo.getUserId()];
		System.runAs(usuario) {
			Final Account acc = TestFactory.createAccount();
			insert TestFactory.createAccountPlanning(acc.Id, gof.Id, null, true);
		}
	}

	/*
	 * @Description  method getAP
	 */
	public static testmethod void getAP() {
		Final Id apId = getCurrentAP().Id;
		Test.startTest();
		Final acpl__Account_Planning__c[] lstAP = BE_AP_Administration_helper.getAp(apId);
		Test.stopTest();
		Final Integer size = lstAP.size();
		System.assertEquals (size, 1, FAIL);
	}

	/*
	 * @Description  method validateStatusExpired
	 */
	public static testmethod void validateStatusExpired() {
		Map<String, Object> mapExpired = new Map<String, Object>();
		Final acpl__Account_Planning__c apR = getCurrentAP();
		apR.acpl__gf_ap_substatus_type_name__c = 'Expired';
		update apR;
		Test.startTest();
		mapExpired = BE_AP_Administration_helper.validateStatus(apR);
		Test.stopTest();
		System.assertEquals (mapExpired.get('status'), 'expirado.', FAIL);
	}

	/*
	 * @Description  method validateStatusPending
	 */
	public static testmethod void validateStatusPending() {
		Map<String, Object> mapPending = new Map<String, Object>();
		Final acpl__Account_Planning__c apR = getCurrentAP();
		apR.acpl__gf_ap_status_type_name__c = 'Pending Validation';
		update apR;
		Test.startTest();
		mapPending = BE_AP_Administration_helper.validateStatus(apR);
		Test.stopTest();
		System.assertEquals (mapPending.get('status'), 'pendiente de validación.', FAIL);
	}

	/*
	 * @Description  method validateStatusValidation
	 */
	public static testmethod void validateStatusValidation() {
		Map<String, Object> mapValidation = new Map<String, Object>();
		Final acpl__Account_Planning__c apR = getCurrentAP();
		apR.acpl__gf_ap_status_type_name__c = 'Validated';
		update apR;
		Test.startTest();
		mapValidation = BE_AP_Administration_helper.validateStatus(apR);
		Test.stopTest();
		System.assertEquals (mapValidation.get('status'), 'validado.', FAIL);
	}

	/*
	 * @Description  method getCurrentAP
	 */
	public static acpl__Account_Planning__c getCurrentAP() {
		return [SELECT Id, acpl__gf_ap_substatus_type_name__c, acpl__gf_ap_status_type_name__c FROM acpl__Account_Planning__c LIMIT 1];
	}
}