src/objects/acpl__Account_Planning__c.object
<CustomObject>
    <label>Account Planning</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Planning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plannings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/dwp_kitv__Visit__c.object
<CustomObject>
    <description>Main object to manage visits</description>
    <fields>
        <fullName>dwp_kitv__account_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account record related to this visit.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>dwp_kitv__visit_desc__c</fullName>
        <description>Visit Description</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>dwp_kitv__visit_end_date__c</fullName>
        <description>Formula field where the duration was added to start date.</description>
        <formula>dwp_kitv__visit_start_date__c + VALUE(TEXT( dwp_kitv__visit_duration_number__c ))/1440</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>start_date_calculated__c</fullName>
        <formula>dwp_kitv__visit_start_date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Date Calculated</label>
        <type>Date</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/BE_AP_LastVisits_tst.cls
/**
 * Test class for BE_AP_LastVisits_tst
 * <p /><p />
 * Modification log:<p />
 * -------------------------------------------------------------------
 * Developer                    Date                Description<p />
 * -------------------------------------------------------------------
 * Diego Carbajal    		05/06/2020          Original version.<p />
 *
 * @author Diego Carbajal
 */
@isTest
public class BE_AP_LastVisits_tst {
	/*
	 * @Description  method setUp
	 */
	@TestSetup
	static void setUp() {
		AP_FactoryTest_tst.forSetUp();
		Final User admin = [SELECT Id FROM USER Where Id =:UserInfo.getUserId()];
		Final User ejecutivo = [SELECT Id FROM USER Where LastName LIKE 'EJECUTIVO' LIMIT 1];
		System.runAs(admin) {
			Account acc = [SELECT Id FROM Account LIMIT 1];
			final acpl__Account_Planning__c accountPlanning1 = TestFactory.createAccountPlanning(acc.Id, ejecutivo.Id, null, false);
			insert accountPlanning1;
		}
	}

	/*
	 * @Description  method readRecords
	 */
	public static testmethod void readRecords() {
		Final String apId = [SELECT Id FROM acpl__Account_Planning__c WHERE RecordType.DeveloperName != 'Question_Catalog' LIMIT 1].Id;
		Final Map<String, Object> mapParams = new Map<String, Object> {'sObjName' => 'dwp_kitv__Visit__c',
			                                                           'sObjFields' => 'Name,start_date_calculated__c,dwp_kitv__visit_desc__c', 'recordId' => apId,
			                                                           'filterSQOL' => 'dwp_kitv__account_id__c = :recordId AND dwp_kitv__visit_end_date__c < TODAY AND dwp_kitv__visit_end_date__c >= LAST_YEAR ORDER BY dwp_kitv__visit_end_date__c DESC'};
		Test.startTest();
		Final BE_SingleRelatedListCRUD_Cls singleClas = (BE_SingleRelatedListCRUD_Cls)Type.forName('BE_AP_LastVisits_cls').newInstance();
		Final BE_SingleRelatedListCRUD_Cls.Response res = singleClas.readRecords(mapParams);
		Test.stopTest();
		System.assert (res.isSuccess, 'Fail');
	}
}