src/objects/acpl__Account_Planning__c.object
<CustomObject>
    <fields>
        <fullName>acpl__gf_ap_indvi_lock_edit_ind_type__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Unlock Account Planning</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acpl__gf_ap_status_type_name__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Validation</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Planning</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Planning Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plannings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/BE_Stockholder__c.object
<CustomObject>
    <fields>
        <fullName>Account_Planning__c</fullName>
        <label>Account Planning</label>
        <referenceTo>acpl__Account_Planning__c</referenceTo>
        <relationshipLabel>Stockholders</relationshipLabel>
        <relationshipName>Stockholders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DocumentNumber__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Número de documento</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DocumentType__c</fullName>
        <label>Tipo de documento</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DNI</fullName>
                </value>
                <value>
                    <fullName>RUC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Stockholder</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre de accionista</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stockholders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AP_StockHolder_Handler_tst.cls
/**
 * Handler of Trigger of the BE_Stockholder__c object.
 * <p /><p />
 * Modification log:<p />
 * -------------------------------------------------------------------
 * Developer                    Date                Description<p />
 * -------------------------------------------------------------------
 * Diego Carbajal    		06/10/2020          Original version.<p />
 *
 * @author Diego Carbajal
 */
@isTest
public class AP_StockHolder_Handler_tst {

    /*** @Description variable DNI*/
    Final static String DNI = 'DNI';
    /*** @Description variable ACCIONISTA*/
    Final static String ACCIONISTA = 'Accionista';
    /*** @Description variable ACCIONISTA*/
    Final static String DOCUMENT_NUMBER = '1029384756';
    /*** @Description variable mapUsers*/
	static Map<String, User> mapUsers = AP_FactoryTest_tst.obtainUsers();
	/*** @Description variable EJECUTIVO*/
	static Final String EJECUTIVO = 'EJECUTIVO';
	/*** @Description variable FAIL*/
	static Final String FAIL = 'FAIL Assertion';
    /*** @Description variable VISIT*/
	static Final String VISIT = 'Visit';
	/**
	 * @Description method setUp
	 */
	@TestSetup
	public static void setUp() {
		AP_FactoryTest_tst.forSetUp();
	}

	/**
	 * @Description Test method beforeInsert
	 */
	public static testmethod void beforeInsert() {
		Final Account acc = [SELECT Id FROM Account LIMIT 1];
		Final acpl__Account_Planning__c apRecord = AP_FactoryTest_tst.createAccountPlanning(acc.Id, mapUsers.get(EJECUTIVO).Id, null, true);
		insert apRecord;
        Boolean error = false;
		Test.startTest();
		System.runAs(mapUsers.get(EJECUTIVO)) {
			try {
				apRecord.ACPL__GF_AP_INDVI_LOCK_EDIT_IND_TYPE__C = false;
                update apRecord;
				insert new BE_Stockholder__c(account_planning__c = apRecord.Id, Name = ACCIONISTA, DocumentNumber__c = DOCUMENT_NUMBER, DocumentType__c = DNI);
			} catch(Exception e) {
                error = true;
				System.debug(e.getMessage());
			}
		}
		Test.stopTest();
		System.assert(error, FAIL);
	}

	/**
	 * @Description Test method beforeUpdate
	 */
	public static testmethod void beforeUpdate() {
		Final Account acc = [SELECT Id FROM Account LIMIT 1];
		Final acpl__Account_Planning__c apRecord = AP_FactoryTest_tst.createAccountPlanning(acc.Id, mapUsers.get(EJECUTIVO).Id, null, true);
		insert apRecord;
		Final BE_Stockholder__c stockholder = new BE_Stockholder__c(account_planning__c = apRecord.Id, Name = ACCIONISTA, DocumentNumber__c = DOCUMENT_NUMBER, DocumentType__c = DNI);
		insert stockholder;
        Boolean error = false;
		Test.startTest();
		System.runAs(mapUsers.get(EJECUTIVO)) {
			try {
				apRecord.ACPL__GF_AP_INDVI_LOCK_EDIT_IND_TYPE__C = false;
                update apRecord;
				stockholder.Name = 'ACCIONISTA Aux';
				update stockholder;
			} catch(Exception e) {
                error = true;
				System.debug(e.getMessage());
			}
		}
		Test.stopTest();
		System.assert(error, FAIL);
	}

	/**
	 * @Description Test method beforeDelete
	 */
	public static testmethod void beforeDelete() {
		Final Account acc = [SELECT Id FROM Account LIMIT 1];
		Final acpl__Account_Planning__c apRecord = AP_FactoryTest_tst.createAccountPlanning(acc.Id, mapUsers.get(EJECUTIVO).Id, null, true);
		insert apRecord;
		Final BE_Stockholder__c stockholder = new BE_Stockholder__c(account_planning__c = apRecord.Id, Name = ACCIONISTA, DocumentNumber__c = DOCUMENT_NUMBER, DocumentType__c = DNI);
		insert stockholder;
        Boolean error = false;
		Test.startTest();
		System.runAs(mapUsers.get(EJECUTIVO)) {
			try {
				apRecord.ACPL__GF_AP_INDVI_LOCK_EDIT_IND_TYPE__C = false;
                update apRecord;
				delete stockholder;
			} catch(Exception e) {
                error = true;
				System.debug(e.getMessage());
			}
		}
		Test.stopTest();
		System.assert(error, FAIL);
	}

	/**
	 * @Description Test method afterInsert
	 */
	public static testmethod void afterInsert() {
		Final Account acc = [SELECT Id FROM Account LIMIT 1];
		Final acpl__Account_Planning__c apRecord = AP_FactoryTest_tst.createAccountPlanning(acc.Id, mapUsers.get(EJECUTIVO).Id, null, true);
		insert apRecord;
		Test.startTest();
		System.runAs(mapUsers.get(EJECUTIVO)) {
			insert new BE_Stockholder__c(account_planning__c = apRecord.Id, Name = ACCIONISTA, DocumentNumber__c = DOCUMENT_NUMBER, DocumentType__c = DNI);
		}
		Test.stopTest();
		Final acpl__Account_Planning__c apAux = [SELECT Id, acpl__gf_ap_status_type_name__c FROM acpl__Account_Planning__c WHERE Id =:apRecord.Id LIMIT 1];
		System.assertEquals('In Progress', apAux.acpl__gf_ap_status_type_name__c, FAIL);
	}
}