src/objects/altm__Commercial_Alert__c.object
<CustomObject>
    <fields>
        <fullName>altm__User_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Banker/Product Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Commercial_Alerts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>altm__commercial_alert_end_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>altm__commercial_alert_record_type__c</fullName>
        <label>Type (not visible)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <label>Current</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>Management</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>Conjunutural</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>altm__commercial_alert_start_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>commercial_alert_category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>altm__commercial_alert_record_type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>3x3</fullName>
                </value>
                <value>
                    <fullName>Anticipa</fullName>
                </value>
                <value>
                    <fullName>CashOut</fullName>
                    <label>Cash Out</label>
                </value>
                <value>
                    <fullName>CashIn</fullName>
                    <label>Cash in</label>
                </value>
                <value>
                    <fullName>Coyuntura</fullName>
                </value>
                <value>
                    <fullName>Descuentos</fullName>
                </value>
                <value>
                    <fullName>Digitalizate</fullName>
                </value>
                <value>
                    <fullName>MedianoPlazo</fullName>
                    <label>Mediano Plazo</label>
                </value>
                <value>
                    <fullName>NuevasLineas</fullName>
                    <label>Nuevas Líneas</label>
                </value>
                <value>
                    <fullName>PagoaProveedores</fullName>
                    <label>Pago a Proveedores</label>
                </value>
                <value>
                    <fullName>PagodeHaberes</fullName>
                    <label>Pago de Haberes</label>
                </value>
                <value>
                    <fullName>PrecioSubestandar</fullName>
                    <label>Precio Subestandar</label>
                </value>
                <value>
                    <fullName>Recursos</fullName>
                </value>
                <value>
                    <fullName>Redes</fullName>
                </value>
                <value>
                    <fullName>UsodeLineas</fullName>
                    <label>Uso de Líneas</label>
                </value>
                <value>
                    <fullName>Vinculación3/7</fullName>
                    <label>Vinculación 3/7</label>
                </value>
                <value>
                    <fullName>Vinculación4/7</fullName>
                    <label>Vinculación 4/7</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Commercial Alert</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Alert Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commercial Alerts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/BE_CA_NewCampaign_Ctr.cls
/**
   ----------------------------------------------------------------------------------------------------
   @Name <BE_CA_NewCampaign_Ctr>
   @Author Lolo Michel Bravo Ruiz (lolo.bravo@bbva.com)
   @Date 2020-02-24
   @Description Class  for Create Contact of Non Client
   @Changes
    Date        Author   Email                  Type
    2020-02-24  LMBR     lolo.bravo@bbva.com    Creation
   ----------------------------------------------------------------------------------------------------
 */
public with sharing class BE_CA_NewCampaign_Ctr extends BE_CustomQuickActionCRUD_Cls {

    /**
    @Description createRecords
    @param  List<SObject> sObjs
    @return BE_SingleRelatedListCRUD_Cls.Response response
    */
    public override BE_CustomQuickActionCRUD_Cls.Response createRecord(sObject sObj,Map<String,Object> params) {
        final BE_CustomQuickActionCRUD_Cls.Response res = new BE_CustomQuickActionCRUD_Cls.Response();
        try {
            System.debug('sObj');
            System.debug(sObj);
            System.debug('params');
            System.debug(params);
            //CREAR UNA CAMPAÑA GERENCIA PARA CADA EJECUTIVO QUE ESTE POR DEBAJO EN LOS ROLES
            //GERENTE DE OFICINA, GERENTE REGIONAL
            //AGREGAR UNA COMMERCIAL ALERT
            //LLAVE EL CODIGO DEL EJECUTIVO (P028037)
            //
            //UserInfo.getUserId();
            //
            Id currentUserId = UserInfo.getUserId();
        	Id currentRoleId = UserInfo.getUserRoleId();
            
            currentRoleId = '00E1I000000tPMcUAM';
            
            Set<Id> allSubUsers = getRoleSubordinateUsers(currentRoleId);
            List<Campaign> campaignList = new List<Campaign>();
            List<altm__Commercial_Alert__c> alertList = new List<altm__Commercial_Alert__c>();
            
            
            System.debug('result from allSubUsers:');
            System.debug(allSubUsers);

            for(Id userId : allSubUsers) {
                Campaign campaign = new Campaign();
                campaign.Name = String.valueOf(sObj.get(altm__Commercial_Alert__c.Name));
                campaign.StartDate = Date.valueOf(sObj.get(altm__Commercial_Alert__c.altm__commercial_alert_start_date__c));
                campaign.EndDate = Date.valueOf(sObj.get(altm__Commercial_Alert__c.altm__commercial_alert_end_date__c));
                campaign.OwnerId = userId;
                campaignList.add(campaign);
            }
            
            if( campaignList.size() != 0)
            {
                insert campaignList;
                System.debug('---campaign inserted----');
                System.debug(campaignList.size());
                
                for(Campaign campaign : campaignList)
                {
                    altm__Commercial_Alert__c alert = new altm__Commercial_Alert__c();
                    alert.Name = String.valueOf(sObj.get(altm__Commercial_Alert__c.Name));
                    alert.altm__commercial_alert_start_date__c = campaign.StartDate;
                    alert.altm__commercial_alert_end_date__c = campaign.EndDate;
                    alert.commercial_alert_category__c = String.valueOf(sObj.get(altm__Commercial_Alert__c.commercial_alert_category__c));
                    alert.altm__commercial_alert_record_type__c = String.valueOf(sObj.get(altm__Commercial_Alert__c.altm__commercial_alert_record_type__c));
                    alert.altm__User_id__c = campaign.OwnerId;
                    alertList.add(alert);
                }
                
                insert alertList;
                System.debug('---alert inserted----');
                System.debug(alertList);
            }
            
            System.debug('campaignList');
            System.debug(campaignList);
            
            res.isSuccess=true;
            res.data=sObj;
        } catch (DmlException e) {
            res.isSuccess=false;
            res.message=e.getMessage();
        }
        return res;
    }
    	
    private static Set<ID> getRoleSubordinateUsers(Id roleId) {
        Set<Id> allSubRoleIds = getAllSubRoleIds(new Set<ID>{roleId});
        Map<Id,User> users = new Map<Id, User>([Select Id, Name From User where IsActive = True AND UserRoleId IN :allSubRoleIds]);
        return users.keySet();
    }
    
    private static Set<ID> getAllSubRoleIds(Set<ID> roleIds) {
        Set<ID> currentRoleIds = new Set<ID>();
        string EXCECUTIVE_ROLE_NAME = 'EJECUTIVO BANCA EMPRESAS%';        
        for(UserRole userRole :[select Id from UserRole where ParentRoleId IN :roleIds AND ParentRoleID != null AND Name like :EXCECUTIVE_ROLE_NAME]) {
            currentRoleIds.add(userRole.Id);
        }
        if(currentRoleIds.size() > 0){
            currentRoleIds.addAll(getAllSubRoleIds(currentRoleIds));
        }
        return currentRoleIds;
    }
    
}