src/objects/altm__Commercial_Alert__c.object
<CustomObject>
    <label>Commercial Alert</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Alert Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commercial Alerts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ctcp__Custom_Team__c.object
<CustomObject>
    <fields>
        <fullName>Commercial_Alert__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commercial Alert</label>
        <referenceTo>altm__Commercial_Alert__c</referenceTo>
        <relationshipLabel>Equipo</relationshipLabel>
        <relationshipName>Custom_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ctcp__gf_team_users_desc__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Custom_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Custom Team</label>
    <nameField>
        <displayFormat>CTM-{0000}</displayFormat>
        <label>Custom Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BE_CA_CustomTeam_Tst.cls
/**
   ----------------------------------------------------------------------------------------------------
   @Name <BE_CA_CustomTeam_Tst>
   @Author Lolo Michel Bravo Ruiz (lolo.bravo@bbva.com)
   @Date 2021-03-10
   @Description Class test BE_CA_CustomTeam_Cls
   @Changes
    Date        Author   Email                  			Type		Description
    2021-03-10  LMBR     lolo.bravo@bbva.com    			Creation
   ----------------------------------------------------------------------------------------------------
 */
@isTest
public class BE_CA_CustomTeam_Tst {
    /** Test Method readRecordsTest */
    @Istest
    public static void readRecordsTest() {
        final Account acc = TestFactory.createAccount();
        final Map<String,Object> param = new Map<String,Object>{'recordId'=>acc.Id,'sObjFields'=>'Id,Name','sObjName'=>'Account','filterSQOL'=>'Id=:recordID'};
    	final BE_CA_CustomTeam_Cls cTeam= new BE_CA_CustomTeam_Cls();
        final BE_SingleRelatedListCRUD_Cls.Response res=cTeam.readRecords(param);
        System.assert(res.isSuccess,'Success Read');
      }
   	 /** Test Method createRecords */
     @Istest
     public static void createRecords() {
        final User cUser= TestFactory.createUser('testuseralertTeam', 'Ejecutivo');
        final User cUser2= TestFactory.createUser('testuseralertTeam2', 'Ejecutivo');
        final altm__Commercial_Alert__c commAlert= new altm__Commercial_Alert__c(Name='Test_CommAlert',OwnerId=cUser.Id);
        final ctcp__Custom_Team__c cTeam = new ctcp__Custom_Team__c(Commercial_Alert__c=commAlert.id,ctcp__gf_team_users_desc__c=cUser2.id);
    	final BE_CA_CustomTeam_Cls cClass= new BE_CA_CustomTeam_Cls();
        final BE_SingleRelatedListCRUD_Cls.Response res=cClass.createRecords(new List<ctcp__Custom_Team__c>{cTeam});
        System.assert(!res.isSuccess,'Success Create');
      }
}