src/objects/altm__Commercial_Alert__c.object
<CustomObject>
    <fields>
        <fullName>altm__participant_id__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Client Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Alerts (Client Name)</relationshipLabel>
        <relationshipName>Commercial_Alerts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Commercial Alert</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Alert Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commercial Alerts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/dwp_kitv__Visit__c.object
<CustomObject>
    <description>Main object to manage visits</description>
    <fields>
        <fullName>dwp_kitv__visit_duration_number__c</fullName>
        <description>Time in minutes it takes to make the visit. The first hour will be intervals about 15 minutes, then 30 minutes intervals.</description>
        <inlineHelpText>Seleccione la duración en minutos</inlineHelpText>
        <label>Duration</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>120</fullName>
                </value>
                <value>
                    <fullName>150</fullName>
                </value>
                <value>
                    <fullName>180</fullName>
                </value>
                <value>
                    <fullName>210</fullName>
                </value>
                <value>
                    <fullName>240</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>dwp_kitv__visit_start_date__c</fullName>
        <description>Field to set the start date time of the visit.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/BE_CA_NewVisit_Tst.cls
/**
   -------------------------------------------------------------------------------------------------
   @Name <BE_CA_NewVisit_Tst>
   @Author Deyby Bazan Villegas (deyby.bazan.contractor@bbva.com)
   @Date 2021-02-23
   @Description test for BE_CA_NewVisit_Ctr class
   @Changes
   Date        Author   Email                              Type
   2021-02-23  DBAV     deyby.bazan.contractor@bbva.com    Creation
   -------------------------------------------------------------------------------------------------
 */
@isTest
public with sharing class BE_CA_NewVisit_Tst {
    
 /**
 @Description test BE_CA_NewVisit_Ctr.createRecord(), correct scenary
 */   
 @IsTest
    static void createSuccessMethodsTest() {
        Final Account acc = new Account(Name='TEST Account');
        insert acc;
        Final altm__Commercial_Alert__c commAlert = new altm__Commercial_Alert__c(Name='TEST CommAlert',altm__participant_id__c=acc.Id);
        insert commAlert;        
        Final dwp_kitv__Visit__c visit = new dwp_kitv__Visit__c(Name='Test Visit',dwp_kitv__visit_duration_number__c='45',dwp_kitv__visit_start_date__c=System.now());
        Final Map<String,Object> paramsMap = new Map<String,Object>{'ClassName'=> '','recordId' => commAlert.Id};
        final BE_CA_NewVisit_Ctr newVisitClass = New BE_CA_NewVisit_Ctr();
        final BE_CustomQuickActionCRUD_Cls.Response res = newVisitClass.createRecord(visit,paramsMap);
        System.assert(res.isSuccess,'Correct Response');    

    }
    
 /**
 @Description test BE_CA_NewVisit_Ctr.createRecord(), incorrect scenary (catch)
 */   
    @IsTest
    static void createErrorMethodsTest() {
        Final altm__Commercial_Alert__c commAlert = new altm__Commercial_Alert__c(Name='TEST CommAlert');     
        Final dwp_kitv__Visit__c visit = new dwp_kitv__Visit__c(Name='Test Visit');
        Final Map<String,Object> paramsMap = new Map<String,Object>{'ClassName'=> '','recordId' => commAlert.Id};
        Final BE_CA_NewVisit_Ctr newVisitClass = New BE_CA_NewVisit_Ctr();
        Final BE_CustomQuickActionCRUD_Cls.Response res = newVisitClass.createRecord(visit,paramsMap);
        System.assert(res.isSuccess, 'Invalid Creation');
    }
}