src/objects/altm__Commercial_Alert__c.object
<CustomObject>
    <fields>
        <fullName>altm__alert_stage_type__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>In management</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>Won</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <label>Discarded</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>altm__commercial_alert_end_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>altm__participant_id__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Client Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Alerts (Client Name)</relationshipLabel>
        <relationshipName>Commercial_Alerts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Commercial Alert</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Alert Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commercial Alerts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/BE_SingleRelatedList_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>FieldsQuery__c</fullName>
        <label>FieldsQuery</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Filter__c</fullName>
        <inlineHelpText>Example: AccountId=:recordId AND Stage IN (@@Close@@),
replace simple  quotes for @@</inlineHelpText>
        <label>Filter</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sObjectApiName__c</fullName>
        <label>sObject</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Single Related List Setting</label>
    <pluralLabel>Single Related List Settings</pluralLabel>
</CustomObject>

src/objects/slmt__Sales_Meeting__c.object
<CustomObject>
    <description>Storing all the planned meetings for each responsible, in addition to the planned date and time, the collaborator and the type.</description>
    <fields>
        <fullName>Collaborator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collaborator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Meetings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>slmt__management_plan_meeting_date__c</fullName>
        <description>The day the meeting is scheduled.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The day the meeting is scheduled.</inlineHelpText>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Sales Meeting</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Meetings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BE_SM_WonAlerts_tst.cls
/**
   -------------------------------------------------------------------------------------------------
   @Name BE_SM_WonAlerts_tst
   @Author Gerson R. Diaz Alvarado (gerson.diaz@bbva.com)
   @Date 2021-05-20
   @Description
   @Changes
   Date        Author   Email                  Type
   2021-05-20  GRDA     gerson.diaz@bbva.com    Creation
   -------------------------------------------------------------------------------------------------
 */
@isTest
public class BE_SM_WonAlerts_tst {

    /*
	 * @Description  method setUp
	 */
    @TestSetup
    static void setUp() {
        BE_SM_Factory_tst.createSalesMeeting(DateTime.newInstance(System.today().addMonths(1).year(), System.today().addMonths(1).month(), 2, 3, 3, 3), UserInfo.getUserId(), 'Planning', true);

        Final Account acc = new Account(Name='Test Account');
        insert acc;
        Final altm__Commercial_Alert__c commAlert = new altm__Commercial_Alert__c(Name='TEST CommAlert',altm__participant_id__c=acc.Id, altm__alert_stage_type__c = '03', OwnerId = UserInfo.getUserId(), altm__commercial_alert_end_date__c = system.today());
        insert commAlert;
    }
    
     /*
	 * @Description method getSMWonAlerts
	 */
    @isTest
    static void getSMWonAlerts() {
        Final slmt__Sales_Meeting__c salesMeeting = [SELECT Id, slmt__management_plan_meeting_date__c, Collaborator__c FROM slmt__Sales_Meeting__c LIMIT 1];
        Final BE_SingleRelatedList_Setting__mdt srl = [SELECT Id, FieldsQuery__c, Filter__c, sObjectApiName__c FROM BE_SingleRelatedList_Setting__mdt WHERE DeveloperName = 'BE_SM_WonAlerts'];
        Test.startTest();
        Final BE_SingleRelatedListCRUD_Cls.Response response = new BE_SM_WonAlerts_cls().readRecords(new Map<String, Object>{'recordId' => salesMeeting.Id, 'sObjName' => srl.sObjectApiName__c, 
            'sObjFields' => srl.FieldsQuery__c, 'filterSQOL' =>srl.Filter__c});
        Test.stopTest();
        System.assertEquals(response.data.size()>0, true, 'Won Alertas!!!');
    }
    
}