src/objects/altm__Commercial_Alert__c.object
<CustomObject>
    <fields>
        <fullName>altm__alert_stage_type__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>In management</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>Won</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <label>Discarded</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Commercial Alert</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Alert Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commercial Alerts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Commercial_Alert_Visit_Relation__c.object
<CustomObject>
    <description>Object to related multiple commercial Altert with multilple visits</description>
    <fields>
        <fullName>commercial_id__c</fullName>
        <label>Commercial Alert</label>
        <referenceTo>altm__Commercial_Alert__c</referenceTo>
        <relationshipLabel>Relación de visitas</relationshipLabel>
        <relationshipName>Commercial_Alert_Task_Relationship</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>visit_id__c</fullName>
        <label>Visit</label>
        <referenceTo>dwp_kitv__Visit__c</referenceTo>
        <relationshipLabel>Commercial Alert Task Relationship</relationshipLabel>
        <relationshipName>Commercial_Alert_Task_Relationship</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Relación de visita</label>
    <nameField>
        <displayFormat>CAT{YYYY}{MM}-{0}{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relación de visitas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BE_CA_NewVisit_Ctr.cls
/**
   ----------------------------------------------------------------------------------------------------
   @Name <BE_General_Utils>
   @Author Lolo Michel Bravo Ruiz (lolo.bravo@bbva.com)
   @Date 2019-09-13
   @Description Class  contains generic logic to use in differents classes.
   @Changes
    Date        Author   Email                  Type
    2020-02-21  LMBR     lolo.bravo@bbva.com    Creation
   ----------------------------------------------------------------------------------------------------
 */
public without sharing class BE_CA_NewVisit_Ctr extends BE_CustomQuickActionCRUD_Cls {
	/** Stage CommAlert */
    Private Final List<String> STAGE_ALERT= new List<String>{'Pending','InManagement'};
    /**
    @Description createRecords
    @param  List<SObject> sObjs
    @return BE_SingleRelatedListCRUD_Cls.Response response
    */
    public override BE_CustomQuickActionCRUD_Cls.Response createRecord(sObject sObj,Map<String,Object> params) {
        final BE_CustomQuickActionCRUD_Cls.Response res = new BE_CustomQuickActionCRUD_Cls.Response();
        try {
            insert sObj;
            insert new Commercial_Alert_Visit_Relation__c(visit_id__c=sObj.Id,commercial_id__c=(String)params.get('recordId'));
            final altm__Commercial_Alert__c commAlert = [SELECT ID,altm__alert_stage_type__c FROM altm__Commercial_Alert__c WHERE Id=:(String)params.get('recordId')];
            if(commAlert.altm__alert_stage_type__c==STAGE_ALERT[0]) {
                commAlert.altm__alert_stage_type__c=STAGE_ALERT[1];
                update commAlert;
            }
            res.isSuccess=true;
            res.data=sObj;
        } catch (DmlException e) {
            res.isSuccess=false;
            res.message=e.getMessage();
        }
        return res;
    } 

}