src/objects/altm__Commercial_Alert__c.object
<CustomObject>
    <fields>
        <fullName>altm__participant_id__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Client Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Alerts (Client Name)</relationshipLabel>
        <relationshipName>Commercial_Alerts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Commercial Alert</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Alert Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commercial Alerts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Commercial_Alert_Visit_Relation__c.object
<CustomObject>
    <description>Object to related multiple commercial Altert with multilple visits</description>
    <fields>
        <fullName>commercial_id__c</fullName>
        <label>Commercial Alert</label>
        <referenceTo>altm__Commercial_Alert__c</referenceTo>
        <relationshipLabel>Relación de visitas</relationshipLabel>
        <relationshipName>Commercial_Alert_Task_Relationship</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>visit_id__c</fullName>
        <label>Visit</label>
        <referenceTo>dwp_kitv__Visit__c</referenceTo>
        <relationshipLabel>Commercial Alert Task Relationship</relationshipLabel>
        <relationshipName>Commercial_Alert_Task_Relationship</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Relación de visita</label>
    <nameField>
        <displayFormat>CAT{YYYY}{MM}-{0}{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relación de visitas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/dwp_kitv__Visit__c.object
<CustomObject>
    <description>Main object to manage visits</description>
    <fields>
        <fullName>dwp_kitv__visit_duration_number__c</fullName>
        <description>Time in minutes it takes to make the visit. The first hour will be intervals about 15 minutes, then 30 minutes intervals.</description>
        <inlineHelpText>Seleccione la duración en minutos</inlineHelpText>
        <label>Duration</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>120</fullName>
                </value>
                <value>
                    <fullName>150</fullName>
                </value>
                <value>
                    <fullName>180</fullName>
                </value>
                <value>
                    <fullName>210</fullName>
                </value>
                <value>
                    <fullName>240</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>dwp_kitv__visit_start_date__c</fullName>
        <description>Field to set the start date time of the visit.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/BE_CA_Visit_Relation_Trigger_tst.cls
/**
 * Test class for AccountContact_Handler class.
 * <p /><p />
 * Modification log:<p />
 * -------------------------------------------------------------------------
 * Developer                    Date                Description<p />
 * -------------------------------------------------------------------------
 * Eduardo Vargas	            03/26/2020          Original version.<p />
 *
 * @author Eduardo Vargas
 */
@isTest(SeeAllData = false)
public class BE_CA_Visit_Relation_Trigger_tst {
    /** Test Method*/
    @isTest
    static void testCAVisitRelationTrg() {
        Boolean expectedExceptionThrown = true;
        Test.startTest();
        Account acc = New Account(
        	Name = 'Test Account'
        );
        insert acc;
        Final altm__Commercial_Alert__c alert = new altm__Commercial_Alert__c(
        	Name='Test Alert',
            altm__participant_id__c = acc.id
        );
        
        Final dwp_kitv__Visit__c visit = new dwp_kitv__Visit__c(
        	Name='Test Visit',
            dwp_kitv__visit_start_date__c = Datetime.newInstance(2020, 5, 28, 1, 6, 8),
            dwp_kitv__visit_duration_number__c = '15'
        );
        
        insert alert;
        insert visit;
        
        Final Commercial_Alert_Visit_Relation__c relation = new Commercial_Alert_Visit_Relation__c(
            visit_id__c = visit.Id,
            commercial_id__c = alert.Id
        );
        
        Database.SaveResult result = Database.insert(relation);
        
        Final Commercial_Alert_Visit_Relation__c duplicatedRelation = new Commercial_Alert_Visit_Relation__c(
            visit_id__c = visit.Id,
            commercial_id__c = alert.Id
        );
        
        try{
            Database.SaveResult resultDuplicated = Database.insert(duplicatedRelation, false);
        }
        catch(Exception ex) {
            expectedExceptionThrown =  ex.getMessage().contains('El registro ya existe') ? true : false;
        }
        Test.stopTest();            
        System.assert(result.isSuccess());
        System.assertEquals(expectedExceptionThrown, true);

    }

}