src/objects/BE_FamilyGroupingForecast__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Family Grouping Forecast</label>
</CustomObject>

src/objects/dwp_frct__grouping__c.object
<CustomObject>
    <description>Object to related plans with opportunity object.</description>
    <fields>
        <fullName>dwp_frct__management_expected_drop_amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Sum of expected executive falls per family and per management plan</description>
        <label>Expected Drop Management Plan</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>dwp_frct__management_plan_id__c</fullName>
        <description>Management plan object</description>
        <label>Management Plan</label>
        <referenceTo>dwp_frct__management_plan__c</referenceTo>
        <relationshipLabel>Groupings</relationshipLabel>
        <relationshipName>Groupings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>dwp_frct__opportunity_amortization_amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Amortization amount of opportunity products.</description>
        <label>Amortizations</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>dwp_frct__opportunity_antcp_expiry_amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Amount modifiable by the manager in case it detects expiration.</description>
        <label>Anticipated maturities</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>dwp_frct__opportunity_cancellation_amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Amount of cancellation per product family of opportunity.</description>
        <label>Cancellations</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>dwp_frct__opportunity_closed_amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Sum of amount opportunities formalized within the period.</description>
        <label>Closed amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>dwp_frct__opportunity_selected_tot_amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total amount of opportunities selected by family</description>
        <label>Selected Opportunities Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>dwp_frct__original_commitment_amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Amount to which the manager commits.</description>
        <label>Commitment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>dwp_frct__solution_category_type__c</fullName>
        <description>Family category opportunity.</description>
        <label>Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Grouping</label>
    <nameField>
        <label>Grouping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groupings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/dwp_frct__management_plan__c.object
<CustomObject>
    <description>Object to manage plans</description>
    <fields>
        <fullName>dwp_frct__management_plan_end_date__c</fullName>
        <description>End Date plan</description>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dwp_frct__management_plan_start_date__c</fullName>
        <description>Start Date plan</description>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <label>Management Plan</label>
    <nameField>
        <label>Management Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BE_ForecastPlanGroupingManager_Queue.cls
/**
   -------------------------------------------------------------------------------------------------
   @Name <BE_ForecastPlanGroupingManager_Queue>
   @Author Lolo Michel Bravo Ruiz (lolo.bravo@bbva.com)
   @Date 2019-11-22
   @Description Queueable Class for create grouping plans to manager.
   @Changes
   Date        Author   Email                  Type
   2019-11-22  LMBR     lolo.bravo@bbva.com    Created
   -------------------------------------------------------------------------------------------------
 */
public with sharing class BE_ForecastPlanGroupingManager_Queue implements Queueable {
/**Profile Owner of Plan */
final String PROF_NAME='Ejecutivo';
/** Over size update */
final Integer SIZE_UPDATE=0;
/**
    @Description create grouping pla for manager.
    @param QueueableContext.
    @return void
 */
public void execute(QueueableContext context) {
	final DateTime dtToday=Datetime.now();
	final List<dwp_frct__grouping__c>groupDataLst=[SELECT Id,dwp_frct__management_plan_id__c,dwp_frct__management_plan_id__r.OwnerId FROM dwp_frct__grouping__c WHERE dwp_frct__management_plan_id__r.dwp_frct__management_plan_start_date__c <=: dtToday AND dwp_frct__management_plan_id__r.dwp_frct__management_plan_end_date__c >=: dtToday];
	final List<dwp_frct__grouping__c>groupList=new List<dwp_frct__grouping__c>();
	if(groupDataLst.size()>SIZE_UPDATE) {
		final Set<Id>planGroupSet= new Set<Id>();
		for(dwp_frct__grouping__c groupItem:groupDataLst) {
			planGroupSet.add(groupItem.dwp_frct__management_plan_id__c);
		}
		final AggregateResult[] groupedResults = [SELECT count(Id) userSize FROM User WHERE Profile.Name=:PROF_NAME];
		if((Integer)groupedResults[0].get('userSize')>planGroupSet.size()) {
			final Map<String,BE_FamilyGroupingForecast__c>familyProductMap=BE_FamilyGroupingForecast__c.getAll();
			for(dwp_frct__management_plan__c plan :[SELECT Id,OwnerId FROM dwp_frct__management_plan__c WHERE Id NOT IN:planGroupSet AND dwp_frct__management_plan_end_date__c >=: dtToday AND dwp_frct__management_plan_start_date__c <=: dtToday AND Owner.Profile.Name=:PROF_NAME]) {
				for(String typeFamily: familyProductMap.keySet()) {
					groupList.add(new dwp_frct__grouping__c(
							      Name=typeFamily,
							      dwp_frct__management_plan_id__c=plan.Id,
							      dwp_frct__solution_category_type__c=typeFamily,
							      dwp_frct__management_expected_drop_amount__c=0,
							      dwp_frct__opportunity_amortization_amount__c=0,
							      dwp_frct__opportunity_antcp_expiry_amount__c=0,
							      dwp_frct__opportunity_cancellation_amount__c=0,
							      dwp_frct__opportunity_closed_amount__c=0,
							      dwp_frct__opportunity_selected_tot_amount__c=0,
							      dwp_frct__original_commitment_amount__c=0
							      ));
				}
			}
		}
	}
	if(groupList.size()>SIZE_UPDATE) {
		insert groupList;
	}
}
}