src/objects/BE_SingleRelatedList_QuickAction__mdt.object
<CustomObject>
    <label>BE_SingleRelatedList_QuickAction</label>
    <pluralLabel>BE_SingleRelatedList_QuickActions</pluralLabel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>decision_making_desc__c</fullName>
        <label>Decisor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Si</fullName>
                    <label>Sí</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>phone_1__c</fullName>
        <label>Phone 1</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>phone_1_area_code__c</fullName>
        <label>Phone 1 Area Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>41</fullName>
                    <label>Amazonas - 41</label>
                </value>
                <value>
                    <fullName>43</fullName>
                    <label>Ancash - 43</label>
                </value>
                <value>
                    <fullName>83</fullName>
                    <label>Apurimac - 83</label>
                </value>
                <value>
                    <fullName>54</fullName>
                    <label>Arequipa - 54</label>
                </value>
                <value>
                    <fullName>66</fullName>
                    <label>Ayacucho - 66</label>
                </value>
                <value>
                    <fullName>76</fullName>
                    <label>Cajamarca - 76</label>
                </value>
                <value>
                    <fullName>84</fullName>
                    <label>Cusco - 84</label>
                </value>
                <value>
                    <fullName>67</fullName>
                    <label>Huancavelica - 67</label>
                </value>
                <value>
                    <fullName>62</fullName>
                    <label>Huanuco - 62</label>
                </value>
                <value>
                    <fullName>56</fullName>
                    <label>Ica - 56</label>
                </value>
                <value>
                    <fullName>64</fullName>
                    <label>Junin - 64</label>
                </value>
                <value>
                    <fullName>44</fullName>
                    <label>La Libertad - 44</label>
                </value>
                <value>
                    <fullName>74</fullName>
                    <label>Lambayeque - 74</label>
                </value>
                <value>
                    <fullName>01</fullName>
                    <label>Lima y Callo - 01</label>
                </value>
                <value>
                    <fullName>65</fullName>
                    <label>Loreto - 65</label>
                </value>
                <value>
                    <fullName>82</fullName>
                    <label>Madre de Dios - 82</label>
                </value>
                <value>
                    <fullName>53</fullName>
                    <label>Moquegua - 53</label>
                </value>
                <value>
                    <fullName>63</fullName>
                    <label>Pasco - 63</label>
                </value>
                <value>
                    <fullName>73</fullName>
                    <label>Piura - 73</label>
                </value>
                <value>
                    <fullName>51</fullName>
                    <label>Puno - 51</label>
                </value>
                <value>
                    <fullName>42</fullName>
                    <label>San Martin - 42</label>
                </value>
                <value>
                    <fullName>52</fullName>
                    <label>Tacna - 52</label>
                </value>
                <value>
                    <fullName>72</fullName>
                    <label>Tumbes - 72</label>
                </value>
                <value>
                    <fullName>61</fullName>
                    <label>Ucayali - 61</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>phone_2__c</fullName>
        <label>Phone 2</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>phone_2_area_code__c</fullName>
        <label>Phone 2 Area Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>41</fullName>
                    <label>Amazonas - 41</label>
                </value>
                <value>
                    <fullName>43</fullName>
                    <label>Ancash - 43</label>
                </value>
                <value>
                    <fullName>83</fullName>
                    <label>Apurimac- 83</label>
                </value>
                <value>
                    <fullName>54</fullName>
                    <label>Arequipa- 54</label>
                </value>
                <value>
                    <fullName>66</fullName>
                    <label>Ayacucho - 66</label>
                </value>
                <value>
                    <fullName>76</fullName>
                    <label>Cajamarca - 76</label>
                </value>
                <value>
                    <fullName>84</fullName>
                    <label>Cusco - 84</label>
                </value>
                <value>
                    <fullName>67</fullName>
                    <label>Huancavelica - 67</label>
                </value>
                <value>
                    <fullName>62</fullName>
                    <label>Huanuco - 62</label>
                </value>
                <value>
                    <fullName>56</fullName>
                    <label>Ica - 56</label>
                </value>
                <value>
                    <fullName>64</fullName>
                    <label>Junin - 64</label>
                </value>
                <value>
                    <fullName>44</fullName>
                    <label>La Libertad - 44</label>
                </value>
                <value>
                    <fullName>74</fullName>
                    <label>Lambayeque - 74</label>
                </value>
                <value>
                    <fullName>01</fullName>
                    <label>Lima y Callao - 01</label>
                </value>
                <value>
                    <fullName>65</fullName>
                    <label>Loreto - 65</label>
                </value>
                <value>
                    <fullName>82</fullName>
                    <label>Madre de Dios - 82</label>
                </value>
                <value>
                    <fullName>53</fullName>
                    <label>Moquegua - 53</label>
                </value>
                <value>
                    <fullName>63</fullName>
                    <label>Pasco - 63</label>
                </value>
                <value>
                    <fullName>73</fullName>
                    <label>Piura - 73</label>
                </value>
                <value>
                    <fullName>51</fullName>
                    <label>Puno - 51</label>
                </value>
                <value>
                    <fullName>42</fullName>
                    <label>San Martin - 42</label>
                </value>
                <value>
                    <fullName>52</fullName>
                    <label>Tacna - 52</label>
                </value>
                <value>
                    <fullName>72</fullName>
                    <label>Tumbes - 72</label>
                </value>
                <value>
                    <fullName>61</fullName>
                    <label>Ucayali - 61</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>prof_position_type__c</fullName>
        <label>Position</label>
        <picklist>
            <picklistValues>
                <fullName>ACCIONISTA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADMINISTRADOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APODERADO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASISTENTE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DIRECTORIO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE COMERCIAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE ADMINISTRACION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE ADMINISTRACION Y FINANZAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE CONTABILIDAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE FINANZAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE OPERACIONES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE RRHH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE GENERAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JEFE DE ADMINISTRACIÓN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JEFE DE ADMINISTRACION Y FINANZAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JEFE DE CONTABILIDAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JEFE DE FINANZAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JEFE DE TESORERIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTROS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRESIDENTE DE DIRECTORIO</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>		
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACCIONISTA</fullName>
                </value>
                <value>
                    <fullName>PRESIDENTE DE DIRECTORIO</fullName>
                </value>
                <value>
                    <fullName>APODERADO</fullName>
                </value>
                <value>
                    <fullName>DIRECTORIO</fullName>
                </value>
                <value>
                    <fullName>GERENTE GENERAL</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE FINANZAS</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE ADMINISTRACION Y FINANZAS</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE ADMINISTRACION</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE RRHH</fullName>
                </value>
                <value>
                    <fullName>GERENTE COMERCIAL</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE OPERACIONES</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE CONTABILIDAD</fullName>
                </value>
                <value>
                    <fullName>JEFE DE FINANZAS</fullName>
                </value>
                <value>
                    <fullName>JEFE DE TESORERIA</fullName>
                </value>
                <value>
                    <fullName>JEFE DE ADMINISTRACION Y FINANZAS</fullName>
                </value>
                <value>
                    <fullName>JEFE DE ADMINISTRACIÓN</fullName>
                </value>
                <value>
                    <fullName>JEFE DE CONTABILIDAD</fullName>
                </value>
                <value>
                    <fullName>ADMINISTRADOR</fullName>
                </value>
                <value>
                    <fullName>ASISTENTE</fullName>
                </value>
                <value>
                    <fullName>OTROS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/BE_CustomQuickAction_Tst.cls
/**
   -------------------------------------------------------------------------------------------------
   @Name <BE_CustomQuickAction_Tst>
   @Author Lolo Michel Bravo Ruiz (lolo.bravo@bbva.com)
   @Date 2020-03-03
   @Description test for BE_CustomQuickAction_Ctr class
   @Changes
   Date        Author   Email                  Type
   2020-03-03  LMBR     lolo.bravo@bbva.com    Creation
   -------------------------------------------------------------------------------------------------
 */
@IsTest
public with sharing class BE_CustomQuickAction_Tst { 
    /** GrantingTickets */
	final static String CLASS_NAME='className';
    
    /**
   @Description test BE_EditNonClient_Ctr.getFields(), correct scenary
     */
    @IsTest
    static void getSettingsTest() {
    	final Contact conOne = new Contact(Salutation='Mr.',FirstName='NON_CLIENT',LastName='NON_CLIENTE_CONTACT_ONE',decision_making_desc__c='Si',Email='contactone@test.com',MobilePhone='924567896',prof_position_type__c='APODERADO', contact_code__c='00001',phone_1__c='9876545',phone_1_area_code__c='01',phone_2__c='2235675',phone_2_area_code__c='01');
        BE_CustomQuickAction_Ctr.getSettings('BE_ModifyContact',conOne.Id);
    	final BE_SingleRelatedList_QuickAction__mdt configMeta=(BE_SingleRelatedList_QuickAction__mdt) JSON.deserialize('{"DeveloperName":"TESTMETADATA_TST","MasterLabel":"Phone"}',BE_SingleRelatedList_QuickAction__mdt.class);
    	System.assertEquals('TESTMETADATA_TST',configMeta.DeveloperName,'Good');
    }
    /**
        @Description test BE_CustomQuickAction_Ctr.getsObjFieldsTest(), correct scenary
     */
    @IsTest    
    static void getsObjFieldsTest() {
        
        final Account acc = new Account(Name='Test_Success01');       
        insert acc;
        test.startTest();
        final Map<String,Object> paramsMap = new Map<String,Object>{'Id'=> acc.Id , 'action' => 'update','sObjectType' => 'Account'};
        final sObject sOBJ=BE_CustomQuickAction_Ctr.getsObjFields(paramsMap, new List<String>{'Name'});
        System.debug('ACCOUNT'+ sOBJ);
        System.assertEquals(sOBJ.get('Name'),acc.Name,'Value Correct');
        test.stopTest();
    }
        /**
        @Description test BE_CustomQuickAction_Ctr.getsObjFieldsTest(), correct scenary
     */
    @IsTest    
    static void getsObjFieldscreateTest() {
        final Account acc = new Account(Name='Test_Success02');       
        insert acc;
        test.startTest();
        final Map<String,Object> paramsMap = new Map<String,Object>{'Id'=> '' , 'action' => 'create','sObjectType' => 'Account'};
        final sObject sOBJ=BE_CustomQuickAction_Ctr.getsObjFields(paramsMap, new List<String>{'Name'});
        System.assertEquals(Account.SobjectType.NewSobject(),sOBJ,'Value Correct');
        test.stopTest();
    }
    /**
     @Description test createRecords method, correct scenary
    */
    @IsTest
    static void createSuccessMethodsTest() {
        final Map<String,Object> paramsMap = new Map<String,Object>{CLASS_NAME=> ''};
        final BE_CustomQuickActionCRUD_Cls.Response resp = (BE_CustomQuickActionCRUD_Cls.Response)BE_CustomQuickAction_Ctr.createRecord(new Account(Name='Test'),paramsMap);
        System.assert(resp.isSuccess, 'success!');
    }
    
    /**
     @Description test updateRecords method, correct scenary
    */
    @IsTest
    static void updateSuccessMethodsTest() {
        final Account acc = new Account(Name='Test_Success03');
        insert acc;
        final Map<String,Object> paramsMap = new Map<String,Object>{CLASS_NAME=> ''};
        final BE_CustomQuickActionCRUD_Cls.Response resp = (BE_CustomQuickActionCRUD_Cls.Response)BE_CustomQuickAction_Ctr.updateRecord(acc, paramsMap);
        System.assert(resp.isSuccess, 'successUpdate!');
    }
    
    /**
     @Description test deleteRecords method, correct scenary
    */
    @IsTest
    static void deleteSuccessMethodsTest() {
        final Account acc = new Account(Name='Test_Delete_Success');
        insert acc;
        final Map<String,Object> paramsMap = new Map<String,Object>{CLASS_NAME=> ''};
        final BE_CustomQuickActionCRUD_Cls.Response resp = (BE_CustomQuickActionCRUD_Cls.Response)BE_CustomQuickAction_Ctr.deleteRecord(acc,paramsMap);
        System.assert(resp.isSuccess, 'successDeleteSucess!');
    }
    
    /**
     @Description test createRecords method, incorrect scenary
    */
    @IsTest
    static void createErrorMethodsTest() {
        final Map<String,Object> paramsMap = new Map<String,Object>{CLASS_NAME=> ''};
    	final BE_CustomQuickActionCRUD_Cls.Response resp = (BE_CustomQuickActionCRUD_Cls.Response)BE_CustomQuickAction_Ctr.createRecord(new Contact(LastName='TestError',MobilePhone='9876543213'), paramsMap);
        System.assert(!resp.isSuccess, 'errorCreate!');
    }

    /**
     @Description test BE_CustomQuickActionCRUD_Cls, correct scenary
    */
    @IsTest
    static void allCRUDsTest() {
    	final BE_CustomQuickActionCRUD_Cls srl = new BE_CustomQuickActionCRUD_Cls();
        final Account acc = new Account(Name='Test_Success04');
        final Map<String,Object> paramsMap = new Map<String,Object>{CLASS_NAME=> ''};
        srl.createRecord(acc,paramsMap);
        srl.updateRecord(acc,paramsMap);
        srl.deleteRecord(acc,paramsMap);
        Boolean isNull = false;
        final BE_CustomQuickActionCRUD_Cls.Response resp = srl.readRecord(acc,paramsMap);
        if(resp==null) {
            isNull = true;
        }
        System.assert(!isNull, 'successAll!'); 
    }
}