src/objects/BE_Urls_Dynamic__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuracion para asiganar dinamicamente Urls</description>
    <fields>
        <fullName>BE_Titulo_Url__c</fullName>
        <description>Muestra el titulo de las Urls</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Titulo Url</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BE_Url__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>ejemplo:&apos;https://www.google.es/&apos;</inlineHelpText>
        <label>Url</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Url Dinamica</label>
</CustomObject>

src/classes/BE_Ulr_Modalwelcome_Test.cls
/**
* _________________________________________________________________________________
* @Name     BE_Ulr_Modalwelcome_Test
* @Author   Antony de la rosa guzman
* @Date     2019-12-04
* @Group    DWP Perú
* @Description Clase de pruebas del controlador BE_Ulr_Modalwelcome_Cls.
* _________________________________________________________________________________
* @Changes
* _________________________________________________________________________________
*/
@isTest
public class BE_Ulr_Modalwelcome_Test {
    @testSetup
    private static void makeData() {
        User thisUser = BE_UtilitysDataTest_Test.crearUsuario('User test','Administrador del sistema','');
        insert thisUser;
        System.runAs(thisUser) {
            List<BE_Urls_Dynamic__c> url = new List<BE_Urls_Dynamic__c>();
            url.add(new BE_Urls_Dynamic__c(Name='test',BE_Titulo_Url__c ='test',BE_Url__c = 'test'));
            insert url;
        }
    }
    
    @isTest
    private static void testMethod1() {
        User thisUser = [SELECT Id FROM User WHERE Name = 'User test'];
        System.runAs(thisUser) {
            test.startTest();
            BE_Ulr_Modalwelcome_Cls.getlisAllData('test');
            test.stopTest();
        }
    }
}