src/objects/Calce__c.object
<CustomObject>
    <fields>
        <fullName>Get_Date__c</fullName>
        <formula>DATE(

(VALUE(LEFT(Name,4))), 

(VALUE(RIGHT(LEFT(Name,7),2))),

(VALUE(RIGHT(LEFT(Name,10),2))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Get Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>close_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>start_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Iniciado</fullName>
                </value>
                <value>
                    <fullName>En progreso</fullName>
                </value>
                <value>
                    <fullName>Compartido</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Calce</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calce</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BE_CalceChartController_tst.cls
@isTest
private with sharing class BE_CalceChartController_tst {
	@isTest   
    private static void testGetCalceChart()
        {
      
            final Calce__c calce = new Calce__c();
			calce.Name = 'Test Calce'; 
            calce.close_date__c = Date.today(); 
            calce.start_date__c = Date.today(); 
      	    calce.status__c = 'Iniciado';
			/*calce.Get_Date__c = Date.today();
            calce.CheckUser__c = true; */
            
            insert calce;
            
            BE_CalceChartController objCalceChartController = new BE_CalceChartController();
            List<AggregateResult> cal = BE_CalceChartController.getCalceChart(); 
            
              test.StartTest();
        		calce.Name = 'Test Calce 1';
              test.stopTest();
            
            System.assertEquals(calce.close_date__c,calce.start_date__c,'Success');
        }

}