src/objects/Calce__c.object
<CustomObject>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Iniciado</fullName>
                </value>
                <value>
                    <fullName>En progreso</fullName>
                </value>
                <value>
                    <fullName>Compartido</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Calce</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calce</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BE_CalceSummary_Tst.cls
/**
   ----------------------------------------------------------------------------------------------------
   @Name <BE_CalceNewOpportunities_Ctr>
   @Author Lolo Michel Bravo Ruiz (lolo.bravo@bbva.com)
   @Date 2020-02-24
   @Description Class Ctr for NewOpportunities
   @Changes
    Date        Author   Email                  Type
    2020-06-21  LMBR     lolo.bravo@bbva.com    Creation
   ----------------------------------------------------------------------------------------------------
 */
@isTest
public with sharing class BE_CalceSummary_Tst {
    /**
    @Description test method updateSummary
    */
    @isTest
    public static void readRecordsTest() {
     final Calce__c calce= new Calce__c(Name=String.valueof(Date.Today()),status__c='Iniciado');
     insert calce;
     final BE_CalceSummary_Ctr.Response res=BE_CalceSummary_Ctr.updateSummaryCalce(calce);
     BE_CalceSummary_Ctr.getSummaryCalce(calce.Id);
     System.assert(res.isSuccess, 'Calce Summary Successfull.');
    }
    /**
    @Description test method updateSummary exception
    */
    @isTest
    public static void readRecordsTestException() {
     final Calce__c calce= new Calce__c(Name=String.valueof(Date.Today()),status__c='Iniciado');
     insert calce;
     calce.status__c='Test';
     final BE_CalceSummary_Ctr.Response res=BE_CalceSummary_Ctr.updateSummaryCalce(calce);
     System.assert(!res.isSuccess, 'Calce Summary Error.');
    }
}