src/objects/Calce__c.object
<CustomObject>
    <fields>
        <fullName>close_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Iniciado</fullName>
                </value>
                <value>
                    <fullName>En progreso</fullName>
                </value>
                <value>
                    <fullName>Compartido</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Calce</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calce</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Calce_Details__c.object
<CustomObject>
    <fields>
        <fullName>account_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Client</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Calce Details</relationshipLabel>
        <relationshipName>Calce_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>calce_id__c</fullName>
        <label>Calce</label>
        <referenceTo>Calce__c</referenceTo>
        <relationshipLabel>Calce Details</relationshipLabel>
        <relationshipName>Calce_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>close_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>product_code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>product_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Calce Details</relationshipLabel>
        <relationshipName>Calce_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sub_type__c</fullName>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <label>cancelaciones del dia</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>Nuevas oportunidades</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>Cancelaciones anticipadas</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <label>Caida de Cartera</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Indirect</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Resource</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Calce Details</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calce Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BE_CalceNewOppHeadAction_Tst.cls
/**
   -------------------------------------------------------------------------------------------------
   @Name <BE_CalceNewOppHeadAction_Tst>
   @Author Martin Alejandro Mori Chavez (martin.mori.contractor@bbva.com)
   @Date 2020-06-21
   @Description Test class from BE_CalceNewOppHeadAction_Ctr
   @Changes
   Date        Author   Email                  				Type		Description
   2020-06-21  MAMC     martin.mori.contractor@bbva.com    	Creation
   2020-07-14  MAMC     martin.mori.contractor@bbva.com    	Modify		add fail methods to correct coverage test
   -------------------------------------------------------------------------------------------------
 */
@isTest
private class BE_CalceNewOppHeadAction_Tst {
    /**
    @Description test method createRecords
    */
    @isTest
    public static void createRecordsTest() {
        final Account acc = TestFactory.createAccount();
        final Product2 prod = TestFactory.createProduct();
        prod.IsActive = true;
        update prod;
        insert new PriceBookEntry(Product2Id=prod.Id, Pricebook2Id=Test.getStandardPricebookId(), UnitPrice=0, IsActive=true, CurrencyIsoCode='PEN');
        final fprd__GBL_Product_version__c prodVersion = new fprd__GBL_Product_version__c();
        prodVersion.fprd__Active__c = true;
        prodVersion.fprd__Product__c = prod.Id;
        prodVersion.fprd__Version_number__c = 1;
        prodVersion.CurrencyIsoCode = 'PEN';
        insert prodVersion;
        Final Calce__c calce = new Calce__c();
        calce.Name = 'Test Calce';
        calce.close_date__c = Date.today();
        calce.status__c = 'Iniciado';
        insert calce;
        final Calce_Details__c detail = new Calce_Details__c();
        detail.calce_id__c=calce.Id;
        detail.account_id__c=acc.Id;
        detail.product_id__c=prod.Id;
        detail.Name='detail';
        detail.CurrencyIsoCode='PEN';
        detail.amount__c=50000;
        detail.close_date__c=date.today();
        detail.type__c='Indirect';
        detail.product_code__c='CODE001';
        detail.sub_type__c='01';
        final List<sObject> lts = new List<sObject>();
        lts.add(detail);
        Test.StartTest();
        final BE_CalceNewOppHeadAction_Ctr newOpp = new BE_CalceNewOppHeadAction_Ctr();
        final BE_SingleRelatedListCRUD_Cls.Response resp = newOpp.createRecords(lts);
        System.assert(resp.isSuccess, 'success!!!');
        test.stopTest();
    }
    
    /**
    @Description test method createRecords fail
    */
    @isTest
    public static void createRecordsFailTest() {
        final Account acc = TestFactory.createAccount();
        Final Calce__c calce = new Calce__c();
        calce.Name = 'Test Calce';
        calce.close_date__c = Date.today();
        calce.status__c = 'Iniciado';
        insert calce;
        final Calce_Details__c detail = new Calce_Details__c();
        detail.calce_id__c=calce.Id;
        detail.account_id__c=acc.Id;
        detail.Name='detail';
        detail.CurrencyIsoCode='PEN';
        detail.amount__c=50000;
        detail.close_date__c=date.today();
        detail.type__c='Indirectas';
        detail.product_code__c='CODE001';
        detail.sub_type__c='01';
        final List<sObject> lts = new List<sObject>();
        lts.add(detail);
        Test.StartTest();
        final BE_CalceNewOppHeadAction_Ctr newOpp = new BE_CalceNewOppHeadAction_Ctr();
        final BE_SingleRelatedListCRUD_Cls.Response resp = newOpp.createRecords(lts);
        System.assert(!resp.isSuccess, 'error!!!');
        test.stopTest();
    }
    
    /**
    @Description test method createRecords fail
    */
    @isTest
    public static void createRecordsNullTest() {
        final Account acc = TestFactory.createAccount();
        final Product2 prod = TestFactory.createProduct();
        prod.IsActive = true;
        update prod;
        insert new PriceBookEntry(Product2Id=prod.Id, Pricebook2Id=Test.getStandardPricebookId(), UnitPrice=0, IsActive=true, CurrencyIsoCode='PEN');
        final fprd__GBL_Product_version__c prodVersion = new fprd__GBL_Product_version__c();
        prodVersion.fprd__Active__c = true;
        prodVersion.fprd__Product__c = prod.Id;
        prodVersion.fprd__Version_number__c = 1;
        prodVersion.CurrencyIsoCode = 'PEN';
        insert prodVersion;
        Final Calce__c calce = new Calce__c();
        calce.Name = 'Test Calce';
        calce.close_date__c = Date.today();
        calce.status__c = 'Iniciado';
        insert calce;
        final Calce_Details__c detail = new Calce_Details__c();
        detail.calce_id__c=calce.Id;
        detail.account_id__c=acc.Id;
        detail.product_id__c=prod.Id;
        detail.Name='detail';
        detail.CurrencyIsoCode='EUR';
        detail.amount__c=50000;
        detail.close_date__c=date.today();
        detail.type__c='Indirect';
        detail.product_code__c='CODE001';
        detail.sub_type__c='01';
        final List<sObject> lts = new List<sObject>();
        lts.add(detail);
        Test.StartTest();
        final BE_CalceNewOppHeadAction_Ctr newOpp = new BE_CalceNewOppHeadAction_Ctr();
        final BE_SingleRelatedListCRUD_Cls.Response resp = newOpp.createRecords(lts);
        System.assert(!resp.isSuccess, 'error!!!');
        test.stopTest();
    }
    
    /**
    @Description test method createRecords fail owner
    */
    @isTest
    public static void createRecordsFailOwnTest() {
        Final Account acc = TestFactory.createAccount();
        Final User usuario = TestFactory.createUser('TestUser1', 'Ejecutivo');
        Final Calce__c calce = new Calce__c();
        calce.Name = 'Test Calce';
        calce.close_date__c = Date.today();
        calce.status__c = 'Iniciado';
        calce.OwnerId = usuario.Id;
        insert calce;
        final Calce_Details__c detail = new Calce_Details__c();
        detail.calce_id__c=calce.Id;
        detail.account_id__c=acc.Id;
        detail.Name='detail';
        detail.CurrencyIsoCode='PEN';
        detail.amount__c=50000;
        detail.close_date__c=date.today();
        detail.type__c='Indirectas';
        detail.product_code__c='CODE001';
        detail.sub_type__c='01';
        final List<sObject> lts = new List<sObject>();
        lts.add(detail);
        Test.StartTest();
        final BE_CalceNewOppHeadAction_Ctr newOpp = new BE_CalceNewOppHeadAction_Ctr();
        final BE_SingleRelatedListCRUD_Cls.Response resp = newOpp.createRecords(lts);
        System.assert(!resp.isSuccess, 'error!!!');
        test.stopTest();
    }
}