src/objects/Calce__c.object
<CustomObject>
    <fields>
        <fullName>Get_Date__c</fullName>
        <formula>DATE(

(VALUE(LEFT(Name,4))), 

(VALUE(RIGHT(LEFT(Name,7),2))),

(VALUE(RIGHT(LEFT(Name,10),2))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Get Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>net_direct_calce__c</fullName>
        <formula>sub_total_direct__c + portfolio_recovery__c - (direct_regular_cancellations__c+ direct_early_cancellations__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Calce Neto Directo</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>net_indirect_calce__c</fullName>
        <formula>sub_total_indirect__c -( indirect_early_cancellations__c + indirect_regular_cancellations__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Calce Neto Indirecto</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>net_resource_calce__c</fullName>
        <formula>+Sub_Total_Resource__c  - resource_regular_cancellations__c  - Early_Cancellations_Resource__c -  Sub_total_Expense__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Calce Neto Recurso</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Calce</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calce</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BE_CalceChartController.cls
public with sharing class BE_CalceChartController {
    
    private BE_CalceChartController() { }
    /* controlador para el dashboard calce */
 
    
    /*Obtener resumen calce*/
    @AuraEnabled(cacheable=true)
    public static List<AggregateResult> getCalceChart() {  
        
   		final List<AggregateResult> resultList = [SELECT SUM(net_direct_calce__c) netDirect, SUM(net_indirect_calce__c) netIndirect, SUM(net_resource_calce__c) netResource from Calce__c where Get_Date__c=TODAY and CheckUser__c = true];
   
    	 return resultList;
 
        	
		 }  
    
    
  
	}