src/objects/Calce__c.object
<CustomObject>
    <fields>
        <fullName>close_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>start_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Calce</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calce</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Calce_Details__c.object
<CustomObject>
    <fields>
        <fullName>account_contract_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Contract</label>
        <referenceTo>Account_Contract__c</referenceTo>
        <relationshipLabel>Calce Details</relationshipLabel>
        <relationshipName>Calce_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>account_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Client</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Calce Details</relationshipLabel>
        <relationshipName>Calce_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>amount_cancelled__c</fullName>
        <label>Amount  Cancelled</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>calce_id__c</fullName>
        <label>Calce</label>
        <referenceTo>Calce__c</referenceTo>
        <relationshipLabel>Calce Details</relationshipLabel>
        <relationshipName>Calce_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>close_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>contract_number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>extension__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Extension</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>return__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Return</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sub_type__c</fullName>
        <label>Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <label>cancelaciones del dia</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>Nuevas oportunidades</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>Cancelaciones anticipadas</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <label>Caida de Cartera</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Calce Details</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calce Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BE_CalcePortafolioFall_Ctr.cls
/**
   -------------------------------------------------------------------------------------------------
   @Name <BE_CalceCancellationsOfDay_Tst>
   @Author Martin Alejandro Mori Chavez (martin.mori.contractor@bbva.com)
   @Date 2020-06-21
   @Description BE_CalceNewOppHeadAction_Ctr for  New Opportunities
   @Changes
   Date        Author   Email                  				Type
   2020-06-21  MAMC     martin.mori.contractor@bbva.com    	Creation
   -------------------------------------------------------------------------------------------------
 */
public with sharing class BE_CalcePortafolioFall_Ctr extends BE_SingleRelatedListCRUD_Cls {
/** Opportunity type Cancelation */
final static String CALCE_TYPE='04';
/** Lang Code */
private static final List<String> LANG_CODE = new List<String> {'es','en_US'};
/**
   @Description updateRecords
   @param  List<SObject> sObjs
   @return BE_SingleRelatedListCRUD_Cls.Response response
 */
public override BE_SingleRelatedListCRUD_Cls.Response readRecords(Map<String,Object>param) {
	final BE_SingleRelatedListCRUD_Cls.Response res=new BE_SingleRelatedListCRUD_Cls.Response();
	final Map<String,String> messages = new Map<String,String>();
	try {
		final Calce__c calce= [SELECT Id,OwnerId,close_date__c,start_date__c FROM Calce__c WHERE Id=:(String)param.get('recordId')];
		BE_CalceDetailManger_Helper.updatePortfolioFall(calce,CALCE_TYPE);
		final List<Calce_Details__c>resData =[SELECT ID,Name,Contract_Number__c,account_id__r.Name,close_date__c,calce_id__c,account_contract_id__c,amount__c,amount_cancelled__c,extension__c,return__c,CurrencyIsoCode FROM Calce_Details__c WHERE sub_type__c=:CALCE_TYPE AND calce_id__c=: calce.Id];
		res.data=resData;
		messages.put(LANG_CODE[0], 'Caida de cartera consultado correctamente.');
		messages.put(LANG_CODE[1], 'Portafolio fall search sucessfully.');
		res.isSuccess = true;
		res.message = messages.get(UserInfo.getLanguage());
	} catch (Exception ex) {
		res.isSuccess=false;
		res.message=ex.getDmlMessage(0);
	}
	return res;
}
/**
    @Description updateRecords
    @param  List<SObject> sObjs
    @return BE_SingleRelatedListCRUD_Cls.Response response
 */
public override BE_SingleRelatedListCRUD_Cls.Response updateRecords(List<SObject>sObjs) {
	final BE_SingleRelatedListCRUD_Cls.Response res=new BE_SingleRelatedListCRUD_Cls.Response();
	final Map<String,String> messages = new Map<String,String>();
	try {
		messages.put(LANG_CODE[0], 'Caida de cartera actualizado correctamente.');
		messages.put(LANG_CODE[1], 'Portafolio fall saved sucessfully.');
		res.isSuccess = true;
		res.message = messages.get(UserInfo.getLanguage());
		BE_CalceDetailManger_Helper.updateCalceStatus(sObjs[0].Id);
		update sObjs;
	} catch (Exception ex) {
		res.isSuccess=false;
		res.message=ex.getDmlMessage(0);
	}
	return res;
}
}