src/objects/Calce__c.object
<CustomObject>
    <fields>
        <fullName>close_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Iniciado</fullName>
                </value>
                <value>
                    <fullName>En progreso</fullName>
                </value>
                <value>
                    <fullName>Compartido</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Calce</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calce</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Calce_Details__c.object
<CustomObject>
    <fields>
        <fullName>account_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Client</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Calce Details</relationshipLabel>
        <relationshipName>Calce_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>calce_id__c</fullName>
        <label>Calce</label>
        <referenceTo>Calce__c</referenceTo>
        <relationshipLabel>Calce Details</relationshipLabel>
        <relationshipName>Calce_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>close_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>product_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Calce Details</relationshipLabel>
        <relationshipName>Calce_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Calce Details</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calce Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>opportunity_planning_date__c</fullName>
        <description>Planning date of an opportunity</description>
        <label>Planning date</label>
        <type>Date</type>
    </fields>
<fields>
        <fullName>opportunity_status_type__c</fullName>
        <description>Status of an opportunity</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/BE_CalceNewOppHeadAction_Ctr.cls
/**
   -------------------------------------------------------------------------------------------------
   @Name <BE_CalceCancellationsOfDay_Tst>
   @Author Martin Alejandro Mori Chavez (martin.mori.contractor@bbva.com)
   @Date 2020-06-21
   @Description BE_CalceNewOppHeadAction_Ctr for  New Opportunities
   @Changes
   Date        Author   Email                  				Type		Description
   2020-06-21  MAMC     martin.mori.contractor@bbva.com    	Creation
   2020-07-14  MAMC     martin.mori.contractor@bbva.com		Modify		change to Exception for DMLException in catch sections
   -------------------------------------------------------------------------------------------------
 */
public with sharing class BE_CalceNewOppHeadAction_Ctr extends BE_SingleRelatedListCRUD_Cls {
	/** Lang Code */
	private static final List<String>LANG_CODE = new List<String> {'es','en_US'}; 
	/**
	   @Description createRecords
	   @param  List<SObject> sObjs
	   @return BE_SingleRelatedListCRUD_Cls.Response response
	 */
	public override Response createRecords(List<SObject>sObjs) {
		final Map<String,String> messages = new Map<String,String>();
		final BE_SingleRelatedListCRUD_Cls.Response res = new BE_SingleRelatedListCRUD_Cls.Response();
		final Savepoint savePoint = Database.setSavepoint();
		try {
			final Calce_Details__c calDet = (Calce_Details__c)sObjs[0];
			final Calce__c calce = [SELECT Id,OwnerId,status__c,close_date__c FROM Calce__c WHERE Id=:calDet.calce_id__c];
			final String accOwnerId=[SELECT Id,OwnerId FROM Account WHERE Id=:calDet.account_id__c].OwnerId;
			if(accOwnerId==calce.OwnerId) {
				final Opportunity opp = new Opportunity(Name=calDet.Name,AccountId = calDet.account_id__c,StageName = '02',opportunity_status_type__c = '03',
													   type='01',CloseDate = calce.close_date__c,opportunity_planning_date__c = calce.close_date__c,
													   CurrencyIsoCode = calDet.CurrencyIsoCode,Amount = calDet.amount__c,Field_Sup_Closing_Date__c = calce.close_date__c,
													   OwnerId=calce.OwnerId);
				insert opp;
				if(String.isNotBlank(calDet.product_id__c)) {
					final String entryId = [SELECT Id FROM PriceBookEntry WHERE Product2Id = :calDet.product_id__c AND CurrencyIsoCode = :opp.CurrencyIsoCode AND IsActive = TRUE LIMIT 1][0].Id;
					final String versionId = [SELECT Id FROM fprd__GBL_Product_version__c WHERE fprd__Product__c = :calDet.product_id__c AND fprd__Active__c = TRUE LIMIT 1][0].Id;
					final OpportunityLineItem oli = new OpportunityLineItem();
					oli.OpportunityId = opp.Id;
					oli.Quantity = 1;
					oli.UnitPrice = Opp.Amount;
					oli.PricebookEntryId = entryId;
					oli.fprd__GBL_Product_version__c = versionId;
					insert oli;
					messages.put(LANG_CODE[0], 'Oportunidad creada correctamente');
					messages.put(LANG_CODE[1], 'Opportunity created successfull');
					res.isSuccess = true;
					res.message = messages.get(UserInfo.getLanguage());
					BE_CalceDetailManger_Helper.setCalceStatus(calce);
				} else {
					Database.rollback(savePoint);
					messages.put(LANG_CODE[0], 'Producto no encontrado');
					messages.put(LANG_CODE[1], 'Product not found');
					res.isSuccess = false;
					res.message = messages.get(UserInfo.getLanguage());
				}
			} else { 
				messages.put(LANG_CODE[0], 'Solo puede crear oportunidades  para su cartera de clientes');
				messages.put(LANG_CODE[1], 'Only can create opportunity for your portafolio of clients.');  
				res.isSuccess = false;
				res.message = messages.get(UserInfo.getLanguage()); 
			}
		} catch (DMLException ex) {
			res.isSuccess = false;
			res.message = ex.getDmlMessage(0);
			Database.rollback(savePoint);
		}
		return res;
	}
}