src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>opportunity_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Opportunity</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>bypass__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/dwp_cvad__Action_Audit__c.object
<CustomObject>
    <description>Stores the basic action audit information</description>
    <fields>
        <fullName>dwp_cvad__audit_audit_comments__c</fullName>
        <description>Comments to describe the action audited.</description>
        <inlineHelpText>Comments to describe the action audited.</inlineHelpText>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <label>Action Audit</label>
    <nameField>
        <displayFormat>AA-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Audits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/dwp_cvad__Action_Audit_Detail__c.object
<CustomObject>
    <description>Stores the details of the audited action.</description>
    <label>Action Audit Detail</label>
    <nameField>
        <displayFormat>AAD-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Audit Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/fprd__GBL_Product_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>fprd__Header__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Header</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>fprd__Header_order__c</fullName>
        <label>Header order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>fprd__Label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fprd__LoV_labels__c</fullName>
        <label>Deprecated</label>
        <length>50000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>fprd__LoV_values__c</fullName>
        <label>Deprecated</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>fprd__Map_field__c</fullName>
        <label>Map field</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fprd__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product configurations</relationshipLabel>
        <relationshipName>Product_configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product configuration</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Product Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product configurations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
<fields>
        <fullName>opportunity_status_type__c</fullName>
        <description>Status of an opportunity</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isProcess__c</fullName>
        <defaultValue>false</defaultValue>
        <description>activated by Process</description>
        <label>isProcess</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>minimun_fee_per__c</fullName>
        <label>Minimun fee (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>proposed_fee_per__c</fullName>
        <label>Proposed fee (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

src/classes/SanctionPriceDecision_ctrl.cls
/**
* @author Global_HUB developers
* @date 01-08-2018
*
* @group Global_HUB
*
* @description Controller class from SanctionPriceDecision_ctrl
**/
public with sharing class SanctionPriceDecision_ctrl {
    @AuraEnabled
    public static Map<String,Object> getInfo(String recordIdOppLineItem){
        Map<String,Object> mapReturn = new Map<String,Object>();

        List<OpportunityLineItem> lstOppLineItem = [SELECT  Id, 
                                                            Product2.Name,
                                                            Product2Id,
                                                            proposed_fee_per__c,
                                                            minimun_fee_per__c
                                                    FROM OpportunityLineItem
                                                    WHERE Id = :recordIdOppLineItem];
        List<fprd__GBL_Product_Configuration__c> lstConfig = [SELECT    Id,
                                                                        fprd__Map_field__c,
                                                                        fprd__Header__c, 
                                                                        fprd__Header_order__c,
                                                                        fprd__LoV_values__c, 
                                                                        fprd__LoV_labels__c, 
                                                                        fprd__Label__c 
                                                                FROM fprd__GBL_Product_Configuration__c
                                                                WHERE fprd__Product__c = :lstOppLineItem[0].Product2Id
                                                                AND fprd__Header__c = true
                                                                ORDER BY fprd__Header_order__c];
        Set<String> setFields = new Set<String>();
        Map<String,Object> mapMapfieldConfig = new Map<String,Object>();
        for(fprd__GBL_Product_Configuration__c prodConfig : lstConfig){
            setFields.add(prodConfig.fprd__Map_field__c);
            mapMapfieldConfig.put(prodConfig.fprd__Map_field__c,prodConfig);
        }
        List<String> lstStringField = new List<String>(setFields);
        mapReturn.put('lstInfoIsEmpty', lstStringField.isEmpty());
        mapReturn.put('lstField', lstStringField);
        mapReturn.put('lstOppLineItem', lstOppLineItem);
        mapReturn.put('mapMapfieldConfig',mapMapfieldConfig);
        if(!lstStringField.isEmpty()){ 
            List<SObject> lstRow = Database.query('SELECT ' + String.join(lstStringField, ',') + ' FROM OpportunityLineItem WHERE Id = \'' + recordIdOppLineItem + '\'');
            mapReturn.put('lstInfo', lstRow);
        }
        
        return mapReturn;
    }

    @AuraEnabled
    public static Map<String,Object> saveDecision(String recordId, String status_opp, String stageName, Boolean createCase, String styleAudit, String nameAudit, String strComments, String storeHtml){
        Map<String,Object> mapReturn = new Map<String,Object>();
        List<dwp_cvad__Action_Audit__c> lstAudit = new List<dwp_cvad__Action_Audit__c>();
        Opportunity opp = new Opportunity();
        opp.Id = recordId;
        opp.StageName = stageName;
        opp.opportunity_status_type__c = status_opp;
        opp.isProcess__c = true;
        try{
            update opp;
            lstAudit.add(Action_Audit_Helper.getAudit(nameAudit, 'Opportunity', recordId, DateTime.now(), label.AuditPriceApproval, UserInfo.getUserId(), styleAudit, null, false));
            lstAudit[0].dwp_cvad__audit_audit_comments__c = strComments;
            insert lstAudit;


            List<dwp_cvad__Action_Audit_Detail__c> lstDetails = new List<dwp_cvad__Action_Audit_Detail__c>();
            lstDetails.add(Action_Audit_Helper.getAuditDetail(lstAudit[0].Id, storeHtml, 1, '', 'Embedded'));
            insert lstDetails;
           
            if(createCase){
                List<Group> queueGroup = [SELECT    Id, 
                                                    DeveloperName,
                                                    Type  
                                                FROM Group 
                                                WHERE Type = 'Queue' 
                                                AND DeveloperName = 'Tier_1'];
                List<Opportunity> lstOpp = [SELECT  Id,
                                                    AccountId
                                            FROM Opportunity
                                            WHERE Id = :recordId];
                Case caseInsert = new Case();
                caseInsert.Status = '01';
                caseInsert.OwnerId = queueGroup[0].Id;
                caseInsert.Type = 'Other';
                caseInsert.AccountId = lstOpp[0].AccountId;
                caseInsert.opportunity_id__c = recordId;
                insert caseInsert;
            }
            mapReturn.put('isOk', true);
        }catch(Exception e){
            mapReturn.put('isOk', false);
        }
        return mapReturn;
    }

    @AuraEnabled
    public static Map<String,Object> saveDecisionAnalist(String recordId, String status_opp, String stageName, Boolean elevateCase, String styleAudit, String nameAudit, String strComments, String recordOli, List<String> lstApiField, List<Object> lstValue, String statusCase, String storeHtml){
        Map<String,Object> mapReturn = new Map<String,Object>();
        List<dwp_cvad__Action_Audit__c> lstAudit = new List<dwp_cvad__Action_Audit__c>();
        Opportunity opp = new Opportunity();
        opp.Id = recordId;
        opp.StageName = stageName;
        opp.opportunity_status_type__c = status_opp;
        opp.isProcess__c = true;
        try{
            update opp;
            lstAudit.add(Action_Audit_Helper.getAudit(nameAudit, 'Opportunity', recordId, DateTime.now(), label.AuditPriceApproval, UserInfo.getUserId(), styleAudit, null, false));
            lstAudit[0].dwp_cvad__audit_audit_comments__c = strComments;
            insert lstAudit;

            List<dwp_cvad__Action_Audit_Detail__c> lstDetails = new List<dwp_cvad__Action_Audit_Detail__c>();
            lstDetails.add(Action_Audit_Helper.getAuditDetail(lstAudit[0].Id, storeHtml, 1, '', 'Embedded'));
            insert lstDetails;

            List<Case> lstCases = [SELECT   Id, 
                                        opportunity_id__c, 
                                        IsClosed,
                                        OwnerId,
                                        Status,
                                        bypass__c
                                FROM Case 
                                WHERE opportunity_id__c = :recordId 
                                AND IsClosed = false];
            lstCases[0].Status = statusCase;
            lstCases[0].bypass__c = true;
            if(elevateCase){
                List<Group> queueGroup = [SELECT    Id, 
                                                    DeveloperName,
                                                    Type  
                                                FROM Group 
                                                WHERE Type = 'Queue' 
                                                AND DeveloperName = 'Tier_2'];
                lstCases[0].OwnerId = queueGroup[0].Id;
            }
            update lstCases;
            Map<String,Object> mapReturnSaveOli = FieldForm_ctrl.doSave(recordOli,'OpportunityLineItem', lstApiField, lstValue);

            mapReturn.put('isOk', (Boolean)mapReturnSaveOli.get('isOk'));
        }catch(Exception e){
            mapReturn.put('isOk', false);
        }
        return mapReturn;
    }

    @AuraEnabled
    public static Map<String,Object> getInfoAnalist(String recordIdOppLineItem){
        Map<String,Object> mapReturn = new Map<String,Object>();

        List<OpportunityLineItem> lstOppLineItem = [SELECT  Id, 
                                                            Product2.Name,
                                                            Product2Id,
                                                            proposed_fee_per__c,
                                                            minimun_fee_per__c,
                                                            OpportunityId
                                                    FROM OpportunityLineItem
                                                    WHERE Id = :recordIdOppLineItem];
        List<fprd__GBL_Product_Configuration__c> lstConfig = [SELECT    Id,
                                                                        fprd__Map_field__c,
                                                                        fprd__Header__c, 
                                                                        fprd__Header_order__c,
                                                                        fprd__LoV_values__c, 
                                                                        fprd__LoV_labels__c, 
                                                                        fprd__Label__c 
                                                                FROM fprd__GBL_Product_Configuration__c
                                                                WHERE fprd__Product__c = :lstOppLineItem[0].Product2Id
                                                                AND fprd__Header__c = true
                                                                ORDER BY fprd__Header_order__c];
        Set<String> setFields = new Set<String>();
        Map<String,Object> mapMapfieldConfig = new Map<String,Object>();
        for(fprd__GBL_Product_Configuration__c prodConfig : lstConfig){
            setFields.add(prodConfig.fprd__Map_field__c);
            mapMapfieldConfig.put(prodConfig.fprd__Map_field__c,prodConfig);
        }
        List<String> lstStringField = new List<String>(setFields);
        mapReturn.put('lstInfoIsEmpty', lstStringField.isEmpty());
        mapReturn.put('lstField', lstStringField);
        mapReturn.put('lstOppLineItem', lstOppLineItem);
        mapReturn.put('mapMapfieldConfig',mapMapfieldConfig);
        if(!lstStringField.isEmpty()){ 
            List<SObject> lstRow = Database.query('SELECT ' + String.join(lstStringField, ',') + ' FROM OpportunityLineItem WHERE Id = \'' + recordIdOppLineItem + '\'');
            mapReturn.put('lstInfo', lstRow);
        }

        List<Case> lstCases = [SELECT   Id, 
                                        opportunity_id__c, 
                                        IsClosed 
                                FROM Case 
                                WHERE opportunity_id__c = :lstOppLineItem[0].OpportunityId
                                AND IsClosed = false
                                AND Status = '01'];
        mapReturn.put('caseOpen', !lstCases.isEmpty());
        
        return mapReturn;
    }
}