src/objects/Commercial_Alert_Visit_Relation__c.object
<CustomObject>
    <description>Object to related multiple commercial Altert with multilple visits</description>
    <fields>
        <fullName>commercial_id__c</fullName>
        <label>Commercial Alert</label>
        <referenceTo>altm__Commercial_Alert__c</referenceTo>
        <relationshipLabel>Relación de visitas</relationshipLabel>
        <relationshipName>Commercial_Alert_Task_Relationship</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>visit_id__c</fullName>
        <label>Visit</label>
        <referenceTo>dwp_kitv__Visit__c</referenceTo>
        <relationshipLabel>Commercial Alert Task Relationship</relationshipLabel>
        <relationshipName>Commercial_Alert_Task_Relationship</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Relación de visita</label>
    <nameField>
        <displayFormat>CAT{YYYY}{MM}-{0}{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relación de visitas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/dwp_kitv__Visit__c.object
<CustomObject>
    <description>Main object to manage visits</description>
    <fields>
        <fullName>dwp_kitv__visit_end_date__c</fullName>
        <description>Formula field where the duration was added to start date.</description>
        <formula>dwp_kitv__visit_start_date__c + VALUE(TEXT( dwp_kitv__visit_duration_number__c ))/1440</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dwp_kitv__visit_start_date__c</fullName>
        <description>Field to set the start date time of the visit.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dwp_kitv__visit_status_type__c</fullName>
        <description>Status visit</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>Arranged</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>Arranged - Pending Updates</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <label>Visit Completed - Pending Feedback</label>
                </value>
                <value>
                    <fullName>05</fullName>
                    <label>Visit Completed - Minute Sent</label>
                </value>
                <value>
                    <fullName>06</fullName>
                    <label>Finalized</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Visit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/BE_CA_AlertVisitRelationship_Cls.cls
public with sharing class BE_CA_AlertVisitRelationship_Cls extends BE_SingleRelatedListCRUD_Cls {
/**
	   @Description readRecords
	   @param  List<SObject> sObjs
	   @return BE_SingleRelatedListCRUD_Cls.Response response
	 */
	public override BE_SingleRelatedListCRUD_Cls.Response readRecords(Map<String,Object>param) {
		final BE_SingleRelatedListCRUD_Cls.Response res=new BE_SingleRelatedListCRUD_Cls.Response();
		final Map<String,String> messages = new Map<String,String>();
		try {
            System.debug((String)param.get('recordId'));
            List<classVistRelation> listVisit= new List<classVistRelation>();
            for (Commercial_Alert_Visit_Relation__c itemRelation : [SELECT commercial_id__c,visit_id__r.dwp_kitv__visit_start_date__c,visit_id__r.dwp_kitv__visit_status_type__c,visit_id__r.Name,visit_id__r.dwp_kitv__visit_end_date__c FROM Commercial_Alert_Visit_Relation__c WHERE commercial_id__c=:(String)param.get('recordId')]) {
                classVistRelation visitRel= new classVistRelation(itemRelation.visit_id__r.Name);
                listVisit.add(visitRel);
            }
            //res.data=listVisit;
            res.isSuccess=true;
		} catch (DMLException ex) {
			res.isSuccess=false;
			res.message=ex.getDmlMessage(0);
		}
		return res;
	}

    public class classVistRelation {
        public String Name {set;get;}
        public classVistRelation (String Name) {
            this.Name=Name;
        }
    }
}