src/objects/Commercial_Alert_Visit_Relation__c.object
<CustomObject>
    <description>Object to related multiple commercial Altert with multilple visits</description>
    <fields>
        <fullName>commercial_id__c</fullName>
        <label>Commercial Alert</label>
        <referenceTo>altm__Commercial_Alert__c</referenceTo>
        <relationshipLabel>Relación de visitas</relationshipLabel>
        <relationshipName>Commercial_Alert_Task_Relationship</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>visit_id__c</fullName>
        <label>Visit</label>
        <referenceTo>dwp_kitv__Visit__c</referenceTo>
        <relationshipLabel>Commercial Alert Task Relationship</relationshipLabel>
        <relationshipName>Commercial_Alert_Task_Relationship</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Relación de visita</label>
    <nameField>
        <displayFormat>CAT{YYYY}{MM}-{0}{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relación de visitas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BE_CA_Visit_Relation_Trigger_cls.cls
/*
 * @Name: Commercial Alert Visit Relation
 * @Description: Trigger de Ejecucion Comercial Visit Alert Relation
 * @Create by: Eduardo Vargas
 * @HIstorial de cambios:
	
 * 
*/
public with sharing class BE_CA_Visit_Relation_Trigger_cls {
    /** MESSAGE */
    final static String TEXT_MESSAGE='El registro ya existe';
	/*Constructor Account_Trigger_cls*/
    private BE_CA_Visit_Relation_Trigger_cls() {}
    
    /*Method Master for trigger*/
    public static void asignBeforeUpdate(list<Commercial_Alert_Visit_Relation__c> accsNew) {
        checkDuplicityBeforeUpdate(accsNew);
    }
    
    /*Validate Duplicate Values*/
    private static void checkDuplicityBeforeUpdate(list<Commercial_Alert_Visit_Relation__c> accsNew) {
        final Integer sizeVal=1;
        if(accsNew.size() == sizeVal) {
            final List<Commercial_Alert_Visit_Relation__c> relation = [SELECT commercial_id__c, visit_id__c FROM Commercial_Alert_Visit_Relation__c WHERE commercial_id__c = :accsNew[0].commercial_id__c AND visit_id__c = :accsNew[0].visit_id__c];
            if(relation.size() >= sizeVal) {
                accsNew[0].visit_id__c.addError(TEXT_MESSAGE);
            }
        }
    }

}