src/objects/Commission_Question__c.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <defaultValue>&quot; &quot;</defaultValue>
        <encryptionScheme>None</encryptionScheme>
        <label>Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Input_Value__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Input Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Commission__c</fullName>
        <label>Product Commission</label>
        <referenceTo>Product_Commission__c</referenceTo>
        <relationshipLabel>Commission Questions</relationshipLabel>
        <relationshipName>Commission_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Commission Question</label>
    <nameField>
        <displayFormat>CQ-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>gipr_Plazo__c</fullName>
        <label>gipr_Plazo</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>gipr_Periodicidad__c</fullName>
        <label>gipr_Periodicidad</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Product_Commission__c.object
<CustomObject>
    <fields>
        <fullName>Authorized_Rate_Value__c</fullName>
        <label>Authorized Rate Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commission_Calculation_Amount__c</fullName>
        <label>Commission Calculation Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commission_Calculation_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Commission Calculation Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commission_Calculation_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Commission Calculation Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commission_Calculation_Version__c</fullName>
        <label>Commission Calculation Version</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Product</label>
        <referenceTo>OpportunityLineItem</referenceTo>
        <relationshipLabel>Product Commissions</relationshipLabel>
        <relationshipName>Product_Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requested_Rate_Value__c</fullName>
        <label>Requested Rate Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Suggested_Rate_Type__c</fullName>
        <label>Suggested Rate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>currency</fullName>
                </value>
                <value>
                    <fullName>percentage</fullName>
                </value>
                <value>
                    <fullName>amount</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Term_Frequency_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Term Frequency Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Term_Number__c</fullName>
        <label>Term Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product Commission</label>
    <nameField>
        <displayFormat>PC-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BE_ProdCommissionSection_Ctr.cls
/**
   -------------------------------------------------------------------------------------------------
   @Name <BE_ProdCommissionSection_Ctr>
   @Author Martin Alejandro Mori Chavez (martin.mori.contractor@bbva.com)
   @Date 2021-03-12
   @Description Controller class of BE_ProdCommissionSection_Lwc
   @Changes
   Date        Author   Email                  				    Type		Description
   2021-03-12  MAMC     martin.mori.contractor@bbva.com    	    Creation
   2021-03-12  MAMC    luis.vargas.matute.contractor@bbva.com   Creation
   -------------------------------------------------------------------------------------------------
 */
public with sharing class BE_ProdCommissionSection_Ctr {
    /* constructor of class */
    private BE_ProdCommissionSection_Ctr() {}
    
    /**Method used to get quotes **/
	@AuraEnabled
    public static List<Product_Commission__c> getCommissions(String recordId, Boolean negotiables) {
        return BE_CalculateCommission_Ctr.getCommissions(recordId, negotiables);
    }

    /**Method used to save answers of questions **/
    @AuraEnabled
    public static void calculateRate(String commissionId, String status) {
        
        Final Product_Commission__c currentCommission = [SELECT Opportunity_Product__r.unitprice, Opportunity_Product__r.gipr_Plazo__c, Opportunity_Product__r.gipr_Periodicidad__c, Opportunity_Product__r.CurrencyIsoCode, Code__c, Term_Frequency_Id__c, Term_Number__c, Suggested_Rate_Type__c, Sugested_Rate_Percentage__c, Requested_Rate_Value__c, Authorized_Rate_Value__c, (SELECT Code__c, Input_Value__c, Answer__c FROM Commission_Questions__r) FROM Product_Commission__c WHERE Id = :commissionId];
        List<Product_Commission__c> commissionsAsoRequest = new List<Product_Commission__c>();
        system.debug('1: ');
        Final BE_CalculateCommissionRequest_Helper listCommissionHelper = new BE_CalculateCommissionRequest_Helper(currentCommission,status);
        system.debug('2: ');
        Final System.HttpResponse invoke = listCommissionHelper.invoke();
        system.debug('3: ');
        switch on invoke.getStatusCode() {
            when 200 {
                system.debug('response: '+ invoke.getBody());
                
                Product_Commission__c commission = new Product_Commission__c();
                Final Map<String, Object> response = (Map<String, Object>) JSON.deserializeUntyped(invoke.getBody());
                Final Map<String, Object> commissionResp = (Map<String, Object>) response.get('data');
                
                commission.Id = commissionId;
                
                Final Map<String, Object> fixedFee = (Map<String, Object>) commissionResp.get('fixedFee');
                commission.Commission_Calculation_Code__c = String.valueOf(fixedFee.get('id'));
                
                Final Map<String, Object> calculatedFee = (Map<String, Object>) commissionResp.get('calculatedFee');
                commission.Commission_Calculation_Id__c = String.valueOf(calculatedFee.get('id'));
                commission.Commission_Calculation_Version__c = Integer.valueOf(calculatedFee.get('version'));
                
                Final Map<String, Object> calculatedAmount = (Map<String, Object>) calculatedFee.get('calculatedAmount');
                commission.Commission_Calculation_Amount__c = Double.valueOf(calculatedAmount.get('amount'));
                commission.CurrencyIsoCode = String.valueOf(calculatedFee.get('currency'));
                commissionsAsoRequest.add(commission);
            }
        }
        System.debug('REQUESTED DATA-----Result:'+commissionsAsoRequest);
        update commissionsAsoRequest;
        System.debug('REQUESTED DATA-----saved!:');        
    }

    /** Save Commission rates and answers */
    @AuraEnabled
    public static void saveCommissions(String rawCommission, String recordId){
        try {
            ProductWrapper c = (ProductWrapper) JSON.deserializeStrict(rawCommission, ProductWrapper.class);
            List<Commission_Question__c> questions = new List<Commission_Question__c>();
            for(Product_Commission__c cm : c.rawCommission) {
                for(Commission_Question__c question : cm.Commission_Questions__r) {
                    questions.add(question);
                }
            }
            OpportunityLineItem oli = [SELECT Id, hasCommissions__c FROM OpportunityLineItem WHERE Id = :recordId];

            oli.hasCommissions__c = true;
            update oli;
            update c.rawCommission;
            update questions;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /** --------------------------------
     *           Utilities Class
     **--------------------------------*/


    /** --------------------------------
     *           Wrapper Class
     **--------------------------------*/
    /** class wrapper */
    public class ProductWrapper {
        List<Product_Commission__c> rawCommission {get; set;}
    }
}