src/objects/compromiso__c.object
<CustomObject>
    <fields>
        <fullName>Oportunidad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Oportunidad</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>compromisos</relationshipLabel>
        <relationshipName>compromisos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PE_DIVISA_Importe__c</fullName>
        <label>Importe</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PE_FM_PRODUCT__c</fullName>
        <formula>PE_SH_PRODUCT__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Producto:</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PE_FOR_Fecha_Vcto__c</fullName>
		<defaultValue>DATETIMEVALUE(DATE( YEAR(DATEVALUE($System.OriginDateTime)), MONTH( DATEVALUE($System.OriginDateTime )) + 2 ,  DAY( DATEVALUE($System.OriginDateTime ))))</defaultValue>
        <label>Fecha vcto</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PE_NUM_Permanencia__c</fullName>
        <label>Permanencia</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PE_NUM_Plazo_Vcto__c</fullName>
        <defaultValue>60</defaultValue>
        <label>Plazo vcto</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>compromiso</label>
    <nameField>
        <label>Nombre de compromiso</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>compromisos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>gipr_Garantia__c</fullName>
        <label>gipr_Garantia</label>
        <type>Picklist</type>
        <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>gipr_Plazo__c</fullName>
        <label>gipr_Plazo</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>gipr_Tipo_Garantia__c</fullName>
        <label>gipr_Tipo_Garantia</label>
        <type>Picklist</type>
        <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>gipr_Periodicidad__c</fullName>
        <label>gipr_Periodicidad</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Product_Gurantee__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GuaranteeType__c</fullName>
        <label>GuaranteeType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Guarantee__c</fullName>
        <label>Guarantee</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Modality__c</fullName>
        <label>Modality</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Product_Gurantees</relationshipLabel>
        <relationshipName>Product_Gurantees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Periodicity__c</fullName>
        <label>Periodicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product_Gurantees</relationshipLabel>
        <relationshipName>Product_Gurantees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>isMaster__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isMaster</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>nGuarantee__c</fullName>
        <label>nGuarantee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product_Gurantee</label>
    <nameField>
        <label>Nombre de Product_Gurantee</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product_Gurantees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Participants__c.object
<CustomObject>
    <fields>
        <fullName>DOI__c</fullName>
        <label>DOI</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marital_Status__c</fullName>
        <label>Marital_Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>N_DOI__c</fullName>
        <label>N_DOI</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Product_Participants</relationshipLabel>
        <relationshipName>Product_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participation__c</fullName>
        <label>Participation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product_Participants</relationshipLabel>
        <relationshipName>Product_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product_Participant</label>
    <nameField>
        <label>Nombre de Product_Participants</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product_Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Product_cls.cls
/*-------------------------------------------------------------------------
 * Name: Product_cls
 * Description : Class to insert a record from Account
 * Created date : May 15 2018
 * Developer name: Isaías Velázquez Cortés Indra(México)
--------------------------------------------------------------------------*/

public with sharing class Product_cls {
	@AuraEnabled public static List<OpportunityLineItem> getIdProductByOpportunity(String IdOpportunity){
		List<OpportunityLineItem> row= [SELECT  Product2Id,gipr_Tipo_Garantia__c,gipr_Garantia__c,PE_DATE_Fecha_cotizacion__c FROM OpportunityLineItem Where OpportunityId=: IdOpportunity LIMIT 1];
		if(!row.isEmpty())
			return row;
		else
			return null;
	}

	@AuraEnabled public static Boolean verifyIfHasQuoted(String IdOpportunity){
		List<OpportunityLineItem> rowOpp=getIdProductByOpportunity(IdOpportunity);
		if(!rowOpp.isEmpty())
		{
			if(rowOpp[0].PE_DATE_Fecha_cotizacion__c!=null && String.valueOf(rowOpp[0].PE_DATE_Fecha_cotizacion__c)!='') return true; else return false;
		}else return false;
	}

	@AuraEnabled public static List<Product_Gurantee__c> getGuaranteeDataByProduct(String IdOpportunity,String IdProduct){	
		List<Product_Gurantee__c> objData= [SELECT Id,GuaranteeType__c,toLabel(Guarantee__c), toLabel(Modality__c), toLabel(Status__c),Term__c, toLabel(Periodicity__c),nGuarantee__c,Amount__c,isMaster__c FROM Product_Gurantee__c Where Product__c=: IdProduct AND Opportunity__c=: IdOpportunity Order by isMaster__c desc];
		return objData;
	}

	@AuraEnabled public static List<Product_Gurantee__c> getGuaranteeDataByProductValues(String PGuaranteeId){	

		List<Product_Gurantee__c> objData= [SELECT Id,GuaranteeType__c,Guarantee__c, Modality__c, Status__c,Term__c, Periodicity__c,nGuarantee__c,Amount__c,isMaster__c FROM Product_Gurantee__c Where Id=: PGuaranteeId];
		return objData;
	}

	@AuraEnabled public static List<Product_Participants__c> getParticipantDataByProduct(String IdOpportunity,String IdProduct){	
		List<Product_Participants__c> objData= [SELECT Id,Name,toLabel(DOI__c), toLabel(Marital_Status__c), toLabel(Participation__c),N_DOI__c,isMaster__c FROM Product_Participants__c Where Product__c=: IdProduct AND Opportunity__c=: IdOpportunity Order by isMaster__c desc];
		return objData;
	}

	@AuraEnabled public static List<Product_Participants__c> getParticipantDataByProductValues(String PParticipantId){	
		List<Product_Participants__c> objData= [SELECT Id,Name,DOI__c, Marital_Status__c, Participation__c,N_DOI__c,isMaster__c FROM Product_Participants__c Where  Id=: PParticipantId];
		return objData;
	}
               
	@AuraEnabled public static List<compromiso__c> getCompromisoDataByProduct(String IdOpportunity){	
		List<compromiso__c> objData= [SELECT PE_FM_PRODUCT__c,PE_DIVISA_Importe__c,PE_NUM_Plazo_Vcto__c,PE_FOR_Fecha_Vcto__c,PE_NUM_Permanencia__c,CurrencyIsoCode FROM compromiso__c Where  Oportunidad__c=:IdOpportunity];
		return objData;
	}

	@AuraEnabled public static List<OpportunityLineItem> getOpportunityLineItemDataByProduct(String IdOpportunity,String IdProduct){	
		List<OpportunityLineItem> objData= [SELECT Product2.Name,Opportunity.Amount,gipr_Plazo__c,toLabel(gipr_Periodicidad__c),PE_POR_TEA_propuesta__c,PE_POR_Spread__c,PE_POR_Comision__c FROM OpportunityLineItem Where OpportunityId=:IdOpportunity and Product2Id=:IdProduct];
		return objData;
	}

	@AuraEnabled public static String getOportunidadSytem(String Filtro) {       
        return Object_Controller.getOportunidadSytem(Filtro);       
    }

	@AuraEnabled public static Boolean deleteGuaranteeDataByProduct(String IdProductGuarantee){
		Product_Gurantee__c objData= [SELECT Id FROM Product_Gurantee__c Where Id=: IdProductGuarantee];
		delete objDAta;
		return true;
	}

	@AuraEnabled public static Boolean deleteParticipantDataByProduct(String IdProductParticipant){
		Product_Participants__c objData= [SELECT Id FROM Product_Participants__c Where Id=: IdProductParticipant];
		delete objDAta;
		return true;
	}

	@AuraEnabled public static Boolean saveGuaranteeDataByProduct(String PGuaranteeId,String IdOpportunity,String IdProuduct,String GuaranteeType,String Guarantee,String Modality,Decimal Amount,String Status,Integer Term,String Periodicity,Integer nGuarantee){
		Product_Gurantee__c row;
		if(PGuaranteeId!=null)		
			row = [SELECT Id,GuaranteeType__c,Guarantee__c, Modality__c, Status__c,Term__c, Periodicity__c,nGuarantee__c,Amount__c FROM Product_Gurantee__c Where Id=: PGuaranteeId];
		else row = new Product_Gurantee__c();

		row.Opportunity__c=IdOpportunity;
		row.Product__c=IdProuduct;
		row.GuaranteeType__c=GuaranteeType;
		row.Guarantee__c=Guarantee;
		row.nGuarantee__c=nGuarantee;
		row.Modality__c=Modality;
		row.Amount__c=Amount;
		row.Status__c=Status;
		row.Term__c=integer.valueOf(Term);
		row.Periodicity__c=Periodicity;
		row.Term__c=Term;

		if(PGuaranteeId!=null) update row; else insert row;	
		return true;
	}


	@AuraEnabled public static Boolean saveParticipantDataByProduct(String PParticipantId,String IdOpportunity,String IdProuduct,String Name,String DOI,String N_DOI,String Participation,String Marital_Status){
		
		Product_Participants__c row;
		if(PParticipantId!=null)		
			row = [SELECT Id,Name,DOI__c, Marital_Status__c, Participation__c,N_DOI__c FROM Product_Participants__c Where Id=:PParticipantId ];
		else row = new Product_Participants__c();

		row.Opportunity__c=IdOpportunity;
		row.Product__c=IdProuduct;
		row.Name=Name;
		row.DOI__c=DOI;
		row.N_DOI__c=N_DOI;
		row.Participation__c=Participation;		
		row.Marital_Status__c=Marital_Status;		

		if(PParticipantId!=null) update row; else insert row;	
		
		return true;
	}

	@AuraEnabled public static String setSanctionPrice(String OpportunityId,String sanAction){
		try
		{
			List<Opportunity> itemOpp= [SELECT Id,opportunity_status_type__c FROM Opportunity WHERE Id=: OpportunityId];
			if(!itemOpp.isEmpty())
			{
				if(sanAction=='btnApprove'){//08
					itemOpp[0].StageName='04';
					itemOpp[0].opportunity_status_type__c='08';

				}
				else if(sanAction=='btnRaise'){//09
					itemOpp[0].StageName='04';
					itemOpp[0].opportunity_status_type__c='09';
				}
				update itemOpp[0];
				return 'true';
			}
			else
			{
				return 'Error';
			}
			
		}
		catch(Dmlexception exp)
		{
			return exp.getMessage();
		}
		
	}

	@AuraEnabled public static String setFormalization(String OpportunityId,String Action,String Body){
		try
		{
			List<Opportunity> itemOpp= [SELECT Id,opportunity_status_type__c,StageName,OwnerId FROM Opportunity WHERE Id=: OpportunityId];
			if(!itemOpp.isEmpty())
			{
				if(Action=='btnApprove'){
                      id id1 = userinfo.getProfileId();
       String prof = [SELECT Name FROM profile WHERE id = :id1 LIMIT 1].Name;
     
        if((prof=='Ejecutivo'&& userinfo.getUserId()==itemOpp[0].OwnerId) || prof=='Administrador del Sistema' || prof=='Migracion'){
            
            
            
            itemOpp[0].IsProcess__c=true;
            update itemOpp[0];   
            itemOpp[0].StageName=label.lblFormalizarEtapa;
            itemOpp[0].opportunity_status_type__c=label.lblFormalizarStatus;          
            FeedItem post = new FeedItem();
            post.ParentId = OpportunityId;
            post.Body = body;
            if(!string.isBlank(Body))
            insert post;
            else{
            itemOpp[0].IsProcess__c=false;
            update itemOpp[0];     
            return label.lblNoCommentsFormalization;
            } 
            }

					
				}
				update itemOpp[0];
                itemOpp[0].IsProcess__c=false;
                update itemOpp[0]; 
				return 'true';
			}
			else
			{
				return 'Error';
			}
			
		}
		catch(Dmlexception exp)
		{
			return exp.getMessage();
		}
		
	}

  	@InvocableMethod(label='Delete Master Guarantee' description='Delete the row from Product_Guarantee')
 	public static void deleteMasterGuarantee(List<OpportunityLineItem> listRow)
    {
        List<Product_Gurantee__c> row =[SELECT Id FROM Product_Gurantee__c WHERE Product__c=: listRow[0].Product2Id and Opportunity__c=: listRow[0].OpportunityId and  isMaster__c=true LIMIT 1];
 		
 		if(!row.isEmpty())
        	delete row;
    }




}