src/objects/compromiso__c.object
<CustomObject>
	<fields>
        <fullName>Product_relate__c</fullName>
        <label>Producto</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>P. Comercial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>compromisos</relationshipLabel>
        <relationshipName>compromisos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Oportunidad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Oportunidad</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>compromisos</relationshipLabel>
        <relationshipName>compromisos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PE_DIVISA_Importe__c</fullName>
        <label>Importe</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PE_FOR_Fecha_Vcto__c</fullName>
		<defaultValue>DATETIMEVALUE(DATE( YEAR(DATEVALUE($System.OriginDateTime)), MONTH( DATEVALUE($System.OriginDateTime )) + 2 ,  DAY( DATEVALUE($System.OriginDateTime ))))</defaultValue>
        <label>Fecha vcto</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PE_NUM_Permanencia__c</fullName>
        <label>Permanencia</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PE_NUM_Plazo_Vcto__c</fullName>
        <defaultValue>60</defaultValue>
        <label>Plazo vcto</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>compromiso</label>
    <nameField>
        <label>Nombre de compromiso</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>compromisos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/dwp_cvad__Action_Audit__c.object
<CustomObject>
    <description>Stores the basic action audit information</description>
    <label>Action Audit</label>
    <nameField>
        <displayFormat>AA-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Audits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
<fields>
        <fullName>opportunity_status_type__c</fullName>
        <description>Status of an opportunity</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
	<fields>
        <fullName>Type_of_quote__c</fullName>
        <label>Tipo de cotización</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Type_of_quote_stock</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Type_of_quote_stock.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>COTIZADOR</fullName>
    </customValue>
    <customValue>
        <fullName>Tarifario</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
    </customValue>
    <description>Valores del tipo de cotizacion</description>
    <masterLabel>Type of quote</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/Object_Controller.cls
public with sharing class Object_Controller {
    @AuraEnabled
    public static List<compromiso__c> getContacts(String Filtro) {
        List<compromiso__c> contacts =
            [SELECT Id, PE_DIVISA_Importe__c,PE_NUM_Plazo_Vcto__c,Product_relate__c,
             PE_FOR_Fecha_Vcto__c, PE_NUM_Permanencia__c, CurrencyIsoCode FROM compromiso__c
             where Oportunidad__c =:Filtro and Oportunidad__c !='' order by createdDate desc];
        return contacts;
    }
    @AuraEnabled
    public static Id getOportunityLineItemID(String Filtro) {
        ID OpLiItem =
            [SELECT Id FROM OpportunityLineItem
             where OpportunityId =:Filtro][0].Id;
        return OpLiItem;
    }

    @AuraEnabled
    public static String getOportunityModality(String Filtro) {
        String Modality = [SELECT Modality__c FROM Opportunity
             WHERE Id =:Filtro LIMIT 1].Modality__c;
        return Modality;
    }


    @AuraEnabled
    public static String getOportunidadSytem(String Filtro) {
        String OpLiItem =
            [SELECT Id, Product2.Type_of_quote__c  FROM OpportunityLineItem
             where OpportunityId =:Filtro][0].Product2.Type_of_quote__c;
        return OpLiItem;

    }
    @AuraEnabled
    public static list<compromiso__c> getCompromisosSytem(String Filtro) {
        list<compromiso__c> OpLiItem =
            [SELECT Id, OwnerId, IsDeleted, Name, CurrencyIsoCode, Product_relate__c,
             CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp,
             LastActivityDate,  PE_DIVISA_Importe__c,
             PE_NUM_Plazo_Vcto__c, PE_NUM_Permanencia__c, PE_FOR_Fecha_Vcto__c, Client__c,
             Oportunidad__c FROM compromiso__c where Oportunidad__c =:Filtro order by createdDate desc limit 5];
        return OpLiItem;
    }


    @AuraEnabled
    public static void  setSanction(String Idopp){

    Opportunity op  = new Opportunity();
    Map<string,string> MapStatus = getMapOppStatus();
    Task t = [SELECT Id,Subject,Status FROM Task WHERE whatId = : idopp ORDER BY CreatedDate DESC];
    op = [SELECT StageName,Modality__c,opportunity_status_type__c FROM Opportunity WHERE ID =:Idopp];
    op.opportunity_status_type__c='10';
    String[] valStatus = t.Subject.split('##');
    String filter = '%'+valStatus[0]+'%';
    Integer totalTrace;
    update op;
    AggregateResult[] countTrace  = [SELECT Count(Id) total FROM dwp_cvad__Action_Audit__c];
    new OpportunityTraceability_cls().addOpportunityTraceability(valStatus[1],'Código SIO:' +valStatus[0],'Opportunity',op.Id,'Aprove',('AT-'+totalTrace),UserInfo.getUserId(),'embedded',1,true);

    }
    private static  Map<string,string> getMapOppStatus(){
       Map<string,string> MapStatus = new Map<string,string>();
       Schema.DescribeFieldResult fieldResult = Opportunity.opportunity_status_type__c.getDescribe();
       List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
       for( Schema.PicklistEntry f : ple)
       {
               MapStatus.put(f.getLabel(), f.getValue());
       }
       return MapStatus;


    }

}