src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>prof_position_type__c</fullName>
        <label>Position</label>
        <picklist>
            <picklistValues>
                <fullName>ACCIONISTA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADMINISTRADOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APODERADO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASISTENTE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DIRECTORIO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE COMERCIAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE ADMINISTRACION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE ADMINISTRACION Y FINANZAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE CONTABILIDAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE FINANZAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE OPERACIONES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE DE RRHH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GERENTE GENERAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JEFE DE ADMINISTRACIÓN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JEFE DE ADMINISTRACION Y FINANZAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JEFE DE CONTABILIDAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JEFE DE FINANZAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JEFE DE TESORERIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTROS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRESIDENTE DE DIRECTORIO</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>		
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACCIONISTA</fullName>
                </value>
                <value>
                    <fullName>PRESIDENTE DE DIRECTORIO</fullName>
                </value>
                <value>
                    <fullName>APODERADO</fullName>
                </value>
                <value>
                    <fullName>DIRECTORIO</fullName>
                </value>
                <value>
                    <fullName>GERENTE GENERAL</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE FINANZAS</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE ADMINISTRACION Y FINANZAS</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE ADMINISTRACION</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE RRHH</fullName>
                </value>
                <value>
                    <fullName>GERENTE COMERCIAL</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE OPERACIONES</fullName>
                </value>
                <value>
                    <fullName>GERENTE DE CONTABILIDAD</fullName>
                </value>
                <value>
                    <fullName>JEFE DE FINANZAS</fullName>
                </value>
                <value>
                    <fullName>JEFE DE TESORERIA</fullName>
                </value>
                <value>
                    <fullName>JEFE DE ADMINISTRACION Y FINANZAS</fullName>
                </value>
                <value>
                    <fullName>JEFE DE ADMINISTRACIÓN</fullName>
                </value>
                <value>
                    <fullName>JEFE DE CONTABILIDAD</fullName>
                </value>
                <value>
                    <fullName>ADMINISTRADOR</fullName>
                </value>
                <value>
                    <fullName>ASISTENTE</fullName>
                </value>
                <value>
                    <fullName>OTROS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/dwp_kitv__Visit_Contact__c.object
<CustomObject>
    <description>Object to relate a contact with a visit. These records will appear on related list of Visit object.</description>
    <fields>
        <fullName>contact_prof_position_type__c</fullName>
        <formula>TEXT(dwp_kitv__contact_id__r.prof_position_type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact position</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dwp_kitv__contact_called_type__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to determinate if this contact has been arranged.</description>
        <label>Arranged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>dwp_kitv__contact_email_desc__c</fullName>
        <description>Retrieve the contact&apos;s email</description>
        <formula>dwp_kitv__contact_id__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dwp_kitv__contact_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relation with a contact record.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Visit Contacts</relationshipLabel>
        <relationshipName>Visit_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>dwp_kitv__visit_id__c</fullName>
        <description>Relation with a visit record.</description>
        <label>Visit</label>
        <referenceTo>dwp_kitv__Visit__c</referenceTo>
        <relationshipLabel>Visit Contacts</relationshipLabel>
        <relationshipName>Visit_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visit Contact</label>
    <nameField>
        <displayFormat>VC-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/dwp_kitv__Visit_Management_Team__c.object
<CustomObject>
    <description>Object to relate users with visits</description>
    <fields>
        <fullName>dwp_kitv__contact_email_desc__c</fullName>
        <description>User email</description>
        <formula>dwp_kitv__user_id__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dwp_kitv__user_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User visit</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Visit_Management_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>dwp_kitv__visit_id__c</fullName>
        <description>Parent Object</description>
        <label>Visit</label>
        <referenceTo>dwp_kitv__Visit__c</referenceTo>
        <relationshipLabel>Visit Management Teams</relationshipLabel>
        <relationshipName>Visit_Management_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>user_prof_position_type__c</fullName>
        <formula>dwp_kitv__user_id__r.prof_position_type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>User position</label>
        <type>Text</type>
    </fields>
    <label>Visit Management Team</label>
    <nameField>
        <displayFormat>VM-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Management Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/dwp_kitv__Visit_Topic__c.object
<CustomObject>
    <description>Topics about visits</description>
    <fields>
        <fullName>dwp_kitv__opportunity_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Opportunity</description>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.IsClosed</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Visit Topics</relationshipLabel>
        <relationshipName>Visit_Topics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>dwp_kitv__topic_desc__c</fullName>
        <description>Topic description</description>
        <label>Topic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dwp_kitv__visit_done_type__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if the visit is complete</description>
        <label>Done</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>dwp_kitv__visit_id__c</fullName>
        <description>Parent Object</description>
        <label>Visit</label>
        <referenceTo>dwp_kitv__Visit__c</referenceTo>
        <relationshipLabel>Visit Topics</relationshipLabel>
        <relationshipName>Visit_Topics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visit Topic</label>
    <nameField>
        <displayFormat>VT-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Topics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>prof_position_type__c</fullName>
        <description>Is the name of Position</description>
        <label>Position</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MinutaWrap.cls
/* -------------------------------------------------------------------
* Jose Rodriguez               07/08/2019          Original version.<p />
*
* @author Jose Rodriguez
*/
public without sharing virtual class MinutaWrap { 

    Public static list<dwp_kitv__Visit_Topic__c> visitTopic {get;set;}
    Public static list<dwp_kitv__Visit_Contact__c> visitContacsAux {get;set;}
    Public static list<dwp_kitv__Visit_Contact__c> visitContacs {get;set;}
    Public static list<dwp_kitv__Visit_Management_Team__c> visitManagementTeam {get;set;}
    Public static list<Task> visitAgreements {get;set;}
	Public static list<User> usuarios {get;set;}
    public static String urlLogo {get; set;}
    public static String urlLogoWhite {get; set;}
    public static String urlLogoFacebook {get; set;}
    public static String urlLogoTwiter {get; set;}
    public static String urlStyle {get; set;}
   
    /*Method to set values*/
    public static string setValues(String visitId) {
        try {
            visitTopic = [Select dwp_kitv__opportunity_id__c,dwp_kitv__opportunity_id__r.name, dwp_kitv__topic_desc__c, 
                          dwp_kitv__visit_done_type__c from dwp_kitv__Visit_Topic__c where dwp_kitv__visit_id__c =:visitId];
            visitContacsAux = new list<dwp_kitv__Visit_Contact__c>();
            visitContacs = new list<dwp_kitv__Visit_Contact__c>();
			visitContacsAux = [Select dwp_kitv__contact_id__c, dwp_kitv__contact_id__r.name, dwp_kitv__contact_email_desc__c, contact_prof_position_type__c, 
                            dwp_kitv__contact_called_type__c from dwp_kitv__Visit_Contact__c where dwp_kitv__visit_id__c =:visitId ];
            for(dwp_kitv__Visit_Contact__c c:visitContacsAux) {
                if(c.dwp_kitv__contact_email_desc__c!='') {
                    visitContacs.add(c);
                }
            }
            System.debug('--Contactos-->'+ visitContacs);
        	visitManagementTeam = [Select dwp_kitv__user_id__c, dwp_kitv__user_id__r.name, 
                                   dwp_kitv__contact_email_desc__c, user_prof_position_type__c from dwp_kitv__Visit_Management_Team__c 
                                   where dwp_kitv__visit_id__c =:visitId and dwp_kitv__contact_email_desc__c !='' and  dwp_owner_visit__c=false];
            Final dwp_kitv__Visit_Management_Team__c owner = [SELECT id, dwp_kitv__user_id__c FROM dwp_kitv__Visit_Management_Team__c WHERE dwp_kitv__visit_id__c=:visitId AND 
                                                       dwp_owner_visit__c=true limit 1];
            usuarios =  new list<User>();
            Final User ownerUser = [select id, name, email, prof_position_type__c from User where id =:owner.dwp_kitv__user_id__c limit 1];
            usuarios.add(ownerUser);
            Set<String> strUserId = new Set<String>();
            for(dwp_kitv__Visit_Management_Team__c vm: visitManagementTeam) {
                strUserId.add(vm.dwp_kitv__user_id__c);
            }
            usuarios.addAll([select id, name, email, prof_position_type__c from User where id IN: strUserId]);
            System.debug('--usuarios-->'+ usuarios);
            visitAgreements = [Select id,ActivityDate,Subject,Status,Owner.Name, RecordType.Name  from Task  where RecordType.Name ='Agreement' and dwp_kitv__visit_id__c =: visitId]; 
            Final List<Document> lstMembrete = [SELECT Id FROM Document WHERE DeveloperName = 'Logo_BBVA'];
            Final List<Document> lstMembreteWhite = [SELECT Id FROM Document WHERE DeveloperName = 'Logo_BBVA_white'];
            Final List<Document> lstLogoFace = [SELECT Id FROM Document WHERE DeveloperName = 'facebook_logo'];
            Final List<Document> lstLogoTwiter = [SELECT Id FROM Document WHERE DeveloperName = 'twitter_logo'];
            Final String sfdcBaseURL = URL.getSalesforceBaseUrl().toExternalForm() + '/servlet/servlet.ImageServer?id=';
            String param = '&oid=';
            urlLogo = sfdcBaseURL+lstMembrete[0].Id+param+UserInfo.getOrganizationId();
            urlLogoFacebook = sfdcBaseURL+lstLogoFace[0].Id+param+UserInfo.getOrganizationId();
            urlLogoTwiter = sfdcBaseURL+lstLogoTwiter[0].Id+param+UserInfo.getOrganizationId();
            urlLogoWhite = sfdcBaseURL+lstMembreteWhite[0].Id+param+UserInfo.getOrganizationId();
        } catch(System.Exception e) {
            system.debug('Exception : '+e.getMessage());
        }
        return 'SUCCESS';
    }
}