src/objects/dwp_cvad__Action_Audit__c.object
<CustomObject>
    <description>Stores the basic action audit information</description>
    <fields>
        <fullName>action_audit_email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Email SIO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>action_opp_sio_code__c</fullName>
        <label>SIO Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dwp_cvad__action_audit_date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>Timestamp of the action audited.</description>
        <inlineHelpText>Timestamp of the action audited.</inlineHelpText>
        <label>Timestamp</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dwp_cvad__action_audit_name__c</fullName>
        <description>Brief description of the action audited.</description>
        <inlineHelpText>Brief description of the action audited.</inlineHelpText>
        <label>Action Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dwp_cvad__action_audit_object_api_name__c</fullName>
        <description>Object API Name of the record to which the action audited refers to.</description>
        <inlineHelpText>Object API Name of the record to which the action audited refers to.</inlineHelpText>
        <label>Object API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dwp_cvad__action_audit_record_id__c</fullName>
        <description>Id of the record to which the action audited refers to.</description>
        <inlineHelpText>Id of the record to which the action audited refers to.</inlineHelpText>
        <label>Record Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dwp_cvad__action_audit_style__c</fullName>
        <description>Audited action visualization style.</description>
        <inlineHelpText>Audited action visualization style.</inlineHelpText>
        <label>Style</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>approve</fullName>
                </value>
                <value>
                    <fullName>approveTop</fullName>
                </value>
                <value>
                    <fullName>deny</fullName>
                </value>
                <value>
                    <fullName>elevate</fullName>
                </value>
                <value>
                    <fullName>elevateTop</fullName>
                </value>
                <value>
                    <fullName>infoAlt</fullName>
                </value>
                <value>
                    <fullName>quickText</fullName>
                </value>
                <value>
                    <fullName>restudy</fullName>
                </value>
                <value>
                    <fullName>sendBack</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>dwp_cvad__action_audit_type__c</fullName>
        <description>Type of the action audited.</description>
        <inlineHelpText>Type of the action audited.</inlineHelpText>
        <label>Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dwp_cvad__action_audit_user_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relation with the user that performed the action audited.</description>
        <inlineHelpText>Relation with the user that performed the action audited.</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Action_Audits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>dwp_cvad__audit_audit_comments__c</fullName>
        <description>Comments to describe the action audited.</description>
        <inlineHelpText>Comments to describe the action audited.</inlineHelpText>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <label>Action Audit</label>
    <nameField>
        <displayFormat>AA-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Audits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/dwp_cvad__Action_Audit_Detail__c.object
<CustomObject>
    <description>Stores the details of the audited action.</description>
    <fields>
        <fullName>dwp_cvad__action_audit_detail_content__c</fullName>
        <description>Contains the action audit detail content.</description>
        <inlineHelpText>Contains the action audit detail content.</inlineHelpText>
        <label>Content</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>dwp_cvad__action_audit_detail_content_format__c</fullName>
        <defaultValue>&apos;HTML&apos;</defaultValue>
        <description>Specifies the action audit detail contact format.</description>
        <inlineHelpText>Specifies the action audit detail contact format.</inlineHelpText>
        <label>Content Format</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>HTML</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>dwp_cvad__action_audit_detail_display_order__c</fullName>
        <description>Specifies the order in which the action audit detail will be displayed within it´s display type grouping.</description>
        <inlineHelpText>Specifies the order in which the action audit detail will be displayed within it´s display type grouping.</inlineHelpText>
        <label>Display Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>dwp_cvad__action_audit_detail_display_title__c</fullName>
        <description>Specifies the link´s text used on the action audit details with type Link.</description>
        <inlineHelpText>Specifies the link´s text used on the action audit details with type Link.</inlineHelpText>
        <label>Display Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dwp_cvad__action_audit_detail_display_type__c</fullName>
        <description>Specifies if the action audit detail content will be displayed embedded or in a pop-up window.</description>
        <inlineHelpText>Specifies if the action audit detail content will be displayed embedded or in a pop-up window.</inlineHelpText>
        <label>Display Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Embedded</fullName>
                </value>
                <value>
                    <fullName>Link</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>dwp_cvad__action_audit_id__c</fullName> 
        <description>Relation with the action audited.</description>
        <inlineHelpText>Relation with the action audited.</inlineHelpText>
        <label>Action Audit</label>
        <referenceTo>dwp_cvad__Action_Audit__c</referenceTo>
        <relationshipLabel>Action Audit Details</relationshipLabel>
        <relationshipName>Action_Audit_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Action Audit Detail</label>
    <nameField>
        <displayFormat>AAD-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Audit Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
<fields>
        <fullName>opportunity_status_type__c</fullName>
        <description>Status of an opportunity</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isProcess__c</fullName>
        <defaultValue>false</defaultValue>
        <description>activated by Process</description>
        <label>isProcess</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity_Solution_Commitment__c.object
<CustomObject>
    <fields>
        <fullName>opp_soln_comt_expiry_days_number__c</fullName>
        <label>Expiry days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>opp_soln_comt_stay_days_number__c</fullName>
        <label>Stay days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>opp_solution_commitment_amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>opp_solution_commitment_id__c</fullName>
        <label>Identifier</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>opp_solution_commitment_number__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>opp_solution_comt_product_name__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>opp_solution_id__c</fullName>
        <label>Opportunity Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>opportunity_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Solution Commitments</relationshipLabel>
        <relationshipName>Opportunity_Solution_Commitments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>price_quote_date__c</fullName>
        <label>Price quote date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>added_to_price_quotation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Added to price quotation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>price_quotation_id__c</fullName>
        <label>Price quotation id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>price_quotation_method__c</fullName>
        <label>Price quotation method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Compromiso Precio</label>
    <nameField>
        <displayFormat>OSC-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compromisos Precio</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>minimun_apr_per__c</fullName>
        <label>Minimun APR (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>price_quote_date__c</fullName>
        <label>Last price quote date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>price_quote_id__c</fullName>
        <label>Cotiza Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>proposed_apr_per__c</fullName>
        <label>Proposed APR (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>suggested_apr_per__c</fullName>
        <label>Suggested APR (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
	<fields>
        <fullName>price_operation_id__c</fullName>
        <label>Price operation Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/BE_SanctionUseQuotation_Ctr.cls
/**
   ----------------------------------------------------------------------------------------------------
   @Name <BE_SanctionUseQuotation_Ctr>
   @Author Martin Alejandro Mori Chavez (martin.mori.contractor@bbva.com)
   @Date 2020-11-06
   @Description Class controller for BE_SanctionUseQuotation_cmp
   @Changes
    Date        Author   Email                  			Type		Description
    2020-11-06  MAMCH    martin.mori.contractor@bbva.com    Creation
   ----------------------------------------------------------------------------------------------------
 */
public with sharing class BE_SanctionUseQuotation_Ctr {    
    /**
	   @Description method used to return comments of audit
	   @param  String recordId id of record related of audit
	   @return String with comments of last audit
	 */
    @AuraEnabled
    public static String getComments(String recordId) {
        try {
            String comments = '';
            for(dwp_cvad__Action_Audit_Detail__c auditDet : [SELECT Id, dwp_cvad__action_audit_detail_content__c, dwp_cvad__action_audit_id__r.dwp_cvad__action_audit_record_id__c FROM dwp_cvad__Action_Audit_Detail__c WHERE dwp_cvad__action_audit_id__r.dwp_cvad__action_audit_record_id__c = :recordId ORDER BY dwp_cvad__action_audit_id__r.CreatedDate DESC LIMIT 1]) {
                comments = auditDet.dwp_cvad__action_audit_detail_content__c;
                comments = comments.substringAfterLast('>Comentarios</h3>');
                comments = comments.substringBefore('</span>');
                comments = comments.stripHtmlTags();
            }
            return comments;
        } catch(Exception e) {
            return null;
        }
    }
    
    /**
	   @Description method used to set opportunity values when selected current quote
	   @param  String oppId id of opportunity
	   @param  String idOliSelected of OpportunityLineItem that has quotation
	   @return Map<String, Object> with result of operation
	 */
    @auraenabled
	public static Map<String, Object> useQuotationPrice(String oppId, String idOliSelected) {
        Final Map<String, Object> mapReturn = new Map<String, Object>();
		mapReturn.put('isOk', true);
        Savepoint sp = Database.setSavepoint();
		try {
			Final opportunity opp  = [SELECT Id FROM Opportunity WHERE ID =:oppId];
			opp.isProcess__c = true;
			opp.opportunity_status_type__c  = '11';
            opp.BE_UseApprovedQuote__c = true;
            update opp;
            
            Final List<OpportunityLineItem> olis = [SELECT Id FROM OpportunityLineItem WHERE OpportunityId = :oppId LIMIT 1];
            Final List<OpportunityLineItem> oliSelected = [SELECT Id, OpportunityId, Opportunity.Account.Name, price_quote_date__c, suggested_apr_per__c, validityDate__c, proposed_apr_per__c, minimun_apr_per__c, price_quote_id__c, Assigned_analyst__c, price_operation_id__c FROM OpportunityLineItem WHERE Id = :idOliSelected LIMIT 1];
            olis[0].price_quote_date__c = oliSelected[0].price_quote_date__c;
            olis[0].suggested_apr_per__c = oliSelected[0].suggested_apr_per__c;
            olis[0].validityDate__c = oliSelected[0].validityDate__c;
            olis[0].proposed_apr_per__c = oliSelected[0].proposed_apr_per__c;
            olis[0].minimun_apr_per__c = oliSelected[0].minimun_apr_per__c;
            olis[0].price_quote_id__c = oliSelected[0].price_quote_id__c;
            olis[0].Assigned_analyst__c = oliSelected[0].Assigned_analyst__c;
            olis[0].price_operation_id__c = oliSelected[0].price_operation_id__c;
            update olis;
            
            Final List<Opportunity_Solution_Commitment__c> commitments = new List<Opportunity_Solution_Commitment__c>();
            for(Opportunity_Solution_Commitment__c commitment : [SELECT added_to_price_quotation__c, opp_solution_commitment_amount__c, price_quote_date__c, opportunity_id__c, opp_soln_comt_expiry_days_number__c, opp_soln_comt_stay_days_number__c, opp_solution_commitment_number__c, CurrencyIsoCode, opp_solution_comt_product_name__c, opp_solution_id__c, price_quotation_id__c, price_quotation_method__c, opp_solution_commitment_id__c FROM Opportunity_Solution_Commitment__c WHERE opportunity_id__c = :oliSelected[0].OpportunityId]) {
                Opportunity_Solution_Commitment__c oppSolCommitment = commitment.clone();
                oppSolCommitment.opportunity_id__c = oppId;
                oppSolCommitment.opp_solution_id__c = olis[0].Id;
                commitments.add(oppSolCommitment);
            }
            if(!commitments.isEmpty()) {
                insert commitments;
            }
            
            Final List<dwp_cvad__Action_Audit__c> audits = new List<dwp_cvad__Action_Audit__c>();
            Final List<dwp_cvad__Action_Audit__c> auditExist = [SELECT action_audit_email__c, dwp_cvad__action_audit_date__c, dwp_cvad__action_audit_user_id__c, dwp_cvad__action_audit_style__c, dwp_cvad__audit_audit_comments__c, dwp_cvad__action_audit_name__c, dwp_cvad__action_audit_object_api_name__c, dwp_cvad__action_audit_record_id__c, action_opp_sio_code__c, dwp_cvad__action_audit_type__c FROM dwp_cvad__Action_Audit__c WHERE dwp_cvad__action_audit_record_id__c = :oliSelected[0].OpportunityId ORDER BY CreatedDate DESC LIMIT 1];
            if(!auditExist.isEmpty()) {
                for(dwp_cvad__Action_Audit__c audit : auditExist) {
                    dwp_cvad__Action_Audit__c auditClone = audit.clone();
                    auditClone.dwp_cvad__action_audit_name__c = label.PriceApprovalUsingQuote;
                    auditClone.dwp_cvad__action_audit_record_id__c = oppId;
                    audits.add(auditClone);
                }
                if(!audits.isEmpty()) {
                    insert audits;
                }
                
                Final List<dwp_cvad__Action_Audit_Detail__c> auditDetails = new List<dwp_cvad__Action_Audit_Detail__c>();
                for(dwp_cvad__Action_Audit_Detail__c detail : [SELECT dwp_cvad__action_audit_detail_content__c, dwp_cvad__action_audit_detail_display_order__c, dwp_cvad__action_audit_detail_content_format__c, CurrencyIsoCode, dwp_cvad__action_audit_detail_display_type__c, dwp_cvad__action_audit_detail_display_title__c FROM dwp_cvad__Action_Audit_Detail__c WHERE dwp_cvad__action_audit_id__c = :auditExist[0].Id]) {
                    dwp_cvad__Action_Audit_Detail__c detailClone = detail.clone();
                    detailClone.dwp_cvad__action_audit_id__c = audits[0].Id;
                    auditDetails.add(detailClone);
                }
                if(!auditDetails.isEmpty()) {
                    insert auditDetails;
                }
            }
            
            Final String namePDF = oliSelected[0].price_quote_id__c + ' - ' + oliSelected[0].Opportunity.Account.Name;
            Final List<ContentDocumentLink> ltsCDL = [SELECT Id, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :oliSelected[0].OpportunityId AND ContentDocument.Title =:namePDF AND ContentDocument.FileType = 'pdf'];
            if(!ltsCDL.isEmpty()) {
                Final Id conDoc = ltsCDL[0].ContentDocumentId;
                Final ContentDocumentLink conDocLink = New ContentDocumentLink();
                conDocLink.LinkedEntityId = oppId;
                conDocLink.ContentDocumentId = conDoc;
                conDocLink.shareType = 'V';
                insert conDocLink;
            }
            
			return mapReturn;
		} catch(Exception e) {
            Database.rollback(sp);
			mapReturn.put('isOk', false);
			mapReturn.put('errorMessage', e.getMessage());
            return mapReturn;
		}
	}
}