src/objects/dwp_kitv__Visit__c.object
<CustomObject>
    <description>Main object to manage visits</description>
    <fields>
        <fullName>dwp_kitv__visit_status_type__c</fullName>
        <description>Status visit</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>Arranged</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>Arranged - Pending Updates</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <label>Visit Completed - Pending Feedback</label>
                </value>
                <value>
                    <fullName>05</fullName>
                    <label>Visit Completed - Minute Sent</label>
                </value>
                <value>
                    <fullName>06</fullName>
                    <label>Finalized</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>start_date_calculated__c</fullName>
        <formula>dwp_kitv__visit_start_date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Date Calculated</label>
        <type>Date</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/dwp_kitv__Visit_Management_Team__c.object
<CustomObject>
    <description>Object to relate users with visits</description>
    <fields>
        <fullName>dwp_kitv__user_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User visit</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Visit_Management_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>dwp_kitv__visit_id__c</fullName>
        <description>Parent Object</description>
        <label>Visit</label>
        <referenceTo>dwp_kitv__Visit__c</referenceTo>
        <relationshipLabel>Visit Management Teams</relationshipLabel>
        <relationshipName>Visit_Management_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visit Management Team</label>
    <nameField>
        <displayFormat>VM-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Management Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/slmt__Sales_Meeting__c.object
<CustomObject>
    <description>Storing all the planned meetings for each responsible, in addition to the planned date and time, the collaborator and the type.</description>
    <fields>
        <fullName>Collaborator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collaborator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Meetings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>slmt__management_plan_meeting_date__c</fullName>
        <description>The day the meeting is scheduled.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The day the meeting is scheduled.</inlineHelpText>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Sales Meeting</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Meetings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BE_SM_Visit_helper.cls
/**
   -------------------------------------------------------------------------------------------------
   @Name BE_SM_Visit_helper
   @Author Martin Alejandro Mori Chavez (martin.mori.contractor@bbva.com)
   @Date 2020-11-11
   @Description
   @Changes
   Date        Author   Email                  				Type
   2020-11-11  MAMCH    martin.mori.contractor@bbva.com    	Creation
   -------------------------------------------------------------------------------------------------
 */
public without sharing class BE_SM_Visit_helper {
    /*
	 * @Description method BE_SM_Opportunity_helper
	 */
    private BE_SM_Visit_helper() {}

    /*
	 * @Description method getSMPlanningVisits
	 */
    public static BE_SingleRelatedListCRUD_Cls.Response getSMPlanningVisits(Set<String> setStatus, Map<String,Object> params) {
        BE_SingleRelatedListCRUD_Cls.Response response = new BE_SingleRelatedListCRUD_Cls.Response(true, '');
        Final slmt__Sales_Meeting__c salesMeeting = [SELECT slmt__management_plan_meeting_date__c, Collaborator__c 
                                                    FROM slmt__Sales_Meeting__c WHERE Id=:(String)params.get('recordId')];
        Final Date initDate = Date.newInstance(salesMeeting.slmt__management_plan_meeting_date__c.year(), 
                                               salesMeeting.slmt__management_plan_meeting_date__c.month(), 1);
        Final Integer numberOfDays = Date.daysInMonth(initDate.year(), initDate.month());
		Final Date lastDate = Date.newInstance(initDate.year(), initDate.month(), numberOfDays);
        Final Set<Id> setIdsVisit = getVisitIds(salesMeeting.Collaborator__c, setStatus, initDate, lastDate);
        if(!setIdsVisit.isEmpty()) {
            response = getVisits(setIdsVisit, params);
        }
        return response;
    }
    
    /*
	 * @Description method getSMRealizedVisits
	 */
    public static BE_SingleRelatedListCRUD_Cls.Response getSMRealizedVisits(Set<String> setStatus, Map<String,Object> params) {
        BE_SingleRelatedListCRUD_Cls.Response response = new BE_SingleRelatedListCRUD_Cls.Response(true, '');
        Final slmt__Sales_Meeting__c salesMeeting = [SELECT slmt__management_plan_meeting_date__c, Collaborator__c 
                                                    FROM slmt__Sales_Meeting__c WHERE Id=:(String)params.get('recordId')];
        Final Date initDate = salesMeeting.slmt__management_plan_meeting_date__c.addDays(-30);
        Final Set<Id> setIdsVisit = getVisitIds(salesMeeting.Collaborator__c, setStatus, initDate, salesMeeting.slmt__management_plan_meeting_date__c);
        if(!setIdsVisit.isEmpty()) {
            response = getVisits(setIdsVisit, params);
        }
        return response;
    }

    /*
	 * @Description method getVisitIds
	 */
    private static Set<Id> getVisitIds(Id collaborator, Set<String> setStages, Date initDate, Date lastDate) {
        Final Set<Id> setIdsVisit = new Set<Id>();
        for(dwp_kitv__Visit_Management_Team__c vTeam : [SELECT Id, dwp_kitv__visit_id__c FROM dwp_kitv__Visit_Management_Team__c  WHERE dwp_kitv__visit_id__r.dwp_kitv__visit_status_type__c IN: setStages 
                                                        AND dwp_kitv__user_id__c = :collaborator AND dwp_kitv__visit_id__r.start_date_calculated__c >= :initDate AND dwp_kitv__visit_id__r.start_date_calculated__c <= :lastDate]) {
            setIdsVisit.add(vTeam.dwp_kitv__visit_id__c);
        }
        return setIdsVisit;
    }

    /*
	 * @Description method getVisits
	 */
    public static BE_SingleRelatedListCRUD_Cls.Response getVisits(Set<Id> setIds, Map<String, Object> params) {
        Final BE_SingleRelatedListCRUD_Cls.Response response = new BE_SingleRelatedListCRUD_Cls.Response();
        Final String query = 'SELECT Id, '+ String.escapeSingleQuotes((String)params.get('sObjFields'))+ ' FROM '+ String.escapeSingleQuotes((String)params.get('sObjName')) + ' WHERE Id IN:setIds';
        response.data = Database.query(query);
        response.isSuccess = true;
        return response;
    }
}