src/objects/dwp_frct__management_plan__c.object
<CustomObject>
    <description>Object to manage plans</description>
    <fields>
        <fullName>dwp_frct__management_plan_end_date__c</fullName>
        <description>End Date plan</description>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dwp_frct__management_plan_stage_type__c</fullName>
        <description>Stages of the plan.</description>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>dwp_frct__management_plan_start_date__c</fullName>
        <description>Start Date plan</description>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <label>Management Plan</label>
    <nameField>
        <label>Management Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Management_Plan_Trigger_Test.cls
/** @Name <Management_Plan_Trigger_Test>
   @Date 09-Septiembre 2021
   Date        Author   Email                  				Type
   2021-09-09  JAAA		jair.anton.contractor@bbva.com		Update test
 */

@isTest
public class Management_Plan_Trigger_Test {
	
	/* Test for handler */
	@isTest
	static void validarTrigger() {
		Test.startTest();
		dwp_frct__management_plan__c rowMGP = new dwp_frct__management_plan__c();
		rowMGP.Name = 'Mi Plan 01';
		rowMGP.dwp_frct__management_plan_start_date__c = Date.today();
		rowMGP.dwp_frct__management_plan_end_date__c = Date.today().addMonths(1);
		insert rowMGP;
		rowMGP.dwp_frct__management_plan_stage_type__c = '03';
		update rowMGP;
		System.assert (true, 'This Works!');
		Test.stopTest();
	}
}