src/objects/dwp_kitv__Visit__c.object
<CustomObject>
    <description>Main object to manage visits</description>
    <fields>
        <fullName>dwp_kitv__account_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account record related to this visit.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>dwp_kitv__visit_duration_number__c</fullName>
        <description>Time in minutes it takes to make the visit. The first hour will be intervals about 15 minutes, then 30 minutes intervals.</description>
        <inlineHelpText>Seleccione la duración en minutos</inlineHelpText>
        <label>Duration</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>120</fullName>
                </value>
                <value>
                    <fullName>150</fullName>
                </value>
                <value>
                    <fullName>180</fullName>
                </value>
                <value>
                    <fullName>210</fullName>
                </value>
                <value>
                    <fullName>240</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>dwp_kitv__visit_start_date__c</fullName>
        <description>Field to set the start date time of the visit.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dwp_kitv__visit_status_type__c</fullName>
        <description>Status visit</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>Arranged</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>Arranged - Pending Updates</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <label>Visit Completed - Pending Feedback</label>
                </value>
                <value>
                    <fullName>05</fullName>
                    <label>Visit Completed - Minute Sent</label>
                </value>
                <value>
                    <fullName>06</fullName>
                    <label>Finalized</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Visit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/dwp_kitv__Visit_Contact__c.object
<CustomObject>
    <description>Object to relate a contact with a visit. These records will appear on related list of Visit object.</description>
    <fields>
        <fullName>dwp_kitv__contact_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relation with a contact record.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Visit Contacts</relationshipLabel>
        <relationshipName>Visit_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>dwp_kitv__visit_id__c</fullName>
        <description>Relation with a visit record.</description>
        <label>Visit</label>
        <referenceTo>dwp_kitv__Visit__c</referenceTo>
        <relationshipLabel>Visit Contacts</relationshipLabel>
        <relationshipName>Visit_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visit Contact</label>
    <nameField>
        <displayFormat>VC-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/dwp_kitv__Visit_Management_Team__c.object
<CustomObject>
    <description>Object to relate users with visits</description>
    <fields>
        <fullName>dwp_kitv__user_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User visit</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Visit_Management_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>dwp_kitv__visit_id__c</fullName>
        <description>Parent Object</description>
        <label>Visit</label>
        <referenceTo>dwp_kitv__Visit__c</referenceTo>
        <relationshipLabel>Visit Management Teams</relationshipLabel>
        <relationshipName>Visit_Management_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visit Management Team</label>
    <nameField>
        <displayFormat>VM-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Management Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/dwp_kitv__Visit_Topic__c.object
<CustomObject>
    <description>Topics about visits</description>
    <fields>
        <fullName>dwp_kitv__topic_desc__c</fullName>
        <description>Topic description</description>
        <label>Topic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dwp_kitv__visit_id__c</fullName>
        <description>Parent Object</description>
        <label>Visit</label>
        <referenceTo>dwp_kitv__Visit__c</referenceTo>
        <relationshipLabel>Visit Topics</relationshipLabel>
        <relationshipName>Visit_Topics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visit Topic</label>
    <nameField>
        <displayFormat>VT-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Topics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/gcal__GBL_Google_Calendar_Sync_Environment__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Google Calendar Sync Environment</label>
</CustomObject>

src/classes/NavigateFromEventToVisit_cmp_ctrl_Test.cls
@isTest
public class NavigateFromEventToVisit_cmp_ctrl_Test {

    @isTest
    public static void test() {
        Account acc = TestFactory.createAccount();
        User user = TestFactory.createUser('testuser1', 'ejecutivo');
        User owner = TestFactory.createUser('owner', 'ejecutivo');
        Contact cont = TestFactory.createContact(acc.Id);
        gcal__GBL_Google_Calendar_Sync_Environment__c gcs = new gcal__GBL_Google_Calendar_Sync_Environment__c(Name='DEV');
        insert gcs;
        
        dwp_kitv__Visit__c visit = new dwp_kitv__Visit__c(
            dwp_kitv__account_id__c = acc.Id,
            dwp_kitv__visit_status_type__c	= '02',
        	dwp_kitv__visit_duration_number__c = '15', 
            dwp_kitv__visit_start_date__c = Date.today());
        insert visit;
        dwp_kitv__Visit_Contact__c visit_contact = new 	dwp_kitv__Visit_Contact__c(dwp_kitv__visit_id__c=visit.Id, dwp_kitv__contact_id__c=cont.Id);
        insert visit_contact;
        dwp_kitv__Visit_Management_Team__c visit_mt = new dwp_kitv__Visit_Management_Team__c(dwp_kitv__visit_id__c=visit.Id,dwp_kitv__user_id__c=user.Id);
        insert visit_mt;
        dwp_kitv__Visit_Topic__c visit_topic = new dwp_kitv__Visit_Topic__c(dwp_kitv__visit_id__c=visit.Id,	dwp_kitv__topic_desc__c='Topic');
        insert visit_topic;
        Event e=new Event(DurationInMinutes=30,ActivityDateTime=Date.today(), dwp_kitv__visit_id__c=visit.Id);
        insert e;
        String result = NavigateFromEventToVisit_cmp_ctrl.getInfo(e.Id);
        String actual = visit.Id;
		System.assertEquals(result, actual);        
    }
}