src/objects/dwp_cvad__Action_Audit__c.object
<CustomObject>
    <description>Stores the basic action audit information</description>
    <label>Action Audit</label>
    <nameField>
        <displayFormat>AA-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Audits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/dwp_cvad__Action_Audit_Detail__c.object
<CustomObject>
    <description>Stores the details of the audited action.</description>
    <fields>
        <fullName>dwp_cvad__action_audit_detail_content__c</fullName>
        <description>Contains the action audit detail content.</description>
        <inlineHelpText>Contains the action audit detail content.</inlineHelpText>
        <label>Content</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>dwp_cvad__action_audit_detail_display_order__c</fullName>
        <description>Specifies the order in which the action audit detail will be displayed within it´s display type grouping.</description>
        <inlineHelpText>Specifies the order in which the action audit detail will be displayed within it´s display type grouping.</inlineHelpText>
        <label>Display Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>dwp_cvad__action_audit_detail_display_type__c</fullName>
        <description>Specifies if the action audit detail content will be displayed embedded or in a pop-up window.</description>
        <inlineHelpText>Specifies if the action audit detail content will be displayed embedded or in a pop-up window.</inlineHelpText>
        <label>Display Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Embedded</fullName>
                </value>
                <value>
                    <fullName>Link</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>dwp_cvad__action_audit_id__c</fullName> 
        <description>Relation with the action audited.</description>
        <inlineHelpText>Relation with the action audited.</inlineHelpText>
        <label>Action Audit</label>
        <referenceTo>dwp_cvad__Action_Audit__c</referenceTo>
        <relationshipLabel>Action Audit Details</relationshipLabel>
        <relationshipName>Action_Audit_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Action Audit Detail</label>
    <nameField>
        <displayFormat>AAD-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Audit Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity_Solution_Commitment__c.object
<CustomObject>
    <fields>
        <fullName>opp_soln_comt_expiry_days_number__c</fullName>
        <label>Expiry days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>opp_solution_commitment_amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>opp_solution_commitment_id__c</fullName>
        <label>Identifier</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>opp_solution_comt_product_name__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>opportunity_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Solution Commitments</relationshipLabel>
        <relationshipName>Opportunity_Solution_Commitments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Compromiso Precio</label>
    <nameField>
        <displayFormat>OSC-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compromisos Precio</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BE_SanctionUseQuotation_Tst.cls
/**BE_SanctionUseQuotation_Tst
 *  object.
 * <p /><p />
 * Modification log:<p />
 * -------------------------------------------------------------------
 * Developer                       Date                Description<p />
 * -------------------------------------------------------------------
 * Martin Alejandro Mori Chavez    18/06/2018          Original version.<p />
 *
 * @author Martin Alejandro Mori Chavez
 */
@istest
public class BE_SanctionUseQuotation_Tst {
	@testSetup
	static void setupData() {
		Final Account acc = TestFactory.createAccount();
		Final User user = TestFactory.createUser_1('TestAdmin', 'Migracion');
		TestFactory.createUserBranch(user.Id);
		Final Opportunity opp = TestFactory.createOpportunity(acc.Id, user.Id);
		Final List<dwp_cvad__Action_Audit__c> action_audit_list = TestFactory.create_Action_Audit(opp.id);
        insert new dwp_cvad__Action_Audit_Detail__c(dwp_cvad__action_audit_id__c = action_audit_list[0].Id, 
                                                    dwp_cvad__action_audit_detail_content__c = '<h3 class="slds-section__title">Comentarios</h3><div class="slds-form-element__control"><span class="slds-form-element__static">analista: tasa aprobada</span></div>',
                                                    dwp_cvad__action_audit_detail_display_order__c = 1.0, 
                                                    dwp_cvad__action_audit_detail_display_type__c = 'Price Approval');
		Final Product2 prod = TestFactory.createProduct();
		TestFactory.productConfiguration_1(Prod.ID);
		Final OpportunityLineItem oli = TestFactory.createOLI(opp.id, prod.id);
        Final Opportunity_Solution_Commitment__c comm = new Opportunity_Solution_Commitment__c();
        comm.opp_solution_commitment_id__c='10';
        comm.opp_solution_commitment_amount__c=200;
        comm.opp_soln_comt_expiry_days_number__c=30;
        comm.opp_solution_comt_product_name__c='INCR. SM VISTA + AHORRO';
        comm.CurrencyIsoCode='PEN';
        comm.opportunity_id__c=opp.Id;
        insert comm;
        
        Final Opportunity oppAux = TestFactory.createOpportunity(acc.Id, user.Id);
		Final OpportunityLineItem oliAux = oli.clone();
        oliAux.OpportunityId = oppAux.Id;
        insert oliAux;
	}

	@isTest
    static void getCommentsTest() {
		Final Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Final String comment = BE_SanctionUseQuotation_Ctr.getComments(opp.Id);
        System.assert(String.isNotBlank(comment), 'success!!!');
	}
    
    @isTest
    static void useQuotationPriceSuccessTest() {
		Final OpportunityLineItem oli = [SELECT Id, OpportunityId FROM OpportunityLineItem ORDER BY CreatedDate ASC LIMIT 1];
        BE_CreateQuotation_cls.generatePDF(oli.OpportunityId);
        BE_CreateQuotation_cls.generatePDF(oli.OpportunityId);
        Final Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate DESC LIMIT 1];
        opp.StageName = '04';
        update opp;
        Final Map<String, Object> mapReturn = BE_SanctionUseQuotation_Ctr.useQuotationPrice(opp.Id, oli.Id);
        System.assert(Boolean.valueOf(mapReturn.get('isOk')), 'success!!!');
	}
    
    @isTest
    static void useQuotationPriceFailTest() {
		Final Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        opp.StageName = '04';
        update opp;
        Final Map<String, Object> mapReturn = BE_SanctionUseQuotation_Ctr.useQuotationPrice(opp.Id, null);
        System.assert(!Boolean.valueOf(mapReturn.get('isOk')), 'fail!!!');
	}
}