src/objects/dwp_frct__management_plan__c.object
<CustomObject>
    <description>Object to manage plans</description>
    <fields>
        <fullName>dwp_frct__management_plan_end_date__c</fullName>
        <description>End Date plan</description>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dwp_frct__management_plan_start_date__c</fullName>
        <description>Start Date plan</description>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <label>Management Plan</label>
    <nameField>
        <label>Management Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/slmt__Sales_Meeting__c.object
<CustomObject>
    <description>Storing all the planned meetings for each responsible, in addition to the planned date and time, the collaborator and the type.</description>
    <fields>
        <fullName>Collaborator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collaborator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Meetings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DateTime__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DateTime</label>
        <type>DateTime</type>
    </fields>
    <label>Sales Meeting</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Meetings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BE_SM_ManagementPlanLink_Cls.cls
public without sharing class BE_SM_ManagementPlanLink_Cls extends BE_ButtonsBarCRUD_cls {
     /**
    @Description createRecords
    @param Map<String,Object> params
    @return BE_SingleRelatedListCRUD_Cls.Response response
    */
    public override BE_ButtonsBarCRUD_cls.Response readRecords(Map<String,Object> params) {
        BE_ButtonsBarCRUD_cls.Response res = new BE_ButtonsBarCRUD_cls.Response();
        final slmt__Sales_Meeting__c salesMeeting= [SELECT DateTime__c,Collaborator__c FROM slmt__Sales_Meeting__c WHERE Id=:(String)params.get('recordId')];
        final List<SObject> plans=[SELECT ID FROM dwp_frct__management_plan__c WHERE dwp_frct__management_plan_end_date__c>=:salesMeeting.DateTime__c AND dwp_frct__management_plan_start_date__c<=:salesMeeting.DateTime__c AND OwnerId=:salesMeeting.Collaborator__c];
        if(plans.size()>0){
            res.data=plans;
            res.isSuccess=true;
        } else {
            res.isSuccess=false;
        }
        return res;
    }
}