src/objects/dwp_cvad__Action_Audit__c.object
<CustomObject>
    <description>Stores the basic action audit information</description>
    <label>Action Audit</label>
    <nameField>
        <displayFormat>AA-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Audits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/fprd__GBL_Product_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>fprd__LoV_labels__c</fullName>
        <label>Deprecated</label>
        <length>50000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>fprd__LoV_values__c</fullName>
        <label>Deprecated</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>fprd__Map_field__c</fullName>
        <label>Map field</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fprd__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product configurations</relationshipLabel>
        <relationshipName>Product_configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product configuration</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Product Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product configurations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
<fields>
        <fullName>opportunity_status_type__c</fullName>
        <description>Status of an opportunity</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>PE_List_Product_mode__c</fullName>
        <label>PE_List_Product_mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>price_quote_id__c</fullName>
        <label>Cotiza Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>price_operation_id__c</fullName>
        <label>Price operation Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/SanctionPriceDecision_ctrl_Test.cls
@istest
public class SanctionPriceDecision_ctrl_Test {
    static String grantTK = 'GrantingTickets';
    static String urlGrantTK = 'https://validation/ok';
    static String ModifQuote = 'ModifyQuotationRequest';
    static String urlModifQuote = 'https://ModifyQuotationRequestRecover/OK';
    
    @testSetup
    static void setData() {
        Account acc = TestFactory.createAccount();
        Opportunity opp = TestFactory.createOpportunity(acc.Id, UserInfo.getUserId());
        Product2 prod = TestFactory.createProduct();
        OpportunityLineItem oli = TestFactory.createOLI(opp.Id, prod.Id);
        oli.PE_List_Product_mode__c = '01';
        update oli;
        Final fprd__GBL_Product_Configuration__c newPd = new fprd__GBL_Product_Configuration__c(fprd__LoV_labels__c = 'Valor Label 1', fprd__LoV_values__c = '01', 
                                                                                       fprd__Map_field__c='PE_List_Product_mode__c', fprd__Product__c=prod.Id);
        insert newPd;
    }

    @isTest
    static void test_method_one() {
        List<OpportunityLineItem> lstOLI = [SELECT Id FROM OpportunityLineItem];
        Map<String,Object> mapReturn = SanctionPriceDecision_ctrl.getInfo(lstOLI[0].Id);
        System.assert(mapReturn.containsKey('lstOppLineItem')); 
        Map<String,Object> mapReturn2 = SanctionPriceDecision_ctrl.getInfoAnalist(lstOLI[0].Id);
        System.assert(mapReturn2.containsKey('lstOppLineItem')); 
        
        List<Opportunity> lstOpp = [SELECT Id FROM Opportunity];
        Map<String,Object> mapReturnSave = SanctionPriceDecision_ctrl.saveDecision(lstOpp[0].Id,'09','04',true,'asd','nameAudit','comments','<div>Hola</div>');
        System.assert((Boolean)mapReturnSave.get('isOk'));
        Map<String,Object> mapReturnSave2 = SanctionPriceDecision_ctrl.saveDecisionAnalist(lstOpp[0].Id, '09', '04', true, 'asd', 'nameAudit', 'comments', lstOLI[0].Id, new List<String>(), new List<Object>(), '01', '<div>Hola</div>','COTIZADOR', null, '');
        System.assert((Boolean)mapReturnSave2.get('isOk'));

        lstOLI[0].price_quote_id__c = '111';
        lstOLI[0].price_operation_id__c = '222';
        update lstOLI[0];

        insert new iaso__GBL_Rest_Services_Url__c(Name = grantTK, iaso__Url__c = urlGrantTK, iaso__Cache_Partition__c = 'local.CredentialsPeru');
        insert new iaso__GBL_Rest_Services_Url__c(Name = ModifQuote, iaso__Url__c = urlModifQuote, iaso__Cache_Partition__c = 'local.CredentialsPeru');
        Test.setMock(HttpCalloutMock.class, new Integration_MockGenerator());
        iaso.GBL_Mock.setMock(new Integration_MockGenerator());

        Test.startTest();
		List<Object> lstData = new List<Object>();
        lstData.add(23);
        lstData.add(23);
        Map<String,Object> mapReturnSave3 = SanctionPriceDecision_ctrl.saveDecisionAnalist(lstOpp[0].Id, '09', '04', true, 'asd', 'nameAudit', 'comments', lstOLI[0].Id, new List<String>(), lstData, '01', '<div>Hola</div>', 'Web', 'APPROVE', '');
        System.assert((Boolean)mapReturnSave3.get('isOk'));

        Test.stopTest();

        List<dwp_cvad__Action_Audit__c> lstAudit = [SELECT Id FROM dwp_cvad__Action_Audit__c];
        SanctionPriceDecision_ctrl.saveAuditWeb(lstAudit[0].Id, '<div>Hola</div>');
        
    }
    
    @isTest
    static void test_method_two() {
        List<OpportunityLineItem> lstOLI = [SELECT Id, OpportunityId FROM OpportunityLineItem];
        lstOLI[0].price_quote_id__c = '111';
        lstOLI[0].price_operation_id__c = '222';
        update lstOLI[0];
        
        Opportunity opp = new Opportunity(Id=lstOLI[0].OpportunityId, opportunity_status_type__c='08', StageName='04');
        update opp;
        
        insert new iaso__GBL_Rest_Services_Url__c(Name = grantTK, iaso__Url__c = urlGrantTK, iaso__Cache_Partition__c = 'local.CredentialsPeru');
        insert new iaso__GBL_Rest_Services_Url__c(Name = 'GetQuotationRequest', iaso__Url__c = 'https://GetQuotationRequest/OK/1111?expand=quotations', iaso__Cache_Partition__c = 'local.CredentialsPeru');
        Test.setMock(HttpCalloutMock.class, new Integration_MockGenerator());
        iaso.GBL_Mock.setMock(new Integration_MockGenerator());
        
        GetQuotationRequest_helper getRequestHelper = new GetQuotationRequest_helper(opp.Id);
        
        Test.startTest();
        Map<String,Object> mapReturn = SanctionPriceDecision_ctrl.getInfo(lstOLI[0].Id);
        System.assert(mapReturn.containsKey('lstOppLineItem'));
        Test.stopTest();
    }
    
    @isTest
    static void test_method_three() {
        List<OpportunityLineItem> lstOLI = [SELECT Id FROM OpportunityLineItem];
        Map<String,Object> mapReturn = SanctionPriceDecision_ctrl.getInfo(lstOLI[0].Id);
        System.assert(mapReturn.containsKey('lstOppLineItem')); 
        Map<String,Object> mapReturn2 = SanctionPriceDecision_ctrl.getInfoAnalist(lstOLI[0].Id);
        System.assert(mapReturn2.containsKey('lstOppLineItem')); 
        
        List<Opportunity> lstOpp = [SELECT Id FROM Opportunity];
        Map<String,Object> mapReturnSave = SanctionPriceDecision_ctrl.saveDecision(lstOpp[0].Id,'09','04',true,'asd','nameAudit','comments','<div>Hola</div>');
        System.assert((Boolean)mapReturnSave.get('isOk'));
        Map<String,Object> mapReturnSave2 = SanctionPriceDecision_ctrl.saveDecisionAnalist(lstOpp[0].Id, '09', '04', true, 'asd', 'nameAudit', 'comments', lstOLI[0].Id, new List<String>(), new List<Object>(), '01', '<div>Hola</div>','COTIZADOR', null, '');
        System.assert((Boolean)mapReturnSave2.get('isOk'));

        lstOLI[0].price_quote_id__c = '111';
        lstOLI[0].price_operation_id__c = '222';
        update lstOLI[0];

        insert new iaso__GBL_Rest_Services_Url__c(Name = grantTK, iaso__Url__c = urlGrantTK, iaso__Cache_Partition__c = 'local.CredentialsPeru');
        insert new iaso__GBL_Rest_Services_Url__c(Name = ModifQuote, iaso__Url__c = urlModifQuote, iaso__Cache_Partition__c = 'local.CredentialsPeru');
        Test.setMock(HttpCalloutMock.class, new Integration_MockGenerator());
        iaso.GBL_Mock.setMock(new Integration_MockGenerator());

        Test.startTest();
		List<Object> lstData = new List<Object>();
        lstData.add(23);
        lstData.add(23);
        Map<String,Object> mapReturnSave3 = SanctionPriceDecision_ctrl.saveDecisionAnalist(lstOpp[0].Id, '13', '04', true, 'asd', 'nameAudit', 'comments', lstOLI[0].Id, new List<String>(), lstData, '01', '<div>Hola</div>', 'Web', 'APPROVE', '');
        System.assert((Boolean)mapReturnSave3.get('isOk'));

        Test.stopTest();
    }
    
    @isTest
    static void test_method_Four() {
        List<OpportunityLineItem> lstOLI = [SELECT Id FROM OpportunityLineItem];
        Map<String,Object> mapReturn = SanctionPriceDecision_ctrl.getInfo(lstOLI[0].Id);
        System.assert(mapReturn.containsKey('lstOppLineItem')); 
        Map<String,Object> mapReturn2 = SanctionPriceDecision_ctrl.getInfoAnalist(lstOLI[0].Id);
        System.assert(mapReturn2.containsKey('lstOppLineItem')); 
        
        List<Opportunity> lstOpp = [SELECT Id FROM Opportunity];
        Map<String,Object> mapReturnSave = SanctionPriceDecision_ctrl.saveDecision(lstOpp[0].Id,'09','04',true,'asd','nameAudit','comments','<div>Hola</div>');
        System.assert((Boolean)mapReturnSave.get('isOk'));
        Map<String,Object> mapReturnSave2 = SanctionPriceDecision_ctrl.saveDecisionAnalist(lstOpp[0].Id, '09', '04', true, 'asd', 'nameAudit', 'comments', lstOLI[0].Id, new List<String>(), new List<Object>(), '01', '<div>Hola</div>','COTIZADOR', null, '');
        System.assert((Boolean)mapReturnSave2.get('isOk'));

        lstOLI[0].price_quote_id__c = '111';
        lstOLI[0].price_operation_id__c = '222';
        update lstOLI[0];

        insert new iaso__GBL_Rest_Services_Url__c(Name = grantTK, iaso__Url__c = urlGrantTK, iaso__Cache_Partition__c = 'local.CredentialsPeru');
        insert new iaso__GBL_Rest_Services_Url__c(Name = ModifQuote, iaso__Url__c = urlModifQuote, iaso__Cache_Partition__c = 'local.CredentialsPeru');
        Test.setMock(HttpCalloutMock.class, new Integration_MockGenerator());
        iaso.GBL_Mock.setMock(new Integration_MockGenerator());

        Test.startTest();
		List<Object> lstData = new List<Object>();
        lstData.add(23);
        lstData.add(23);
        Map<String,Object> mapReturnSave3 = SanctionPriceDecision_ctrl.saveDecisionAnalist(lstOpp[0].Id, '10', '04', true, 'asd', 'nameAudit', 'comments', lstOLI[0].Id, new List<String>(), lstData, '01', '<div>Hola</div>', 'Web', 'APPROVE', '');
        System.assert(!(Boolean)mapReturnSave3.get('isOk'));
        Test.stopTest();
    }
    
    @isTest
    static void testRedirect() {
        Map<String, Object> mapRes = new Map<String, Object>();
        Test.startTest();
        mapRes = SanctionPriceDecision_ctrl.redirect();
        Test.stopTest();
        System.assertEquals(false, mapRes.get('isError'), 'Error en resultado esperado.');
    }
}