src/objects/dwp_cvad__Action_Audit__c.object
<CustomObject>
    <description>Stores the basic action audit information</description>
    <fields>
        <fullName>action_audit_email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Email SIO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>action_opp_sio_code__c</fullName>
        <label>SIO Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dwp_cvad__action_audit_date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>Timestamp of the action audited.</description>
        <inlineHelpText>Timestamp of the action audited.</inlineHelpText>
        <label>Timestamp</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dwp_cvad__action_audit_name__c</fullName>
        <description>Brief description of the action audited.</description>
        <inlineHelpText>Brief description of the action audited.</inlineHelpText>
        <label>Action Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dwp_cvad__action_audit_object_api_name__c</fullName>
        <description>Object API Name of the record to which the action audited refers to.</description>
        <inlineHelpText>Object API Name of the record to which the action audited refers to.</inlineHelpText>
        <label>Object API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dwp_cvad__action_audit_record_id__c</fullName>
        <description>Id of the record to which the action audited refers to.</description>
        <inlineHelpText>Id of the record to which the action audited refers to.</inlineHelpText>
        <label>Record Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dwp_cvad__action_audit_style__c</fullName>
        <description>Audited action visualization style.</description>
        <inlineHelpText>Audited action visualization style.</inlineHelpText>
        <label>Style</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>approve</fullName>
                </value>
                <value>
                    <fullName>approveTop</fullName>
                </value>
                <value>
                    <fullName>deny</fullName>
                </value>
                <value>
                    <fullName>elevate</fullName>
                </value>
                <value>
                    <fullName>elevateTop</fullName>
                </value>
                <value>
                    <fullName>infoAlt</fullName>
                </value>
                <value>
                    <fullName>quickText</fullName>
                </value>
                <value>
                    <fullName>restudy</fullName>
                </value>
                <value>
                    <fullName>sendBack</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>dwp_cvad__action_audit_type__c</fullName>
        <description>Type of the action audited.</description>
        <inlineHelpText>Type of the action audited.</inlineHelpText>
        <label>Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dwp_cvad__action_audit_user_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relation with the user that performed the action audited.</description>
        <inlineHelpText>Relation with the user that performed the action audited.</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Action_Audits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Action Audit</label>
    <nameField>
        <displayFormat>AA-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Audits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/dwp_cvad__Action_Audit_Detail__c.object
<CustomObject>
    <description>Stores the details of the audited action.</description>
    <fields>
        <fullName>dwp_cvad__action_audit_detail_content__c</fullName>
        <description>Contains the action audit detail content.</description>
        <inlineHelpText>Contains the action audit detail content.</inlineHelpText>
        <label>Content</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>dwp_cvad__action_audit_detail_display_order__c</fullName>
        <description>Specifies the order in which the action audit detail will be displayed within it´s display type grouping.</description>
        <inlineHelpText>Specifies the order in which the action audit detail will be displayed within it´s display type grouping.</inlineHelpText>
        <label>Display Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>dwp_cvad__action_audit_detail_display_title__c</fullName>
        <description>Specifies the link´s text used on the action audit details with type Link.</description>
        <inlineHelpText>Specifies the link´s text used on the action audit details with type Link.</inlineHelpText>
        <label>Display Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dwp_cvad__action_audit_detail_display_type__c</fullName>
        <description>Specifies if the action audit detail content will be displayed embedded or in a pop-up window.</description>
        <inlineHelpText>Specifies if the action audit detail content will be displayed embedded or in a pop-up window.</inlineHelpText>
        <label>Display Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Embedded</fullName>
                </value>
                <value>
                    <fullName>Link</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>dwp_cvad__action_audit_id__c</fullName> 
        <description>Relation with the action audited.</description>
        <inlineHelpText>Relation with the action audited.</inlineHelpText>
        <label>Action Audit</label>
        <referenceTo>dwp_cvad__Action_Audit__c</referenceTo>
        <relationshipLabel>Action Audit Details</relationshipLabel>
        <relationshipName>Action_Audit_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Action Audit Detail</label>
    <nameField>
        <displayFormat>AAD-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Audit Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Action_Audit_Helper.cls
/**
* @author Global_HUB developers
* @date 10-07-2018
*
* @group Global_HUB
*
* @description Helper class to get Action Audits and Action Audits Detail
**/
public class Action_Audit_Helper {
    //method helper to get Action Audit
    public static dwp_cvad__Action_Audit__c getAudit(String auditName, String apiName, String recordId, DateTime auditDate, String auditType, String userId, String auditStyle, String sioCode, Boolean email){
        
        dwp_cvad__Action_Audit__c actAudit = new dwp_cvad__Action_Audit__c();
        
        actAudit.dwp_cvad__action_audit_name__c = auditName;
        actAudit.dwp_cvad__action_audit_object_api_name__c  = apiName;
        actAudit.dwp_cvad__action_audit_record_id__c = recordId;
        actAudit.dwp_cvad__action_audit_date__c = auditDate;
        actAudit.dwp_cvad__action_audit_type__c = auditType;
        actAudit.dwp_cvad__action_audit_user_id__c = userId;
        actAudit.dwp_cvad__action_audit_style__c = auditStyle;
        actAudit.action_opp_SIO_code__c = sioCode;
        actAudit.action_audit_email__c = email;
        
        return actAudit;
    }
    //method helper to get Action Audit Detail
    public static dwp_cvad__Action_Audit_Detail__c getAuditDetail(String auditId, String content, Integer order, String title, String disType){
        
        dwp_cvad__Action_Audit_Detail__c auditDetail = new dwp_cvad__Action_Audit_Detail__c();
        
        auditDetail.dwp_cvad__action_audit_id__c = auditId;
        auditDetail.dwp_cvad__action_audit_detail_content__c = content;
        auditDetail.dwp_cvad__action_audit_detail_display_order__c = order;
        auditDetail.dwp_cvad__action_audit_detail_display_title__c = title;
        auditDetail.dwp_cvad__action_audit_detail_display_type__c = disType;
        
        return auditDetail;        
    }
    
}