src/objects/dwp_kitv__Visit__c.object
<CustomObject>
    <description>Main object to manage visits</description>
    <fields>
        <fullName>dwp_kitv__visit_start_date__c</fullName>
        <description>Field to set the start date time of the visit.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dwp_kitv__visit_status_type__c</fullName>
        <description>Status visit</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>Arranged</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>Arranged - Pending Updates</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <label>Visit Completed - Pending Feedback</label>
                </value>
                <value>
                    <fullName>05</fullName>
                    <label>Visit Completed - Minute Sent</label>
                </value>
                <value>
                    <fullName>06</fullName>
                    <label>Finalized</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>start_date_calculated__c</fullName>
        <formula>dwp_kitv__visit_start_date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Date Calculated</label>
        <type>Date</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/dwp_kitv__Visit_Management_Team__c.object
<CustomObject>
    <description>Object to relate users with visits</description>
    <fields>
        <fullName>dwp_kitv__user_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User visit</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Visit_Management_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>dwp_kitv__visit_id__c</fullName>
        <description>Parent Object</description>
        <label>Visit</label>
        <referenceTo>dwp_kitv__Visit__c</referenceTo>
        <relationshipLabel>Visit Management Teams</relationshipLabel>
        <relationshipName>Visit_Management_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visit Management Team</label>
    <nameField>
        <displayFormat>VM-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Management Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BE_SM_CampaignQVC_Cls.cls
global class BE_SM_CampaignQVC_Cls implements slmt.Sales_Meeting_Item_Details_Itf {
    
    public List<Map<String,String>> getCardDetails(sObject contextRecord, String cardId) {
        Integer monthVisit = 0;
        Integer lastVisit = 0;
        Integer nextVisit = 0;
        /*for(dwp_kitv__Visit_Management_Team__c visitTeam : [SELECT Id, dwp_kitv__visit_id__c, dwp_kitv__user_id__c, dwp_kitv__visit_id__r.dwp_kitv__visit_status_type__c, dwp_kitv__visit_id__r.dwp_kitv__visit_start_date__c FROM dwp_kitv__Visit_Management_Team__c 
                                                            WHERE dwp_kitv__user_id__c = :String.valueOf(contextRecord.get('OwnerId')) AND 
                                                           ((dwp_kitv__visit_id__r.start_date_calculated__c <= :Date.valueOf(contextRecord.get('slmt__management_plan_meeting_date__c')).addDays(7) AND dwp_kitv__visit_id__r.start_date_calculated__c >= :Date.valueOf(contextRecord.get('slmt__management_plan_meeting_date__c')).addDays(-7)) OR 
                                                            (CALENDAR_YEAR(dwp_kitv__visit_id__r.start_date_calculated__c) = :Date.valueOf(contextRecord.get('slmt__management_plan_meeting_date__c')).year() AND CALENDAR_MONTH(dwp_kitv__visit_id__r.start_date_calculated__c) = :Date.valueOf(contextRecord.get('slmt__management_plan_meeting_date__c')).month()))]) {
            Integer noOfDays = Date.valueOf(visitTeam.dwp_kitv__visit_id__r.dwp_kitv__visit_start_date__c).daysBetween(Date.valueOf(contextRecord.get('slmt__management_plan_meeting_date__c')));
            if(visitTeam.dwp_kitv__visit_id__r.dwp_kitv__visit_status_type__c == '06' && visitTeam.dwp_kitv__visit_id__r.dwp_kitv__visit_start_date__c.year() == Date.valueOf(contextRecord.get('slmt__management_plan_meeting_date__c')).year() && visitTeam.dwp_kitv__visit_id__r.dwp_kitv__visit_start_date__c.month() == Date.valueOf(contextRecord.get('slmt__management_plan_meeting_date__c')).month()) {
                monthVisit++;
            }
            if(noOfDays>=0 && noOfDays<=7) {
                nextVisit++;
            } if(noOfDays<=0 && noOfDays>=-7) {
                lastVisit++;
            }
        }*/

        List<Map<String,String>> lstReturn = new List<Map<String,String>>();
        Map<String,String> title = new Map<String,String>();
        //title.put('label','Name');
        title.put('value','Campañas');
        title.put('type','08');
        title.put('format','NOTHING');
        title.put('icon','NOTHING');
        title.put('typeIcon','NOTHING');
        title.put('idRecord', cardId);
        title.put('isSubtitle','true');
        lstReturn.add(title);
        
        Map<String,String> item1 = new Map<String,String>();
        item1.put('label','Item 1');
        item1.put('value',String.valueOf(monthVisit));
        item1.put('type','06');
        item1.put('format','###,###,##0');
        item1.put('icon','NOTHING');
        item1.put('typeIcon','NOTHING');
        item1.put('idRecord', cardId);
        item1.put('isSubtitle','false');
        lstReturn.add(item1);
        
        Map<String,String> item2 = new Map<String,String>();
        item2.put('label','Item 2');
        item2.put('value',String.valueOf(lastVisit));
        item2.put('type','06');
        item2.put('format','###,###,##0');
        item2.put('icon','NOTHING');
        item2.put('typeIcon','NOTHING');
        item2.put('idRecord', cardId);
        item2.put('isSubtitle','false');
        lstReturn.add(item2);
        
        Map<String,String> item3 = new Map<String,String>();
        item3.put('label','Item 3');
        item3.put('value',String.valueOf(nextVisit));
        item3.put('type','06');
        item3.put('format','###,###,##0');
        item3.put('icon','NOTHING');
        item3.put('typeIcon','NOTHING');
        item3.put('idRecord', cardId);
        item3.put('isSubtitle','false');
        lstReturn.add(item3);
        
        return lstReturn;
    }
}