src/objects/dwp_cvad__Action_Audit__c.object
<CustomObject>
    <description>Stores the basic action audit information</description>
    <fields>
        <fullName>action_opp_sio_code__c</fullName>
        <label>SIO Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dwp_cvad__action_audit_record_id__c</fullName>
        <description>Id of the record to which the action audited refers to.</description>
        <inlineHelpText>Id of the record to which the action audited refers to.</inlineHelpText>
        <label>Record Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Action Audit</label>
    <nameField>
        <displayFormat>AA-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Audits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
<fields>
        <fullName>opportunity_status_type__c</fullName>
        <description>Status of an opportunity</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Risk_Approval_Test.cls
@isTest
public class Risk_Approval_Test {
    static Account acctest;
    static Opportunity opptest;
    static dwp_cvad__Action_Audit__c audit1, audit2, audit3;
    
    @testSetup
    static void setupData() {
		acctest = TestFactory.createAccount();
        opptest = TestFactory.createOpportunity(acctest.Id,UserInfo.getUserId());
        audit1 = Action_Audit_Helper.getAudit('Sanción Aprobado CM', Label.ApiNameAccount, acctest.Id, System.now(), Label.RiskApproval, UserInfo.getUserId(), Label.AuditStyleApproveTop, '1234', true);
        audit2 = Action_Audit_Helper.getAudit('Sanción Denegado', Label.ApiNameAccount, acctest.Id, System.now(), Label.RiskApproval, UserInfo.getUserId(), Label.AuditStyleDeny, '5678', true);
        audit3 = Action_Audit_Helper.getAudit('1er Ingreso a Controller', Label.ApiNameAccount, acctest.Id, System.now(), Label.RiskApproval, UserInfo.getUserId(), Label.AuditStyleElevate, '1900', true);
    }
    @isTest
    static void oppModalityDL() {
        setupData();
        Test.startTest();
            Opportunity oppDetails = Risk_Approval_cls.getOpportunity(opptest.Id);
            Risk_Approval_cls.sendApproval(oppDetails);
        Test.stopTest();
        System.assertEquals(oppDetails.StageName, Label.lblSanctionStage);
        System.assertEquals(oppDetails.opportunity_status_type__c, Label.lblOpportunityStatusApprovedInsideLine);
    }
    @isTest
    static void oppModalityRAAuthorized() {
        setupData();
        Test.startTest();
            Opportunity oppDetails = Risk_Approval_cls.getOpportunity(opptest.Id);
        	insert audit1;
            Risk_Approval_cls.getSIOCodesToSelect('', oppDetails);
        	Risk_Approval_cls.saveSIO(oppDetails, audit1.action_opp_sio_code__c);
        Test.stopTest();
        System.assertEquals(oppDetails.StageName, Label.lblSanctionStage);
        System.assertEquals(oppDetails.opportunity_status_type__c, Label.lblOpportunityStatusRiskAuth);
        List<dwp_cvad__Action_Audit__c> audits = [Select Id From dwp_cvad__Action_Audit__c Where dwp_cvad__action_audit_record_id__c = :oppDetails.Id];
        System.assertEquals(2, audits.size());
    }
    @isTest
    static void oppModalityRADenied() {
        setupData();
        Test.startTest();
            Opportunity oppDetails = Risk_Approval_cls.getOpportunity(opptest.Id);
        	insert audit2;
            Risk_Approval_cls.getSIOCodesToSelect('56', oppDetails);
        	Risk_Approval_cls.saveSIO(oppDetails, audit2.action_opp_sio_code__c);
        Test.stopTest();
        System.assertEquals(oppDetails.StageName, Label.lblSanctionStage);
        System.assertEquals(oppDetails.opportunity_status_type__c, Label.lblOpportunityStatusRiskDenied);
        List<dwp_cvad__Action_Audit__c> audits = [Select Id From dwp_cvad__Action_Audit__c Where dwp_cvad__action_audit_record_id__c = :oppDetails.Id];
        System.assertEquals(2, audits.size());
    }
    @isTest
    static void oppModalityRASentForAuth() {
        setupData();
        Test.startTest();
            Opportunity oppDetails = Risk_Approval_cls.getOpportunity(opptest.Id);
        	insert audit3;
            Risk_Approval_cls.getSIOCodesToSelect('', oppDetails);
        	Risk_Approval_cls.saveSIO(oppDetails, audit3.action_opp_sio_code__c);
        	Risk_Approval_cls.saveSIO(oppDetails, audit3.action_opp_sio_code__c);
        Test.stopTest();
        System.assertEquals(oppDetails.StageName, Label.lblSanctionStage);
        System.assertEquals(oppDetails.opportunity_status_type__c, Label.lblOpportunityStatusSentRisk);
        List<dwp_cvad__Action_Audit__c> audits = [Select Id From dwp_cvad__Action_Audit__c Where dwp_cvad__action_audit_record_id__c = :oppDetails.Id];
        System.assertEquals(3, audits.size());
    }
    @isTest
    static void passCatch() {
        Test.startTest();
            Opportunity oppDetails = Risk_Approval_cls.getOpportunity(null);
            Risk_Approval_cls.getSIOCodesToSelect('', oppDetails);
        	Risk_Approval_cls.saveSIO(oppDetails, '');
        	Risk_Approval_cls.sendApproval(oppDetails);
        Test.stopTest();
    }
}