src/objects/dwp_kitv__Visit__c.object
<CustomObject>
    <description>Main object to manage visits</description>
    <fields>
        <fullName>dwp_kitv__account_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account record related to this visit.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>dwp_kitv__visit_duration_number__c</fullName>
        <description>Time in minutes it takes to make the visit. The first hour will be intervals about 15 minutes, then 30 minutes intervals.</description>
        <inlineHelpText>Seleccione la duración en minutos</inlineHelpText>
        <label>Duration</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>120</fullName>
                </value>
                <value>
                    <fullName>150</fullName>
                </value>
                <value>
                    <fullName>180</fullName>
                </value>
                <value>
                    <fullName>210</fullName>
                </value>
                <value>
                    <fullName>240</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>dwp_kitv__visit_start_date__c</fullName>
        <description>Field to set the start date time of the visit.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/dwp_kitv__Visit_Management_Team__c.object
<CustomObject>
    <description>Object to relate users with visits</description>
    <fields>
        <fullName>dwp_kitv__user_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User visit</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Visit_Management_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit Management Team</label>
    <nameField>
        <displayFormat>VM-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Management Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/visit_helper_Trigger_tst.cls
/* Test class for AccountContact_Handler class.
 * <p /><p />
 * Modification log:<p />
 * -------------------------------------------------------------------------
 * Developer                    Date                Description<p />
 * -------------------------------------------------------------------------
 * Diego Carbajal            0/06/2019          Original version.<p />
 *
 * @author Diego Carbajal
 */
@isTest
public class Visit_helper_Trigger_tst {

    /*Setup Data*/
    @TestSetup
    public static void setUp() {
        //Creación de cuentas con perfil de Migracion
        Final User usuario=TestFactory.createUser('Owner_Account', 'Ejecutivo');
        Final Account[] lstAccount=new Account[]{};
        Account acc;
        for(Integer i=0; i<250; i++) {
            acc=new Account(Name='Cuenta '+i, OwnerId=usuario.Id);
            lstAccount.add(acc);
        }
        insert lstAccount;
        
        //Creación de visitas
        Final dwp_kitv__Visit__c [] lstVisitas=new dwp_kitv__Visit__c[]{};
        dwp_kitv__Visit__c tmpV;
        for(Account a:lstAccount) {
            tmpV=new dwp_kitv__Visit__c(dwp_kitv__account_id__c=a.Id, dwp_kitv__visit_duration_number__c='15', dwp_kitv__visit_start_date__c=System.now());
            lstVisitas.add(tmpV);
        }
        insert lstVisitas;
    }
    
    /*Method to test deleteOwners*/
    @isTest
    public static void deleteOwners() {
        Final User usuario=[SELECT ID, Name, profile.Name FROM USER WHERE Name LIKE '%Owner_Account%'];
        Final dwp_kitv__Visit_Management_Team__c[] lstEquipos =[SELECT Id FROM dwp_kitv__Visit_Management_Team__c WHERE 
                                                           dwp_kitv__user_id__c=:usuario.Id AND dwp_owner_visit__c=true limit 250];
        Test.startTest();
        Boolean pass=true;
        System.runAs(usuario) {
            try {
                delete lstEquipos;
            } catch(Exception e) {
                System.debug('Exception e ==> '+e.getMessage());
                pass=false;
            }
        }
        Test.stopTest();
        System.assert(!pass, '!pass is false');
    }
}