src/objects/dwp_frct__grouping__c.object
<CustomObject>
    <description>Object to related plans with opportunity object.</description>
    <fields>
        <fullName>dwp_frct__management_plan_id__c</fullName>
        <description>Management plan object</description>
        <label>Management Plan</label>
        <referenceTo>dwp_frct__management_plan__c</referenceTo>
        <relationshipLabel>Groupings</relationshipLabel>
        <relationshipName>Groupings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>dwp_frct__solution_category_type__c</fullName>
        <description>Family category opportunity.</description>
        <label>Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Grouping</label>
    <nameField>
        <label>Grouping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groupings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/dwp_frct__management_plan__c.object
<CustomObject>
    <description>Object to manage plans</description>
    <label>Management Plan</label>
    <nameField>
        <label>Management Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Management Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Grouping_Trigger_Test.cls
@isTest
public class Grouping_Trigger_Test {

    @isTest
    static void validarTrigger(){
        Test.startTest();
        dwp_frct__management_plan__c rowMGP= new dwp_frct__management_plan__c();
        rowMGP.Name='Mi Plan';
        insert rowMGP;
        List<dwp_frct__grouping__c> row = new List<dwp_frct__grouping__c>();
        row.add(new dwp_frct__grouping__c(Name='Test',dwp_frct__solution_category_type__c='MyProd',dwp_frct__management_plan_id__c=rowMGP.id));
         insert row;
        row[0].Name='Changed';
        update row;
		System.debug(row[0].id);
	  	System.assert(true,'This Works!');
		Test.stopTest();
    }
    
}