src/objects/gfsc__Guidance_for_Success__c.object
<CustomObject>
    <description>Values for the different guidance for success implementations.</description>
    <label>Guidance for Success</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Guidance for Success Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guidance for Success</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/gfsc__Guidance_for_Success_Item__c.object
<CustomObject>
    <description>guidance for success items</description>
    <fields>
        <fullName>gfsc__Guidance_for_Success__c</fullName>
        <description>Parent</description>
        <label>Guidance for Success</label>
        <referenceTo>gfsc__Guidance_for_Success__c</referenceTo>
        <relationshipLabel>Guidance for Success Item</relationshipLabel>
        <relationshipName>Guidance_for_Success_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Guidance for Success Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Guidance for Success Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guidance for Success Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Guidance_Handler_cls.cls
/**
 * Handler of Trigger of the Guidance object.
 * <p /><p />
 * Modification log:<p />
 * --------------------------------------------------------------------------------
 * Developer                   			 Date                Description<p />
 * --------------------------------------------------------------------------------
 * Martín Alejandro Mori Chávez    		20/01/2021          Original version.<p />
 *
 * @author Martín Alejandro Mori Chávez
 */
public class Guidance_Handler_cls extends TriggerHandler {
    /**
     * @Description variable triggerNew
     */
	List<gfsc__Guidance_for_Success__c> triggerNew = Trigger.new;
    /**
     * @Description variable triggerOld
     */
	List<gfsc__Guidance_for_Success__c> triggerOld = Trigger.Old;
    /**
     * @Description variable triggerNewMap
     */
	Map<id, gfsc__Guidance_for_Success__c> triggerNewMap = ((Map<Id, gfsc__Guidance_for_Success__c>)(Trigger.NewMap));
    /**
     * @Description variable triggerOldMap
     */
	Map<id, gfsc__Guidance_for_Success__c> triggerOldMap = ((Map<Id, gfsc__Guidance_for_Success__c>)(Trigger.OldMap));
	/*** @Description Clase implementada por Global*/
	final acpl.GuidanceForSuccessHandler guidanceHandler =  new acpl.GuidanceForSuccessHandler();

    /**
     * @Description afterInsert
     */
	@TestVisible
	protected override void afterInsert() {
		//Creates a related record gfsc__Guidance_for_Success_Item__c
		guidanceHandler.afterInsert(Trigger.new);
	}
}