src/objects/Guarantee__c.object
<CustomObject>
    <label>Garantía</label>
    <nameField>
        <displayFormat>G-{0000000}</displayFormat>
        <label>Número de garantía</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantías</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>gipr_Garantia__c</fullName>
        <label>gipr_Garantia</label>
        <type>Picklist</type>
        <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>gipr_Tipo_Garantia__c</fullName>
        <label>gipr_Tipo_Garantia</label>
        <type>Picklist</type>
        <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Product_Gurantee__c.object
<CustomObject>
    <fields>
        <fullName>GuaranteeType__c</fullName>
        <label>GuaranteeType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Guarantee__c</fullName>
        <label>Guarantee</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Product_Gurantees</relationshipLabel>
        <relationshipName>Product_Gurantees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product_Gurantees</relationshipLabel>
        <relationshipName>Product_Gurantees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isMaster__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isMaster</label>
        <type>Checkbox</type>
    </fields>
    <label>Product_Gurantee</label>
    <nameField>
        <label>Nombre de Product_Gurantee</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product_Gurantees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/classMasterGuarantee_cls.cls
/*-------------------------------------------------------------------------
 * Name: classMasterGuarantee_cls
 * Description : Class Master row Guarantee
 * Created date : May 22 2018
 * Developer name: Isaías Velázquez Cortés Indra(México)
--------------------------------------------------------------------------*/
public with sharing class classMasterGuarantee_cls {
	@InvocableMethod(label='Create Master Guarantee' description='Create the row from Product_Guarantee')
 	public static void createMasterGuarantee(List<OpportunityLineItem> listRow)
    {
        List<Product_Gurantee__c> row =[SELECT Id FROM Product_Gurantee__c WHERE Product__c=: listRow[0].Product2Id and Opportunity__c=: listRow[0].OpportunityId and  isMaster__c=true];
 		if(row.isEmpty())
 		{
 			Product_Gurantee__c nRow = new Product_Gurantee__c();
 			nRow.Product__c=listRow[0].Product2Id;
 			nRow.Opportunity__c=listRow[0].OpportunityId;
 			nRow.GuaranteeType__c=listRow[0].gipr_Tipo_Garantia__c;
 			nRow.Guarantee__c=listRow[0].gipr_Garantia__c;
 			nRow.isMaster__c=true;
 			insert nRow;
  		}
  		else
  		{
  			row[0].GuaranteeType__c=listRow[0].gipr_Tipo_Garantia__c;
  			row[0].Guarantee__c=listRow[0].gipr_Garantia__c;
  			update row;
  		}        
    }
}