src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>fprd__GBL_Sample_Checkbox__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field for test class</description>
        <label>Sample Checkbox</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>gipr_Plazo__c</fullName>
        <label>gipr_Plazo</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>minimun_fee_per__c</fullName>
        <label>Minimun fee (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>price_quote_date__c</fullName>
        <label>Last price quote date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>price_quote_id__c</fullName>
        <label>Cotiza Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/FieldForm_ctrl_Test.cls
@istest
public class FieldForm_ctrl_Test {

    @testSetup
    static void setData() {
        Account acc = TestFactory.createAccount();
        Opportunity opp = TestFactory.createOpportunity(acc.Id, UserInfo.getUserId());
        Product2 prod = TestFactory.createProduct();
        OpportunityLineItem oli = TestFactory.createOLI(opp.Id, prod.Id);
    }

    @isTest
    static void test_method_one(){
        List<OpportunityLineItem> lstOLI = [SELECT Id FROM OpportunityLineItem];
        Map<String,Object> getData = FieldForm_ctrl.getInfo(lstOLI[0].Id,'COTIZA Beta_Proposal');
        System.assertEquals(true, (Boolean)getData.get('isOk'));
        Map<String,Object> getDataError = FieldForm_ctrl.getInfo('skdfjowe23','COTIZA Beta_Proposal');
        System.assertEquals(false, (Boolean)getDataError.get('isOk'));

        List<String> lstFields = new List<String>();
        List<Object> lstData = new List<Object>();
        lstFields.add('price_quote_id__c');
        lstData.add('eeee');
        lstFields.add('minimun_fee_per__c');
        lstData.add(34.5);
        lstFields.add('gipr_Plazo__c');
        lstData.add(435.56);
        lstFields.add('fprd__GBL_Sample_Checkbox__c');
        lstData.add(true);
        lstFields.add('price_quote_date__c');
        lstData.add('2018-12-12');
        Map<String,Object> mapSave = FieldForm_ctrl.doSave(lstOLI[0].Id, 'OpportunityLineItem',lstFields, lstData);

    }
}