src/objects/Opportunity.object
<CustomObject>
<fields>
        <fullName>opportunity_status_type__c</fullName>
        <description>Status of an opportunity</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
	<fields>
        <fullName>Siocode__c</fullName>
        <label>Siocode</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/OpportunityProduct_Controller.cls
/**OpportunityProduct_Controller
*  object.
* <p /><p />
* Modification log:<p />
* -------------------------------------------------------------------
* Developer                    Date                Description<p />
* -------------------------------------------------------------------
* Julio Medellin               7/05/2018          Original version.<p />
*
* @author Julio Medellin
*/
public class OpportunityProduct_Controller {

    
@AuraEnabled     
    public static list<Task> getTasks(String val){    
    string Search ='%'+val+'%';    
    list<Task>  tasks = new list<task>();   
    tasks = [SELECT Status,Subject FROM Task WHERE /*Status =: System.Label.taskFilter AND*/ Subject LIKE : Search LIMIT 10];
    return tasks;    
    }    

@AuraEnabled     
    public static string getOppLI(String opp){   
    OpportunityLineItem  oli = new OpportunityLineItem();   
    oli = [SELECT Id FROM OpportunityLineItem WHERE OpportunityID =:opp LIMIT 1];   
    return oli.Id;    
    }        
 @AuraEnabled     
    public static void saveSIO(String opp,String savedRow){
    Opportunity op  = new Opportunity();
    op = [SELECT StageName FROM Opportunity WHERE ID =:opp];
    op.StageName='04';    
    OpportunityLineItem  oli = new OpportunityLineItem();   
    oli = [SELECT Id FROM OpportunityLineItem WHERE OpportunityID =:opp LIMIT 1];   
    oli.SIOCode__c = savedRow;
    update oli;
    update op;    
    }
 @AuraEnabled     
    public static void sendApproval(String opp){
    Opportunity op  = new Opportunity();
    op = [SELECT StageName FROM Opportunity WHERE ID =:opp];
    op.StageName='04';
    op.opportunity_status_type__c = '08';    
    update op;    
    }          
}