src/objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>Unique_id__c</fullName>
        <externalId>true</externalId>
        <label>Unique_id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
	<fields>
        <fullName>Unique_id__c</fullName>
        <externalId>true</externalId>
        <label>Unique_id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/slmt__Sales_Meeting__c.object
<CustomObject>
    <description>Storing all the planned meetings for each responsible, in addition to the planned date and time, the collaborator and the type.</description>
    <fields>
        <fullName>Collaborator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collaborator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Meetings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DateTime__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type_of_meeting__c</fullName>
        <label>Type of meeting</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Tracing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Meeting</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Meetings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BE_SM_Factory_tst.cls
@isTest
public with sharing class BE_SM_Factory_tst {
    
    public static Id getEjecutivoProfile() {
        return [SELECT Id FROM Profile WHERE Name = 'Ejecutivo' LIMIT 1].Id;
    }
    
    public static slmt__Sales_Meeting__c createSalesMeeting(DateTime smDT, Id colaboratorId, String smType, Boolean doInsert) {
        Final slmt__Sales_Meeting__c smRecord = new slmt__Sales_Meeting__c(DateTime__c = smDT, Collaborator__c = colaboratorId, 
                                                                           Name = 'SM Test '+Math.random(), Type_of_meeting__c = smType);
        if(doInsert) {insert smRecord;}
        return smRecord;
    }
    
    /** @Description  createProduct*/
	public static Product2 createProduct(String code) {
		Final Product2 prod = new Product2(Name = 'Product Test', Family = 'Test', ProductCode = code, Unique_id__c = code);
		insert prod;
		return prod;
	}
    
    /** @Description  createProduct*/
	public static PricebookEntry createPriceBookEntry(Id pricebookId, Id productId, Decimal unitPrice) {
		Final PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = pricebookId, Product2Id = productId, UnitPrice = unitPrice, IsActive = true);
		insert standardPrice;
		return standardPrice;
	}
    
}