src/objects/slmt__Sales_Meeting__c.object
<CustomObject>
    <description>Storing all the planned meetings for each responsible, in addition to the planned date and time, the collaborator and the type.</description>
    <fields>
        <fullName>Collaborator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collaborator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Meetings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DateTime__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type_of_meeting__c</fullName>
        <label>Type of meeting</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Tracing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Meeting</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Meetings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>prof_position_id__c</fullName>
        <description>Id for the user position</description>
        <label>Position code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/BE_SM_SyncAttendees_Tst.cls
/**
   -------------------------------------------------------------------------------------------------
   @Name BE_SM_SyncAttendees_Tst
   @Author Martin Alejandro Mori Chavez (martin.mori.contractor@bbva.com)
   @Date 2020-11-11
   @Description
   @Changes
   Date        Author   Email                  				Type
   2020-11-11  MAMCH    martin.mori.contractor@bbva.com    	Creation
   -------------------------------------------------------------------------------------------------
 */
@isTest
public with sharing class BE_SM_SyncAttendees_Tst {
    
    /*
	 * @Description  method setUp
	 */
    @TestSetup
    static void setUp() {
        Final Id ejeProfileId = BE_SM_Factory_tst.ID_EJE;
        Final User userGOF = TestFactory.getUser(true, new Map<Schema.SObjectField, Object>{User.ProfileId => ejeProfileId, User.prof_position_id__c => 'E01'});
        Final User ejecutivo = TestFactory.getUser(true, new Map<Schema.SObjectField, Object>{User.ProfileId => ejeProfileId, User.prof_position_id__c => 'E03', User.ManagerId => userGOF.Id});
        
        Final List<slmt__Sales_Meeting__c> lstSM = new List<slmt__Sales_Meeting__c>();
        for(Integer aux = 0; aux <= 3; aux++) {
            Final slmt__Sales_Meeting__c smRecord = new slmt__Sales_Meeting__c();
            smRecord.DateTime__c = DateTime.newInstance(System.today().addMonths(1).year(), System.today().addMonths(1).month(), 9+aux*7);
            smRecord.Collaborator__c = ejecutivo.Id;
            smRecord.Type_of_meeting__c = 'Tracing';
            lstSM.add(smRecord);
        }
        System.runAs(ejecutivo) {
            insert lstSM;
        }
    }
    
    /*
	 * @Description method unitTest
	 */
    @isTest
    static void unitTest() {
        Test.startTest();
        final Set<String> setSMIds = new Set<String>();
        for(slmt__Sales_Meeting__c slmt : [SELECT Id FROM slmt__Sales_Meeting__c LIMIT 4]) {
            setSMIds.add(slmt.Id);
        }
        if(!setSMIds.isEmpty()) {
            final Set<Id> evtIds = new Set<Id>();
        	for(Event evt : [SELECT Id FROM Event WHERE slmt__management_plan_meeting_id__c IN :setSMIds AND IsChild = FALSE]) {
                evtIds.add(evt.Id);
            }
            Database.executeBatch(new BE_SyncEventAttendees_Batch(evtIds));
        }
        Test.stopTest();
        final List<gcal__Event_Attendees__c> attends = [SELECT Id FROM gcal__Event_Attendees__c LIMIT 4];
        System.assertEquals(attends.size(), 4, 'success!!!');
    }
}