src/objects/Web_Service_Value_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pricing_model_id__c</fullName>
        <label>Pricing model</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>web_service_parameter_id__c</fullName>
        <label>Web service parameter identifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>web_service_value__c</fullName>
        <label>Web service value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Web Service Value Mapping</label>
    <nameField>
        <displayFormat>WSV-{0000000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Web Service Values Mapping</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WebServiceUtils_Test.cls
@istest
public class WebServiceUtils_Test {
	@isTest
	public static void test_method_one() {
		insert new Web_Service_Value_Mapping__c(label__c = 'a',
		                                        value__c = 'a',
		                                        web_service_value__c = 'a',
		                                        web_service_parameter_id__c = 'ws1',
		                                        pricing_model_id__c = '3');
		Map<String, Web_Service_Value_Mapping__c> mapReturn = WebServiceUtils.getWebServiceValuesMapping(new List<String> {'ws1'}, '3');
		System.assertEquals(mapReturn.get('ws1a').value__c, 'a');

		String endPoint = WebServiceUtils.getUrlFromCustomSettings('customSettingEndpoint');
		System.assertEquals(endPoint, '');
		insert new iaso__GBL_Rest_Services_Url__c(Name = 'customSettingEndpoint', iaso__Url__c = 'https://validation/ok', iaso__Cache_Partition__c = 'local.CredentialsPeru');
		endPoint = WebServiceUtils.getUrlFromCustomSettings('customSettingEndpoint');
		System.assertEquals(endPoint, 'https://validation/ok');

		WebServiceUtils.ResponseErrorMessage_Wrapper errorWrapper = WebServiceUtils.parse('{"version":1,"severity":"FATAL","http-status":409,"error-code":"functionalError","error-message":null,"consumer-request-id":"96a1c59d-f5df-40eb-ac83-551f5ceca963","system-error-code":"functionalError","system-error-description":"Default functional error."}');
		System.assertEquals(errorWrapper.status, 409);
	}
}